[package]
name = "rust_colors"
version = "0.2.0"
edition = "2024"

[dependencies]
phf = { version = "0.11.3", features = ["macros"] }
iced = { version = "0.13", features = ["advanced", "canvas"] }
hex = "0.4.3"