pub const COLORS_BRANDS: &[(&str, &str)] = &[
    ("#0099e5", "500px cloudy blue"),
    ("#ff4c4c", "500px orange pink"),
    ("#34bf49", "500px cloudy blue"),
    ("#00a98f", "About Me cloudy blue"),
    ("#000000", "Adidas warm purple"),
    ("#be0027", "Adidas warm purple"),
    ("#cf8d2e", "Adidas orange pink"),
    ("#e4e932", "Adidas orange pink"),
    ("#2c9f45", "Adidas warm purple"),
    ("#371777", "Adidas warm purple"),
    ("#52325d", "Adidas warm purple"),
    ("#511378", "Adidas warm purple"),
    ("#ff0000", "Adobe orange pink"),
    ("#fbb034", "Adobe orange pink"),
    ("#ffdd00", "Adobe orange pink"),
    ("#c1d82f", "Adobe orange pink"),
    ("#00a4e4", "Adobe cloudy blue"),
    ("#8a7967", "Adobe warm purple"),
    ("#6a737b", "Adobe warm purple"),
    ("#0abf53", "Adyen warm purple"),
    ("#00112c", "Adyen warm purple"),
    ("#279b37", "Adzuna warm purple"),
    ("#008374", "Aer Lingus warm purple"),
    ("#89ba16", "Aer Lingus orange pink"),
    ("#fefefe", "Aer Lingus cloudy blue"),
    ("#d20962", "Aetna warm purple"),
    ("#f47721", "Aetna orange pink"),
    ("#7ac143", "Aetna orange pink"),
    ("#00a78e", "Aetna cloudy blue"),
    ("#00bce4", "Aetna cloudy blue"),
    ("#7d3f98", "Aetna warm purple"),
    ("#037ef3", "Aiesec cloudy blue"),
    ("#f85a40", "Aiesec orange pink"),
    ("#00c16e", "Aiesec cloudy blue"),
    ("#7552cc", "Aiesec warm purple"),
    ("#0cb9c1", "Aiesec cloudy blue"),
    ("#f48924", "Aiesec orange pink"),
    ("#ffc845", "Aiesec orange pink"),
    ("#52565e", "Aiesec warm purple"),
    ("#caccd1", "Aiesec cloudy blue"),
    ("#f3f4f7", "Aiesec cloudy blue"),
    ("#ffd900", "Aim orange pink"),
    ("#fd5c63", "Airbnb orange pink"),
    ("#74d2e7", "Airbus cloudy blue"),
    ("#48a9c5", "Airbus cloudy blue"),
    ("#0085ad", "Airbus warm purple"),
    ("#8db9ca", "Airbus cloudy blue"),
    ("#4298b5", "Airbus cloudy blue"),
    ("#005670", "Airbus warm purple"),
    ("#00205b", "Airbus warm purple"),
    ("#009f4d", "Airbus warm purple"),
    ("#84bd00", "Airbus orange pink"),
    ("#efdf00", "Airbus orange pink"),
    ("#fe5000", "Airbus orange pink"),
    ("#e4002b", "Airbus orange pink"),
    ("#da1884", "Airbus warm purple"),
    ("#a51890", "Airbus warm purple"),
    ("#0077c8", "Airbus warm purple"),
    ("#008eaa", "Airbus warm purple"),
    ("#0099cc", "Akamai cloudy blue"),
    ("#ff9933", "Akamai orange pink"),
    ("#0079c1", "Alcon warm purple"),
    ("#49176d", "Alcon warm purple"),
    ("#00a0af", "Alcon cloudy blue"),
    ("#49a942", "Alcon warm purple"),
    ("#050f2c", "Algolia warm purple"),
    ("#003666", "Algolia warm purple"),
    ("#00aeff", "Algolia cloudy blue"),
    ("#3369e7", "Algolia warm purple"),
    ("#8e43e7", "Algolia warm purple"),
    ("#b84592", "Algolia warm purple"),
    ("#ff4f81", "Algolia orange pink"),
    ("#ff6c5f", "Algolia orange pink"),
    ("#ffc168", "Algolia orange pink"),
    ("#2dde98", "Algolia cloudy blue"),
    ("#1cc7d0", "Algolia cloudy blue"),
    ("#ff6a00", "Alibaba orange pink"),
    ("#0c3866", "Alienware warm purple"),
    ("#49c0b6", "Alienware cloudy blue"),
    ("#ce181e", "Alienware orange pink"),
    ("#007cc0", "Alienware warm purple"),
    ("#ffc20e", "Alienware orange pink"),
    ("#ed1c24", "Alphabet orange pink"),
    ("#ff9900", "Amazon orange pink"),
    ("#146eb4", "Amazon warm purple"),
    ("#002663", "American Express warm purple"),
    ("#4d4f53", "American Express warm purple"),
    ("#ed1b2e", "American Red Cross orange pink"),
    ("#6d6e70", "American Red Cross warm purple"),
    ("#d7d7d8", "American Red Cross cloudy blue"),
    ("#b4a996", "American Red Cross cloudy blue"),
    ("#ecb731", "American Red Cross orange pink"),
    ("#8ec06c", "American Red Cross cloudy blue"),
    ("#537b35", "American Red Cross warm purple"),
    ("#c4dff6", "American Red Cross cloudy blue"),
    ("#56a0d3", "American Red Cross cloudy blue"),
    ("#0091cd", "American Red Cross cloudy blue"),
    ("#004b79", "American Red Cross warm purple"),
    ("#7f181b", "American Red Cross warm purple"),
    ("#9f9fa3", "American Red Cross cloudy blue"),
    ("#000000", "American Red Cross warm purple"),
    ("#1c79c0", "Amp warm purple"),
    ("#0dd3ff", "Amp cloudy blue"),
    ("#0389ff", "Amp cloudy blue"),
    ("#a4c639", "Android orange pink"),
    ("#7fbb00", "Angies List orange pink"),
    ("#b52e31", "Angularjs warm purple"),
    ("#000000", "Angularjs warm purple"),
    ("#136ad5", "Answers warm purple"),
    ("#fb8a2e", "Answers orange pink"),
    ("#ff0b00", "Aol orange pink"),
    ("#00c4ff", "Aol cloudy blue"),
    ("#ea1d5d", "Aparat orange pink"),
    ("#1793d1", "Arch Linux cloudy blue"),
    ("#333333", "Arch Linux warm purple"),
    ("#990033", "Arizona State University Asu warm purple"),
    ("#ffb310", "Arizona State University Asu orange pink"),
    ("#004d73", "Arriva warm purple"),
    ("#00334e", "Arriva warm purple"),
    ("#007fdb", "Arriva cloudy blue"),
    ("#dbebfa", "Arriva cloudy blue"),
    ("#832561", "Arriva warm purple"),
    ("#11862f", "Arriva warm purple"),
    ("#bfca02", "Arriva orange pink"),
    ("#848a8c", "Arriva warm purple"),
    ("#004d73", "Arriva Danmark warm purple"),
    ("#00334e", "Arriva Danmark warm purple"),
    ("#007fbd", "Arriva Danmark warm purple"),
    ("#dbebfa", "Arriva Danmark cloudy blue"),
    ("#ff4e00", "Ars Technica orange pink"),
    ("#01cd74", "Ars Technica cloudy blue"),
    ("#3be8b0", "Asana cloudy blue"),
    ("#1aafd0", "Asana cloudy blue"),
    ("#6a67ce", "Asana warm purple"),
    ("#ffb900", "Asana orange pink"),
    ("#fc636b", "Asana orange pink"),
    ("#db3552", "Askfm orange pink"),
    ("#ff322e", "Associated Press orange pink"),
    ("#00a8e0", "Att cloudy blue"),
    ("#000000", "Atlanta Falcons warm purple"),
    ("#a71930", "Atlanta Falcons warm purple"),
    ("#a5acaf", "Atlanta Falcons cloudy blue"),
    ("#013ca6", "Atlantic Coast Conference Acc warm purple"),
    ("#a5a9ab", "Atlantic Coast Conference Acc cloudy blue"),
    ("#003366", "Atlassian warm purple"),
    ("#0066a1", "Atos warm purple"),
    ("#231f20", "Atos warm purple"),
    ("#bfbfbf", "Atos cloudy blue"),
    ("#00b2a9", "Atos cloudy blue"),
    ("#a626aa", "Atos warm purple"),
    ("#6639b7", "Atos warm purple"),
    ("#aea400", "Atos orange pink"),
    ("#ff6319", "Atos orange pink"),
    ("#ffffff", "Audi cloudy blue"),
    ("#000000", "Audi warm purple"),
    ("#f50537", "Audi orange pink"),
    ("#16214d", "Auth0 warm purple"),
    ("#44c7f4", "Auth0 cloudy blue"),
    ("#eb5424", "Auth0 orange pink"),
    ("#d0d2d3", "Auth0 cloudy blue"),
    ("#ff7800", "Avast orange pink"),
    ("#2d364c", "Avast warm purple"),
    ("#6534ac", "Avast warm purple"),
    ("#d40000", "Avira orange pink"),
    ("#de0f17", "Baidu orange pink"),
    ("#2529d8", "Baidu warm purple"),
    ("#629aa9", "Bandcamp cloudy blue"),
    ("#00aeef", "Barclays cloudy blue"),
    ("#00395d", "Barclays warm purple"),
    ("#2a5934", "Barnes Noble warm purple"),
    ("#b3dcff", "Basecamp cloudy blue"),
    ("#5ecc62", "Basecamp cloudy blue"),
    ("#00ad45", "Basecamp warm purple"),
    ("#e01f3d", "Beats By Dre orange pink"),
    ("#e04646", "Bebo orange pink"),
    ("#1769ff", "Behance cloudy blue"),
    ("#003b64", "Best Buy warm purple"),
    ("#fff200", "Best Buy orange pink"),
    ("#a0ac48", "Big Cartel orange pink"),
    ("#70b29c", "Big Cartel cloudy blue"),
    ("#ffb900", "Bing orange pink"),
    ("#505050", "Bing warm purple"),
    ("#a3a3a3", "Bing cloudy blue"),
    ("#205081", "Bitbucket warm purple"),
    ("#ee6123", "Bitly orange pink"),
    ("#61b3de", "Bitly cloudy blue"),
    ("#005387", "Blackberry warm purple"),
    ("#8cb811", "Blackberry orange pink"),
    ("#fdb813", "Blackberry orange pink"),
    ("#88aca1", "Blackberry cloudy blue"),
    ("#000000", "Blackberry warm purple"),
    ("#788cb6", "Blackberry cloudy blue"),
    ("#a1a1a4", "Blackberry cloudy blue"),
    ("#8f8f8c", "Blackberry cloudy blue"),
    ("#123962", "Blockchain warm purple"),
    ("#2754ba", "Blockchain warm purple"),
    ("#00aee6", "Blockchain cloudy blue"),
    ("#799eb2", "Blockchain cloudy blue"),
    ("#b1d4e5", "Blockchain cloudy blue"),
    ("#f57d00", "Blogger orange pink"),
    ("#0033a1", "Boeing warm purple"),
    ("#09347a", "Boise State University warm purple"),
    ("#007dc3", "Boise State University warm purple"),
    ("#0169a4", "Boise State University warm purple"),
    ("#3399cc", "Boise State University cloudy blue"),
    ("#f1632a", "Boise State University orange pink"),
    ("#464646", "Boise State University warm purple"),
    ("#b7b7b7", "Boise State University cloudy blue"),
    ("#f6f6f5", "Boise State University cloudy blue"),
    ("#8996a0", "Bombardier cloudy blue"),
    ("#003580", "Booking Com warm purple"),
    ("#009fe3", "Booking Com cloudy blue"),
    ("#feba02", "Booking Com orange pink"),
    ("#f2f6fa", "Booking Com cloudy blue"),
    ("#2b80ff", "Booqable cloudy blue"),
    ("#ffcc2f", "Bower orange pink"),
    ("#ef5734", "Bower orange pink"),
    ("#00acee", "Bower cloudy blue"),
    ("#2baf2b", "Bower warm purple"),
    ("#543729", "Bower warm purple"),
    ("#cecece", "Bower cloudy blue"),
    ("#0061d5", "Box warm purple"),
    ("#ce1126", "Boy Scouts Of America orange pink"),
    ("#003f87", "Boy Scouts Of America warm purple"),
    ("#075aaa", "British Airways warm purple"),
    ("#eb2226", "British Airways orange pink"),
    ("#01295c", "British Airways warm purple"),
    ("#efe9e5", "British Airways cloudy blue"),
    ("#aca095", "British Airways cloudy blue"),
    ("#b9cfed", "British Airways cloudy blue"),
    ("#a7a9ac", "British Airways cloudy blue"),
    ("#c90f23", "Brt orange pink"),
    ("#d52685", "Bt warm purple"),
    ("#553a99", "Bt warm purple"),
    ("#6cbc35", "Bt orange pink"),
    ("#fd9f3e", "Bt orange pink"),
    ("#08538c", "Bt warm purple"),
    ("#168eea", "Buffer cloudy blue"),
    ("#ee4f4f", "Buffer orange pink"),
    ("#fff9ea", "Buffer cloudy blue"),
    ("#76b852", "Buffer cloudy blue"),
    ("#323b43", "Buffer warm purple"),
    ("#59626a", "Buffer warm purple"),
    ("#ced7df", "Buffer cloudy blue"),
    ("#eff3f6", "Buffer cloudy blue"),
    ("#f4f7f9", "Buffer cloudy blue"),
    ("#00d1b2", "Bulma cloudy blue"),
    ("#ec1c24", "Burger King orange pink"),
    ("#fdbd10", "Burger King orange pink"),
    ("#0066b2", "Burger King warm purple"),
    ("#ed7902", "Burger King orange pink"),
    ("#ee3322", "Buzzfeed orange pink"),
    ("#00aaff", "Bynder cloudy blue"),
    ("#472f92", "Cadbury warm purple"),
    ("#bc0024", "Canon warm purple"),
    ("#000000", "Canon warm purple"),
    ("#00c4cc", "Canva cloudy blue"),
    ("#6a3be4", "Canva warm purple"),
    ("#004977", "Capital One warm purple"),
    ("#d03027", "Capital One orange pink"),
    ("#613854", "Carbonmade warm purple"),
    ("#00387b", "Carrefour warm purple"),
    ("#bb1e10", "Carrefour orange pink"),
    ("#f67828", "Carrefour orange pink"),
    ("#237f52", "Carrefour warm purple"),
    ("#388ed1", "Carrot cloudy blue"),
    ("#d74e26", "Carrot orange pink"),
    ("#006837", "Carrot warm purple"),
    ("#fa9f1e", "Carrot orange pink"),
    ("#f7931e", "Carrot orange pink"),
    ("#00aeef", "Cartoon Network cloudy blue"),
    ("#ed008c", "Cartoon Network warm purple"),
    ("#fff000", "Cartoon Network orange pink"),
    ("#000000", "Cartoon Network warm purple"),
    ("#84754e", "Case Mate warm purple"),
    ("#a6192e", "Case Mate warm purple"),
    ("#decba5", "Case Mate cloudy blue"),
    ("#000000", "Case Mate warm purple"),
    ("#ec2c22", "Change Org orange pink"),
    ("#2e1f54", "Channel warm purple"),
    ("#2e1f54", "Channel 4 warm purple"),
    ("#52057f", "Channel 4 warm purple"),
    ("#bf033b", "Channel 4 warm purple"),
    ("#f00a36", "Channel 4 orange pink"),
    ("#ed3b21", "Channel 4 orange pink"),
    ("#ff6908", "Channel 4 orange pink"),
    ("#ffc719", "Channel 4 orange pink"),
    ("#598c14", "Channel 4 warm purple"),
    ("#335238", "Channel 4 warm purple"),
    ("#4a8594", "Channel 4 warm purple"),
    ("#051736", "Channel 4 warm purple"),
    ("#000000", "Channel 4 warm purple"),
    ("#706357", "Channel 4 warm purple"),
    ("#b0a696", "Channel 4 cloudy blue"),
    ("#dbe0e3", "Channel 4 cloudy blue"),
    ("#dbeede", "Channel 4 cloudy blue"),
    ("#ffc907", "Charity Water orange pink"),
    ("#2e9df7", "Charity Water cloudy blue"),
    ("#231f20", "Charity Water warm purple"),
    ("#ff7243", "Cheddar orange pink"),
    ("#60afdc", "Clas Ohlson cloudy blue"),
    ("#f66733", "Clemson University orange pink"),
    ("#522d80", "Clemson University warm purple"),
    ("#d4c99e", "Clemson University cloudy blue"),
    ("#685c53", "Clemson University warm purple"),
    ("#a25016", "Clemson University orange pink"),
    ("#562e19", "Clemson University warm purple"),
    ("#86898c", "Clemson University warm purple"),
    ("#f9e498", "Clemson University cloudy blue"),
    ("#566127", "Clemson University warm purple"),
    ("#3a4958", "Clemson University warm purple"),
    ("#b5c327", "Clemson University orange pink"),
    ("#109dc0", "Clemson University cloudy blue"),
    ("#213e97", "Cloob warm purple"),
    ("#ffac25", "Cloob orange pink"),
    ("#d0002c", "Cloob warm purple"),
    ("#ff4816", "Cloob orange pink"),
    ("#f38020", "Cloudflare orange pink"),
    ("#faae40", "Cloudflare orange pink"),
    ("#404041", "Cloudflare warm purple"),
    ("#292526", "Cnbc warm purple"),
    ("#cd004b", "Cnbc warm purple"),
    ("#f37023", "Cnbc orange pink"),
    ("#fcb711", "Cnbc orange pink"),
    ("#0eb24e", "Cnbc warm purple"),
    ("#0087d2", "Cnbc cloudy blue"),
    ("#6561ac", "Cnbc warm purple"),
    ("#cc0000", "Cnn orange pink"),
    ("#000000", "Cnn warm purple"),
    ("#282828", "Cnn warm purple"),
    ("#464646", "Cnn warm purple"),
    ("#ed1c16", "Coca Cola orange pink"),
    ("#616f67", "Code School warm purple"),
    ("#c68143", "Code School orange pink"),
    ("#f65a5b", "Codecademy orange pink"),
    ("#204056", "Codecademy warm purple"),
    ("#0ebeff", "Codepen cloudy blue"),
    ("#47cf73", "Codepen cloudy blue"),
    ("#ae63e4", "Codepen cloudy blue"),
    ("#fcd000", "Codepen orange pink"),
    ("#ff3c41", "Codepen orange pink"),
    ("#76daff", "Codepen cloudy blue"),
    ("#d2ea32", "Connexxion orange pink"),
    ("#016773", "Connexxion warm purple"),
    ("#439fd3", "Constant Contact cloudy blue"),
    ("#f6b128", "Constant Contact orange pink"),
    ("#ffa500", "Continental Ag orange pink"),
    ("#00a5dc", "Continental Ag cloudy blue"),
    ("#004eaf", "Continental Ag warm purple"),
    ("#2db928", "Continental Ag warm purple"),
    ("#057855", "Continental Ag warm purple"),
    ("#ff2d37", "Continental Ag orange pink"),
    ("#000000", "Continental Ag warm purple"),
    ("#737373", "Continental Ag warm purple"),
    ("#969696", "Continental Ag cloudy blue"),
    ("#cdcdcd", "Continental Ag cloudy blue"),
    ("#f0f0f0", "Continental Ag cloudy blue"),
    ("#689550", "Courtyard warm purple"),
    ("#85c446", "Courtyard orange pink"),
    ("#c0de9e", "Courtyard cloudy blue"),
    ("#b9dca4", "Courtyard cloudy blue"),
    ("#da5a47", "Craft Cms orange pink"),
    ("#b62b6e", "Creative Commons warm purple"),
    ("#9628c6", "Creative Commons warm purple"),
    ("#4374b7", "Creative Commons warm purple"),
    ("#abb8af", "Creative Commons cloudy blue"),
    ("#98c807", "Creative Commons orange pink"),
    ("#b1a24a", "Creative Commons orange pink"),
    ("#edd812", "Creative Commons orange pink"),
    ("#ef9421", "Creative Commons orange pink"),
    ("#d13814", "Creative Commons orange pink"),
    ("#8ba753", "Creative Market orange pink"),
    ("#30660f", "Crowdin warm purple"),
    ("#b8cc1c", "Crowdin orange pink"),
    ("#830051", "Crowne Plaza warm purple"),
    ("#cf0072", "Crowne Plaza warm purple"),
    ("#d9e506", "Crowne Plaza orange pink"),
    ("#ff7900", "Crowne Plaza orange pink"),
    ("#00c6d7", "Crowne Plaza cloudy blue"),
    ("#766a65", "Crowne Plaza warm purple"),
    ("#2292a7", "Crunchbase warm purple"),
    ("#005696", "Culvers warm purple"),
    ("#1d1d1b", "Cunard warm purple"),
    ("#ae9a64", "Cunard orange pink"),
    ("#e42313", "Cunard orange pink"),
    ("#8b8c8d", "Cunard warm purple"),
    ("#cc0000", "Cvs orange pink"),
    ("#00aaff", "Dailymotion cloudy blue"),
    ("#00d2f3", "Dailymotion cloudy blue"),
    ("#263f6a", "Daimler warm purple"),
    ("#182b45", "Daimler warm purple"),
    ("#6b0f24", "Daimler warm purple"),
    ("#193725", "Daimler warm purple"),
    ("#606061", "Daimler warm purple"),
    ("#774aa4", "Datadog warm purple"),
    ("#095280", "Dealhack warm purple"),
    ("#00a1f1", "Dealhack cloudy blue"),
    ("#a80030", "Debian warm purple"),
    ("#ff0000", "Deezer orange pink"),
    ("#ffed00", "Deezer orange pink"),
    ("#ff0092", "Deezer warm purple"),
    ("#c2ff00", "Deezer orange pink"),
    ("#00c7f2", "Deezer cloudy blue"),
    ("#c1f1fc", "Deezer cloudy blue"),
    ("#ebffac", "Deezer cloudy blue"),
    ("#ffc2e5", "Deezer cloudy blue"),
    ("#ffaaaa", "Deezer cloudy blue"),
    ("#334858", "Delectable warm purple"),
    ("#cd595a", "Delectable orange pink"),
    ("#94938f", "Delectable cloudy blue"),
    ("#a3a7a6", "Delectable cloudy blue"),
    ("#dbc5b0", "Delectable cloudy blue"),
    ("#f8dfc2", "Delectable cloudy blue"),
    ("#f9ebdf", "Delectable cloudy blue"),
    ("#3399ff", "Delicious cloudy blue"),
    ("#222222", "Delicious warm purple"),
    ("#eeeeee", "Delicious cloudy blue"),
    ("#00c1b2", "Deliveroo cloudy blue"),
    ("#0085c3", "Dell warm purple"),
    ("#7ab800", "Dell orange pink"),
    ("#f2af00", "Dell orange pink"),
    ("#dc5034", "Dell orange pink"),
    ("#ce1126", "Dell orange pink"),
    ("#b7295a", "Dell warm purple"),
    ("#6e2585", "Dell warm purple"),
    ("#71c6c1", "Dell cloudy blue"),
    ("#5482ab", "Dell warm purple"),
    ("#009bbb", "Dell cloudy blue"),
    ("#444444", "Dell warm purple"),
    ("#eeeeee", "Dell cloudy blue"),
    ("#c8102e", "Delta Airlines warm purple"),
    ("#862633", "Delta Airlines warm purple"),
    ("#003a70", "Delta Airlines warm purple"),
    ("#f99104", "Dental Plans orange pink"),
    ("#00b7c9", "Dental Plans cloudy blue"),
    ("#2d72d9", "Designer News warm purple"),
    ("#e64b50", "Designmoo orange pink"),
    ("#dbc65d", "Designmoo orange pink"),
    ("#ff0000", "Deutsche Bahn orange pink"),
    ("#0a0a0a", "Dev To warm purple"),
    ("#ffffff", "Dev To cloudy blue"),
    ("#05cc47", "Deviantart cloudy blue"),
    ("#4dc47d", "Deviantart cloudy blue"),
    ("#181a1b", "Deviantart warm purple"),
    ("#ff0000", "Devour orange pink"),
    ("#febd17", "Dewalt orange pink"),
    ("#ba0c2f", "Dhl warm purple"),
    ("#ffcd00", "Dhl orange pink"),
    ("#c9c9c9", "Dhl cloudy blue"),
    ("#007dc3", "Diebold warm purple"),
    ("#003f69", "Diebold warm purple"),
    ("#954010", "Diebold warm purple"),
    ("#445c6e", "Diebold warm purple"),
    ("#005238", "Diebold warm purple"),
    ("#97824b", "Diebold orange pink"),
    ("#005be2", "Digg warm purple"),
    ("#000000", "Digg warm purple"),
    ("#008bcf", "Digital Ocean cloudy blue"),
    ("#fdb94e", "Dindr orange pink"),
    ("#f9a852", "Dindr orange pink"),
    ("#f69653", "Dindr orange pink"),
    ("#f38654", "Dindr orange pink"),
    ("#f07654", "Dindr orange pink"),
    ("#ed6856", "Dindr orange pink"),
    ("#ef5956", "Dindr orange pink"),
    ("#ee4c58", "Dindr orange pink"),
    ("#56c1ab", "Dindr cloudy blue"),
    ("#6a6b6a", "Dindr warm purple"),
    ("#f05d21", "Direct Energy orange pink"),
    ("#2c5770", "Direct Energy warm purple"),
    ("#0f723a", "Direct Energy warm purple"),
    ("#c7c8ca", "Direct Energy cloudy blue"),
    ("#666666", "Direct Energy warm purple"),
    ("#00a6d6", "Directv cloudy blue"),
    ("#00629b", "Directv warm purple"),
    ("#003865", "Directv warm purple"),
    ("#000000", "Discogs warm purple"),
    ("#333333", "Discogs warm purple"),
    ("#f5df2e", "Discogs orange pink"),
    ("#5865f2", "Discord cloudy blue"),
    ("#57f287", "Discord cloudy blue"),
    ("#fee75c", "Discord orange pink"),
    ("#eb459e", "Discord orange pink"),
    ("#ed4245", "Discord orange pink"),
    ("#ffffff", "Discord cloudy blue"),
    ("#000000", "Discord warm purple"),
    ("#2c2f33", "Discord warm purple"),
    ("#23272a", "Discord warm purple"),
    ("#ec1944", "Dish Network orange pink"),
    ("#0af167", "Disney Xd cloudy blue"),
    ("#ee70a6", "Disney Xd orange pink"),
    ("#520099", "Disney Xd warm purple"),
    ("#39eafd", "Disney Xd cloudy blue"),
    ("#0d0735", "Disney Xd warm purple"),
    ("#f5f5f5", "Disney Xd cloudy blue"),
    ("#2e9fff", "Disqus cloudy blue"),
    ("#092e20", "Django warm purple"),
    ("#0db7ed", "Docker cloudy blue"),
    ("#384d54", "Docker warm purple"),
    ("#0b648f", "Dominos warm purple"),
    ("#e21737", "Dominos orange pink"),
    ("#e80033", "Dow orange pink"),
    ("#fdbb30", "Dow orange pink"),
    ("#ed8b00", "Dow orange pink"),
    ("#f15d22", "Dow orange pink"),
    ("#bf0d3e", "Dow warm purple"),
    ("#910048", "Dow warm purple"),
    ("#d0006f", "Dow warm purple"),
    ("#444444", "Dribbble warm purple"),
    ("#ea4c89", "Dribbble orange pink"),
    ("#8aba56", "Dribbble cloudy blue"),
    ("#ff8833", "Dribbble orange pink"),
    ("#00b6e3", "Dribbble cloudy blue"),
    ("#9ba5a8", "Dribbble cloudy blue"),
    ("#007ee5", "Dropbox cloudy blue"),
    ("#7b8994", "Dropbox warm purple"),
    ("#47525d", "Dropbox warm purple"),
    ("#3d464d", "Dropbox warm purple"),
    ("#5654a4", "Droplr warm purple"),
    ("#0077c0", "Drupal warm purple"),
    ("#81ceff", "Drupal cloudy blue"),
    ("#00598e", "Drupal warm purple"),
    ("#e37151", "Duckduckgo orange pink"),
    ("#de5833", "Duckduckgo orange pink"),
    ("#ffffff", "Duckduckgo cloudy blue"),
    ("#e5e5e5", "Duckduckgo cloudy blue"),
    ("#5b9e4d", "Duckduckgo warm purple"),
    ("#4495d4", "Duckduckgo cloudy blue"),
    ("#001a57", "Duke University warm purple"),
    ("#003366", "Duke University warm purple"),
    ("#2da9d7", "Dunked cloudy blue"),
    ("#212a3e", "Dunked warm purple"),
    ("#7ac70c", "Duolingo orange pink"),
    ("#8ee000", "Duolingo orange pink"),
    ("#faa918", "Duolingo orange pink"),
    ("#ffc715", "Duolingo orange pink"),
    ("#d33131", "Duolingo orange pink"),
    ("#e53838", "Duolingo orange pink"),
    ("#1cb0f6", "Duolingo cloudy blue"),
    ("#14d4f4", "Duolingo cloudy blue"),
    ("#8549ba", "Duolingo warm purple"),
    ("#a560e8", "Duolingo cloudy blue"),
    ("#4c4c4c", "Duolingo warm purple"),
    ("#6f6f6f", "Duolingo warm purple"),
    ("#cfcfcf", "Duolingo cloudy blue"),
    ("#f0f0f0", "Duolingo cloudy blue"),
    ("#bff199", "Duolingo cloudy blue"),
    ("#f7c8c9", "Duolingo cloudy blue"),
    ("#ff7404", "Dwolla orange pink"),
    ("#6633cc", "Etrade warm purple"),
    ("#99cc00", "Etrade orange pink"),
    ("#6d1d7c", "E4 warm purple"),
    ("#ff6600", "Easy Jet orange pink"),
    ("#000000", "Easy Jet warm purple"),
    ("#58595b", "Easy Jet warm purple"),
    ("#e53238", "Ebay orange pink"),
    ("#0064d2", "Ebay warm purple"),
    ("#f5af02", "Ebay orange pink"),
    ("#86b817", "Ebay orange pink"),
    ("#131137", "El Al warm purple"),
    ("#918978", "El Al warm purple"),
    ("#0d69af", "Elance warm purple"),
    ("#000000", "Ello warm purple"),
    ("#f23819", "Ember orange pink"),
    ("#314855", "Emma warm purple"),
    ("#5cc3e8", "Emma cloudy blue"),
    ("#ffdb00", "Emma orange pink"),
    ("#79ceb8", "Emma cloudy blue"),
    ("#e95f5c", "Emma orange pink"),
    ("#87aa14", "Endomundo orange pink"),
    ("#40b3ff", "Engadget cloudy blue"),
    ("#82b541", "Envato orange pink"),
    ("#39c2d7", "Epam cloudy blue"),
    ("#a3c644", "Epam orange pink"),
    ("#464547", "Epam warm purple"),
    ("#b22746", "Epam warm purple"),
    ("#8e244d", "Epam warm purple"),
    ("#ff2052", "Epictions orange pink"),
    ("#e6e6e6", "Epictions cloudy blue"),
    ("#404040", "Epictions warm purple"),
    ("#01b5dd", "Epictions cloudy blue"),
    ("#b0db64", "Epictions cloudy blue"),
    ("#002561", "Ericsson warm purple"),
    ("#0d9ddb", "Esl cloudy blue"),
    ("#48b8e7", "Esl cloudy blue"),
    ("#efecea", "Esl cloudy blue"),
    ("#2c2b2b", "Esl warm purple"),
    ("#ff0033", "Espn orange pink"),
    ("#6a9c84", "Estimote cloudy blue"),
    ("#790f59", "Estimote warm purple"),
    ("#373b9c", "Estimote warm purple"),
    ("#f784b6", "Estimote orange pink"),
    ("#39b7dd", "Estimote cloudy blue"),
    ("#ccc900", "Estimote orange pink"),
    ("#d5641c", "Etsy orange pink"),
    ("#33cc99", "Evaneos cloudy blue"),
    ("#4ba6f5", "Evaneos cloudy blue"),
    ("#fdca30", "Evaneos orange pink"),
    ("#f79400", "Evaneos orange pink"),
    ("#f34235", "Evaneos orange pink"),
    ("#ff8000", "Eventbrite orange pink"),
    ("#2dbe60", "Evernote cloudy blue"),
    ("#7b868a", "Evernote warm purple"),
    ("#2facb2", "Evernote cloudy blue"),
    ("#166a8f", "Evernote warm purple"),
    ("#3b4446", "Evernote warm purple"),
    ("#525e61", "Evernote warm purple"),
    ("#aeb6b8", "Evernote cloudy blue"),
    ("#d7dcdd", "Evernote cloudy blue"),
    ("#eff2f3", "Evernote cloudy blue"),
    ("#203143", "Execucar warm purple"),
    ("#da9a39", "Execucar orange pink"),
    ("#00a0e9", "Eztalks cloudy blue"),
    ("#dd0017", "Fab Com orange pink"),
    ("#000000", "Fab Com warm purple"),
    ("#1877f2", "Facebook cloudy blue"),
    ("#6caddf", "Fairfield Inn Suites cloudy blue"),
    ("#b06010", "Fairfield Inn Suites orange pink"),
    ("#004990", "Fairfield Inn Suites warm purple"),
    ("#b50938", "Fairfield Inn Suites warm purple"),
    ("#a6a685", "Fairmont cloudy blue"),
    ("#000000", "Fairmont warm purple"),
    ("#fa5c4f", "Famo Us orange pink"),
    ("#333333", "Famo Us warm purple"),
    ("#3098dc", "Fancy cloudy blue"),
    ("#494e58", "Fancy warm purple"),
    ("#4d148c", "Fedex warm purple"),
    ("#ff6600", "Fedex orange pink"),
    ("#2bb24c", "Feedly warm purple"),
    ("#f9b949", "Fendi orange pink"),
    ("#e32119", "Ferrari orange pink"),
    ("#96172e", "Fiat warm purple"),
    ("#6d2d41", "Fiat warm purple"),
    ("#000000", "Film4 warm purple"),
    ("#d6182a", "Film4 orange pink"),
    ("#e66000", "Firefox orange pink"),
    ("#ff9500", "Firefox orange pink"),
    ("#ffcb00", "Firefox orange pink"),
    ("#00539f", "Firefox warm purple"),
    ("#0095dd", "Firefox cloudy blue"),
    ("#331e54", "Firefox warm purple"),
    ("#002147", "Firefox warm purple"),
    ("#ff8e00", "Fiskars orange pink"),
    ("#000000", "Fiskars warm purple"),
    ("#955214", "Fiskars orange pink"),
    ("#55601c", "Fiskars warm purple"),
    ("#005172", "Fiskars warm purple"),
    ("#4cc2c4", "Fitbit cloudy blue"),
    ("#f54785", "Fitbit orange pink"),
    ("#343434", "Fitbit warm purple"),
    ("#ed174f", "Five Guys orange pink"),
    ("#fbb040", "Five Guys orange pink"),
    ("#efc402", "Five Guys orange pink"),
    ("#d4891c", "Five Guys orange pink"),
    ("#00b22d", "Fiverr warm purple"),
    ("#ed713a", "Fivethirtyeight orange pink"),
    ("#000000", "Fivethirtyeight warm purple"),
    ("#f67c1a", "Flattr orange pink"),
    ("#338d11", "Flattr warm purple"),
    ("#f10087", "Flavors Me warm purple"),
    ("#009ae7", "Flavors Me cloudy blue"),
    ("#0063dc", "Flickr warm purple"),
    ("#ff0084", "Flickr warm purple"),
    ("#e12828", "Flipboard orange pink"),
    ("#2971b2", "Flixster warm purple"),
    ("#3fa9f5", "Fluid Ui cloudy blue"),
    ("#989898", "Fluid Ui cloudy blue"),
    ("#f8f8f8", "Fluid Ui cloudy blue"),
    ("#4dc9f6", "Follr cloudy blue"),
    ("#f67019", "Follr orange pink"),
    ("#f53794", "Follr orange pink"),
    ("#537bc4", "Follr warm purple"),
    ("#acc236", "Follr orange pink"),
    ("#228ae6", "Fontawesome cloudy blue"),
    ("#1c396d", "Ford warm purple"),
    ("#ee3440", "4ormat orange pink"),
    ("#5b9a68", "Forrst warm purple"),
    ("#f94877", "Foursquare orange pink"),
    ("#0732a2", "Foursquare warm purple"),
    ("#2d5be3", "Foursquare warm purple"),
    ("#006400", "Freecodecamp warm purple"),
    ("#ff9c2a", "Freecodecamp orange pink"),
    ("#ff4025", "Freecodecamp orange pink"),
    ("#3949ab", "Freecodecamp warm purple"),
    ("#efefef", "Freecodecamp cloudy blue"),
    ("#0f99d6", "Friend2friend cloudy blue"),
    ("#00457c", "Gallaudet University warm purple"),
    ("#e8d4a2", "Gallaudet University cloudy blue"),
    ("#009bff", "Gannett cloudy blue"),
    ("#007cc3", "Garmin warm purple"),
    ("#484848", "Garuda warm purple"),
    ("#002561", "Garuda warm purple"),
    ("#2f6f7e", "Garuda warm purple"),
    ("#1b212b", "Generatepress warm purple"),
    ("#1e72bd", "Generatepress warm purple"),
    ("#efefef", "Generatepress cloudy blue"),
    ("#4a742c", "Geocaching warm purple"),
    ("#041e42", "Georgia Southern University warm purple"),
    ("#a99260", "Georgia Southern University orange pink"),
    ("#212425", "Ghost warm purple"),
    ("#718087", "Ghost warm purple"),
    ("#5ba4e5", "Ghost cloudy blue"),
    ("#9fbb58", "Ghost orange pink"),
    ("#e9e8dd", "Ghost cloudy blue"),
    ("#000000", "Gibson warm purple"),
    ("#436f8e", "Gibson warm purple"),
    ("#887d59", "Gibson warm purple"),
    ("#8f9696", "Gibson cloudy blue"),
    ("#d6156c", "Gimmebar warm purple"),
    ("#4078c0", "Github warm purple"),
    ("#6cc644", "Github cloudy blue"),
    ("#bd2c00", "Github orange pink"),
    ("#c9510c", "Github orange pink"),
    ("#6e5494", "Github warm purple"),
    ("#fafafa", "Github cloudy blue"),
    ("#f5f5f5", "Github cloudy blue"),
    ("#fca326", "Gitlab orange pink"),
    ("#fc6d26", "Gitlab orange pink"),
    ("#e24329", "Gitlab orange pink"),
    ("#554488", "Gitlab warm purple"),
    ("#46bc99", "Gitter cloudy blue"),
    ("#f68d42", "Gitter orange pink"),
    ("#ed1965", "Gitter orange pink"),
    ("#f2f0ed", "Gitter cloudy blue"),
    ("#3a3133", "Gitter warm purple"),
    ("#663300", "Gittip warm purple"),
    ("#339966", "Gittip warm purple"),
    ("#f36f21", "Glaxosmithkline orange pink"),
    ("#72635c", "Glaxosmithkline warm purple"),
    ("#aca6a2", "Glaxosmithkline cloudy blue"),
    ("#ffffff", "Glaxosmithkline cloudy blue"),
    ("#7db701", "Godaddy orange pink"),
    ("#ff8a00", "Godaddy orange pink"),
    ("#a5c500", "Goethe orange pink"),
    ("#810061", "Goethe warm purple"),
    ("#303600", "Goethe warm purple"),
    ("#ec6400", "Goethe orange pink"),
    ("#d4c78c", "Goethe cloudy blue"),
    ("#5ec6f2", "Goethe cloudy blue"),
    ("#003468", "Goethe warm purple"),
    ("#4b1702", "Goethe warm purple"),
    ("#717a83", "Goethe warm purple"),
    ("#e80029", "Gogo orange pink"),
    ("#40b4e5", "Gogo cloudy blue"),
    ("#7c868d", "Gogo warm purple"),
    ("#553b08", "Goodreads warm purple"),
    ("#4285f4", "Google cloudy blue"),
    ("#34a853", "Google warm purple"),
    ("#fbbc05", "Google orange pink"),
    ("#ea4335", "Google orange pink"),
    ("#fbbc05", "Google Allo orange pink"),
    ("#4285f4", "Google Duo cloudy blue"),
    ("#dd4b39", "Google Plus orange pink"),
    ("#099d84", "Gospel For Asia warm purple"),
    ("#4d9db3", "Gospel For Asia cloudy blue"),
    ("#456acf", "Gospel For Asia warm purple"),
    ("#8762c9", "Gospel For Asia warm purple"),
    ("#ad182d", "Gospel For Asia warm purple"),
    ("#e15f5f", "Gospel For Asia orange pink"),
    ("#1e8cbe", "Gravatar cloudy blue"),
    ("#e30061", "Gravit warm purple"),
    ("#d5df00", "Gravit orange pink"),
    ("#475258", "Gravit warm purple"),
    ("#0b2d27", "Gwr warm purple"),
    ("#000000", "Gwr warm purple"),
    ("#ffffff", "Gwr cloudy blue"),
    ("#00b2a9", "Greenhouse cloudy blue"),
    ("#82b548", "Groupon orange pink"),
    ("#fba919", "Grunt orange pink"),
    ("#463014", "Grunt warm purple"),
    ("#8f1010", "Gucci warm purple"),
    ("#204030", "Gucci warm purple"),
    ("#a11826", "Gucci warm purple"),
    ("#0f403f", "Gucci warm purple"),
    ("#000000", "Gucci warm purple"),
    ("#72ef36", "Gumtree cloudy blue"),
    ("#3b3141", "Gumtree warm purple"),
    ("#f0ece6", "Gumtree cloudy blue"),
    ("#0863b5", "Gvb warm purple"),
    ("#fec600", "Gvb orange pink"),
    ("#f39100", "Gvb orange pink"),
    ("#e3001f", "Gvb orange pink"),
    ("#e50064", "Gvb warm purple"),
    ("#954a97", "Gvb warm purple"),
    ("#009ee3", "Gvb cloudy blue"),
    ("#13a538", "Gvb warm purple"),
    ("#ff4000", "Hacker News orange pink"),
    ("#0f9d58", "Hangouts warm purple"),
    ("#0087b4", "Happn warm purple"),
    ("#008200", "Heineken warm purple"),
    ("#205527", "Heineken warm purple"),
    ("#ff2b00", "Heineken orange pink"),
    ("#c3c3c3", "Heineken cloudy blue"),
    ("#0093d0", "Hellowallet cloudy blue"),
    ("#3197d6", "Help Scout cloudy blue"),
    ("#394956", "Help Scout warm purple"),
    ("#d6dde3", "Help Scout cloudy blue"),
    ("#c9c3e6", "Heroku cloudy blue"),
    ("#6762a6", "Heroku warm purple"),
    ("#00b388", "Hewlett Packard Enterprise cloudy blue"),
    ("#425563", "Hewlett Packard Enterprise warm purple"),
    ("#fd9827", "Hi5 orange pink"),
    ("#a26eea", "Highfive cloudy blue"),
    ("#f7afff", "Highfive cloudy blue"),
    ("#5d70ea", "Highfive cloudy blue"),
    ("#46b7fd", "Highfive cloudy blue"),
    ("#f96302", "Home Depot orange pink"),
    ("#2a6ebb", "Homeaway warm purple"),
    ("#ff8a00", "Homeaway orange pink"),
    ("#003265", "Hootsuite warm purple"),
    ("#f7e8d5", "Hootsuite cloudy blue"),
    ("#ffbd0a", "Hootsuite orange pink"),
    ("#c6af92", "Hootsuite cloudy blue"),
    ("#71685f", "Hootsuite warm purple"),
    ("#54493f", "Hootsuite warm purple"),
    ("#38322d", "Hootsuite warm purple"),
    ("#7ac142", "Houzz orange pink"),
    ("#000000", "Houzz warm purple"),
    ("#0096d6", "Hp cloudy blue"),
    ("#d7410b", "Hp orange pink"),
    ("#db0011", "Hsbc orange pink"),
    ("#e34f26", "Html5 orange pink"),
    ("#66aa33", "Hulu warm purple"),
    ("#99cc33", "Hulu orange pink"),
    ("#41811e", "Hulu warm purple"),
    ("#222222", "Hulu warm purple"),
    ("#666666", "Hulu warm purple"),
    ("#e8e8e8", "Hulu cloudy blue"),
    ("#cb272c", "Humble Bundle orange pink"),
    ("#6d6e71", "Hyatt warm purple"),
    ("#bf5b20", "Hyatt orange pink"),
    ("#006e96", "Hyatt warm purple"),
    ("#8c8700", "Hyatt orange pink"),
    ("#ad5f7d", "Hyatt warm purple"),
    ("#d79100", "Hyatt orange pink"),
    ("#006699", "Ibm warm purple"),
    ("#32c24d", "Icons8 cloudy blue"),
    ("#cc0066", "Ideal warm purple"),
    ("#79afc1", "Ideal cloudy blue"),
    ("#000000", "Ideal warm purple"),
    ("#789240", "Identi Ca warm purple"),
    ("#7d0100", "Identi Ca warm purple"),
    ("#8baaff", "Identi Ca cloudy blue"),
    ("#33ccff", "Ifttt cloudy blue"),
    ("#ff4400", "Ifttt orange pink"),
    ("#000000", "Ifttt warm purple"),
    ("#c6002b", "Iheartradio warm purple"),
    ("#ffcc00", "Ikea orange pink"),
    ("#003399", "Ikea warm purple"),
    ("#f5de50", "Imdb orange pink"),
    ("#85bf25", "Imgur orange pink"),
    ("#2164f4", "Indeed warm purple"),
    ("#ff6600", "Indeed orange pink"),
    ("#eb1478", "Indiegogo warm purple"),
    ("#ff6200", "Ing orange pink"),
    ("#000066", "Ing warm purple"),
    ("#60ab59", "Instacart warm purple"),
    ("#405de6", "Instagram warm purple"),
    ("#5851db", "Instagram warm purple"),
    ("#833ab4", "Instagram warm purple"),
    ("#c13584", "Instagram warm purple"),
    ("#e1306c", "Instagram orange pink"),
    ("#fd1d1d", "Instagram orange pink"),
    ("#f56040", "Instagram orange pink"),
    ("#f77737", "Instagram orange pink"),
    ("#fcaf45", "Instagram orange pink"),
    ("#ffdc80", "Instagram orange pink"),
    ("#0d1a2b", "Instapage warm purple"),
    ("#1565c0", "Instapage warm purple"),
    ("#1e88e5", "Instapage cloudy blue"),
    ("#bcced6", "Instapage cloudy blue"),
    ("#f2f7f9", "Instapage cloudy blue"),
    ("#000000", "Instapaper warm purple"),
    ("#428bca", "Instapaper cloudy blue"),
    ("#0f7dc2", "Intel warm purple"),
    ("#0c1c2c", "Internet Society warm purple"),
    ("#3a82e4", "Internet Society cloudy blue"),
    ("#40b2a4", "Internet Society cloudy blue"),
    ("#eff2ec", "Internet Society cloudy blue"),
    ("#dedad0", "Internet Society cloudy blue"),
    ("#d0e6da", "Internet Society cloudy blue"),
    ("#085856", "Internet Society warm purple"),
    ("#24366e", "Internet Society warm purple"),
    ("#143e50", "Internet Society warm purple"),
    ("#7e245c", "Internet Society warm purple"),
    ("#d25238", "Internet Society orange pink"),
    ("#eeca4a", "Internet Society orange pink"),
    ("#365ebf", "Intuit warm purple"),
    ("#ff3366", "Invision orange pink"),
    ("#252b33", "Invision warm purple"),
    ("#2f7bbd", "Invision warm purple"),
    ("#323a45", "Invision warm purple"),
    ("#8a959e", "Invision cloudy blue"),
    ("#d4d7da", "Invision cloudy blue"),
    ("#e9ebec", "Invision cloudy blue"),
    ("#5fc9f8", "Ios cloudy blue"),
    ("#fecb2e", "Ios orange pink"),
    ("#fd9426", "Ios orange pink"),
    ("#fc3158", "Ios orange pink"),
    ("#147efb", "Ios cloudy blue"),
    ("#53d769", "Ios cloudy blue"),
    ("#fc3d39", "Ios orange pink"),
    ("#8e8e93", "Ios cloudy blue"),
    ("#1e1f56", "Israel Railways warm purple"),
    ("#f36d5d", "Issuu orange pink"),
    ("#fe423f", "Istock orange pink"),
    ("#02a388", "Istock warm purple"),
    ("#0c0d0d", "Istock warm purple"),
    ("#e8eded", "Istock cloudy blue"),
    ("#dce1e1", "Istock cloudy blue"),
    ("#f7df1e", "Javascript orange pink"),
    ("#000000", "Jawbone warm purple"),
    ("#ff6600", "Jbl orange pink"),
    ("#669c34", "Jetpack warm purple"),
    ("#72af3a", "Jetpack orange pink"),
    ("#f44321", "Joomla orange pink"),
    ("#5091cd", "Joomla cloudy blue"),
    ("#f9a541", "Joomla orange pink"),
    ("#7ac143", "Joomla orange pink"),
    ("#ff6600", "Joyent orange pink"),
    ("#0769ad", "Jquery warm purple"),
    ("#7acef4", "Jquery cloudy blue"),
    ("#006c54", "Kaspersky Lab warm purple"),
    ("#d52a1d", "Kaspersky Lab orange pink"),
    ("#00a9c0", "Keeeb cloudy blue"),
    ("#9cb443", "Khan Academy orange pink"),
    ("#242f3a", "Khan Academy warm purple"),
    ("#c21a30", "Kia warm purple"),
    ("#2bde73", "Kickstarter cloudy blue"),
    ("#0f2105", "Kickstarter warm purple"),
    ("#82bc23", "Kik orange pink"),
    ("#3db4e7", "Kik cloudy blue"),
    ("#d51007", "Kippt orange pink"),
    ("#d70021", "Kitkat orange pink"),
    ("#63a541", "Kiva warm purple"),
    ("#236133", "Kiva warm purple"),
    ("#26b6e8", "Kiva cloudy blue"),
    ("#00b0df", "Kiwipay cloudy blue"),
    ("#00a1e4", "Klm cloudy blue"),
    ("#000000", "Knight Foundation warm purple"),
    ("#03cce6", "Knight Foundation cloudy blue"),
    ("#29c876", "Knight Foundation cloudy blue"),
    ("#ff4081", "Knight Foundation orange pink"),
    ("#fdce2e", "Knight Foundation orange pink"),
    ("#f5f4f2", "Knight Foundation cloudy blue"),
    ("#cccccc", "Knight Foundation cloudy blue"),
    ("#666666", "Knight Foundation warm purple"),
    ("#ff3939", "Knight Foundation orange pink"),
    ("#ddb321", "Lamborghini orange pink"),
    ("#f55247", "Laravel orange pink"),
    ("#d51007", "Lastfm orange pink"),
    ("#d32d27", "Lastpass orange pink"),
    ("#af0809", "Lastpass warm purple"),
    ("#000000", "Lastpass warm purple"),
    ("#0c2340", "Lastpass warm purple"),
    ("#00a3e0", "Lastpass cloudy blue"),
    ("#ede04b", "Lastpass orange pink"),
    ("#333f48", "Lastpass warm purple"),
    ("#d9e1e2", "Lastpass cloudy blue"),
    ("#f6ec35", "Lego orange pink"),
    ("#d11013", "Lego orange pink"),
    ("#000000", "Lego warm purple"),
    ("#00c300", "Line warm purple"),
    ("#0a66c2", "Linkedin warm purple"),
    ("#83941f", "Linkedin orange pink"),
    ("#e7a33e", "Linkedin orange pink"),
    ("#f5987e", "Linkedin orange pink"),
    ("#56687a", "Linkedin warm purple"),
    ("#004182", "Linkedin warm purple"),
    ("#44712e", "Linkedin warm purple"),
    ("#915907", "Linkedin orange pink"),
    ("#b24020", "Linkedin orange pink"),
    ("#38434f", "Linkedin warm purple"),
    ("#dce6f1", "Linkedin cloudy blue"),
    ("#d7ebce", "Linkedin cloudy blue"),
    ("#fce2ba", "Linkedin cloudy blue"),
    ("#fadfd8", "Linkedin cloudy blue"),
    ("#e9e5df", "Linkedin cloudy blue"),
    ("#fdfaf5", "Linkedin cloudy blue"),
    ("#cf202e", "Livestream orange pink"),
    ("#232121", "Livestream warm purple"),
    ("#f78822", "Livestream orange pink"),
    ("#f6db35", "Livestream orange pink"),
    ("#6dc067", "Livestream cloudy blue"),
    ("#4185be", "Livestream cloudy blue"),
    ("#8f499c", "Livestream warm purple"),
    ("#d81f2a", "Lloyds orange pink"),
    ("#ff9900", "Lloyds orange pink"),
    ("#e0d86e", "Lloyds orange pink"),
    ("#9ea900", "Lloyds orange pink"),
    ("#6ec9e0", "Lloyds cloudy blue"),
    ("#007ea3", "Lloyds warm purple"),
    ("#9e4770", "Lloyds warm purple"),
    ("#631d76", "Lloyds warm purple"),
    ("#1e1e1e", "Lloyds warm purple"),
    ("#006fbf", "Localbitcoins Com warm purple"),
    ("#ff7b00", "Localbitcoins Com orange pink"),
    ("#008ecf", "Login Radius cloudy blue"),
    ("#09263c", "Login Radius warm purple"),
    ("#020b13", "Login Radius warm purple"),
    ("#e3f1f8", "Login Radius cloudy blue"),
    ("#073857", "Login Radius warm purple"),
    ("#eb0028", "Lomo orange pink"),
    ("#00a0df", "Lomo cloudy blue"),
    ("#000099", "London Underground warm purple"),
    ("#cc3333", "London Underground orange pink"),
    ("#004990", "Lowes warm purple"),
    ("#15b6e5", "Lowes cloudy blue"),
    ("#576396", "Lumo warm purple"),
    ("#ff00bf", "Lyft warm purple"),
    ("#352384", "Lyft warm purple"),
    ("#333447", "Lyft warm purple"),
    ("#f3f3f5", "Lyft cloudy blue"),
    ("#f46f25", "Magento orange pink"),
    ("#168de2", "Mail Ru cloudy blue"),
    ("#ffa930", "Mail Ru orange pink"),
    ("#239ab9", "Mailchimp cloudy blue"),
    ("#52bad5", "Mailchimp cloudy blue"),
    ("#6dc5dc", "Mailchimp cloudy blue"),
    ("#373737", "Mailchimp warm purple"),
    ("#5d5c5d", "Mailchimp warm purple"),
    ("#b7b7b7", "Mailchimp cloudy blue"),
    ("#34be5b", "Manjaro Linux cloudy blue"),
    ("#3bb2d0", "Mapbox cloudy blue"),
    ("#3887be", "Mapbox cloudy blue"),
    ("#8a8acb", "Mapbox cloudy blue"),
    ("#56b881", "Mapbox cloudy blue"),
    ("#50667f", "Mapbox warm purple"),
    ("#41afa5", "Mapbox cloudy blue"),
    ("#f9886c", "Mapbox orange pink"),
    ("#e55e5e", "Mapbox orange pink"),
    ("#ed6498", "Mapbox orange pink"),
    ("#fbb03b", "Mapbox orange pink"),
    ("#142736", "Mapbox warm purple"),
    ("#28353d", "Mapbox warm purple"),
    ("#222b30", "Mapbox warm purple"),
    ("#a31f34", "Massachusetts Institute Of Technology warm purple"),
    ("#8a8b8c", "Massachusetts Institute Of Technology warm purple"),
    ("#c2c0bf", "Massachusetts Institute Of Technology cloudy blue"),
    ("#004a77", "Massy Group warm purple"),
    ("#00adee", "Massy Group cloudy blue"),
    ("#ff8100", "Massy Group orange pink"),
    ("#ffd200", "Massy Group orange pink"),
    ("#eb001b", "Mastercard orange pink"),
    ("#ff5f00", "Mastercard orange pink"),
    ("#f79e1b", "Mastercard orange pink"),
    ("#615ef8", "Mastodon warm purple"),
    ("#29002d", "Mastodon warm purple"),
    ("#150118", "Mastodon warm purple"),
    ("#bd0017", "Mcdonalds warm purple"),
    ("#ffc836", "Mcdonalds orange pink"),
    ("#264f36", "Mcdonalds warm purple"),
    ("#00ab6c", "Medium warm purple"),
    ("#e0393e", "Meetup orange pink"),
    ("#0a4d8c", "Meijer warm purple"),
    ("#dd1321", "Meijer orange pink"),
    ("#ffe600", "Mercadolibre Com orange pink"),
    ("#2d3277", "Mercadolibre Com warm purple"),
    ("#0084ff", "Messenger cloudy blue"),
    ("#0082fb", "Meta cloudy blue"),
    ("#0064e0", "Meta warm purple"),
    ("#18453b", "Msu warm purple"),
    ("#000000", "Msu warm purple"),
    ("#ffffff", "Msu cloudy blue"),
    ("#008208", "Msu warm purple"),
    ("#7bbd00", "Msu orange pink"),
    ("#0b9a6d", "Msu warm purple"),
    ("#f65314", "Microsoft orange pink"),
    ("#7cbb00", "Microsoft orange pink"),
    ("#00a1f1", "Microsoft cloudy blue"),
    ("#ffbb00", "Microsoft orange pink"),
    ("#783bd2", "Microsoft Band warm purple"),
    ("#ea3e23", "Microsoft Office orange pink"),
    ("#0078d7", "Microsoft Surface warm purple"),
    ("#eeeeee", "Microsoft Surface cloudy blue"),
    ("#737373", "Microsoft Surface warm purple"),
    ("#505050", "Microsoft Surface warm purple"),
    ("#000000", "Microsoft Surface warm purple"),
    ("#9b4dca", "Milligram warm purple"),
    ("#f4f5f6", "Milligram cloudy blue"),
    ("#606c76", "Milligram warm purple"),
    ("#52aad8", "Mixcloud cloudy blue"),
    ("#273a4b", "Mixcloud warm purple"),
    ("#1d2d3b", "Mixcloud warm purple"),
    ("#a086d3", "Mixpanel cloudy blue"),
    ("#000088", "Mlb warm purple"),
    ("#cc0000", "Mlb orange pink"),
    ("#ee1d23", "Mobilink orange pink"),
    ("#db1f29", "Mojang orange pink"),
    ("#000000", "Mojang warm purple"),
    ("#c6d6df", "Mollie cloudy blue"),
    ("#ec4534", "Mollie orange pink"),
    ("#589636", "Mongodb warm purple"),
    ("#ce1141", "Montclair State University warm purple"),
    ("#eeb111", "Montclair State University orange pink"),
    ("#e87d1e", "Montclair State University orange pink"),
    ("#94ce08", "Montclair State University orange pink"),
    ("#00386b", "Montclair State University warm purple"),
    ("#969491", "Montclair State University cloudy blue"),
    ("#949483", "More4 cloudy blue"),
    ("#f47b7b", "More4 orange pink"),
    ("#9f1f5c", "More4 warm purple"),
    ("#ef9020", "More4 orange pink"),
    ("#00af3e", "More4 warm purple"),
    ("#85b7e2", "More4 cloudy blue"),
    ("#29245c", "More4 warm purple"),
    ("#ffd616", "More4 orange pink"),
    ("#e5352b", "More4 orange pink"),
    ("#e990ab", "More4 cloudy blue"),
    ("#0081b4", "More4 warm purple"),
    ("#96cbb3", "More4 cloudy blue"),
    ("#91be3e", "More4 orange pink"),
    ("#39a6dd", "More4 cloudy blue"),
    ("#eb0973", "More4 warm purple"),
    ("#dde2e0", "More4 cloudy blue"),
    ("#333c41", "More4 warm purple"),
    ("#5c92fa", "Motorola cloudy blue"),
    ("#c13832", "Mozilla orange pink"),
    ("#d7d3c8", "Mozilla cloudy blue"),
    ("#4d4e53", "Mozilla warm purple"),
    ("#ff6050", "Musixmatch orange pink"),
    ("#ff0e83", "Musixmatch orange pink"),
    ("#d54262", "Musixmatch orange pink"),
    ("#813867", "Musixmatch warm purple"),
    ("#66336e", "Musixmatch warm purple"),
    ("#341539", "Musixmatch warm purple"),
    ("#5677fc", "Musixmatch cloudy blue"),
    ("#9013fe", "Musixmatch warm purple"),
    ("#ffc208", "Musixmatch orange pink"),
    ("#00cc99", "Musixmatch cloudy blue"),
    ("#1fadc5", "Muut cloudy blue"),
    ("#ff8000", "Muut orange pink"),
    ("#2e51a2", "Myanimelist warm purple"),
    ("#000000", "Myspace warm purple"),
    ("#00758f", "Mysql warm purple"),
    ("#f29111", "Mysql orange pink"),
    ("#2b697a", "N26 warm purple"),
    ("#000000", "N26 warm purple"),
    ("#ffffff", "N26 cloudy blue"),
    ("#93dee8", "Nanowrimo cloudy blue"),
    ("#5a2e14", "Nanowrimo warm purple"),
    ("#fc3d21", "Nasa orange pink"),
    ("#0b3d91", "Nasa warm purple"),
    ("#ffd659", "Nascar orange pink"),
    ("#e4002b", "Nascar orange pink"),
    ("#007ac2", "Nascar warm purple"),
    ("#ffcc00", "National Geographic orange pink"),
    ("#000000", "National Geographic warm purple"),
    ("#0071bf", "Nationwide warm purple"),
    ("#000000", "Nationwide warm purple"),
    ("#e1ac26", "Nbc orange pink"),
    ("#dc380f", "Nbc orange pink"),
    ("#9f0812", "Nbc warm purple"),
    ("#6347b2", "Nbc warm purple"),
    ("#368dd5", "Nbc cloudy blue"),
    ("#70af1e", "Nbc orange pink"),
    ("#7e887a", "Nbc warm purple"),
    ("#cc0000", "Nc State University orange pink"),
    ("#000000", "Nc State University warm purple"),
    ("#00afd8", "Nest cloudy blue"),
    ("#7b858e", "Nest warm purple"),
    ("#e50914", "Netflix orange pink"),
    ("#221f1f", "Netflix warm purple"),
    ("#f5f5f1", "Netflix cloudy blue"),
    ("#39bd00", "Netvibes warm purple"),
    ("#ce2724", "New Balance orange pink"),
    ("#f3ec19", "New Balance orange pink"),
    ("#207c88", "New Balance warm purple"),
    ("#aac1bf", "New Balance cloudy blue"),
    ("#e8e9d7", "New Balance cloudy blue"),
    ("#4c4d4f", "New Balance warm purple"),
    ("#231f20", "New Balance warm purple"),
    ("#cc3333", "New York Post orange pink"),
    ("#2a2a2a", "New York Post warm purple"),
    ("#fbb040", "Nexar orange pink"),
    ("#44355b", "Nexar warm purple"),
    ("#31263e", "Nexar warm purple"),
    ("#ee5622", "Nexar orange pink"),
    ("#221e22", "Nexar warm purple"),
    ("#0077c8", "Nexmo warm purple"),
    ("#ff8200", "Nexmo orange pink"),
    ("#f0537a", "Nexmo orange pink"),
    ("#19975d", "Nextdoor warm purple"),
    ("#013369", "Nfl warm purple"),
    ("#d50a0a", "Nfl orange pink"),
    ("#005eb8", "Nhs warm purple"),
    ("#ffffff", "Nhs cloudy blue"),
    ("#504847", "Nike Football warm purple"),
    ("#27a770", "Nike Football warm purple"),
    ("#4bad31", "Nikefuel warm purple"),
    ("#f5dc00", "Nikefuel orange pink"),
    ("#e95814", "Nikefuel orange pink"),
    ("#e2142d", "Nikefuel orange pink"),
    ("#75af42", "Ning orange pink"),
    ("#a98c66", "Ninjas In Pyjamas orange pink"),
    ("#12191c", "Ninjas In Pyjamas warm purple"),
    ("#6f7f8d", "Ninjas In Pyjamas warm purple"),
    ("#000000", "Ninjas In Pyjamas warm purple"),
    ("#e60012", "Nintendo orange pink"),
    ("#8c8c8c", "Nintendo warm purple"),
    ("#ffffff", "Nintendo cloudy blue"),
    ("#215732", "Node Js warm purple"),
    ("#6cc24a", "Node Js cloudy blue"),
    ("#44883e", "Node Js warm purple"),
    ("#333333", "Node Js warm purple"),
    ("#124191", "Nokia warm purple"),
    ("#0390d8", "Norsan Media cloudy blue"),
    ("#003466", "Northern Arizona University warm purple"),
    ("#557665", "Northern Arizona University warm purple"),
    ("#4e2a84", "Northwestern University warm purple"),
    ("#836eaa", "Northwestern University warm purple"),
    ("#401f68", "Northwestern University warm purple"),
    ("#b6acd1", "Northwestern University cloudy blue"),
    ("#e4e0ee", "Northwestern University cloudy blue"),
    ("#342f2e", "Northwestern University warm purple"),
    ("#716c6b", "Northwestern University warm purple"),
    ("#bbb8b8", "Northwestern University cloudy blue"),
    ("#d8d6d6", "Northwestern University cloudy blue"),
    ("#765438", "Novartis warm purple"),
    ("#a13323", "Novartis warm purple"),
    ("#e65124", "Novartis orange pink"),
    ("#ec7f22", "Novartis orange pink"),
    ("#f8b22a", "Novartis orange pink"),
    ("#ffd430", "Novartis orange pink"),
    ("#cb3837", "Npm orange pink"),
    ("#ffc61e", "Ns orange pink"),
    ("#00337f", "Ns warm purple"),
    ("#003082", "Ns warm purple"),
    ("#003082", "Ns 2 warm purple"),
    ("#ffc917", "Ns 2 orange pink"),
    ("#76b900", "Nvidia orange pink"),
    ("#51007a", "Nzxt warm purple"),
    ("#dbe800", "Nzxt orange pink"),
    ("#d0d3d4", "Nzxt cloudy blue"),
    ("#7c878e", "Nzxt warm purple"),
    ("#e2002a", "Obb orange pink"),
    ("#6e6e6e", "Obb warm purple"),
    ("#ed812b", "Odnoklassniki orange pink"),
    ("#008272", "Office Sway warm purple"),
    ("#001f2d", "Oktopost warm purple"),
    ("#008fd4", "Oktopost cloudy blue"),
    ("#696969", "Oktopost warm purple"),
    ("#cccccc", "Oktopost cloudy blue"),
    ("#eeeeee", "Oktopost cloudy blue"),
    ("#8d989a", "Olark cloudy blue"),
    ("#744da8", "Olark warm purple"),
    ("#1fb3e0", "Olark cloudy blue"),
    ("#49c219", "Olark warm purple"),
    ("#f4dc2a", "Olark orange pink"),
    ("#eeb417", "Olark orange pink"),
    ("#d65129", "Olark orange pink"),
    ("#08107b", "Olympus warm purple"),
    ("#dfb226", "Olympus orange pink"),
    ("#777777", "Olympus warm purple"),
    ("#eb0029", "Oneplus orange pink"),
    ("#1b5faa", "Onshape warm purple"),
    ("#90cef1", "Onshape cloudy blue"),
    ("#ffc20e", "Onshape orange pink"),
    ("#eeaf00", "Oovoo orange pink"),
    ("#cc0f16", "Opera orange pink"),
    ("#9c9e9f", "Opera cloudy blue"),
    ("#ff0000", "Oracle orange pink"),
    ("#000000", "Oracle warm purple"),
    ("#7f7f7f", "Oracle warm purple"),
    ("#dc4405", "Oregon State University orange pink"),
    ("#000000", "Oregon State University warm purple"),
    ("#c7202c", "Overstock orange pink"),
    ("#060606", "Overwolf warm purple"),
    ("#171717", "Overwolf warm purple"),
    ("#cccccc", "Overwolf cloudy blue"),
    ("#ffffff", "Overwolf cloudy blue"),
    ("#002147", "Oxford University Press warm purple"),
    ("#000000", "Oxford University Press warm purple"),
    ("#666666", "Oxford University Press warm purple"),
    ("#004b91", "Pac warm purple"),
    ("#004b91", "Pac 12 warm purple"),
    ("#00274d", "Pac 12 warm purple"),
    ("#0076c0", "Pac 12 warm purple"),
    ("#000007", "Pac 12 warm purple"),
    ("#d6e03d", "Pac 12 orange pink"),
    ("#a1a1a4", "Pac 12 cloudy blue"),
    ("#e5c5bb", "Pac 12 cloudy blue"),
    ("#0f58a8", "Panasonic warm purple"),
    ("#000000", "Panasonic warm purple"),
    ("#005483", "Pandora warm purple"),
    ("#ee3423", "Path orange pink"),
    ("#f96854", "Patreon orange pink"),
    ("#052d49", "Patreon warm purple"),
    ("#f05000", "Paymill orange pink"),
    ("#22d0b8", "Paymo cloudy blue"),
    ("#34c950", "Paymo cloudy blue"),
    ("#8de86e", "Paymo cloudy blue"),
    ("#003087", "Paypal warm purple"),
    ("#009cde", "Paypal cloudy blue"),
    ("#012169", "Paypal warm purple"),
    ("#ed6b06", "Pearson orange pink"),
    ("#9d1348", "Pearson warm purple"),
    ("#008b5d", "Pearson warm purple"),
    ("#364395", "Pearson warm purple"),
    ("#ff6900", "Penguin Books orange pink"),
    ("#ee7200", "Peopleperhour Com orange pink"),
    ("#e32934", "Pepsi orange pink"),
    ("#004883", "Pepsi warm purple"),
    ("#3aa4c6", "Periscope cloudy blue"),
    ("#d75444", "Periscope orange pink"),
    ("#0093d0", "Pfizer cloudy blue"),
    ("#000000", "Pfizer warm purple"),
    ("#616365", "Pfizer warm purple"),
    ("#00aeef", "Pfizer cloudy blue"),
    ("#d6006e", "Pfizer warm purple"),
    ("#75d1e0", "Pfizer cloudy blue"),
    ("#7dba00", "Pfizer orange pink"),
    ("#cc292b", "Pfizer orange pink"),
    ("#00a950", "Pfizer warm purple"),
    ("#f8971d", "Pfizer orange pink"),
    ("#f7d417", "Pfizer orange pink"),
    ("#4a245e", "Pfizer warm purple"),
    ("#f26649", "Pfizer orange pink"),
    ("#0e5fd8", "Philips warm purple"),
    ("#0ea0db", "Photobucket cloudy blue"),
    ("#000000", "Photobucket warm purple"),
    ("#8892be", "Php cloudy blue"),
    ("#4f5b93", "Php warm purple"),
    ("#99cc99", "Php cloudy blue"),
    ("#5dbe57", "Pikabu cloudy blue"),
    ("#0000e6", "Pinboard warm purple"),
    ("#e60023", "Pinterest orange pink"),
    ("#ee3124", "Pizza Hut orange pink"),
    ("#00a160", "Pizza Hut warm purple"),
    ("#ffc425", "Pizza Hut orange pink"),
    ("#6585ed", "Plasso cloudy blue"),
    ("#f5756c", "Plasso orange pink"),
    ("#98afc0", "Plasso cloudy blue"),
    ("#2f3148", "Plasso warm purple"),
    ("#414f5a", "Plaxo warm purple"),
    ("#003087", "Playstation warm purple"),
    ("#e5a00d", "Plex orange pink"),
    ("#282a2d", "Plex warm purple"),
    ("#ef4056", "Pocket orange pink"),
    ("#50bcb6", "Pocket cloudy blue"),
    ("#d52b1e", "Poczta Polska orange pink"),
    ("#00a3e2", "Polariod cloudy blue"),
    ("#1ba548", "Polariod warm purple"),
    ("#fdc800", "Polariod orange pink"),
    ("#f1860e", "Polariod orange pink"),
    ("#e41b13", "Polariod orange pink"),
    ("#0099ff", "Portfolium cloudy blue"),
    ("#fb0a2a", "Portfolium orange pink"),
    ("#17ad49", "Portfolium warm purple"),
    ("#333333", "Portfolium warm purple"),
    ("#ef5b25", "Postman orange pink"),
    ("#000000", "Postmates warm purple"),
    ("#36454f", "Postmates warm purple"),
    ("#df0067", "Prestashop warm purple"),
    ("#251b5b", "Prestashop warm purple"),
    ("#25b9d7", "Prestashop cloudy blue"),
    ("#fbbb22", "Prestashop orange pink"),
    ("#68737f", "Prestashop warm purple"),
    ("#bbbfc3", "Prestashop cloudy blue"),
    ("#318bff", "Prezi cloudy blue"),
    ("#1885bf", "Priceline warm purple"),
    ("#ee7f2d", "Princeton University orange pink"),
    ("#000000", "Princeton University warm purple"),
    ("#da552f", "Product Hunt orange pink"),
    ("#534540", "Product Hunt warm purple"),
    ("#988f8c", "Product Hunt cloudy blue"),
    ("#00b27f", "Product Hunt cloudy blue"),
    ("#505264", "Protonmail warm purple"),
    ("#8a90c7", "Protonmail cloudy blue"),
    ("#000000", "Puma warm purple"),
    ("#44403f", "Puma warm purple"),
    ("#696965", "Puma warm purple"),
    ("#ba2026", "Puma warm purple"),
    ("#ae946d", "Puma orange pink"),
    ("#c28e0e", "Purdue University orange pink"),
    ("#98700d", "Purdue University orange pink"),
    ("#000000", "Purdue University warm purple"),
    ("#ffde57", "Python orange pink"),
    ("#4584b6", "Python warm purple"),
    ("#646464", "Python warm purple"),
    ("#e0001b", "Qantas Airlines orange pink"),
    ("#6b5aed", "Qonto warm purple"),
    ("#262a3e", "Qonto warm purple"),
    ("#fafafc", "Qonto cloudy blue"),
    ("#63ebe4", "Qonto cloudy blue"),
    ("#e10019", "Qualtrics orange pink"),
    ("#4257b2", "Quizlet warm purple"),
    ("#3ccfcf", "Quizlet cloudy blue"),
    ("#f0f0f0", "Quizlet cloudy blue"),
    ("#ff5454", "Quizup orange pink"),
    ("#a82400", "Quora orange pink"),
    ("#66ceff", "Quote Fm cloudy blue"),
    ("#c7053d", "Raspberry Pi warm purple"),
    ("#8cc04b", "Raspberry Pi orange pink"),
    ("#00ff00", "Razer cloudy blue"),
    ("#007dc3", "Rdio warm purple"),
    ("#e11b22", "Remax orange pink"),
    ("#0054a4", "Remax warm purple"),
    ("#00d8ff", "React cloudy blue"),
    ("#990000", "Readability warm purple"),
    ("#f29023", "Realex Payments orange pink"),
    ("#4d5255", "Realex Payments warm purple"),
    ("#cc0000", "Red Hat orange pink"),
    ("#ff4500", "Reddit orange pink"),
    ("#5f99cf", "Reddit cloudy blue"),
    ("#cee3f8", "Reddit cloudy blue"),
    ("#a02021", "Redfin warm purple"),
    ("#0a2239", "Redox warm purple"),
    ("#01b287", "Redox cloudy blue"),
    ("#ff9f1c", "Redox orange pink"),
    ("#e5505a", "Redox orange pink"),
    ("#854c9e", "Redox warm purple"),
    ("#000000", "Renaissance Hotels warm purple"),
    ("#999999", "Renaissance Hotels cloudy blue"),
    ("#f58021", "Renaissance Hotels orange pink"),
    ("#ed1c27", "Rentler orange pink"),
    ("#b32317", "Residence Inn orange pink"),
    ("#f58025", "Residence Inn orange pink"),
    ("#3a6e8f", "Residence Inn warm purple"),
    ("#87b2d8", "Residence Inn cloudy blue"),
    ("#8d8b00", "Residence Inn orange pink"),
    ("#c1d72f", "Residence Inn orange pink"),
    ("#e43526", "Reverbnation orange pink"),
    ("#f36e21", "Rochester Institute Of Technology orange pink"),
    ("#513127", "Rochester Institute Of Technology warm purple"),
    ("#f76902", "Rit orange pink"),
    ("#ffffff", "Rit cloudy blue"),
    ("#000000", "Rit warm purple"),
    ("#0ba6ab", "Rockpack cloudy blue"),
    ("#6f1ab1", "Roku warm purple"),
    ("#680021", "Rolls Royce warm purple"),
    ("#fffaec", "Rolls Royce cloudy blue"),
    ("#939598", "Rolls Royce cloudy blue"),
    ("#000000", "Rolls Royce warm purple"),
    ("#e22027", "Roo Kids orange pink"),
    ("#a1cd3d", "Roo Kids orange pink"),
    ("#003e70", "Roo Kids warm purple"),
    ("#62b0d9", "Roon cloudy blue"),
    ("#0098db", "Rosetta Stone cloudy blue"),
    ("#ecc400", "Rosetta Stone orange pink"),
    ("#fdd800", "Rounds orange pink"),
    ("#3f1a0a", "Rowan University warm purple"),
    ("#edd51c", "Rowan University orange pink"),
    ("#1b5692", "Cssd warm purple"),
    ("#c32128", "Cssd orange pink"),
    ("#43a756", "Cssd warm purple"),
    ("#999999", "Cssd cloudy blue"),
    ("#de8a3d", "Cssd orange pink"),
    ("#74a2d7", "Cssd cloudy blue"),
    ("#f0c33b", "Cssd orange pink"),
    ("#9fc54d", "Cssd orange pink"),
    ("#ff0000", "Royal Mail orange pink"),
    ("#ffff00", "Royal Mail orange pink"),
    ("#000000", "Royal Mail warm purple"),
    ("#f26522", "Rss orange pink"),
    ("#f26522", "Rss 2 orange pink"),
    ("#cc342d", "Ruby orange pink"),
    ("#cc0000", "Ruby On Rails orange pink"),
    ("#cc0033", "Rutgers University warm purple"),
    ("#073590", "Ryanair warm purple"),
    ("#f1c933", "Ryanair orange pink"),
    ("#2091eb", "Ryanair cloudy blue"),
    ("#e50000", "Sabre orange pink"),
    ("#111111", "Sabre warm purple"),
    ("#00dc06", "Sage warm purple"),
    ("#ec8a00", "Sainsburys orange pink"),
    ("#1798c1", "Salesforce cloudy blue"),
    ("#ff1100", "Salesforce orange pink"),
    ("#1428a0", "Samsung warm purple"),
    ("#75787b", "Samsung warm purple"),
    ("#0689d8", "Samsung cloudy blue"),
    ("#ffc600", "Samsung orange pink"),
    ("#ff6900", "Samsung orange pink"),
    ("#e4002b", "Samsung orange pink"),
    ("#c800a1", "Samsung warm purple"),
    ("#685bc7", "Samsung warm purple"),
    ("#0057b8", "Samsung warm purple"),
    ("#00a9e0", "Samsung cloudy blue"),
    ("#009ca6", "Samsung cloudy blue"),
    ("#00b140", "Samsung warm purple"),
    ("#e91e22", "San Francisco 49ers orange pink"),
    ("#c8aa76", "San Francisco 49ers orange pink"),
    ("#000000", "San Francisco 49ers warm purple"),
    ("#fd5a1e", "San Francisco Giants orange pink"),
    ("#000000", "San Francisco Giants warm purple"),
    ("#003366", "Sap warm purple"),
    ("#999999", "Sap cloudy blue"),
    ("#4d2177", "Scouts Uk warm purple"),
    ("#84a40b", "Scouts Uk orange pink"),
    ("#004851", "Scouts Uk warm purple"),
    ("#009a44", "Scouts Uk warm purple"),
    ("#0095c8", "Scouts Uk cloudy blue"),
    ("#003da5", "Scouts Uk warm purple"),
    ("#002855", "Scouts Uk warm purple"),
    ("#ffcd00", "Scouts Uk orange pink"),
    ("#ff8200", "Scouts Uk orange pink"),
    ("#ba0c2f", "Scouts Uk warm purple"),
    ("#ad1aac", "Scouts Uk warm purple"),
    ("#7c3a2d", "Scouts Uk warm purple"),
    ("#8c857b", "Scouts Uk warm purple"),
    ("#1a7bba", "Scribd warm purple"),
    ("#1f4fa3", "Septa warm purple"),
    ("#f14728", "Septa orange pink"),
    ("#004488", "Seton Hall University warm purple"),
    ("#0088ff", "Shazam cloudy blue"),
    ("#ffaa00", "Shazam orange pink"),
    ("#ff7700", "Shazam orange pink"),
    ("#ff0033", "Shazam orange pink"),
    ("#9911aa", "Shazam warm purple"),
    ("#cc2288", "Shazam warm purple"),
    ("#aadd22", "Shazam orange pink"),
    ("#242424", "Shazam warm purple"),
    ("#646464", "Shazam warm purple"),
    ("#949494", "Shazam cloudy blue"),
    ("#e4e4e4", "Shazam cloudy blue"),
    ("#f4f4f4", "Shazam cloudy blue"),
    ("#0168b3", "Sherwin Williams warm purple"),
    ("#ee3e34", "Sherwin Williams orange pink"),
    ("#96bf48", "Shopify orange pink"),
    ("#479ccf", "Shopify cloudy blue"),
    ("#2d3538", "Shopify warm purple"),
    ("#f5f5f5", "Shopify cloudy blue"),
    ("#f2f7fa", "Shopify cloudy blue"),
    ("#666666", "Shopify warm purple"),
    ("#f01f74", "Shopmium orange pink"),
    ("#009999", "Siemens warm purple"),
    ("#f26b21", "Skillshare orange pink"),
    ("#68b8be", "Skillshare cloudy blue"),
    ("#00800d", "Skoda warm purple"),
    ("#00aff0", "Skype cloudy blue"),
    ("#00338d", "Skywest warm purple"),
    ("#6ecadc", "Slack cloudy blue"),
    ("#e9a820", "Slack orange pink"),
    ("#e01563", "Slack warm purple"),
    ("#3eb991", "Slack cloudy blue"),
    ("#0077b5", "Slideshare warm purple"),
    ("#7c9cb0", "Slipcase cloudy blue"),
    ("#e53b2c", "Smashing Magazine orange pink"),
    ("#41b7d8", "Smashing Magazine cloudy blue"),
    ("#f36f21", "Snagajob orange pink"),
    ("#fffc00", "Snapchat orange pink"),
    ("#6cb33f", "Soapui warm purple"),
    ("#4a494d", "Soapui warm purple"),
    ("#29c4d0", "Socialbro cloudy blue"),
    ("#f29556", "Socialbro orange pink"),
    ("#84afa2", "Socialbro cloudy blue"),
    ("#72c427", "Socialbro orange pink"),
    ("#f24c7c", "Socialbro orange pink"),
    ("#00aaf2", "Socialbro cloudy blue"),
    ("#008ace", "Softonic cloudy blue"),
    ("#f80046", "Songkick orange pink"),
    ("#ff6600", "Sonicbids orange pink"),
    ("#0c88b1", "Sonicbids warm purple"),
    ("#d8a158", "Sonos orange pink"),
    ("#ba4724", "Sonos orange pink"),
    ("#1c5f4a", "Sonos warm purple"),
    ("#d8d8d8", "Sonos cloudy blue"),
    ("#000000", "Sony warm purple"),
    ("#7c8285", "Sony warm purple"),
    ("#bfbdb0", "Sony cloudy blue"),
    ("#b1b134", "Sony orange pink"),
    ("#bbd634", "Sony orange pink"),
    ("#dbe3b6", "Sony cloudy blue"),
    ("#b2c8bd", "Sony cloudy blue"),
    ("#165b65", "Sony warm purple"),
    ("#697d99", "Sony warm purple"),
    ("#96b8db", "Sony cloudy blue"),
    ("#00a4e8", "Sony cloudy blue"),
    ("#a4dbdb", "Sony cloudy blue"),
    ("#fdd666", "Sony orange pink"),
    ("#dc9018", "Sony orange pink"),
    ("#e31a22", "Sony orange pink"),
    ("#df8f2d", "Sony orange pink"),
    ("#b24f3f", "Sony orange pink"),
    ("#b51f29", "Sony warm purple"),
    ("#f58268", "Sony orange pink"),
    ("#f4979c", "Sony orange pink"),
    ("#fedf00", "Soulcycle orange pink"),
    ("#1e1e1e", "Soulcycle warm purple"),
    ("#a7a8aa", "Soulcycle cloudy blue"),
    ("#ff8800", "Soundcloud orange pink"),
    ("#ff3300", "Soundcloud orange pink"),
    ("#fc00c1", "Spoken warm purple"),
    ("#000000", "Spoken warm purple"),
    ("#1db954", "Spotify warm purple"),
    ("#191414", "Spotify warm purple"),
    ("#ffe100", "Sprint orange pink"),
    ("#75dd66", "Sprout Social cloudy blue"),
    ("#59cb59", "Sprout Social cloudy blue"),
    ("#2bb656", "Sprout Social warm purple"),
    ("#0ca750", "Sprout Social warm purple"),
    ("#f3f4f4", "Sprout Social cloudy blue"),
    ("#364141", "Sprout Social warm purple"),
    ("#28c101", "Square Cash warm purple"),
    ("#222222", "Squarespace warm purple"),
    ("#1e5397", "Stack Exchange warm purple"),
    ("#376db6", "Stack Exchange warm purple"),
    ("#4ca2da", "Stack Exchange cloudy blue"),
    ("#91d8f4", "Stack Exchange cloudy blue"),
    ("#f48024", "Stackoverflow orange pink"),
    ("#222426", "Stackoverflow warm purple"),
    ("#bcbbbb", "Stackoverflow cloudy blue"),
    ("#cc0000", "Staples orange pink"),
    ("#2c8aec", "Staples cloudy blue"),
    ("#ffcc00", "Staples orange pink"),
    ("#00704a", "Starbucks warm purple"),
    ("#e1261c", "State Farm orange pink"),
    ("#d7584f", "Status Chart orange pink"),
    ("#00adee", "Steam cloudy blue"),
    ("#000000", "Steam warm purple"),
    ("#3b5a6f", "Sterling Hotels warm purple"),
    ("#828a87", "Sterling Hotels warm purple"),
    ("#000000", "Sterling Hotels warm purple"),
    ("#9db7c4", "Sterling Hotels cloudy blue"),
    ("#ccd7dd", "Sterling Hotels cloudy blue"),
    ("#838f97", "Sterling Hotels cloudy blue"),
    ("#002054", "Sterling Hotels warm purple"),
    ("#000000", "Stockton University warm purple"),
    ("#79bde9", "Stockton University cloudy blue"),
    ("#ffc423", "Stockton University orange pink"),
    ("#bc9b6a", "Stockton University orange pink"),
    ("#a7a9ac", "Stockton University cloudy blue"),
    ("#f97200", "Storyful orange pink"),
    ("#010101", "Storyful warm purple"),
    ("#8b8b64", "Storyful warm purple"),
    ("#bbbdc0", "Storyful cloudy blue"),
    ("#fc4c02", "Strava orange pink"),
    ("#0f90fa", "Streamable cloudy blue"),
    ("#00afe1", "Stripe cloudy blue"),
    ("#004b91", "Stubhub warm purple"),
    ("#ff7300", "Stubhub orange pink"),
    ("#00afe1", "Studyblue cloudy blue"),
    ("#eb4924", "Stumbleupon orange pink"),
    ("#489e3b", "Subway warm purple"),
    ("#fabd42", "Subway orange pink"),
    ("#cd0a20", "Subway orange pink"),
    ("#e61718", "Sugarcrm orange pink"),
    ("#e8e9ea", "Sugarcrm cloudy blue"),
    ("#595a5c", "Sugarcrm warm purple"),
    ("#282828", "Sugarcrm warm purple"),
    ("#00447c", "Suntrust warm purple"),
    ("#fdb913", "Suntrust orange pink"),
    ("#e36f1e", "Suntrust orange pink"),
    ("#4285f4", "Supershuttle cloudy blue"),
    ("#ffcd1a", "Supershuttle orange pink"),
    ("#f06d1f", "Swarm orange pink"),
    ("#ffa633", "Swarm orange pink"),
    ("#e20074", "T Mobile warm purple"),
    ("#e74635", "Tagstr orange pink"),
    ("#444444", "Taiga warm purple"),
    ("#b8b8b8", "Taiga cloudy blue"),
    ("#72a114", "Taiga orange pink"),
    ("#9dce0a", "Taiga orange pink"),
    ("#879b89", "Taiga cloudy blue"),
    ("#cc0000", "Target orange pink"),
    ("#2580c3", "Teamspeak warm purple"),
    ("#1c2537", "Teamspeak warm purple"),
    ("#e0e0e0", "Teamspeak cloudy blue"),
    ("#25dd85", "Teamspeak cloudy blue"),
    ("#339900", "Technorati warm purple"),
    ("#e62b1e", "Ted orange pink"),
    ("#0088cc", "Telegram cloudy blue"),
    ("#e92c4c", "Tvtag orange pink"),
    ("#c82641", "Tvtag orange pink"),
    ("#a41e35", "Temple warm purple"),
    ("#222222", "Temple warm purple"),
    ("#899197", "Temple cloudy blue"),
    ("#ee1c2e", "Tesco orange pink"),
    ("#00539f", "Tesco warm purple"),
    ("#cc0000", "Tesla orange pink"),
    ("#500000", "Texas Am University warm purple"),
    ("#003c71", "Texas Am University warm purple"),
    ("#5b6236", "Texas Am University warm purple"),
    ("#744f28", "Texas Am University warm purple"),
    ("#998542", "Texas Am University orange pink"),
    ("#332c2c", "Texas Am University warm purple"),
    ("#707373", "Texas Am University warm purple"),
    ("#d6d3c4", "Texas Am University cloudy blue"),
    ("#cc0000", "Texas Tech University orange pink"),
    ("#000000", "Texas Tech University warm purple"),
    ("#ee8421", "The Audience Awards orange pink"),
    ("#8c8a8a", "The Audience Awards warm purple"),
    ("#222222", "The Audience Awards warm purple"),
    ("#293f6f", "The College Of New Jersey warm purple"),
    ("#a67a00", "The College Of New Jersey orange pink"),
    ("#ff3c1f", "The Next Web orange pink"),
    ("#26313b", "The Next Web warm purple"),
    ("#4e5860", "The Next Web warm purple"),
    ("#a6abaf", "The Next Web cloudy blue"),
    ("#d9e0e2", "The Next Web cloudy blue"),
    ("#fafbfc", "The Next Web cloudy blue"),
    ("#006b95", "The Ritz Carlton warm purple"),
    ("#4f5b65", "The Ritz Carlton warm purple"),
    ("#b3812a", "The Ritz Carlton orange pink"),
    ("#a01a1f", "The Ritz Carlton warm purple"),
    ("#ed1c24", "The Sun orange pink"),
    ("#b90c13", "The Sun warm purple"),
    ("#00745e", "The Sun Goals warm purple"),
    ("#086556", "The Sun Goals warm purple"),
    ("#8560a8", "The Sun Perks warm purple"),
    ("#431c69", "The Sun Perks warm purple"),
    ("#000000", "The Times warm purple"),
    ("#ff8000", "Thomson Reuters orange pink"),
    ("#555555", "Thomson Reuters warm purple"),
    ("#444444", "Thomson Reuters warm purple"),
    ("#666666", "Thomson Reuters warm purple"),
    ("#cccccc", "Thomson Reuters cloudy blue"),
    ("#e9e9e9", "Thomson Reuters cloudy blue"),
    ("#f7f7f7", "Thomson Reuters cloudy blue"),
    ("#da3d34", "Tivo orange pink"),
    ("#00a480", "Tivo warm purple"),
    ("#ed9f40", "Tivo orange pink"),
    ("#6a76ac", "Tivo warm purple"),
    ("#17170e", "Tivo warm purple"),
    ("#534b38", "Tivo warm purple"),
    ("#a6a480", "Tivo cloudy blue"),
    ("#66bd00", "Totaljobs orange pink"),
    ("#eb0a1e", "Toyota orange pink"),
    ("#ffffff", "Toyota cloudy blue"),
    ("#000000", "Toyota warm purple"),
    ("#58595b", "Toyota warm purple"),
    ("#6fbc6d", "Treehouse cloudy blue"),
    ("#47535b", "Treehouse warm purple"),
    ("#0079bf", "Trello warm purple"),
    ("#70b500", "Trello orange pink"),
    ("#ff9f1a", "Trello orange pink"),
    ("#eb5a46", "Trello orange pink"),
    ("#f2d600", "Trello orange pink"),
    ("#c377e0", "Trello cloudy blue"),
    ("#ff78cb", "Trello cloudy blue"),
    ("#00c2e0", "Trello cloudy blue"),
    ("#51e898", "Trello cloudy blue"),
    ("#c4c9cc", "Trello cloudy blue"),
    ("#00af87", "Tripadvisor cloudy blue"),
    ("#5eab1f", "Trulia warm purple"),
    ("#e12729", "Trustpilot orange pink"),
    ("#f37324", "Trustpilot orange pink"),
    ("#f8cc1b", "Trustpilot orange pink"),
    ("#72b043", "Trustpilot warm purple"),
    ("#007f4e", "Trustpilot warm purple"),
    ("#c8c8c8", "Trustpilot cloudy blue"),
    ("#35465c", "Tumblr warm purple"),
    ("#c30f24", "Tunngle warm purple"),
    ("#355ebe", "Turbotax warm purple"),
    ("#d52b1d", "Turbotax orange pink"),
    ("#1ec95b", "Twentythree cloudy blue"),
    ("#043623", "Twentythree warm purple"),
    ("#eff5f0", "Twentythree cloudy blue"),
    ("#9146ff", "Twitch warm purple"),
    ("#000000", "Twitch warm purple"),
    ("#f0f0ff", "Twitch cloudy blue"),
    ("#1da1f2", "Twitter cloudy blue"),
    ("#14171a", "Twitter warm purple"),
    ("#657786", "Twitter warm purple"),
    ("#aab8c2", "Twitter cloudy blue"),
    ("#e1e8ed", "Twitter cloudy blue"),
    ("#f5f8fa", "Twitter cloudy blue"),
    ("#98ce1e", "Typekit orange pink"),
    ("#d2de61", "Typepad orange pink"),
    ("#3178c6", "Typescript warm purple"),
    ("#00273f", "Typescript warm purple"),
    ("#ff8700", "Typo3 orange pink"),
    ("#09091a", "Uber warm purple"),
    ("#c0c0c8", "Uber cloudy blue"),
    ("#1fbad6", "Uber cloudy blue"),
    ("#dd4814", "Ubuntu orange pink"),
    ("#77216f", "Ubuntu warm purple"),
    ("#5e2750", "Ubuntu warm purple"),
    ("#2c001e", "Ubuntu warm purple"),
    ("#aea79f", "Ubuntu cloudy blue"),
    ("#333333", "Ubuntu warm purple"),
    ("#003262", "Uc Berkeley warm purple"),
    ("#3b7ea1", "Uc Berkeley warm purple"),
    ("#fdb515", "Uc Berkeley orange pink"),
    ("#c4820e", "Uc Berkeley orange pink"),
    ("#052049", "Ucsf warm purple"),
    ("#18a3ac", "Ucsf cloudy blue"),
    ("#90bd31", "Ucsf orange pink"),
    ("#178ccb", "Ucsf cloudy blue"),
    ("#f48024", "Ucsf orange pink"),
    ("#10167f", "United Way warm purple"),
    ("#fe230a", "United Way orange pink"),
    ("#ff9600", "United Way orange pink"),
    ("#000064", "United Way warm purple"),
    ("#b41428", "United Way warm purple"),
    ("#f57814", "United Way orange pink"),
    ("#e6d7aa", "United Way cloudy blue"),
    ("#505050", "United Way warm purple"),
    ("#f0e6c8", "United Way cloudy blue"),
    ("#969696", "United Way cloudy blue"),
    ("#7c81b8", "United Way cloudy blue"),
    ("#ff967d", "United Way orange pink"),
    ("#ffc87d", "United Way orange pink"),
    ("#222c37", "Unity warm purple"),
    ("#00cccc", "Unity cloudy blue"),
    ("#fff600", "Unity orange pink"),
    ("#ff0066", "Unity orange pink"),
    ("#19e3b1", "Unity cloudy blue"),
    ("#ff7f33", "Unity orange pink"),
    ("#b83c82", "Unity warm purple"),
    ("#e2001a", "Universitat Hamburg orange pink"),
    ("#009cd1", "Universitat Hamburg cloudy blue"),
    ("#3b515b", "Universitat Hamburg warm purple"),
    ("#46166b", "University At Albany warm purple"),
    ("#eeb211", "University At Albany orange pink"),
    ("#006c68", "University At Albany warm purple"),
    ("#97a4af", "University At Albany cloudy blue"),
    ("#005bbb", "University At Buffalo warm purple"),
    ("#e56a54", "University At Buffalo orange pink"),
    ("#ffc72c", "University At Buffalo orange pink"),
    ("#ebec00", "University At Buffalo orange pink"),
    ("#00a69c", "University At Buffalo cloudy blue"),
    ("#990000", "University At Buffalo warm purple"),
    ("#ad841f", "University At Buffalo orange pink"),
    ("#6da04b", "University At Buffalo warm purple"),
    ("#006570", "University At Buffalo warm purple"),
    ("#2f9fd0", "University At Buffalo cloudy blue"),
    ("#002f56", "University At Buffalo warm purple"),
    ("#e4e4e4", "University At Buffalo cloudy blue"),
    ("#666666", "University At Buffalo warm purple"),
    ("#007c41", "University Of Alberta warm purple"),
    ("#ffdb05", "University Of Alberta orange pink"),
    ("#cc0033", "University Of Arizona warm purple"),
    ("#003366", "University Of Arizona warm purple"),
    ("#d6083b", "University Of Cambridge warm purple"),
    ("#0072cf", "University Of Cambridge warm purple"),
    ("#ea7125", "University Of Cambridge orange pink"),
    ("#55a51c", "University Of Cambridge warm purple"),
    ("#8f2bbc", "University Of Cambridge warm purple"),
    ("#00b1c1", "University Of Cambridge cloudy blue"),
    ("#e00122", "University Of Cincinnati orange pink"),
    ("#000000", "University Of Cincinnati warm purple"),
    ("#ce1141", "University Of Dayton warm purple"),
    ("#004b8d", "University Of Dayton warm purple"),
    ("#000000", "University Of Dayton warm purple"),
    ("#faf2f3", "University Of Dayton cloudy blue"),
    ("#d1cdb8", "University Of Dayton cloudy blue"),
    ("#cf0a2c", "University Of Dayton orange pink"),
    ("#0082ca", "University Of Dayton warm purple"),
    ("#199051", "University Of Dayton warm purple"),
    ("#e76829", "University Of Dayton orange pink"),
    ("#ffdd00", "University Of Dayton orange pink"),
    ("#fa4616", "University Of Florida orange pink"),
    ("#0021a5", "University Of Florida warm purple"),
    ("#131f33", "University Of Illinois Urbana Champaign warm purple"),
    ("#fa6300", "University Of Illinois Urbana Champaign orange pink"),
    ("#005daa", "University Of Kentucky warm purple"),
    ("#00274c", "University Of Michigan warm purple"),
    ("#ffcb05", "University Of Michigan orange pink"),
    ("#4b9cd3", "University Of North Carolina cloudy blue"),
    ("#007fae", "University Of North Carolina warm purple"),
    ("#13294b", "University Of North Carolina warm purple"),
    ("#e1e1e1", "University Of North Carolina cloudy blue"),
    ("#767676", "University Of North Carolina warm purple"),
    ("#151515", "University Of North Carolina warm purple"),
    ("#154733", "University Of Oregon warm purple"),
    ("#fee123", "University Of Oregon orange pink"),
    ("#ffd100", "University Of Rochester orange pink"),
    ("#003b71", "University Of Rochester warm purple"),
    ("#bf5700", "University Of Texas orange pink"),
    ("#333f48", "University Of Texas warm purple"),
    ("#005f86", "University Of Texas warm purple"),
    ("#43695b", "University Of Texas warm purple"),
    ("#f2a900", "University Of Texas orange pink"),
    ("#382f2d", "University Of Texas warm purple"),
    ("#d6d2c4", "University Of Texas cloudy blue"),
    ("#005493", "University Of Victoria warm purple"),
    ("#f5aa1c", "University Of Victoria orange pink"),
    ("#c63527", "University Of Victoria orange pink"),
    ("#002754", "University Of Victoria warm purple"),
    ("#4b2e83", "University Of Washington warm purple"),
    ("#b7a57a", "University Of Washington orange pink"),
    ("#85754d", "University Of Washington warm purple"),
    ("#ffd54f", "University Of Waterloo orange pink"),
    ("#ffbd00", "University Of Wisconsin Milwaukee orange pink"),
    ("#000000", "University Of Wisconsin Milwaukee warm purple"),
    ("#98c646", "University Of Wisconsin Milwaukee orange pink"),
    ("#694d88", "University Of Wisconsin Milwaukee warm purple"),
    ("#5382af", "University Of Wisconsin Milwaukee warm purple"),
    ("#d06d34", "University Of Wisconsin Milwaukee orange pink"),
    ("#5f9a38", "University Of Wisconsin Milwaukee warm purple"),
    ("#474d52", "University Of Wisconsin Milwaukee warm purple"),
    ("#c822b0", "Univision warm purple"),
    ("#351c15", "Ups warm purple"),
    ("#ffb500", "Ups orange pink"),
    ("#64a70b", "Ups orange pink"),
    ("#315cfd", "Usertesting warm purple"),
    ("#333366", "Usps warm purple"),
    ("#e71921", "Usps orange pink"),
    ("#218748", "Usps warm purple"),
    ("#3388ff", "Ustream cloudy blue"),
    ("#ff0000", "Verizon orange pink"),
    ("#f2f2f2", "Verizon cloudy blue"),
    ("#3285dc", "Verizon cloudy blue"),
    ("#f07355", "Viadeo orange pink"),
    ("#59267c", "Viber warm purple"),
    ("#8f5db7", "Viber warm purple"),
    ("#e2d4e7", "Viber cloudy blue"),
    ("#a5cfd5", "Viber cloudy blue"),
    ("#81cd50", "Viber cloudy blue"),
    ("#f82a53", "Vidme orange pink"),
    ("#111111", "Vidme warm purple"),
    ("#f5f5f5", "Vidme cloudy blue"),
    ("#9f2af8", "Vidme warm purple"),
    ("#aaaaaa", "Vidme cloudy blue"),
    ("#dff0d8", "Vidme cloudy blue"),
    ("#3c9cd7", "Viki cloudy blue"),
    ("#d24663", "Viki orange pink"),
    ("#162221", "Vimeo warm purple"),
    ("#1ab7ea", "Vimeo cloudy blue"),
    ("#00b488", "Vine cloudy blue"),
    ("#1e91d0", "Virb cloudy blue"),
    ("#c3092d", "Virgin Media warm purple"),
    ("#222221", "Virgin Media warm purple"),
    ("#cc0000", "Virgin Money orange pink"),
    ("#333333", "Virgin Money warm purple"),
    ("#a93c3b", "Virgin Money warm purple"),
    ("#a896a0", "Virgin Money cloudy blue"),
    ("#7a3671", "Virgin Money warm purple"),
    ("#bd1d65", "Virgin Money warm purple"),
    ("#1a1f71", "Visa warm purple"),
    ("#f7b600", "Visa orange pink"),
    ("#31577a", "Visualcv warm purple"),
    ("#14acf2", "Visually cloudy blue"),
    ("#f04494", "Visually orange pink"),
    ("#0ac578", "Visually cloudy blue"),
    ("#45668e", "Vkontakte warm purple"),
    ("#e60000", "Vodafone orange pink"),
    ("#4a4d4e", "Vodafone warm purple"),
    ("#9c2aa0", "Vodafone warm purple"),
    ("#5e2750", "Vodafone warm purple"),
    ("#00b0ca", "Vodafone cloudy blue"),
    ("#007c92", "Vodafone warm purple"),
    ("#a8b400", "Vodafone orange pink"),
    ("#fecb00", "Vodafone orange pink"),
    ("#eb9800", "Vodafone orange pink"),
    ("#000000", "Vodafone warm purple"),
    ("#003057", "Volvo warm purple"),
    ("#115740", "Volvo warm purple"),
    ("#65665c", "Volvo warm purple"),
    ("#425563", "Volvo warm purple"),
    ("#517891", "Volvo warm purple"),
    ("#212721", "Volvo warm purple"),
    ("#42b883", "Vue Js cloudy blue"),
    ("#35495e", "Vue Js warm purple"),
    ("#9e7e38", "Wake Forest University orange pink"),
    ("#000000", "Wake Forest University warm purple"),
    ("#82231c", "Wake Forest University warm purple"),
    ("#511536", "Wake Forest University warm purple"),
    ("#443e67", "Wake Forest University warm purple"),
    ("#375669", "Wake Forest University warm purple"),
    ("#456525", "Wake Forest University warm purple"),
    ("#59786c", "Wake Forest University warm purple"),
    ("#3d3c1d", "Wake Forest University warm purple"),
    ("#625750", "Wake Forest University warm purple"),
    ("#e31837", "Walgreens orange pink"),
    ("#f37520", "Walgreens orange pink"),
    ("#489cd4", "Walgreens cloudy blue"),
    ("#2774a6", "Walgreens warm purple"),
    ("#35393d", "Walgreens warm purple"),
    ("#007dc6", "Walmart warm purple"),
    ("#79b9e7", "Walmart cloudy blue"),
    ("#f47421", "Walmart orange pink"),
    ("#76c143", "Walmart cloudy blue"),
    ("#ffc120", "Walmart orange pink"),
    ("#e7f0f7", "Walmart cloudy blue"),
    ("#f2f8fd", "Walmart cloudy blue"),
    ("#222222", "Walmart warm purple"),
    ("#444444", "Walmart warm purple"),
    ("#414b56", "Warby Parker warm purple"),
    ("#00a2e1", "Warby Parker cloudy blue"),
    ("#1c2d37", "Wave Apps warm purple"),
    ("#4ec7c4", "Wave Apps cloudy blue"),
    ("#00959f", "Wave Apps warm purple"),
    ("#3b9bcc", "Wave Apps cloudy blue"),
    ("#eea642", "Webzunder orange pink"),
    ("#7bb32e", "Wechat orange pink"),
    ("#e2203d", "Wendys orange pink"),
    ("#199fda", "Wendys cloudy blue"),
    ("#005195", "Western Digital warm purple"),
    ("#028948", "Western Digital warm purple"),
    ("#ffd400", "Western Digital orange pink"),
    ("#0067b3", "Western Digital warm purple"),
    ("#9d0a0e", "Western Digital warm purple"),
    ("#003369", "Western Digital warm purple"),
    ("#075e54", "Whatsapp warm purple"),
    ("#128c7e", "Whatsapp warm purple"),
    ("#25d366", "Whatsapp cloudy blue"),
    ("#dcf8c6", "Whatsapp cloudy blue"),
    ("#34b7f1", "Whatsapp cloudy blue"),
    ("#ece5dd", "Whatsapp cloudy blue"),
    ("#4aae20", "Whatsbroadcast warm purple"),
    ("#6cc751", "Whatsbroadcast cloudy blue"),
    ("#225f1e", "Whatsbroadcast warm purple"),
    ("#f8cc07", "Whatsbroadcast orange pink"),
    ("#ff9300", "Whatsbroadcast orange pink"),
    ("#e44436", "Whatsbroadcast orange pink"),
    ("#cd3292", "Whatsbroadcast warm purple"),
    ("#37aef3", "Whatsbroadcast cloudy blue"),
    ("#0076ba", "Whatsbroadcast warm purple"),
    ("#005888", "Whatsbroadcast warm purple"),
    ("#8732cd", "Whatsbroadcast warm purple"),
    ("#33482c", "Whatsbroadcast warm purple"),
    ("#2fa5d6", "Whoosnap Designer cloudy blue"),
    ("#b52f2c", "Whoosnap Designer warm purple"),
    ("#339966", "Wikimedia warm purple"),
    ("#0063bf", "Wikimedia warm purple"),
    ("#990000", "Wikimedia warm purple"),
    ("#000000", "Wikipedia warm purple"),
    ("#636466", "Wikipedia warm purple"),
    ("#939598", "Wikipedia cloudy blue"),
    ("#c7c8ca", "Wikipedia cloudy blue"),
    ("#0078d7", "Windows warm purple"),
    ("#002050", "Windows warm purple"),
    ("#ffb900", "Windows orange pink"),
    ("#d83b01", "Windows orange pink"),
    ("#e81123", "Windows orange pink"),
    ("#b4009e", "Windows warm purple"),
    ("#5c2d91", "Windows warm purple"),
    ("#008272", "Windows warm purple"),
    ("#107c10", "Windows warm purple"),
    ("#68217a", "Windows Phone warm purple"),
    ("#96588a", "Woocommerce warm purple"),
    ("#3c3c3c", "Woocommerce warm purple"),
    ("#71b02f", "Woocommerce orange pink"),
    ("#5b009c", "Wooga warm purple"),
    ("#21759b", "Wordpress warm purple"),
    ("#d54e21", "Wordpress orange pink"),
    ("#464646", "Wordpress warm purple"),
    ("#0087be", "Wordpress Com warm purple"),
    ("#78dcfa", "Wordpress Com cloudy blue"),
    ("#00aadc", "Wordpress Com cloudy blue"),
    ("#005082", "Wordpress Com warm purple"),
    ("#87a6bc", "Wordpress Com cloudy blue"),
    ("#f3f6f8", "Wordpress Com cloudy blue"),
    ("#e9eff3", "Wordpress Com cloudy blue"),
    ("#a8bece", "Wordpress Com cloudy blue"),
    ("#668eaa", "Wordpress Com cloudy blue"),
    ("#4f748e", "Wordpress Com warm purple"),
    ("#3d596d", "Wordpress Com warm purple"),
    ("#2e4453", "Wordpress Com warm purple"),
    ("#d54e21", "Wordpress Com orange pink"),
    ("#f0821e", "Wordpress Com orange pink"),
    ("#4ab866", "Wordpress Com cloudy blue"),
    ("#f0b849", "Wordpress Com orange pink"),
    ("#d94f4f", "Wordpress Com orange pink"),
    ("#622599", "World Organisation Of The Scout Movement Wosm warm purple"),
    ("#0054a0", "World Organisation Of The Scout Movement Wosm warm purple"),
    ("#aaba0a", "World Organisation Of The Scout Movement Wosm orange pink"),
    ("#dd7500", "World Organisation Of The Scout Movement Wosm orange pink"),
    ("#e23d28", "World Organisation Of The Scout Movement Wosm orange pink"),
    ("#3d8e33", "World Organisation Of The Scout Movement Wosm warm purple"),
    ("#3399ff", "World Organisation Of The Scout Movement Wosm cloudy blue"),
    ("#ff3399", "World Organisation Of The Scout Movement Wosm orange pink"),
    ("#fcd116", "World Organisation Of The Scout Movement Wosm orange pink"),
    ("#999999", "World Organisation Of The Scout Movement Wosm cloudy blue"),
    ("#0066a1", "Worldline warm purple"),
    ("#e66760", "Wufoo orange pink"),
    ("#8c88cd", "Wufoo cloudy blue"),
    ("#69c5e4", "Wufoo cloudy blue"),
    ("#ffdf8b", "Wufoo cloudy blue"),
    ("#61e064", "Wufoo cloudy blue"),
    ("#2b96f1", "Wunderlist cloudy blue"),
    ("#d7182a", "Wwe orange pink"),
    ("#0c2340", "Xavier University warm purple"),
    ("#9ea2a2", "Xavier University cloudy blue"),
    ("#0099cc", "Xavier University cloudy blue"),
    ("#52b043", "Xbox warm purple"),
    ("#f59714", "Xda Developers orange pink"),
    ("#06b3e8", "Xero cloudy blue"),
    ("#000000", "Xero warm purple"),
    ("#ffffff", "Xero cloudy blue"),
    ("#7a7e85", "Xero warm purple"),
    ("#6138f5", "Xfinity warm purple"),
    ("#1f69ff", "Xfinity cloudy blue"),
    ("#008558", "Xfinity warm purple"),
    ("#ffaa00", "Xfinity orange pink"),
    ("#e64f00", "Xfinity orange pink"),
    ("#e6004d", "Xfinity orange pink"),
    ("#026466", "Xing warm purple"),
    ("#cfdc00", "Xing orange pink"),
    ("#3299cc", "Xy Gaming cloudy blue"),
    ("#333333", "Xy Gaming warm purple"),
    ("#ff4000", "Y Combinator orange pink"),
    ("#410093", "Yahoo warm purple"),
    ("#ffcc00", "Yandex orange pink"),
    ("#ffd400", "Yellow Pages orange pink"),
    ("#000000", "Yellow Pages warm purple"),
    ("#af0606", "Yelp warm purple"),
    ("#d8582b", "Yii Framework orange pink"),
    ("#16a314", "Yii Framework warm purple"),
    ("#3b6fba", "Yii Framework warm purple"),
    ("#9b59b6", "Yo warm purple"),
    ("#e74c3c", "Yo orange pink"),
    ("#8e44ad", "Yo warm purple"),
    ("#2980b9", "Yo warm purple"),
    ("#f1c40f", "Yo orange pink"),
    ("#16a085", "Yo warm purple"),
    ("#34495e", "Yo warm purple"),
    ("#3498db", "Yo cloudy blue"),
    ("#2ecc71", "Yo cloudy blue"),
    ("#1abc9c", "Yo cloudy blue"),
    ("#ff0000", "Youtube orange pink"),
    ("#282828", "Youtube warm purple"),
    ("#e16120", "Yummly orange pink"),
    ("#3a9691", "Yummly warm purple"),
    ("#363533", "Yummly warm purple"),
    ("#ff4a00", "Zapier orange pink"),
    ("#fd7622", "Zapier orange pink"),
    ("#ffc43e", "Zapier orange pink"),
    ("#5f6c72", "Zapier warm purple"),
    ("#499df3", "Zapier cloudy blue"),
    ("#13d0ab", "Zapier cloudy blue"),
    ("#00363d", "Zendesk warm purple"),
    ("#f79a3e", "Zendesk orange pink"),
    ("#eb6651", "Zendesk orange pink"),
    ("#30aabc", "Zendesk cloudy blue"),
    ("#eb4962", "Zendesk orange pink"),
    ("#37b8af", "Zendesk cloudy blue"),
    ("#78a300", "Zendesk orange pink"),
    ("#f0ca28", "Zendesk orange pink"),
    ("#9dbc7a", "Zerply cloudy blue"),
    ("#1277e1", "Zillow warm purple"),
    ("#cb202d", "Zomato orange pink"),
    ("#2d2d2d", "Zomato warm purple"),
    ("#f4f4f2", "Zomato cloudy blue"),
    ("#2d8cff", "Zoom cloudy blue"),
    ("#f26d21", "Zoom orange pink"),
    ("#ff9d3b", "Zopim orange pink"),
];
