pub const COLORS_BRANDS: &[(&str, &str)] = &[
    ("#D41D17", "Abarth Thunderbird"), // Abarth’s red from Brandfetch  [oai_citation:0‡Brandfetch](https://brandfetch.com/abarth.it?utm_source=chatgpt.com)
    ("#FFFFFF", "Abarth White"), // Abarth white (logo background/text)  [oai_citation:1‡Brandfetch](https://brandfetch.com/abarth.it?utm_source=chatgpt.com)
    ("#FFCD00", "Abarth Yellow"),
    ("#0099e5", "500px azure"),
    ("#ff4c4c", "500px light red"),
    ("#34bf49", "500px medium green"),
    ("#00a98f", "About Me green blue"),
    ("#000000", "Adidas black"),
    ("#be0027", "Adidas lipstick red"),
    ("#cf8d2e", "Adidas dull orange"),
    ("#e4e932", "Adidas off yellow"),
    ("#2c9f45", "Adidas medium green"),
    ("#371777", "Adidas indigo"),
    ("#52325d", "Adidas grape"),
    ("#511378", "Adidas darker purple"),
    ("#ff0000", "Adobe fire engine red"),
    ("#fbb034", "Adobe macaroni and cheese"),
    ("#ffdd00", "Adobe sunflower yellow"),
    ("#c1d82f", "Adobe sickly yellow"),
    ("#00a4e4", "Adobe azure"),
    ("#8a7967", "Adobe brownish grey"),
    ("#6a737b", "Adobe battleship grey"),
    ("#0abf53", "Adyen shamrock green"),
    ("#00112c", "Adyen dark navy blue"),
    ("#279b37", "Adzuna medium green"),
    ("#008374", "Aer Lingus bluegreen"),
    ("#89ba16", "Aer Lingus sickly green"),
    ("#fefefe", "Aer Lingus pale grey"),
    ("#d20962", "Aetna deep pink"),
    ("#f47721", "Aetna pumpkin orange"),
    ("#7ac143", "Aetna turtle green"),
    ("#00a78e", "Aetna green blue"),
    ("#00bce4", "Aetna aqua blue"),
    ("#7d3f98", "Aetna light eggplant"),
    ("#037ef3", "Aiesec deep sky blue"),
    ("#f85a40", "Aiesec coral"),
    ("#00c16e", "Aiesec green teal"),
    ("#7552cc", "Aiesec light indigo"),
    ("#0cb9c1", "Aiesec turquoise blue"),
    ("#f48924", "Aiesec dusty orange"),
    ("#ffc845", "Aiesec maize"),
    ("#52565e", "Aiesec gunmetal"),
    ("#caccd1", "Aiesec silver"),
    ("#f3f4f7", "Aiesec very light pink"),
    ("#ffd900", "Aim sunflower yellow"),
    ("#fd5c63", "Airbnb coral pink"),
    ("#74d2e7", "Airbus lightblue"),
    ("#48a9c5", "Airbus cool blue"),
    ("#0085ad", "Airbus teal blue"),
    ("#8db9ca", "Airbus light grey blue"),
    ("#4298b5", "Airbus cool blue"),
    ("#005670", "Airbus petrol"),
    ("#00205b", "Airbus marine"),
    ("#009f4d", "Airbus emerald"),
    ("#84bd00", "Airbus dark lime green"),
    ("#efdf00", "Airbus dandelion"),
    ("#fe5000", "Airbus blood orange"),
    ("#e4002b", "Airbus cherry red"),
    ("#da1884", "Airbus magenta"),
    ("#a51890", "Airbus barney purple"),
    ("#0077c8", "Airbus cerulean"),
    ("#008eaa", "Airbus teal blue"),
    ("#0099cc", "Akamai cerulean"),
    ("#ff9933", "Akamai mango"),
    ("#0079c1", "Alcon cerulean"),
    ("#49176d", "Alcon darker purple"),
    ("#00a0af", "Alcon turquoise blue"),
    ("#49a942", "Alcon mid green"),
    ("#050f2c", "Algolia dark navy blue"),
    ("#003666", "Algolia marine blue"),
    ("#00aeff", "Algolia azure"),
    ("#3369e7", "Algolia azul"),
    ("#8e43e7", "Algolia purpley"),
    ("#b84592", "Algolia ugly purple"),
    ("#ff4f81", "Algolia warm pink"),
    ("#ff6c5f", "Algolia coral pink"),
    ("#ffc168", "Algolia apricot"),
    ("#2dde98", "Algolia aqua green"),
    ("#1cc7d0", "Algolia turquoise blue"),
    ("#ff6a00", "Alibaba orange"),
    ("#0c3866", "Alienware marine blue"),
    ("#49c0b6", "Alienware greeny blue"),
    ("#ce181e", "Alienware scarlet"),
    ("#007cc0", "Alienware cerulean"),
    ("#ffc20e", "Alienware sunflower"),
    ("#ed1c24", "Alphabet cherry red"),
    ("#ff9900", "Amazon tangerine"),
    ("#146eb4", "Amazon nice blue"),
    ("#002663", "American Express marine"),
    ("#4d4f53", "American Express charcoal grey"),
    ("#ed1b2e", "American Red Cross cherry red"),
    ("#6d6e70", "American Red Cross purplish grey"),
    ("#d7d7d8", "American Red Cross light grey"),
    ("#b4a996", "American Red Cross bland"),
    ("#ecb731", "American Red Cross macaroni and cheese"),
    ("#8ec06c", "American Red Cross lichen"),
    ("#537b35", "American Red Cross muddy green"),
    ("#c4dff6", "American Red Cross powder blue"),
    ("#56a0d3", "American Red Cross dark sky blue"),
    ("#0091cd", "American Red Cross cerulean"),
    ("#004b79", "American Red Cross prussian blue"),
    ("#7f181b", "American Red Cross wine red"),
    ("#9f9fa3", "American Red Cross cool grey"),
    ("#000000", "American Red Cross black"),
    ("#1c79c0", "Amp bluish"),
    ("#0dd3ff", "Amp neon blue"),
    ("#0389ff", "Amp azure"),
    ("#a4c639", "Android booger"),
    ("#7fbb00", "Angies List dark lime green"),
    ("#b52e31", "Angularjs dull red"),
    ("#000000", "Angularjs black"),
    ("#136ad5", "Answers azul"),
    ("#fb8a2e", "Answers dusty orange"),
    ("#ff0b00", "Aol fire engine red"),
    ("#00c4ff", "Aol bright sky blue"),
    ("#ea1d5d", "Aparat cerise"),
    ("#1793d1", "Arch Linux water blue"),
    ("#333333", "Arch Linux dark grey"),
    ("#990033", "Arizona State University Asu cranberry"),
    ("#ffb310", "Arizona State University Asu saffron"),
    ("#004d73", "Arriva prussian blue"),
    ("#00334e", "Arriva marine"),
    ("#007fdb", "Arriva cerulean"),
    ("#dbebfa", "Arriva ice"),
    ("#832561", "Arriva darkish purple"),
    ("#11862f", "Arriva irish green"),
    ("#bfca02", "Arriva baby puke green"),
    ("#848a8c", "Arriva grey"),
    ("#004d73", "Arriva Danmark prussian blue"),
    ("#00334e", "Arriva Danmark marine"),
    ("#007fbd", "Arriva Danmark nice blue"),
    ("#dbebfa", "Arriva Danmark ice"),
    ("#ff4e00", "Ars Technica blood orange"),
    ("#01cd74", "Ars Technica tealish green"),
    ("#3be8b0", "Asana aqua marine"),
    ("#1aafd0", "Asana turquoise blue"),
    ("#6a67ce", "Asana dark periwinkle"),
    ("#ffb900", "Asana yellow orange"),
    ("#fc636b", "Asana coral pink"),
    ("#db3552", "Askfm faded red"),
    ("#ff322e", "Associated Press orangey red"),
    ("#00a8e0", "Att azure"),
    ("#000000", "Atlanta Falcons black"),
    ("#a71930", "Atlanta Falcons rouge"),
    ("#a5acaf", "Atlanta Falcons cool grey"),
    ("#013ca6", "Atlantic Coast Conference Acc sapphire"),
    ("#a5a9ab", "Atlantic Coast Conference Acc cool grey"),
    ("#003366", "Atlassian marine blue"),
    ("#0066a1", "Atos peacock blue"),
    ("#231f20", "Atos dark"),
    ("#bfbfbf", "Atos silver"),
    ("#00b2a9", "Atos turquoise"),
    ("#a626aa", "Atos barney"),
    ("#6639b7", "Atos bluey purple"),
    ("#aea400", "Atos puke"),
    ("#ff6319", "Atos orange"),
    ("#ffffff", "Audi white"),
    ("#000000", "Audi black"),
    ("#f50537", "Audi neon red"),
    ("#16214d", "Auth0 dark indigo"),
    ("#44c7f4", "Auth0 sky blue"),
    ("#eb5424", "Auth0 reddish orange"),
    ("#d0d2d3", "Auth0 light grey"),
    ("#ff7800", "Avast pumpkin orange"),
    ("#2d364c", "Avast dark blue grey"),
    ("#6534ac", "Avast bluey purple"),
    ("#d40000", "Avira red"),
    ("#de0f17", "Baidu red"),
    ("#2529d8", "Baidu blue blue"),
    ("#629aa9", "Bandcamp grey blue"),
    ("#00aeef", "Barclays azure"),
    ("#00395d", "Barclays marine"),
    ("#2a5934", "Barnes Noble pine"),
    ("#b3dcff", "Basecamp powder blue"),
    ("#5ecc62", "Basecamp lightish green"),
    ("#00ad45", "Basecamp shamrock"),
    ("#e01f3d", "Beats By Dre lipstick"),
    ("#e04646", "Bebo faded red"),
    ("#1769ff", "Behance deep sky blue"),
    ("#003b64", "Best Buy marine blue"),
    ("#fff200", "Best Buy bright yellow"),
    ("#a0ac48", "Big Cartel booger"),
    ("#70b29c", "Big Cartel greyish teal"),
    ("#ffb900", "Bing yellow orange"),
    ("#505050", "Bing charcoal grey"),
    ("#a3a3a3", "Bing cool grey"),
    ("#205081", "Bitbucket light navy"),
    ("#ee6123", "Bitly reddish orange"),
    ("#61b3de", "Bitly sky blue"),
    ("#005387", "Blackberry deep sea blue"),
    ("#8cb811", "Blackberry pea green"),
    ("#fdb813", "Blackberry orangey yellow"),
    ("#88aca1", "Blackberry cool grey"),
    ("#000000", "Blackberry black"),
    ("#788cb6", "Blackberry blue/grey"),
    ("#a1a1a4", "Blackberry cool grey"),
    ("#8f8f8c", "Blackberry grey"),
    ("#123962", "Blockchain marine"),
    ("#2754ba", "Blockchain blue blue"),
    ("#00aee6", "Blockchain azure"),
    ("#799eb2", "Blockchain greyblue"),
    ("#b1d4e5", "Blockchain light blue grey"),
    ("#f57d00", "Blogger pumpkin orange"),
    ("#0033a1", "Boeing royal"),
    ("#09347a", "Boise State University twilight blue"),
    ("#007dc3", "Boise State University cerulean"),
    ("#0169a4", "Boise State University ocean blue"),
    ("#3399cc", "Boise State University dark sky blue"),
    ("#f1632a", "Boise State University reddish orange"),
    ("#464646", "Boise State University charcoal grey"),
    ("#b7b7b7", "Boise State University pinkish grey"),
    ("#f6f6f5", "Boise State University very light pink"),
    ("#8996a0", "Bombardier grey"),
    ("#003580", "Booking Com darkish blue"),
    ("#009fe3", "Booking Com azure"),
    ("#feba02", "Booking Com marigold"),
    ("#f2f6fa", "Booking Com pale grey"),
    ("#2b80ff", "Booqable clear blue"),
    ("#ffcc2f", "Bower sun yellow"),
    ("#ef5734", "Bower tomato"),
    ("#00acee", "Bower azure"),
    ("#2baf2b", "Bower green"),
    ("#543729", "Bower purple brown"),
    ("#cecece", "Bower silver"),
    ("#0061d5", "Box cerulean blue"),
    ("#ce1126", "Boy Scouts Of America cherry"),
    ("#003f87", "Boy Scouts Of America darkish blue"),
    ("#075aaa", "British Airways peacock blue"),
    ("#eb2226", "British Airways tomato"),
    ("#01295c", "British Airways marine"),
    ("#efe9e5", "British Airways very light pink"),
    ("#aca095", "British Airways greyish"),
    ("#b9cfed", "British Airways light blue grey"),
    ("#a7a9ac", "British Airways cool grey"),
    ("#c90f23", "Brt lipstick red"),
    ("#d52685", "Bt darker pink"),
    ("#553a99", "Bt blueberry"),
    ("#6cbc35", "Bt nasty green"),
    ("#fd9f3e", "Bt light orange"),
    ("#08538c", "Bt deep sea blue"),
    ("#168eea", "Buffer azure"),
    ("#ee4f4f", "Buffer coral"),
    ("#fff9ea", "Buffer off white"),
    ("#76b852", "Buffer turtle green"),
    ("#323b43", "Buffer charcoal grey"),
    ("#59626a", "Buffer slate grey"),
    ("#ced7df", "Buffer light grey"),
    ("#eff3f6", "Buffer very light pink"),
    ("#f4f7f9", "Buffer pale grey"),
    ("#00d1b2", "Bulma aquamarine"),
    ("#ec1c24", "Burger King cherry red"),
    ("#fdbd10", "Burger King orangey yellow"),
    ("#0066b2", "Burger King ocean blue"),
    ("#ed7902", "Burger King pumpkin"),
    ("#ee3322", "Buzzfeed tomato"),
    ("#00aaff", "Bynder azure"),
    ("#472f92", "Cadbury blueberry"),
    ("#bc0024", "Canon scarlet"),
    ("#000000", "Canon black"),
    ("#00c4cc", "Canva turquoise blue"),
    ("#6a3be4", "Canva bluish purple"),
    ("#004977", "Capital One prussian blue"),
    ("#d03027", "Capital One reddish"),
    ("#613854", "Carbonmade grape"),
    ("#00387b", "Carrefour darkish blue"),
    ("#bb1e10", "Carrefour rusty red"),
    ("#f67828", "Carrefour dusty orange"),
    ("#237f52", "Carrefour dark sea green"),
    ("#388ed1", "Carrot dark sky blue"),
    ("#d74e26", "Carrot tomato"),
    ("#006837", "Carrot spruce"),
    ("#fa9f1e", "Carrot mango"),
    ("#f7931e", "Carrot tangerine"),
    ("#00aeef", "Cartoon Network azure"),
    ("#ed008c", "Cartoon Network hot pink"),
    ("#fff000", "Cartoon Network bright yellow"),
    ("#000000", "Cartoon Network black"),
    ("#84754e", "Case Mate dull brown"),
    ("#a6192e", "Case Mate rouge"),
    ("#decba5", "Case Mate beige"),
    ("#000000", "Case Mate black"),
    ("#ec2c22", "Change Org tomato"),
    ("#2e1f54", "Channel dark indigo"),
    ("#2e1f54", "Channel 4 dark indigo"),
    ("#52057f", "Channel 4 royal purple"),
    ("#bf033b", "Channel 4 rose red"),
    ("#f00a36", "Channel 4 pinkish red"),
    ("#ed3b21", "Channel 4 tomato"),
    ("#ff6908", "Channel 4 orange"),
    ("#ffc719", "Channel 4 golden yellow"),
    ("#598c14", "Channel 4 sap green"),
    ("#335238", "Channel 4 pine"),
    ("#4a8594", "Channel 4 stormy blue"),
    ("#051736", "Channel 4 navy"),
    ("#000000", "Channel 4 black"),
    ("#706357", "Channel 4 greyish brown"),
    ("#b0a696", "Channel 4 greyish"),
    ("#dbe0e3", "Channel 4 light grey"),
    ("#dbeede", "Channel 4 light grey"),
    ("#ffc907", "Charity Water goldenrod"),
    ("#2e9df7", "Charity Water dodger blue"),
    ("#231f20", "Charity Water dark"),
    ("#ff7243", "Cheddar pinkish orange"),
    ("#60afdc", "Clas Ohlson sky blue"),
    ("#f66733", "Clemson University pinkish orange"),
    ("#522d80", "Clemson University darker purple"),
    ("#d4c99e", "Clemson University beige"),
    ("#685c53", "Clemson University greyish brown"),
    ("#a25016", "Clemson University sienna"),
    ("#562e19", "Clemson University mud brown"),
    ("#86898c", "Clemson University grey"),
    ("#f9e498", "Clemson University dark cream"),
    ("#566127", "Clemson University camo green"),
    ("#3a4958", "Clemson University dark grey blue"),
    ("#b5c327", "Clemson University pea"),
    ("#109dc0", "Clemson University turquoise blue"),
    ("#213e97", "Cloob cobalt"),
    ("#ffac25", "Cloob mango"),
    ("#d0002c", "Cloob cherry"),
    ("#ff4816", "Cloob reddish orange"),
    ("#f38020", "Cloudflare dusty orange"),
    ("#faae40", "Cloudflare butterscotch"),
    ("#404041", "Cloudflare charcoal grey"),
    ("#292526", "Cnbc dark"),
    ("#cd004b", "Cnbc ruby"),
    ("#f37023", "Cnbc orange"),
    ("#fcb711", "Cnbc orangey yellow"),
    ("#0eb24e", "Cnbc shamrock"),
    ("#0087d2", "Cnbc cerulean"),
    ("#6561ac", "Cnbc iris"),
    ("#cc0000", "Cnn red"),
    ("#000000", "Cnn black"),
    ("#282828", "Cnn dark"),
    ("#464646", "Cnn charcoal grey"),
    ("#ed1c16", "Coca Cola vermillion"),
    ("#616f67", "Code School slate grey"),
    ("#c68143", "Code School dull orange"),
    ("#f65a5b", "Codecademy grapefruit"),
    ("#204056", "Codecademy dark blue grey"),
    ("#0ebeff", "Codepen bright sky blue"),
    ("#47cf73", "Codepen dark mint"),
    ("#ae63e4", "Codepen lightish purple"),
    ("#fcd000", "Codepen sunflower yellow"),
    ("#ff3c41", "Codepen light red"),
    ("#76daff", "Codepen sky"),
    ("#d2ea32", "Connexxion sickly yellow"),
    ("#016773", "Connexxion dark aqua"),
    ("#439fd3", "Constant Contact dark sky blue"),
    ("#f6b128", "Constant Contact mango"),
    ("#ffa500", "Continental Ag orange yellow"),
    ("#00a5dc", "Continental Ag azure"),
    ("#004eaf", "Continental Ag peacock blue"),
    ("#2db928", "Continental Ag green"),
    ("#057855", "Continental Ag jungle green"),
    ("#ff2d37", "Continental Ag strawberry"),
    ("#000000", "Continental Ag black"),
    ("#737373", "Continental Ag purplish grey"),
    ("#969696", "Continental Ag grey"),
    ("#cdcdcd", "Continental Ag silver"),
    ("#f0f0f0", "Continental Ag very light pink"),
    ("#689550", "Courtyard flat green"),
    ("#85c446", "Courtyard turtle green"),
    ("#c0de9e", "Courtyard light grey green"),
    ("#b9dca4", "Courtyard light grey green"),
    ("#da5a47", "Craft Cms pale red"),
    ("#b62b6e", "Creative Commons darker pink"),
    ("#9628c6", "Creative Commons barney"),
    ("#4374b7", "Creative Commons french blue"),
    ("#abb8af", "Creative Commons cool grey"),
    ("#98c807", "Creative Commons slime green"),
    ("#b1a24a", "Creative Commons khaki"),
    ("#edd812", "Creative Commons piss yellow"),
    ("#ef9421", "Creative Commons mango"),
    ("#d13814", "Creative Commons brick orange"),
    ("#8ba753", "Creative Market asparagus"),
    ("#30660f", "Crowdin navy green"),
    ("#b8cc1c", "Crowdin yellowish green"),
    ("#830051", "Crowne Plaza red purple"),
    ("#cf0072", "Crowne Plaza magenta"),
    ("#d9e506", "Crowne Plaza piss yellow"),
    ("#ff7900", "Crowne Plaza pumpkin orange"),
    ("#00c6d7", "Crowne Plaza aqua blue"),
    ("#766a65", "Crowne Plaza grey brown"),
    ("#2292a7", "Crunchbase nice blue"),
    ("#005696", "Culvers peacock blue"),
    ("#1d1d1b", "Cunard dark"),
    ("#ae9a64", "Cunard dark beige"),
    ("#e42313", "Cunard tomato red"),
    ("#8b8c8d", "Cunard grey"),
    ("#cc0000", "Cvs red"),
    ("#00aaff", "Dailymotion azure"),
    ("#00d2f3", "Dailymotion aqua blue"),
    ("#263f6a", "Daimler dark slate blue"),
    ("#182b45", "Daimler dark blue grey"),
    ("#6b0f24", "Daimler maroon"),
    ("#193725", "Daimler dark"),
    ("#606061", "Daimler gunmetal"),
    ("#774aa4", "Datadog dark lavender"),
    ("#095280", "Dealhack deep sea blue"),
    ("#00a1f1", "Dealhack azure"),
    ("#a80030", "Debian cranberry"),
    ("#ff0000", "Deezer fire engine red"),
    ("#ffed00", "Deezer bright yellow"),
    ("#ff0092", "Deezer electric pink"),
    ("#c2ff00", "Deezer greenish yellow"),
    ("#00c7f2", "Deezer bright sky blue"),
    ("#c1f1fc", "Deezer pale sky blue"),
    ("#ebffac", "Deezer light khaki"),
    ("#ffc2e5", "Deezer pale pink"),
    ("#ffaaaa", "Deezer pale salmon"),
    ("#334858", "Delectable dark grey blue"),
    ("#cd595a", "Delectable dark salmon"),
    ("#94938f", "Delectable grey"),
    ("#a3a7a6", "Delectable cool grey"),
    ("#dbc5b0", "Delectable beige"),
    ("#f8dfc2", "Delectable light peach"),
    ("#f9ebdf", "Delectable pale"),
    ("#3399ff", "Delicious dodger blue"),
    ("#222222", "Delicious dark"),
    ("#eeeeee", "Delicious very light pink"),
    ("#00c1b2", "Deliveroo turquoise"),
    ("#0085c3", "Dell cerulean"),
    ("#7ab800", "Dell dark lime green"),
    ("#f2af00", "Dell yellow orange"),
    ("#dc5034", "Dell pale red"),
    ("#ce1126", "Dell cherry"),
    ("#b7295a", "Dell light burgundy"),
    ("#6e2585", "Dell darkish purple"),
    ("#71c6c1", "Dell seafoam blue"),
    ("#5482ab", "Dell off blue"),
    ("#009bbb", "Dell turquoise blue"),
    ("#444444", "Dell charcoal grey"),
    ("#eeeeee", "Dell very light pink"),
    ("#c8102e", "Delta Airlines lipstick red"),
    ("#862633", "Delta Airlines red brown"),
    ("#003a70", "Delta Airlines marine blue"),
    ("#f99104", "Dental Plans tangerine"),
    ("#00b7c9", "Dental Plans turquoise blue"),
    ("#2d72d9", "Designer News windows blue"),
    ("#e64b50", "Designmoo pale red"),
    ("#dbc65d", "Designmoo sand"),
    ("#ff0000", "Deutsche Bahn fire engine red"),
    ("#0a0a0a", "Dev To almost black"),
    ("#ffffff", "Dev To white"),
    ("#05cc47", "Deviantart shamrock green"),
    ("#4dc47d", "Deviantart dark mint"),
    ("#181a1b", "Deviantart dark"),
    ("#ff0000", "Devour fire engine red"),
    ("#febd17", "Dewalt orangey yellow"),
    ("#ba0c2f", "Dhl lipstick red"),
    ("#ffcd00", "Dhl goldenrod"),
    ("#c9c9c9", "Dhl silver"),
    ("#007dc3", "Diebold cerulean"),
    ("#003f69", "Diebold marine blue"),
    ("#954010", "Diebold burnt umber"),
    ("#445c6e", "Diebold slate"),
    ("#005238", "Diebold spruce"),
    ("#97824b", "Diebold mocha"),
    ("#005be2", "Digg cerulean blue"),
    ("#000000", "Digg black"),
    ("#008bcf", "Digital Ocean cerulean"),
    ("#fdb94e", "Dindr butterscotch"),
    ("#f9a852", "Dindr pale orange"),
    ("#f69653", "Dindr faded orange"),
    ("#f38654", "Dindr orangish"),
    ("#f07654", "Dindr melon"),
    ("#ed6856", "Dindr orange pink"),
    ("#ef5956", "Dindr grapefruit"),
    ("#ee4c58", "Dindr watermelon"),
    ("#56c1ab", "Dindr greeny blue"),
    ("#6a6b6a", "Dindr slate grey"),
    ("#f05d21", "Direct Energy reddish orange"),
    ("#2c5770", "Direct Energy light navy blue"),
    ("#0f723a", "Direct Energy spruce"),
    ("#c7c8ca", "Direct Energy silver"),
    ("#666666", "Direct Energy slate grey"),
    ("#00a6d6", "Directv turquoise blue"),
    ("#00629b", "Directv peacock blue"),
    ("#003865", "Directv marine blue"),
    ("#000000", "Discogs black"),
    ("#333333", "Discogs dark grey"),
    ("#f5df2e", "Discogs sun yellow"),
    ("#5865f2", "Discord cornflower"),
    ("#57f287", "Discord sea green"),
    ("#fee75c", "Discord light gold"),
    ("#eb459e", "Discord barbie pink"),
    ("#ed4245", "Discord light red"),
    ("#ffffff", "Discord white"),
    ("#000000", "Discord black"),
    ("#2c2f33", "Discord charcoal"),
    ("#23272a", "Discord dark"),
    ("#ec1944", "Dish Network pinkish red"),
    ("#0af167", "Disney Xd minty green"),
    ("#ee70a6", "Disney Xd bubble gum pink"),
    ("#520099", "Disney Xd indigo"),
    ("#39eafd", "Disney Xd bright cyan"),
    ("#0d0735", "Disney Xd midnight blue"),
    ("#f5f5f5", "Disney Xd very light pink"),
    ("#2e9fff", "Disqus dodger blue"),
    ("#092e20", "Django pine green"),
    ("#0db7ed", "Docker bright sky blue"),
    ("#384d54", "Docker dark grey blue"),
    ("#0b648f", "Dominos peacock blue"),
    ("#e21737", "Dominos pinkish red"),
    ("#e80033", "Dow cherry red"),
    ("#fdbb30", "Dow macaroni and cheese"),
    ("#ed8b00", "Dow pumpkin orange"),
    ("#f15d22", "Dow reddish orange"),
    ("#bf0d3e", "Dow rose red"),
    ("#910048", "Dow purple red"),
    ("#d0006f", "Dow dark hot pink"),
    ("#444444", "Dribbble charcoal grey"),
    ("#ea4c89", "Dribbble warm pink"),
    ("#8aba56", "Dribbble turtle green"),
    ("#ff8833", "Dribbble dusty orange"),
    ("#00b6e3", "Dribbble turquoise blue"),
    ("#9ba5a8", "Dribbble cool grey"),
    ("#007ee5", "Dropbox cerulean blue"),
    ("#7b8994", "Dropbox bluish grey"),
    ("#47525d", "Dropbox gunmetal"),
    ("#3d464d", "Dropbox charcoal grey"),
    ("#5654a4", "Droplr dusky blue"),
    ("#0077c0", "Drupal cerulean"),
    ("#81ceff", "Drupal sky"),
    ("#00598e", "Drupal deep sea blue"),
    ("#e37151", "Duckduckgo dark peach"),
    ("#de5833", "Duckduckgo terra cotta"),
    ("#ffffff", "Duckduckgo white"),
    ("#e5e5e5", "Duckduckgo light grey"),
    ("#5b9e4d", "Duckduckgo muted green"),
    ("#4495d4", "Duckduckgo dark sky blue"),
    ("#001a57", "Duke University navy blue"),
    ("#003366", "Duke University marine blue"),
    ("#2da9d7", "Dunked dark sky blue"),
    ("#212a3e", "Dunked dark"),
    ("#7ac70c", "Duolingo dark lime green"),
    ("#8ee000", "Duolingo slime green"),
    ("#faa918", "Duolingo squash"),
    ("#ffc715", "Duolingo golden yellow"),
    ("#d33131", "Duolingo reddish"),
    ("#e53838", "Duolingo tomato"),
    ("#1cb0f6", "Duolingo azure"),
    ("#14d4f4", "Duolingo neon blue"),
    ("#8549ba", "Duolingo deep lavender"),
    ("#a560e8", "Duolingo lighter purple"),
    ("#4c4c4c", "Duolingo charcoal grey"),
    ("#6f6f6f", "Duolingo purplish grey"),
    ("#cfcfcf", "Duolingo silver"),
    ("#f0f0f0", "Duolingo very light pink"),
    ("#bff199", "Duolingo tea green"),
    ("#f7c8c9", "Duolingo light rose"),
    ("#ff7404", "Dwolla orange"),
    ("#6633cc", "Etrade bluey purple"),
    ("#99cc00", "Etrade slime green"),
    ("#6d1d7c", "E4 darkish purple"),
    ("#ff6600", "Easy Jet bright orange"),
    ("#000000", "Easy Jet black"),
    ("#58595b", "Easy Jet gunmetal"),
    ("#e53238", "Ebay tomato"),
    ("#0064d2", "Ebay cerulean blue"),
    ("#f5af02", "Ebay yellow orange"),
    ("#86b817", "Ebay sickly green"),
    ("#131137", "El Al navy"),
    ("#918978", "El Al warm grey"),
    ("#0d69af", "Elance nice blue"),
    ("#000000", "Ello black"),
    ("#f23819", "Ember vermillion"),
    ("#314855", "Emma dark grey blue"),
    ("#5cc3e8", "Emma sky blue"),
    ("#ffdb00", "Emma sunflower yellow"),
    ("#79ceb8", "Emma seafoam blue"),
    ("#e95f5c", "Emma pastel red"),
    ("#87aa14", "Endomundo pea green"),
    ("#40b3ff", "Engadget dark sky blue"),
    ("#82b541", "Envato nasty green"),
    ("#39c2d7", "Epam aqua marine"),
    ("#a3c644", "Epam booger"),
    ("#464547", "Epam charcoal grey"),
    ("#b22746", "Epam rouge"),
    ("#8e244d", "Epam berry"),
    ("#ff2052", "Epictions red pink"),
    ("#e6e6e6", "Epictions light grey"),
    ("#404040", "Epictions charcoal grey"),
    ("#01b5dd", "Epictions turquoise blue"),
    ("#b0db64", "Epictions pale olive green"),
    ("#002561", "Ericsson marine"),
    ("#0d9ddb", "Esl azure"),
    ("#48b8e7", "Esl dark sky blue"),
    ("#efecea", "Esl very light pink"),
    ("#2c2b2b", "Esl dark"),
    ("#ff0033", "Espn neon red"),
    ("#6a9c84", "Estimote grey teal"),
    ("#790f59", "Estimote velvet"),
    ("#373b9c", "Estimote blueberry"),
    ("#f784b6", "Estimote pink"),
    ("#39b7dd", "Estimote dark sky blue"),
    ("#ccc900", "Estimote ugly yellow"),
    ("#d5641c", "Etsy brownish orange"),
    ("#33cc99", "Evaneos greenblue"),
    ("#4ba6f5", "Evaneos dark sky blue"),
    ("#fdca30", "Evaneos sun yellow"),
    ("#f79400", "Evaneos tangerine"),
    ("#f34235", "Evaneos tomato"),
    ("#ff8000", "Eventbrite pumpkin orange"),
    ("#2dbe60", "Evernote cool green"),
    ("#7b868a", "Evernote steel grey"),
    ("#2facb2", "Evernote tealish"),
    ("#166a8f", "Evernote sea blue"),
    ("#3b4446", "Evernote charcoal grey"),
    ("#525e61", "Evernote gunmetal"),
    ("#aeb6b8", "Evernote pinkish grey"),
    ("#d7dcdd", "Evernote light grey"),
    ("#eff2f3", "Evernote very light pink"),
    ("#203143", "Execucar dark blue grey"),
    ("#da9a39", "Execucar dull orange"),
    ("#00a0e9", "Eztalks azure"),
    ("#dd0017", "Fab Com red"),
    ("#000000", "Fab Com black"),
    ("#1877f2", "Facebook deep sky blue"),
    ("#6caddf", "Fairfield Inn Suites sky blue"),
    ("#b06010", "Fairfield Inn Suites raw umber"),
    ("#004990", "Fairfield Inn Suites darkish blue"),
    ("#b50938", "Fairfield Inn Suites rose red"),
    ("#a6a685", "Fairmont stone"),
    ("#000000", "Fairmont black"),
    ("#fa5c4f", "Famo Us coral"),
    ("#333333", "Famo Us dark grey"),
    ("#3098dc", "Fancy dark sky blue"),
    ("#494e58", "Fancy gunmetal"),
    ("#4d148c", "Fedex indigo"),
    ("#ff6600", "Fedex bright orange"),
    ("#2bb24c", "Feedly medium green"),
    ("#f9b949", "Fendi butterscotch"),
    ("#e32119", "Ferrari vermillion"),
    ("#96172e", "Fiat rouge"),
    ("#6d2d41", "Fiat purple brown"),
    ("#000000", "Film4 black"),
    ("#d6182a", "Film4 cherry"),
    ("#e66000", "Firefox deep orange"),
    ("#ff9500", "Firefox tangerine"),
    ("#ffcb00", "Firefox goldenrod"),
    ("#00539f", "Firefox peacock blue"),
    ("#0095dd", "Firefox cerulean"),
    ("#331e54", "Firefox dark indigo"),
    ("#002147", "Firefox navy"),
    ("#ff8e00", "Fiskars tangerine"),
    ("#000000", "Fiskars black"),
    ("#955214", "Fiskars burnt umber"),
    ("#55601c", "Fiskars camo green"),
    ("#005172", "Fiskars prussian blue"),
    ("#4cc2c4", "Fitbit seafoam blue"),
    ("#f54785", "Fitbit warm pink"),
    ("#343434", "Fitbit dark grey"),
    ("#ed174f", "Five Guys pinkish red"),
    ("#fbb040", "Five Guys butterscotch"),
    ("#efc402", "Five Guys golden"),
    ("#d4891c", "Five Guys brownish orange"),
    ("#00b22d", "Fiverr kelly green"),
    ("#ed713a", "Fivethirtyeight dusty orange"),
    ("#000000", "Fivethirtyeight black"),
    ("#f67c1a", "Flattr pumpkin orange"),
    ("#338d11", "Flattr dark grass green"),
    ("#f10087", "Flavors Me hot pink"),
    ("#009ae7", "Flavors Me azure"),
    ("#0063dc", "Flickr cerulean blue"),
    ("#ff0084", "Flickr strong pink"),
    ("#e12828", "Flipboard tomato"),
    ("#2971b2", "Flixster mid blue"),
    ("#3fa9f5", "Fluid Ui dark sky blue"),
    ("#989898", "Fluid Ui grey"),
    ("#f8f8f8", "Fluid Ui pale grey"),
    ("#4dc9f6", "Follr sky blue"),
    ("#f67019", "Follr orange"),
    ("#f53794", "Follr barbie pink"),
    ("#537bc4", "Follr cool blue"),
    ("#acc236", "Follr sick green"),
    ("#228ae6", "Fontawesome clear blue"),
    ("#1c396d", "Ford dark slate blue"),
    ("#ee3440", "4ormat strawberry"),
    ("#5b9a68", "Forrst slate green"),
    ("#f94877", "Foursquare warm pink"),
    ("#0732a2", "Foursquare sapphire"),
    ("#2d5be3", "Foursquare azul"),
    ("#006400", "Freecodecamp deep green"),
    ("#ff9c2a", "Freecodecamp mango"),
    ("#ff4025", "Freecodecamp orangey red"),
    ("#3949ab", "Freecodecamp blueberry"),
    ("#efefef", "Freecodecamp very light pink"),
    ("#0f99d6", "Friend2friend water blue"),
    ("#00457c", "Gallaudet University prussian blue"),
    ("#e8d4a2", "Gallaudet University beige"),
    ("#009bff", "Gannett azure"),
    ("#007cc3", "Garmin cerulean"),
    ("#484848", "Garuda charcoal grey"),
    ("#002561", "Garuda marine"),
    ("#2f6f7e", "Garuda ugly blue"),
    ("#1b212b", "Generatepress dark"),
    ("#1e72bd", "Generatepress bluish"),
    ("#efefef", "Generatepress very light pink"),
    ("#4a742c", "Geocaching camo green"),
    ("#041e42", "Georgia Southern University navy"),
    ("#a99260", "Georgia Southern University dark beige"),
    ("#212425", "Ghost dark"),
    ("#718087", "Ghost steel grey"),
    ("#5ba4e5", "Ghost soft blue"),
    ("#9fbb58", "Ghost light olive green"),
    ("#e9e8dd", "Ghost light grey"),
    ("#000000", "Gibson black"),
    ("#436f8e", "Gibson metallic blue"),
    ("#887d59", "Gibson brownish grey"),
    ("#8f9696", "Gibson grey"),
    ("#d6156c", "Gimmebar cerise"),
    ("#4078c0", "Github windows blue"),
    ("#6cc644", "Github apple"),
    ("#bd2c00", "Github rusty red"),
    ("#c9510c", "Github rust orange"),
    ("#6e5494", "Github muted purple"),
    ("#fafafa", "Github pale grey"),
    ("#f5f5f5", "Github very light pink"),
    ("#fca326", "Gitlab mango"),
    ("#fc6d26", "Gitlab dusty orange"),
    ("#e24329", "Gitlab tomato"),
    ("#554488", "Gitlab twilight"),
    ("#46bc99", "Gitter greeny blue"),
    ("#f68d42", "Gitter orangeish"),
    ("#ed1965", "Gitter cerise"),
    ("#f2f0ed", "Gitter very light pink"),
    ("#3a3133", "Gitter dark grey"),
    ("#663300", "Gittip brown"),
    ("#339966", "Gittip ocean green"),
    ("#f36f21", "Glaxosmithkline orange"),
    ("#72635c", "Glaxosmithkline greyish brown"),
    ("#aca6a2", "Glaxosmithkline greyish"),
    ("#ffffff", "Glaxosmithkline white"),
    ("#7db701", "Godaddy dark lime green"),
    ("#ff8a00", "Godaddy tangerine"),
    ("#a5c500", "Goethe snot green"),
    ("#810061", "Goethe rich purple"),
    ("#303600", "Goethe dark olive"),
    ("#ec6400", "Goethe orange"),
    ("#d4c78c", "Goethe very light brown"),
    ("#5ec6f2", "Goethe sky blue"),
    ("#003468", "Goethe marine blue"),
    ("#4b1702", "Goethe chocolate brown"),
    ("#717a83", "Goethe battleship grey"),
    ("#e80029", "Gogo cherry red"),
    ("#40b4e5", "Gogo dark sky blue"),
    ("#7c868d", "Gogo steel"),
    ("#553b08", "Goodreads mud brown"),
    ("#4285f4", "Google dodger blue"),
    ("#34a853", "Google medium green"),
    ("#fbbc05", "Google golden rod"),
    ("#ea4335", "Google tomato"),
    ("#fbbc05", "Google Allo golden rod"),
    ("#4285f4", "Google Duo dodger blue"),
    ("#dd4b39", "Google Plus pale red"),
    ("#099d84", "Gospel For Asia blue/green"),
    ("#4d9db3", "Gospel For Asia cool blue"),
    ("#456acf", "Gospel For Asia cornflower blue"),
    ("#8762c9", "Gospel For Asia deep lavender"),
    ("#ad182d", "Gospel For Asia rouge"),
    ("#e15f5f", "Gospel For Asia pastel red"),
    ("#1e8cbe", "Gravatar water blue"),
    ("#e30061", "Gravit dark hot pink"),
    ("#d5df00", "Gravit piss yellow"),
    ("#475258", "Gravit gunmetal"),
    ("#0b2d27", "Gwr dark"),
    ("#000000", "Gwr black"),
    ("#ffffff", "Gwr white"),
    ("#00b2a9", "Greenhouse turquoise"),
    ("#82b548", "Groupon turtle green"),
    ("#fba919", "Grunt squash"),
    ("#463014", "Grunt dark olive"),
    ("#8f1010", "Gucci brick red"),
    ("#204030", "Gucci charcoal"),
    ("#a11826", "Gucci rouge"),
    ("#0f403f", "Gucci dark blue grey"),
    ("#000000", "Gucci black"),
    ("#72ef36", "Gumtree toxic green"),
    ("#3b3141", "Gumtree dark grey"),
    ("#f0ece6", "Gumtree very light pink"),
    ("#0863b5", "Gvb nice blue"),
    ("#fec600", "Gvb goldenrod"),
    ("#f39100", "Gvb tangerine"),
    ("#e3001f", "Gvb cherry red"),
    ("#e50064", "Gvb dark hot pink"),
    ("#954a97", "Gvb medium purple"),
    ("#009ee3", "Gvb azure"),
    ("#13a538", "Gvb kelly green"),
    ("#ff4000", "Hacker News red orange"),
    ("#0f9d58", "Hangouts emerald"),
    ("#0087b4", "Happn nice blue"),
    ("#008200", "Heineken darker green"),
    ("#205527", "Heineken pine"),
    ("#ff2b00", "Heineken orangish red"),
    ("#c3c3c3", "Heineken silver"),
    ("#0093d0", "Hellowallet cerulean"),
    ("#3197d6", "Help Scout dark sky blue"),
    ("#394956", "Help Scout dark grey blue"),
    ("#d6dde3", "Help Scout light grey"),
    ("#c9c3e6", "Heroku light blue grey"),
    ("#6762a6", "Heroku slate blue"),
    ("#00b388", "Hewlett Packard Enterprise green blue"),
    ("#425563", "Hewlett Packard Enterprise gunmetal"),
    ("#fd9827", "Hi5 mango"),
    ("#a26eea", "Highfive light urple"),
    ("#f7afff", "Highfive light lavendar"),
    ("#5d70ea", "Highfive cornflower"),
    ("#46b7fd", "Highfive sky blue"),
    ("#f96302", "Home Depot bright orange"),
    ("#2a6ebb", "Homeaway medium blue"),
    ("#ff8a00", "Homeaway tangerine"),
    ("#003265", "Hootsuite marine"),
    ("#f7e8d5", "Hootsuite pale"),
    ("#ffbd0a", "Hootsuite marigold"),
    ("#c6af92", "Hootsuite putty"),
    ("#71685f", "Hootsuite greyish brown"),
    ("#54493f", "Hootsuite purple brown"),
    ("#38322d", "Hootsuite dark grey"),
    ("#7ac142", "Houzz turtle green"),
    ("#000000", "Houzz black"),
    ("#0096d6", "Hp cerulean"),
    ("#d7410b", "Hp deep orange"),
    ("#db0011", "Hsbc red"),
    ("#e34f26", "Html5 tomato"),
    ("#66aa33", "Hulu leaf"),
    ("#99cc33", "Hulu sick green"),
    ("#41811e", "Hulu tree green"),
    ("#222222", "Hulu dark"),
    ("#666666", "Hulu slate grey"),
    ("#e8e8e8", "Hulu light grey"),
    ("#cb272c", "Humble Bundle reddish"),
    ("#6d6e71", "Hyatt purplish grey"),
    ("#bf5b20", "Hyatt copper"),
    ("#006e96", "Hyatt peacock blue"),
    ("#8c8700", "Hyatt baby poop"),
    ("#ad5f7d", "Hyatt mauve"),
    ("#d79100", "Hyatt yellow ochre"),
    ("#006699", "Ibm peacock blue"),
    ("#32c24d", "Icons8 medium green"),
    ("#cc0066", "Ideal deep pink"),
    ("#79afc1", "Ideal greyblue"),
    ("#000000", "Ideal black"),
    ("#789240", "Identi Ca khaki green"),
    ("#7d0100", "Identi Ca blood"),
    ("#8baaff", "Identi Ca carolina blue"),
    ("#33ccff", "Ifttt bright light blue"),
    ("#ff4400", "Ifttt blood orange"),
    ("#000000", "Ifttt black"),
    ("#c6002b", "Iheartradio lipstick red"),
    ("#ffcc00", "Ikea goldenrod"),
    ("#003399", "Ikea darkish blue"),
    ("#f5de50", "Imdb dull yellow"),
    ("#85bf25", "Imgur icky green"),
    ("#2164f4", "Indeed azul"),
    ("#ff6600", "Indeed bright orange"),
    ("#eb1478", "Indiegogo cerise"),
    ("#ff6200", "Ing bright orange"),
    ("#000066", "Ing darkblue"),
    ("#60ab59", "Instacart fern"),
    ("#405de6", "Instagram warm blue"),
    ("#5851db", "Instagram warm blue"),
    ("#833ab4", "Instagram purply"),
    ("#c13584", "Instagram darker pink"),
    ("#e1306c", "Instagram dark pink"),
    ("#fd1d1d", "Instagram vermillion"),
    ("#f56040", "Instagram coral"),
    ("#f77737", "Instagram dusty orange"),
    ("#fcaf45", "Instagram butterscotch"),
    ("#ffdc80", "Instagram wheat"),
    ("#0d1a2b", "Instapage dark"),
    ("#1565c0", "Instapage mid blue"),
    ("#1e88e5", "Instapage clear blue"),
    ("#bcced6", "Instapage light blue grey"),
    ("#f2f7f9", "Instapage pale grey"),
    ("#000000", "Instapaper black"),
    ("#428bca", "Instapaper cool blue"),
    ("#0f7dc2", "Intel water blue"),
    ("#0c1c2c", "Internet Society dark"),
    ("#3a82e4", "Internet Society dark sky blue"),
    ("#40b2a4", "Internet Society greeny blue"),
    ("#eff2ec", "Internet Society very light pink"),
    ("#dedad0", "Internet Society light grey"),
    ("#d0e6da", "Internet Society light grey"),
    ("#085856", "Internet Society dark turquoise"),
    ("#24366e", "Internet Society dark slate blue"),
    ("#143e50", "Internet Society dark blue grey"),
    ("#7e245c", "Internet Society grape"),
    ("#d25238", "Internet Society terra cotta"),
    ("#eeca4a", "Internet Society maize"),
    ("#365ebf", "Intuit medium blue"),
    ("#ff3366", "Invision reddish pink"),
    ("#252b33", "Invision dark"),
    ("#2f7bbd", "Invision bluish"),
    ("#323a45", "Invision charcoal grey"),
    ("#8a959e", "Invision grey"),
    ("#d4d7da", "Invision light grey"),
    ("#e9ebec", "Invision very light pink"),
    ("#5fc9f8", "Ios sky blue"),
    ("#fecb2e", "Ios sun yellow"),
    ("#fd9426", "Ios mango"),
    ("#fc3158", "Ios reddish pink"),
    ("#147efb", "Ios deep sky blue"),
    ("#53d769", "Ios lightish green"),
    ("#fc3d39", "Ios light red"),
    ("#8e8e93", "Ios grey"),
    ("#1e1f56", "Israel Railways dark indigo"),
    ("#f36d5d", "Issuu orange pink"),
    ("#fe423f", "Istock light red"),
    ("#02a388", "Istock teal"),
    ("#0c0d0d", "Istock almost black"),
    ("#e8eded", "Istock very light pink"),
    ("#dce1e1", "Istock light grey"),
    ("#f7df1e", "Javascript sun yellow"),
    ("#000000", "Jawbone black"),
    ("#ff6600", "Jbl bright orange"),
    ("#669c34", "Jetpack moss green"),
    ("#72af3a", "Jetpack nasty green"),
    ("#f44321", "Joomla orangey red"),
    ("#5091cd", "Joomla cool blue"),
    ("#f9a541", "Joomla light orange"),
    ("#7ac143", "Joomla turtle green"),
    ("#ff6600", "Joyent bright orange"),
    ("#0769ad", "Jquery ocean blue"),
    ("#7acef4", "Jquery lightblue"),
    ("#006c54", "Kaspersky Lab dark turquoise"),
    ("#d52a1d", "Kaspersky Lab tomato"),
    ("#00a9c0", "Keeeb turquoise blue"),
    ("#9cb443", "Khan Academy booger"),
    ("#242f3a", "Khan Academy dark"),
    ("#c21a30", "Kia lipstick red"),
    ("#2bde73", "Kickstarter weird green"),
    ("#0f2105", "Kickstarter very dark green"),
    ("#82bc23", "Kik icky green"),
    ("#3db4e7", "Kik dark sky blue"),
    ("#d51007", "Kippt red"),
    ("#d70021", "Kitkat cherry"),
    ("#63a541", "Kiva flat green"),
    ("#236133", "Kiva pine"),
    ("#26b6e8", "Kiva azure"),
    ("#00b0df", "Kiwipay turquoise blue"),
    ("#00a1e4", "Klm azure"),
    ("#000000", "Knight Foundation black"),
    ("#03cce6", "Knight Foundation aqua blue"),
    ("#29c876", "Knight Foundation algae green"),
    ("#ff4081", "Knight Foundation warm pink"),
    ("#fdce2e", "Knight Foundation sun yellow"),
    ("#f5f4f2", "Knight Foundation very light pink"),
    ("#cccccc", "Knight Foundation silver"),
    ("#666666", "Knight Foundation slate grey"),
    ("#ff3939", "Knight Foundation strawberry"),
    ("#ddb321", "Lamborghini gold"),
    ("#f55247", "Laravel coral"),
    ("#d51007", "Lastfm red"),
    ("#d32d27", "Lastpass tomato"),
    ("#af0809", "Lastpass darkish red"),
    ("#000000", "Lastpass black"),
    ("#0c2340", "Lastpass navy"),
    ("#00a3e0", "Lastpass azure"),
    ("#ede04b", "Lastpass dull yellow"),
    ("#333f48", "Lastpass charcoal grey"),
    ("#d9e1e2", "Lastpass light grey"),
    ("#f6ec35", "Lego off yellow"),
    ("#d11013", "Lego scarlet"),
    ("#000000", "Lego black"),
    ("#00c300", "Line vibrant green"),
    ("#0a66c2", "Linkedin nice blue"),
    ("#83941f", "Linkedin baby shit green"),
    ("#e7a33e", "Linkedin macaroni and cheese"),
    ("#f5987e", "Linkedin peachy pink"),
    ("#56687a", "Linkedin slate"),
    ("#004182", "Linkedin darkish blue"),
    ("#44712e", "Linkedin camo green"),
    ("#915907", "Linkedin poo brown"),
    ("#b24020", "Linkedin brick"),
    ("#38434f", "Linkedin charcoal grey"),
    ("#dce6f1", "Linkedin ice"),
    ("#d7ebce", "Linkedin light grey"),
    ("#fce2ba", "Linkedin pale peach"),
    ("#fadfd8", "Linkedin light pink"),
    ("#e9e5df", "Linkedin light grey"),
    ("#fdfaf5", "Linkedin very light pink"),
    ("#cf202e", "Livestream cherry"),
    ("#232121", "Livestream dark"),
    ("#f78822", "Livestream dusty orange"),
    ("#f6db35", "Livestream sun yellow"),
    ("#6dc067", "Livestream soft green"),
    ("#4185be", "Livestream cool blue"),
    ("#8f499c", "Livestream medium purple"),
    ("#d81f2a", "Lloyds cherry"),
    ("#ff9900", "Lloyds tangerine"),
    ("#e0d86e", "Lloyds sand"),
    ("#9ea900", "Lloyds puke"),
    ("#6ec9e0", "Lloyds lightblue"),
    ("#007ea3", "Lloyds teal blue"),
    ("#9e4770", "Lloyds light burgundy"),
    ("#631d76", "Lloyds darker purple"),
    ("#1e1e1e", "Lloyds dark"),
    ("#006fbf", "Localbitcoins Com nice blue"),
    ("#ff7b00", "Localbitcoins Com pumpkin orange"),
    ("#008ecf", "Login Radius cerulean"),
    ("#09263c", "Login Radius navy"),
    ("#020b13", "Login Radius almost black"),
    ("#e3f1f8", "Login Radius ice"),
    ("#073857", "Login Radius marine"),
    ("#eb0028", "Lomo cherry red"),
    ("#00a0df", "Lomo azure"),
    ("#000099", "London Underground cobalt blue"),
    ("#cc3333", "London Underground reddish"),
    ("#004990", "Lowes darkish blue"),
    ("#15b6e5", "Lowes azure"),
    ("#576396", "Lumo dusky blue"),
    ("#ff00bf", "Lyft bright pink"),
    ("#352384", "Lyft indigo"),
    ("#333447", "Lyft charcoal"),
    ("#f3f3f5", "Lyft very light pink"),
    ("#f46f25", "Magento dusty orange"),
    ("#168de2", "Mail Ru water blue"),
    ("#ffa930", "Mail Ru mango"),
    ("#239ab9", "Mailchimp water blue"),
    ("#52bad5", "Mailchimp dark sky blue"),
    ("#6dc5dc", "Mailchimp lightblue"),
    ("#373737", "Mailchimp dark grey"),
    ("#5d5c5d", "Mailchimp gunmetal"),
    ("#b7b7b7", "Mailchimp pinkish grey"),
    ("#34be5b", "Manjaro Linux cool green"),
    ("#3bb2d0", "Mapbox dark sky blue"),
    ("#3887be", "Mapbox windows blue"),
    ("#8a8acb", "Mapbox perrywinkle"),
    ("#56b881", "Mapbox tea"),
    ("#50667f", "Mapbox slate"),
    ("#41afa5", "Mapbox greeny blue"),
    ("#f9886c", "Mapbox salmon"),
    ("#e55e5e", "Mapbox pastel red"),
    ("#ed6498", "Mapbox medium pink"),
    ("#fbb03b", "Mapbox butterscotch"),
    ("#142736", "Mapbox dark"),
    ("#28353d", "Mapbox charcoal"),
    ("#222b30", "Mapbox dark"),
    ("#a31f34", "Massachusetts Institute Of Technology rouge"),
    ("#8a8b8c", "Massachusetts Institute Of Technology grey"),
    ("#c2c0bf", "Massachusetts Institute Of Technology silver"),
    ("#004a77", "Massy Group prussian blue"),
    ("#00adee", "Massy Group azure"),
    ("#ff8100", "Massy Group pumpkin orange"),
    ("#ffd200", "Massy Group sunflower yellow"),
    ("#eb001b", "Mastercard cherry red"),
    ("#ff5f00", "Mastercard bright orange"),
    ("#f79e1b", "Mastercard squash"),
    ("#615ef8", "Mastodon cornflower"),
    ("#29002d", "Mastodon very dark purple"),
    ("#150118", "Mastodon almost black"),
    ("#bd0017", "Mcdonalds scarlet"),
    ("#ffc836", "Mcdonalds macaroni and cheese"),
    ("#264f36", "Mcdonalds pine"),
    ("#00ab6c", "Medium bluish green"),
    ("#e0393e", "Meetup faded red"),
    ("#0a4d8c", "Meijer light navy"),
    ("#dd1321", "Meijer cherry"),
    ("#ffe600", "Mercadolibre Com dandelion"),
    ("#2d3277", "Mercadolibre Com dark slate blue"),
    ("#0084ff", "Messenger deep sky blue"),
    ("#0082fb", "Meta deep sky blue"),
    ("#0064e0", "Meta cerulean blue"),
    ("#18453b", "Msu dark blue grey"),
    ("#000000", "Msu black"),
    ("#ffffff", "Msu white"),
    ("#008208", "Msu darker green"),
    ("#7bbd00", "Msu dark lime green"),
    ("#0b9a6d", "Msu bluish green"),
    ("#f65314", "Microsoft reddish orange"),
    ("#7cbb00", "Microsoft dark lime green"),
    ("#00a1f1", "Microsoft azure"),
    ("#ffbb00", "Microsoft marigold"),
    ("#783bd2", "Microsoft Band bluish purple"),
    ("#ea3e23", "Microsoft Office tomato"),
    ("#0078d7", "Microsoft Surface cerulean"),
    ("#eeeeee", "Microsoft Surface very light pink"),
    ("#737373", "Microsoft Surface purplish grey"),
    ("#505050", "Microsoft Surface charcoal grey"),
    ("#000000", "Microsoft Surface black"),
    ("#9b4dca", "Milligram amethyst"),
    ("#f4f5f6", "Milligram very light pink"),
    ("#606c76", "Milligram slate grey"),
    ("#52aad8", "Mixcloud dark sky blue"),
    ("#273a4b", "Mixcloud dark blue grey"),
    ("#1d2d3b", "Mixcloud dark"),
    ("#a086d3", "Mixpanel wisteria"),
    ("#000088", "Mlb darker blue"),
    ("#cc0000", "Mlb red"),
    ("#ee1d23", "Mobilink cherry red"),
    ("#db1f29", "Mojang cherry"),
    ("#000000", "Mojang black"),
    ("#c6d6df", "Mollie light blue grey"),
    ("#ec4534", "Mollie tomato"),
    ("#589636", "Mongodb fern green"),
    ("#ce1141", "Montclair State University lipstick"),
    ("#eeb111", "Montclair State University squash"),
    ("#e87d1e", "Montclair State University dusty orange"),
    ("#94ce08", "Montclair State University slime green"),
    ("#00386b", "Montclair State University marine blue"),
    ("#969491", "Montclair State University grey"),
    ("#949483", "More4 warm grey"),
    ("#f47b7b", "More4 salmon pink"),
    ("#9f1f5c", "More4 berry"),
    ("#ef9020", "More4 dusty orange"),
    ("#00af3e", "More4 shamrock"),
    ("#85b7e2", "More4 lightblue"),
    ("#29245c", "More4 dark blue grey"),
    ("#ffd616", "More4 sun yellow"),
    ("#e5352b", "More4 tomato"),
    ("#e990ab", "More4 pig pink"),
    ("#0081b4", "More4 nice blue"),
    ("#96cbb3", "More4 pale teal"),
    ("#91be3e", "More4 booger"),
    ("#39a6dd", "More4 dark sky blue"),
    ("#eb0973", "More4 cerise"),
    ("#dde2e0", "More4 light grey"),
    ("#333c41", "More4 charcoal grey"),
    ("#5c92fa", "Motorola soft blue"),
    ("#c13832", "Mozilla dull red"),
    ("#d7d3c8", "Mozilla light grey"),
    ("#4d4e53", "Mozilla charcoal grey"),
    ("#ff6050", "Musixmatch coral"),
    ("#ff0e83", "Musixmatch strong pink"),
    ("#d54262", "Musixmatch dark pink"),
    ("#813867", "Musixmatch bruise"),
    ("#66336e", "Musixmatch grape"),
    ("#341539", "Musixmatch eggplant"),
    ("#5677fc", "Musixmatch cornflower"),
    ("#9013fe", "Musixmatch vivid purple"),
    ("#ffc208", "Musixmatch marigold"),
    ("#00cc99", "Musixmatch green/blue"),
    ("#1fadc5", "Muut turquoise blue"),
    ("#ff8000", "Muut pumpkin orange"),
    ("#2e51a2", "Myanimelist dusk blue"),
    ("#000000", "Myspace black"),
    ("#00758f", "Mysql ocean"),
    ("#f29111", "Mysql tangerine"),
    ("#2b697a", "N26 ugly blue"),
    ("#000000", "N26 black"),
    ("#ffffff", "N26 white"),
    ("#93dee8", "Nanowrimo light blue"),
    ("#5a2e14", "Nanowrimo brown"),
    ("#fc3d21", "Nasa orange red"),
    ("#0b3d91", "Nasa darkish blue"),
    ("#ffd659", "Nascar light gold"),
    ("#e4002b", "Nascar cherry red"),
    ("#007ac2", "Nascar cerulean"),
    ("#ffcc00", "National Geographic goldenrod"),
    ("#000000", "National Geographic black"),
    ("#0071bf", "Nationwide nice blue"),
    ("#000000", "Nationwide black"),
    ("#e1ac26", "Nbc macaroni and cheese"),
    ("#dc380f", "Nbc tomato red"),
    ("#9f0812", "Nbc carmine"),
    ("#6347b2", "Nbc bluey purple"),
    ("#368dd5", "Nbc dark sky blue"),
    ("#70af1e", "Nbc leaf"),
    ("#7e887a", "Nbc medium grey"),
    ("#cc0000", "Nc State University red"),
    ("#000000", "Nc State University black"),
    ("#00afd8", "Nest turquoise blue"),
    ("#7b858e", "Nest steel"),
    ("#e50914", "Netflix red"),
    ("#221f1f", "Netflix dark"),
    ("#f5f5f1", "Netflix very light pink"),
    ("#39bd00", "Netvibes frog green"),
    ("#ce2724", "New Balance rusty red"),
    ("#f3ec19", "New Balance sunny yellow"),
    ("#207c88", "New Balance dark cyan"),
    ("#aac1bf", "New Balance light grey blue"),
    ("#e8e9d7", "New Balance light grey"),
    ("#4c4d4f", "New Balance charcoal grey"),
    ("#231f20", "New Balance dark"),
    ("#cc3333", "New York Post reddish"),
    ("#2a2a2a", "New York Post dark"),
    ("#fbb040", "Nexar butterscotch"),
    ("#44355b", "Nexar charcoal grey"),
    ("#31263e", "Nexar dark grey"),
    ("#ee5622", "Nexar reddish orange"),
    ("#221e22", "Nexar dark"),
    ("#0077c8", "Nexmo cerulean"),
    ("#ff8200", "Nexmo pumpkin orange"),
    ("#f0537a", "Nexmo warm pink"),
    ("#19975d", "Nextdoor viridian"),
    ("#013369", "Nfl marine blue"),
    ("#d50a0a", "Nfl red"),
    ("#005eb8", "Nhs nice blue"),
    ("#ffffff", "Nhs white"),
    ("#504847", "Nike Football charcoal grey"),
    ("#27a770", "Nike Football teal green"),
    ("#4bad31", "Nikefuel leafy green"),
    ("#f5dc00", "Nikefuel sunflower yellow"),
    ("#e95814", "Nikefuel reddish orange"),
    ("#e2142d", "Nikefuel cherry"),
    ("#75af42", "Ning nasty green"),
    ("#a98c66", "Ninjas In Pyjamas dark beige"),
    ("#12191c", "Ninjas In Pyjamas almost black"),
    ("#6f7f8d", "Ninjas In Pyjamas steel grey"),
    ("#000000", "Ninjas In Pyjamas black"),
    ("#e60012", "Nintendo red"),
    ("#8c8c8c", "Nintendo grey"),
    ("#ffffff", "Nintendo white"),
    ("#215732", "Node Js pine"),
    ("#6cc24a", "Node Js turtle green"),
    ("#44883e", "Node Js fern green"),
    ("#333333", "Node Js dark grey"),
    ("#124191", "Nokia cobalt"),
    ("#0390d8", "Norsan Media cerulean"),
    ("#003466", "Northern Arizona University marine blue"),
    ("#557665", "Northern Arizona University slate grey"),
    ("#4e2a84", "Northwestern University blueberry"),
    ("#836eaa", "Northwestern University dark lavender"),
    ("#401f68", "Northwestern University darker purple"),
    ("#b6acd1", "Northwestern University cloudy blue"),
    ("#e4e0ee", "Northwestern University pale lavender"),
    ("#342f2e", "Northwestern University dark grey"),
    ("#716c6b", "Northwestern University purplish grey"),
    ("#bbb8b8", "Northwestern University pinkish grey"),
    ("#d8d6d6", "Northwestern University light grey"),
    ("#765438", "Novartis dirt brown"),
    ("#a13323", "Novartis brick"),
    ("#e65124", "Novartis tomato"),
    ("#ec7f22", "Novartis dusty orange"),
    ("#f8b22a", "Novartis mango"),
    ("#ffd430", "Novartis sun yellow"),
    ("#cb3837", "Npm reddish"),
    ("#ffc61e", "Ns golden yellow"),
    ("#00337f", "Ns darkish blue"),
    ("#003082", "Ns darkish blue"),
    ("#003082", "Ns 2 darkish blue"),
    ("#ffc917", "Ns 2 golden yellow"),
    ("#76b900", "Nvidia dark lime green"),
    ("#51007a", "Nzxt royal purple"),
    ("#dbe800", "Nzxt greenish yellow"),
    ("#d0d3d4", "Nzxt light grey"),
    ("#7c878e", "Nzxt steel"),
    ("#e2002a", "Obb cherry red"),
    ("#6e6e6e", "Obb purplish grey"),
    ("#ed812b", "Odnoklassniki dusty orange"),
    ("#008272", "Office Sway bluegreen"),
    ("#001f2d", "Oktopost navy"),
    ("#008fd4", "Oktopost cerulean"),
    ("#696969", "Oktopost slate grey"),
    ("#cccccc", "Oktopost silver"),
    ("#eeeeee", "Oktopost very light pink"),
    ("#8d989a", "Olark grey"),
    ("#744da8", "Olark deep lavender"),
    ("#1fb3e0", "Olark turquoise blue"),
    ("#49c219", "Olark frog green"),
    ("#f4dc2a", "Olark sun yellow"),
    ("#eeb417", "Olark squash"),
    ("#d65129", "Olark terra cotta"),
    ("#08107b", "Olympus darker blue"),
    ("#dfb226", "Olympus macaroni and cheese"),
    ("#777777", "Olympus medium grey"),
    ("#eb0029", "Oneplus cherry red"),
    ("#1b5faa", "Onshape mid blue"),
    ("#90cef1", "Onshape light blue"),
    ("#ffc20e", "Onshape sunflower"),
    ("#eeaf00", "Oovoo yellow orange"),
    ("#cc0f16", "Opera scarlet"),
    ("#9c9e9f", "Opera cool grey"),
    ("#ff0000", "Oracle fire engine red"),
    ("#000000", "Oracle black"),
    ("#7f7f7f", "Oracle medium grey"),
    ("#dc4405", "Oregon State University deep orange"),
    ("#000000", "Oregon State University black"),
    ("#c7202c", "Overstock lipstick red"),
    ("#060606", "Overwolf almost black"),
    ("#171717", "Overwolf almost black"),
    ("#cccccc", "Overwolf silver"),
    ("#ffffff", "Overwolf white"),
    ("#002147", "Oxford University Press navy"),
    ("#000000", "Oxford University Press black"),
    ("#666666", "Oxford University Press slate grey"),
    ("#004b91", "Pac deep sea blue"),
    ("#004b91", "Pac 12 deep sea blue"),
    ("#00274d", "Pac 12 marine"),
    ("#0076c0", "Pac 12 nice blue"),
    ("#000007", "Pac 12 black"),
    ("#d6e03d", "Pac 12 sickly yellow"),
    ("#a1a1a4", "Pac 12 cool grey"),
    ("#e5c5bb", "Pac 12 pale rose"),
    ("#0f58a8", "Panasonic peacock blue"),
    ("#000000", "Panasonic black"),
    ("#005483", "Pandora deep sea blue"),
    ("#ee3423", "Path tomato"),
    ("#f96854", "Patreon orange pink"),
    ("#052d49", "Patreon marine"),
    ("#f05000", "Paymill blood orange"),
    ("#22d0b8", "Paymo tealish"),
    ("#34c950", "Paymo cool green"),
    ("#8de86e", "Paymo light grass green"),
    ("#003087", "Paypal darkish blue"),
    ("#009cde", "Paypal azure"),
    ("#012169", "Paypal marine"),
    ("#ed6b06", "Pearson orange"),
    ("#9d1348", "Pearson berry"),
    ("#008b5d", "Pearson dark sea green"),
    ("#364395", "Pearson blueberry"),
    ("#ff6900", "Penguin Books orange"),
    ("#ee7200", "Peopleperhour Com orange"),
    ("#e32934", "Pepsi strawberry"),
    ("#004883", "Pepsi darkish blue"),
    ("#3aa4c6", "Periscope cool blue"),
    ("#d75444", "Periscope pale red"),
    ("#0093d0", "Pfizer cerulean"),
    ("#000000", "Pfizer black"),
    ("#616365", "Pfizer slate grey"),
    ("#00aeef", "Pfizer azure"),
    ("#d6006e", "Pfizer dark hot pink"),
    ("#75d1e0", "Pfizer lightblue"),
    ("#7dba00", "Pfizer dark lime green"),
    ("#cc292b", "Pfizer reddish"),
    ("#00a950", "Pfizer emerald"),
    ("#f8971d", "Pfizer mango"),
    ("#f7d417", "Pfizer golden yellow"),
    ("#4a245e", "Pfizer darker purple"),
    ("#f26649", "Pfizer coral"),
    ("#0e5fd8", "Philips azul"),
    ("#0ea0db", "Photobucket azure"),
    ("#000000", "Photobucket black"),
    ("#8892be", "Php bluey grey"),
    ("#4f5b93", "Php dusky blue"),
    ("#99cc99", "Php hospital green"),
    ("#5dbe57", "Pikabu dark pastel green"),
    ("#0000e6", "Pinboard pure blue"),
    ("#e60023", "Pinterest cherry red"),
    ("#ee3124", "Pizza Hut tomato"),
    ("#00a160", "Pizza Hut emerald"),
    ("#ffc425", "Pizza Hut golden yellow"),
    ("#6585ed", "Plasso soft blue"),
    ("#f5756c", "Plasso salmon"),
    ("#98afc0", "Plasso light grey blue"),
    ("#2f3148", "Plasso charcoal"),
    ("#414f5a", "Plaxo dark grey blue"),
    ("#003087", "Playstation darkish blue"),
    ("#e5a00d", "Plex squash"),
    ("#282a2d", "Plex dark"),
    ("#ef4056", "Pocket watermelon"),
    ("#50bcb6", "Pocket greeny blue"),
    ("#d52b1e", "Poczta Polska tomato"),
    ("#00a3e2", "Polariod azure"),
    ("#1ba548", "Polariod emerald"),
    ("#fdc800", "Polariod goldenrod"),
    ("#f1860e", "Polariod pumpkin orange"),
    ("#e41b13", "Polariod tomato red"),
    ("#0099ff", "Portfolium azure"),
    ("#fb0a2a", "Portfolium cherry red"),
    ("#17ad49", "Portfolium shamrock"),
    ("#333333", "Portfolium dark grey"),
    ("#ef5b25", "Postman reddish orange"),
    ("#000000", "Postmates black"),
    ("#36454f", "Postmates charcoal grey"),
    ("#df0067", "Prestashop dark hot pink"),
    ("#251b5b", "Prestashop dark indigo"),
    ("#25b9d7", "Prestashop turquoise blue"),
    ("#fbbb22", "Prestashop orangey yellow"),
    ("#68737f", "Prestashop battleship grey"),
    ("#bbbfc3", "Prestashop silver"),
    ("#318bff", "Prezi dodger blue"),
    ("#1885bf", "Priceline water blue"),
    ("#ee7f2d", "Princeton University dusty orange"),
    ("#000000", "Princeton University black"),
    ("#da552f", "Product Hunt terra cotta"),
    ("#534540", "Product Hunt purple brown"),
    ("#988f8c", "Product Hunt warm grey"),
    ("#00b27f", "Product Hunt green blue"),
    ("#505264", "Protonmail gunmetal"),
    ("#8a90c7", "Protonmail bluey grey"),
    ("#000000", "Puma black"),
    ("#44403f", "Puma charcoal grey"),
    ("#696965", "Puma slate grey"),
    ("#ba2026", "Puma rouge"),
    ("#ae946d", "Puma pale brown"),
    ("#c28e0e", "Purdue University ochre"),
    ("#98700d", "Purdue University puke brown"),
    ("#000000", "Purdue University black"),
    ("#ffde57", "Python light gold"),
    ("#4584b6", "Python cool blue"),
    ("#646464", "Python slate grey"),
    ("#e0001b", "Qantas Airlines red"),
    ("#6b5aed", "Qonto purpleish blue"),
    ("#262a3e", "Qonto dark"),
    ("#fafafc", "Qonto pale grey"),
    ("#63ebe4", "Qonto tiffany blue"),
    ("#e10019", "Qualtrics red"),
    ("#4257b2", "Quizlet french blue"),
    ("#3ccfcf", "Quizlet aqua marine"),
    ("#f0f0f0", "Quizlet very light pink"),
    ("#ff5454", "Quizup grapefruit"),
    ("#a82400", "Quora rust red"),
    ("#66ceff", "Quote Fm lightblue"),
    ("#c7053d", "Raspberry Pi rose red"),
    ("#8cc04b", "Raspberry Pi booger"),
    ("#00ff00", "Razer bright green"),
    ("#007dc3", "Rdio cerulean"),
    ("#e11b22", "Remax cherry red"),
    ("#0054a4", "Remax peacock blue"),
    ("#00d8ff", "React neon blue"),
    ("#990000", "Readability blood red"),
    ("#f29023", "Realex Payments dusty orange"),
    ("#4d5255", "Realex Payments gunmetal"),
    ("#cc0000", "Red Hat red"),
    ("#ff4500", "Reddit blood orange"),
    ("#5f99cf", "Reddit faded blue"),
    ("#cee3f8", "Reddit pale sky blue"),
    ("#a02021", "Redfin brick"),
    ("#0a2239", "Redox navy"),
    ("#01b287", "Redox green blue"),
    ("#ff9f1c", "Redox mango"),
    ("#e5505a", "Redox pastel red"),
    ("#854c9e", "Redox purplish"),
    ("#000000", "Renaissance Hotels black"),
    ("#999999", "Renaissance Hotels grey"),
    ("#f58021", "Renaissance Hotels dusty orange"),
    ("#ed1c27", "Rentler cherry red"),
    ("#b32317", "Residence Inn rusty red"),
    ("#f58025", "Residence Inn dusty orange"),
    ("#3a6e8f", "Residence Inn denim"),
    ("#87b2d8", "Residence Inn light grey blue"),
    ("#8d8b00", "Residence Inn baby poop green"),
    ("#c1d72f", "Residence Inn sickly yellow"),
    ("#e43526", "Reverbnation tomato"),
    ("#f36e21", "Rochester Institute Of Technology orange"),
    ("#513127", "Rochester Institute Of Technology dark grey"),
    ("#f76902", "Rit orange"),
    ("#ffffff", "Rit white"),
    ("#000000", "Rit black"),
    ("#0ba6ab", "Rockpack topaz"),
    ("#6f1ab1", "Roku purple"),
    ("#680021", "Rolls Royce maroon"),
    ("#fffaec", "Rolls Royce very light pink"),
    ("#939598", "Rolls Royce grey"),
    ("#000000", "Rolls Royce black"),
    ("#e22027", "Roo Kids tomato"),
    ("#a1cd3d", "Roo Kids booger"),
    ("#003e70", "Roo Kids marine blue"),
    ("#62b0d9", "Roon sky blue"),
    ("#0098db", "Rosetta Stone cerulean"),
    ("#ecc400", "Rosetta Stone golden"),
    ("#fdd800", "Rounds sunflower yellow"),
    ("#3f1a0a", "Rowan University chocolate"),
    ("#edd51c", "Rowan University piss yellow"),
    ("#1b5692", "Cssd dusk blue"),
    ("#c32128", "Cssd lipstick red"),
    ("#43a756", "Cssd medium green"),
    ("#999999", "Cssd grey"),
    ("#de8a3d", "Cssd dull orange"),
    ("#74a2d7", "Cssd greyblue"),
    ("#f0c33b", "Cssd macaroni and cheese"),
    ("#9fc54d", "Cssd light olive green"),
    ("#ff0000", "Royal Mail fire engine red"),
    ("#ffff00", "Royal Mail bright yellow"),
    ("#000000", "Royal Mail black"),
    ("#f26522", "Rss reddish orange"),
    ("#f26522", "Rss 2 reddish orange"),
    ("#cc342d", "Ruby reddish"),
    ("#cc0000", "Ruby On Rails red"),
    ("#cc0033", "Rutgers University cherry"),
    ("#073590", "Ryanair darkish blue"),
    ("#f1c933", "Ryanair macaroni and cheese"),
    ("#2091eb", "Ryanair azure"),
    ("#e50000", "Sabre red"),
    ("#111111", "Sabre almost black"),
    ("#00dc06", "Sage vibrant green"),
    ("#ec8a00", "Sainsburys pumpkin orange"),
    ("#1798c1", "Salesforce water blue"),
    ("#ff1100", "Salesforce fire engine red"),
    ("#1428a0", "Samsung royal"),
    ("#75787b", "Samsung medium grey"),
    ("#0689d8", "Samsung cerulean"),
    ("#ffc600", "Samsung goldenrod"),
    ("#ff6900", "Samsung orange"),
    ("#e4002b", "Samsung cherry red"),
    ("#c800a1", "Samsung barney purple"),
    ("#685bc7", "Samsung iris"),
    ("#0057b8", "Samsung ocean blue"),
    ("#00a9e0", "Samsung azure"),
    ("#009ca6", "Samsung teal blue"),
    ("#00b140", "Samsung shamrock"),
    ("#e91e22", "San Francisco 49ers vermillion"),
    ("#c8aa76", "San Francisco 49ers sandstone"),
    ("#000000", "San Francisco 49ers black"),
    ("#fd5a1e", "San Francisco Giants reddish orange"),
    ("#000000", "San Francisco Giants black"),
    ("#003366", "Sap marine blue"),
    ("#999999", "Sap grey"),
    ("#4d2177", "Scouts Uk darker purple"),
    ("#84a40b", "Scouts Uk vomit green"),
    ("#004851", "Scouts Uk dark teal"),
    ("#009a44", "Scouts Uk emerald"),
    ("#0095c8", "Scouts Uk cerulean"),
    ("#003da5", "Scouts Uk sapphire"),
    ("#002855", "Scouts Uk marine"),
    ("#ffcd00", "Scouts Uk goldenrod"),
    ("#ff8200", "Scouts Uk pumpkin orange"),
    ("#ba0c2f", "Scouts Uk lipstick red"),
    ("#ad1aac", "Scouts Uk barney"),
    ("#7c3a2d", "Scouts Uk milk chocolate"),
    ("#8c857b", "Scouts Uk warm grey"),
    ("#1a7bba", "Scribd nice blue"),
    ("#1f4fa3", "Septa cobalt"),
    ("#f14728", "Septa tomato"),
    ("#004488", "Seton Hall University darkish blue"),
    ("#0088ff", "Shazam azure"),
    ("#ffaa00", "Shazam orange yellow"),
    ("#ff7700", "Shazam orange"),
    ("#ff0033", "Shazam neon red"),
    ("#9911aa", "Shazam barney purple"),
    ("#cc2288", "Shazam darker pink"),
    ("#aadd22", "Shazam yellowish green"),
    ("#242424", "Shazam dark"),
    ("#646464", "Shazam slate grey"),
    ("#949494", "Shazam grey"),
    ("#e4e4e4", "Shazam light grey"),
    ("#f4f4f4", "Shazam very light pink"),
    ("#0168b3", "Sherwin Williams nice blue"),
    ("#ee3e34", "Sherwin Williams tomato"),
    ("#96bf48", "Shopify booger"),
    ("#479ccf", "Shopify dark sky blue"),
    ("#2d3538", "Shopify charcoal"),
    ("#f5f5f5", "Shopify very light pink"),
    ("#f2f7fa", "Shopify pale grey"),
    ("#666666", "Shopify slate grey"),
    ("#f01f74", "Shopmium cerise"),
    ("#009999", "Siemens teal blue"),
    ("#f26b21", "Skillshare orange"),
    ("#68b8be", "Skillshare greyblue"),
    ("#00800d", "Skoda darker green"),
    ("#00aff0", "Skype azure"),
    ("#00338d", "Skywest darkish blue"),
    ("#6ecadc", "Slack lightblue"),
    ("#e9a820", "Slack squash"),
    ("#e01563", "Slack cerise"),
    ("#3eb991", "Slack greeny blue"),
    ("#0077b5", "Slideshare nice blue"),
    ("#7c9cb0", "Slipcase greyblue"),
    ("#e53b2c", "Smashing Magazine tomato"),
    ("#41b7d8", "Smashing Magazine dark sky blue"),
    ("#f36f21", "Snagajob orange"),
    ("#fffc00", "Snapchat bright yellow"),
    ("#6cb33f", "Soapui nasty green"),
    ("#4a494d", "Soapui charcoal grey"),
    ("#29c4d0", "Socialbro topaz"),
    ("#f29556", "Socialbro faded orange"),
    ("#84afa2", "Socialbro bluegrey"),
    ("#72c427", "Socialbro apple green"),
    ("#f24c7c", "Socialbro warm pink"),
    ("#00aaf2", "Socialbro azure"),
    ("#008ace", "Softonic cerulean"),
    ("#f80046", "Songkick pink red"),
    ("#ff6600", "Sonicbids bright orange"),
    ("#0c88b1", "Sonicbids nice blue"),
    ("#d8a158", "Sonos sand brown"),
    ("#ba4724", "Sonos sienna"),
    ("#1c5f4a", "Sonos dark green blue"),
    ("#d8d8d8", "Sonos light grey"),
    ("#000000", "Sony black"),
    ("#7c8285", "Sony medium grey"),
    ("#bfbdb0", "Sony pinkish grey"),
    ("#b1b134", "Sony sick green"),
    ("#bbd634", "Sony sickly yellow"),
    ("#dbe3b6", "Sony beige"),
    ("#b2c8bd", "Sony silver"),
    ("#165b65", "Sony dark green blue"),
    ("#697d99", "Sony grey/blue"),
    ("#96b8db", "Sony light grey blue"),
    ("#00a4e8", "Sony azure"),
    ("#a4dbdb", "Sony cloudy blue"),
    ("#fdd666", "Sony light mustard"),
    ("#dc9018", "Sony yellow ochre"),
    ("#e31a22", "Sony cherry red"),
    ("#df8f2d", "Sony dull orange"),
    ("#b24f3f", "Sony dusty red"),
    ("#b51f29", "Sony rouge"),
    ("#f58268", "Sony salmon"),
    ("#f4979c", "Sony blush"),
    ("#fedf00", "Soulcycle sunflower yellow"),
    ("#1e1e1e", "Soulcycle dark"),
    ("#a7a8aa", "Soulcycle cool grey"),
    ("#ff8800", "Soundcloud pumpkin orange"),
    ("#ff3300", "Soundcloud red orange"),
    ("#fc00c1", "Spoken hot magenta"),
    ("#000000", "Spoken black"),
    ("#1db954", "Spotify cool green"),
    ("#191414", "Spotify almost black"),
    ("#ffe100", "Sprint sunflower yellow"),
    ("#75dd66", "Sprout Social lightish green"),
    ("#59cb59", "Sprout Social fresh green"),
    ("#2bb656", "Sprout Social cool green"),
    ("#0ca750", "Sprout Social emerald"),
    ("#f3f4f4", "Sprout Social very light pink"),
    ("#364141", "Sprout Social charcoal grey"),
    ("#28c101", "Square Cash green"),
    ("#222222", "Squarespace dark"),
    ("#1e5397", "Stack Exchange dusk blue"),
    ("#376db6", "Stack Exchange medium blue"),
    ("#4ca2da", "Stack Exchange dark sky blue"),
    ("#91d8f4", "Stack Exchange light blue"),
    ("#f48024", "Stackoverflow dusty orange"),
    ("#222426", "Stackoverflow dark"),
    ("#bcbbbb", "Stackoverflow silver"),
    ("#cc0000", "Staples red"),
    ("#2c8aec", "Staples clear blue"),
    ("#ffcc00", "Staples goldenrod"),
    ("#00704a", "Starbucks jungle green"),
    ("#e1261c", "State Farm vermillion"),
    ("#d7584f", "Status Chart pale red"),
    ("#00adee", "Steam azure"),
    ("#000000", "Steam black"),
    ("#3b5a6f", "Sterling Hotels slate"),
    ("#828a87", "Sterling Hotels medium grey"),
    ("#000000", "Sterling Hotels black"),
    ("#9db7c4", "Sterling Hotels light grey blue"),
    ("#ccd7dd", "Sterling Hotels light grey"),
    ("#838f97", "Sterling Hotels bluish grey"),
    ("#002054", "Sterling Hotels marine"),
    ("#000000", "Stockton University black"),
    ("#79bde9", "Stockton University lightblue"),
    ("#ffc423", "Stockton University golden yellow"),
    ("#bc9b6a", "Stockton University dust"),
    ("#a7a9ac", "Stockton University cool grey"),
    ("#f97200", "Storyful orange"),
    ("#010101", "Storyful black"),
    ("#8b8b64", "Storyful brown grey"),
    ("#bbbdc0", "Storyful silver"),
    ("#fc4c02", "Strava blood orange"),
    ("#0f90fa", "Streamable azure"),
    ("#00afe1", "Stripe azure"),
    ("#004b91", "Stubhub deep sea blue"),
    ("#ff7300", "Stubhub orange"),
    ("#00afe1", "Studyblue azure"),
    ("#eb4924", "Stumbleupon tomato"),
    ("#489e3b", "Subway mid green"),
    ("#fabd42", "Subway butterscotch"),
    ("#cd0a20", "Subway scarlet"),
    ("#e61718", "Sugarcrm tomato red"),
    ("#e8e9ea", "Sugarcrm very light pink"),
    ("#595a5c", "Sugarcrm gunmetal"),
    ("#282828", "Sugarcrm dark"),
    ("#00447c", "Suntrust prussian blue"),
    ("#fdb913", "Suntrust orangey yellow"),
    ("#e36f1e", "Suntrust brownish orange"),
    ("#4285f4", "Supershuttle dodger blue"),
    ("#ffcd1a", "Supershuttle golden yellow"),
    ("#f06d1f", "Swarm orange"),
    ("#ffa633", "Swarm mango"),
    ("#e20074", "T Mobile dark hot pink"),
    ("#e74635", "Tagstr tomato"),
    ("#444444", "Taiga charcoal grey"),
    ("#b8b8b8", "Taiga pinkish grey"),
    ("#72a114", "Taiga ugly green"),
    ("#9dce0a", "Taiga slime green"),
    ("#879b89", "Taiga grey/green"),
    ("#cc0000", "Target red"),
    ("#2580c3", "Teamspeak bluish"),
    ("#1c2537", "Teamspeak dark"),
    ("#e0e0e0", "Teamspeak light grey"),
    ("#25dd85", "Teamspeak seaweed"),
    ("#339900", "Technorati grassy green"),
    ("#e62b1e", "Ted vermillion"),
    ("#0088cc", "Telegram cerulean"),
    ("#e92c4c", "Tvtag red pink"),
    ("#c82641", "Tvtag lipstick"),
    ("#a41e35", "Temple rouge"),
    ("#222222", "Temple dark"),
    ("#899197", "Temple grey"),
    ("#ee1c2e", "Tesco cherry red"),
    ("#00539f", "Tesco peacock blue"),
    ("#cc0000", "Tesla red"),
    ("#500000", "Texas Am University dried blood"),
    ("#003c71", "Texas Am University marine blue"),
    ("#5b6236", "Texas Am University camo green"),
    ("#744f28", "Texas Am University milk chocolate"),
    ("#998542", "Texas Am University coffee"),
    ("#332c2c", "Texas Am University dark grey"),
    ("#707373", "Texas Am University purplish grey"),
    ("#d6d3c4", "Texas Am University silver"),
    ("#cc0000", "Texas Tech University red"),
    ("#000000", "Texas Tech University black"),
    ("#ee8421", "The Audience Awards dusty orange"),
    ("#8c8a8a", "The Audience Awards warm grey"),
    ("#222222", "The Audience Awards dark"),
    ("#293f6f", "The College Of New Jersey dark slate blue"),
    ("#a67a00", "The College Of New Jersey bronze"),
    ("#ff3c1f", "The Next Web orange red"),
    ("#26313b", "The Next Web charcoal"),
    ("#4e5860", "The Next Web gunmetal"),
    ("#a6abaf", "The Next Web cool grey"),
    ("#d9e0e2", "The Next Web light grey"),
    ("#fafbfc", "The Next Web pale grey"),
    ("#006b95", "The Ritz Carlton peacock blue"),
    ("#4f5b65", "The Ritz Carlton gunmetal"),
    ("#b3812a", "The Ritz Carlton leather"),
    ("#a01a1f", "The Ritz Carlton carmine"),
    ("#ed1c24", "The Sun cherry red"),
    ("#b90c13", "The Sun scarlet"),
    ("#00745e", "The Sun Goals dark aqua"),
    ("#086556", "The Sun Goals dark turquoise"),
    ("#8560a8", "The Sun Perks deep lavender"),
    ("#431c69", "The Sun Perks darker purple"),
    ("#000000", "The Times black"),
    ("#ff8000", "Thomson Reuters pumpkin orange"),
    ("#555555", "Thomson Reuters gunmetal"),
    ("#444444", "Thomson Reuters charcoal grey"),
    ("#666666", "Thomson Reuters slate grey"),
    ("#cccccc", "Thomson Reuters silver"),
    ("#e9e9e9", "Thomson Reuters very light pink"),
    ("#f7f7f7", "Thomson Reuters very light pink"),
    ("#da3d34", "Tivo tomato"),
    ("#00a480", "Tivo teal"),
    ("#ed9f40", "Tivo faded orange"),
    ("#6a76ac", "Tivo greyish blue"),
    ("#17170e", "Tivo almost black"),
    ("#534b38", "Tivo charcoal grey"),
    ("#a6a480", "Tivo stone"),
    ("#66bd00", "Totaljobs kermit green"),
    ("#eb0a1e", "Toyota cherry red"),
    ("#ffffff", "Toyota white"),
    ("#000000", "Toyota black"),
    ("#58595b", "Toyota gunmetal"),
    ("#6fbc6d", "Treehouse soft green"),
    ("#47535b", "Treehouse gunmetal"),
    ("#0079bf", "Trello nice blue"),
    ("#70b500", "Trello dark lime green"),
    ("#ff9f1a", "Trello yellowish orange"),
    ("#eb5a46", "Trello coral"),
    ("#f2d600", "Trello sunflower yellow"),
    ("#c377e0", "Trello light purple"),
    ("#ff78cb", "Trello bubblegum pink"),
    ("#00c2e0", "Trello aqua blue"),
    ("#51e898", "Trello sea green"),
    ("#c4c9cc", "Trello silver"),
    ("#00af87", "Tripadvisor green blue"),
    ("#5eab1f", "Trulia grass"),
    ("#e12729", "Trustpilot tomato"),
    ("#f37324", "Trustpilot dusty orange"),
    ("#f8cc1b", "Trustpilot golden yellow"),
    ("#72b043", "Trustpilot nasty green"),
    ("#007f4e", "Trustpilot jungle green"),
    ("#c8c8c8", "Trustpilot silver"),
    ("#35465c", "Tumblr dark grey blue"),
    ("#c30f24", "Tunngle lipstick red"),
    ("#355ebe", "Turbotax medium blue"),
    ("#d52b1d", "Turbotax tomato"),
    ("#1ec95b", "Twentythree algae green"),
    ("#043623", "Twentythree evergreen"),
    ("#eff5f0", "Twentythree very light pink"),
    ("#9146ff", "Twitch lighter purple"),
    ("#000000", "Twitch black"),
    ("#f0f0ff", "Twitch pale grey"),
    ("#1da1f2", "Twitter azure"),
    ("#14171a", "Twitter almost black"),
    ("#657786", "Twitter battleship grey"),
    ("#aab8c2", "Twitter light grey blue"),
    ("#e1e8ed", "Twitter light grey"),
    ("#f5f8fa", "Twitter pale grey"),
    ("#98ce1e", "Typekit gross green"),
    ("#d2de61", "Typepad pear"),
    ("#3178c6", "Typescript windows blue"),
    ("#00273f", "Typescript navy"),
    ("#ff8700", "Typo3 pumpkin orange"),
    ("#09091a", "Uber almost black"),
    ("#c0c0c8", "Uber silver"),
    ("#1fbad6", "Uber turquoise blue"),
    ("#dd4814", "Ubuntu deep orange"),
    ("#77216f", "Ubuntu darkish purple"),
    ("#5e2750", "Ubuntu grape purple"),
    ("#2c001e", "Ubuntu very dark purple"),
    ("#aea79f", "Ubuntu greyish"),
    ("#333333", "Ubuntu dark grey"),
    ("#003262", "Uc Berkeley marine"),
    ("#3b7ea1", "Uc Berkeley dirty blue"),
    ("#fdb515", "Uc Berkeley orangey yellow"),
    ("#c4820e", "Uc Berkeley dirty orange"),
    ("#052049", "Ucsf navy"),
    ("#18a3ac", "Ucsf topaz"),
    ("#90bd31", "Ucsf avocado"),
    ("#178ccb", "Ucsf water blue"),
    ("#f48024", "Ucsf dusty orange"),
    ("#10167f", "United Way darker blue"),
    ("#fe230a", "United Way vermillion"),
    ("#ff9600", "United Way tangerine"),
    ("#000064", "United Way darkblue"),
    ("#b41428", "United Way rouge"),
    ("#f57814", "United Way pumpkin orange"),
    ("#e6d7aa", "United Way beige"),
    ("#505050", "United Way charcoal grey"),
    ("#f0e6c8", "United Way pale"),
    ("#969696", "United Way grey"),
    ("#7c81b8", "United Way blue/grey"),
    ("#ff967d", "United Way peachy pink"),
    ("#ffc87d", "United Way wheat"),
    ("#222c37", "Unity dark"),
    ("#00cccc", "Unity turquoise blue"),
    ("#fff600", "Unity bright yellow"),
    ("#ff0066", "Unity pink red"),
    ("#19e3b1", "Unity aquamarine"),
    ("#ff7f33", "Unity dusty orange"),
    ("#b83c82", "Unity darker pink"),
    ("#e2001a", "Universitat Hamburg red"),
    ("#009cd1", "Universitat Hamburg cerulean"),
    ("#3b515b", "Universitat Hamburg dark grey blue"),
    ("#46166b", "University At Albany royal purple"),
    ("#eeb211", "University At Albany squash"),
    ("#006c68", "University At Albany dark aqua"),
    ("#97a4af", "University At Albany cool grey"),
    ("#005bbb", "University At Buffalo nice blue"),
    ("#e56a54", "University At Buffalo pastel red"),
    ("#ffc72c", "University At Buffalo golden yellow"),
    ("#ebec00", "University At Buffalo dandelion"),
    ("#00a69c", "University At Buffalo green blue"),
    ("#990000", "University At Buffalo blood red"),
    ("#ad841f", "University At Buffalo yellowy brown"),
    ("#6da04b", "University At Buffalo flat green"),
    ("#006570", "University At Buffalo dark aqua"),
    ("#2f9fd0", "University At Buffalo dark sky blue"),
    ("#002f56", "University At Buffalo marine"),
    ("#e4e4e4", "University At Buffalo light grey"),
    ("#666666", "University At Buffalo slate grey"),
    ("#007c41", "University Of Alberta jungle green"),
    ("#ffdb05", "University Of Alberta sunflower yellow"),
    ("#cc0033", "University Of Arizona cherry"),
    ("#003366", "University Of Arizona marine blue"),
    ("#d6083b", "University Of Cambridge cherry"),
    ("#0072cf", "University Of Cambridge cerulean"),
    ("#ea7125", "University Of Cambridge dusty orange"),
    ("#55a51c", "University Of Cambridge grass"),
    ("#8f2bbc", "University Of Cambridge purply"),
    ("#00b1c1", "University Of Cambridge turquoise blue"),
    ("#e00122", "University Of Cincinnati cherry red"),
    ("#000000", "University Of Cincinnati black"),
    ("#ce1141", "University Of Dayton lipstick"),
    ("#004b8d", "University Of Dayton deep sea blue"),
    ("#000000", "University Of Dayton black"),
    ("#faf2f3", "University Of Dayton very light pink"),
    ("#d1cdb8", "University Of Dayton silver"),
    ("#cf0a2c", "University Of Dayton cherry"),
    ("#0082ca", "University Of Dayton cerulean"),
    ("#199051", "University Of Dayton dark sea green"),
    ("#e76829", "University Of Dayton brownish orange"),
    ("#ffdd00", "University Of Dayton sunflower yellow"),
    ("#fa4616", "University Of Florida reddish orange"),
    ("#0021a5", "University Of Florida cobalt blue"),
    ("#131f33", "University Of Illinois Urbana Champaign dark"),
    (
        "#fa6300",
        "University Of Illinois Urbana Champaign bright orange",
    ),
    ("#005daa", "University Of Kentucky peacock blue"),
    ("#00274c", "University Of Michigan marine"),
    ("#ffcb05", "University Of Michigan goldenrod"),
    ("#4b9cd3", "University Of North Carolina dark sky blue"),
    ("#007fae", "University Of North Carolina nice blue"),
    ("#13294b", "University Of North Carolina dark blue grey"),
    ("#e1e1e1", "University Of North Carolina light grey"),
    ("#767676", "University Of North Carolina medium grey"),
    ("#151515", "University Of North Carolina almost black"),
    ("#154733", "University Of Oregon evergreen"),
    ("#fee123", "University Of Oregon sun yellow"),
    ("#ffd100", "University Of Rochester sunflower yellow"),
    ("#003b71", "University Of Rochester marine blue"),
    ("#bf5700", "University Of Texas burnt orange"),
    ("#333f48", "University Of Texas charcoal grey"),
    ("#005f86", "University Of Texas deep sea blue"),
    ("#43695b", "University Of Texas gunmetal"),
    ("#f2a900", "University Of Texas yellow orange"),
    ("#382f2d", "University Of Texas dark grey"),
    ("#d6d2c4", "University Of Texas silver"),
    ("#005493", "University Of Victoria deep sea blue"),
    ("#f5aa1c", "University Of Victoria squash"),
    ("#c63527", "University Of Victoria dull red"),
    ("#002754", "University Of Victoria marine"),
    ("#4b2e83", "University Of Washington blueberry"),
    ("#b7a57a", "University Of Washington taupe"),
    ("#85754d", "University Of Washington dull brown"),
    ("#ffd54f", "University Of Waterloo maize"),
    ("#ffbd00", "University Of Wisconsin Milwaukee marigold"),
    ("#000000", "University Of Wisconsin Milwaukee black"),
    ("#98c646", "University Of Wisconsin Milwaukee booger"),
    ("#694d88", "University Of Wisconsin Milwaukee muted purple"),
    ("#5382af", "University Of Wisconsin Milwaukee off blue"),
    ("#d06d34", "University Of Wisconsin Milwaukee terra cotta"),
    ("#5f9a38", "University Of Wisconsin Milwaukee moss green"),
    ("#474d52", "University Of Wisconsin Milwaukee charcoal grey"),
    ("#c822b0", "Univision purpley pink"),
    ("#351c15", "Ups dark brown"),
    ("#ffb500", "Ups yellow orange"),
    ("#64a70b", "Ups leaf green"),
    ("#315cfd", "Usertesting azul"),
    ("#333366", "Usps dark grey blue"),
    ("#e71921", "Usps cherry red"),
    ("#218748", "Usps darkish green"),
    ("#3388ff", "Ustream dodger blue"),
    ("#ff0000", "Verizon fire engine red"),
    ("#f2f2f2", "Verizon very light pink"),
    ("#3285dc", "Verizon dark sky blue"),
    ("#f07355", "Viadeo melon"),
    ("#59267c", "Viber darker purple"),
    ("#8f5db7", "Viber deep lavender"),
    ("#e2d4e7", "Viber light grey"),
    ("#a5cfd5", "Viber cloudy blue"),
    ("#81cd50", "Viber turtle green"),
    ("#f82a53", "Vidme red pink"),
    ("#111111", "Vidme almost black"),
    ("#f5f5f5", "Vidme very light pink"),
    ("#9f2af8", "Vidme electric purple"),
    ("#aaaaaa", "Vidme greyish"),
    ("#dff0d8", "Vidme light grey"),
    ("#3c9cd7", "Viki dark sky blue"),
    ("#d24663", "Viki dark pink"),
    ("#162221", "Vimeo dark"),
    ("#1ab7ea", "Vimeo azure"),
    ("#00b488", "Vine green blue"),
    ("#1e91d0", "Virb water blue"),
    ("#c3092d", "Virgin Media lipstick red"),
    ("#222221", "Virgin Media dark"),
    ("#cc0000", "Virgin Money red"),
    ("#333333", "Virgin Money dark grey"),
    ("#a93c3b", "Virgin Money dull red"),
    ("#a896a0", "Virgin Money greyish"),
    ("#7a3671", "Virgin Money bruise"),
    ("#bd1d65", "Virgin Money deep pink"),
    ("#1a1f71", "Visa marine"),
    ("#f7b600", "Visa yellow orange"),
    ("#31577a", "Visualcv light navy blue"),
    ("#14acf2", "Visually azure"),
    ("#f04494", "Visually barbie pink"),
    ("#0ac578", "Visually green teal"),
    ("#45668e", "Vkontakte dusky blue"),
    ("#e60000", "Vodafone red"),
    ("#4a4d4e", "Vodafone charcoal grey"),
    ("#9c2aa0", "Vodafone warm purple"),
    ("#5e2750", "Vodafone grape purple"),
    ("#00b0ca", "Vodafone turquoise blue"),
    ("#007c92", "Vodafone ocean"),
    ("#a8b400", "Vodafone mustard green"),
    ("#fecb00", "Vodafone goldenrod"),
    ("#eb9800", "Vodafone tangerine"),
    ("#000000", "Vodafone black"),
    ("#003057", "Volvo marine"),
    ("#115740", "Volvo spruce"),
    ("#65665c", "Volvo slate grey"),
    ("#425563", "Volvo gunmetal"),
    ("#517891", "Volvo metallic blue"),
    ("#212721", "Volvo dark"),
    ("#42b883", "Vue Js dark seafoam green"),
    ("#35495e", "Vue Js dark grey blue"),
    ("#9e7e38", "Wake Forest University leather"),
    ("#000000", "Wake Forest University black"),
    ("#82231c", "Wake Forest University red brown"),
    ("#511536", "Wake Forest University plum"),
    ("#443e67", "Wake Forest University dark grey blue"),
    ("#375669", "Wake Forest University dark grey blue"),
    ("#456525", "Wake Forest University camo green"),
    ("#59786c", "Wake Forest University slate grey"),
    ("#3d3c1d", "Wake Forest University dark grey"),
    ("#625750", "Wake Forest University purplish brown"),
    ("#e31837", "Walgreens pinkish red"),
    ("#f37520", "Walgreens orange"),
    ("#489cd4", "Walgreens dark sky blue"),
    ("#2774a6", "Walgreens mid blue"),
    ("#35393d", "Walgreens charcoal"),
    ("#007dc6", "Walmart cerulean"),
    ("#79b9e7", "Walmart lightblue"),
    ("#f47421", "Walmart orange"),
    ("#76c143", "Walmart apple"),
    ("#ffc120", "Walmart golden yellow"),
    ("#e7f0f7", "Walmart ice"),
    ("#f2f8fd", "Walmart pale grey"),
    ("#222222", "Walmart dark"),
    ("#444444", "Walmart charcoal grey"),
    ("#414b56", "Warby Parker charcoal grey"),
    ("#00a2e1", "Warby Parker azure"),
    ("#1c2d37", "Wave Apps dark"),
    ("#4ec7c4", "Wave Apps seafoam blue"),
    ("#00959f", "Wave Apps teal blue"),
    ("#3b9bcc", "Wave Apps dark sky blue"),
    ("#eea642", "Webzunder light orange"),
    ("#7bb32e", "Wechat leaf"),
    ("#e2203d", "Wendys lipstick"),
    ("#199fda", "Wendys water blue"),
    ("#005195", "Western Digital deep sea blue"),
    ("#028948", "Western Digital jungle green"),
    ("#ffd400", "Western Digital sunflower yellow"),
    ("#0067b3", "Western Digital nice blue"),
    ("#9d0a0e", "Western Digital carmine"),
    ("#003369", "Western Digital marine blue"),
    ("#075e54", "Whatsapp dark turquoise"),
    ("#128c7e", "Whatsapp greenish blue"),
    ("#25d366", "Whatsapp algae green"),
    ("#dcf8c6", "Whatsapp very light green"),
    ("#34b7f1", "Whatsapp dark sky blue"),
    ("#ece5dd", "Whatsapp light grey"),
    ("#4aae20", "Whatsbroadcast grass"),
    ("#6cc751", "Whatsbroadcast fresh green"),
    ("#225f1e", "Whatsbroadcast pine"),
    ("#f8cc07", "Whatsbroadcast goldenrod"),
    ("#ff9300", "Whatsbroadcast tangerine"),
    ("#e44436", "Whatsbroadcast tomato"),
    ("#cd3292", "Whatsbroadcast darker pink"),
    ("#37aef3", "Whatsbroadcast dark sky blue"),
    ("#0076ba", "Whatsbroadcast nice blue"),
    ("#005888", "Whatsbroadcast deep sea blue"),
    ("#8732cd", "Whatsbroadcast purply"),
    ("#33482c", "Whatsbroadcast charcoal"),
    ("#2fa5d6", "Whoosnap Designer dark sky blue"),
    ("#b52f2c", "Whoosnap Designer brick"),
    ("#339966", "Wikimedia ocean green"),
    ("#0063bf", "Wikimedia nice blue"),
    ("#990000", "Wikimedia blood red"),
    ("#000000", "Wikipedia black"),
    ("#636466", "Wikipedia slate grey"),
    ("#939598", "Wikipedia grey"),
    ("#c7c8ca", "Wikipedia silver"),
    ("#0078d7", "Windows cerulean"),
    ("#002050", "Windows navy blue"),
    ("#ffb900", "Windows yellow orange"),
    ("#d83b01", "Windows deep orange"),
    ("#e81123", "Windows cherry red"),
    ("#b4009e", "Windows barney purple"),
    ("#5c2d91", "Windows blueberry"),
    ("#008272", "Windows bluegreen"),
    ("#107c10", "Windows darker green"),
    ("#68217a", "Windows Phone darkish purple"),
    ("#96588a", "Woocommerce purplish"),
    ("#3c3c3c", "Woocommerce charcoal grey"),
    ("#71b02f", "Woocommerce leaf"),
    ("#5b009c", "Wooga indigo"),
    ("#21759b", "Wordpress muted blue"),
    ("#d54e21", "Wordpress rusty orange"),
    ("#464646", "Wordpress charcoal grey"),
    ("#0087be", "Wordpress Com cerulean"),
    ("#78dcfa", "Wordpress Com robin's egg"),
    ("#00aadc", "Wordpress Com turquoise blue"),
    ("#005082", "Wordpress Com deep sea blue"),
    ("#87a6bc", "Wordpress Com bluegrey"),
    ("#f3f6f8", "Wordpress Com very light pink"),
    ("#e9eff3", "Wordpress Com very light pink"),
    ("#a8bece", "Wordpress Com cloudy blue"),
    ("#668eaa", "Wordpress Com grey blue"),
    ("#4f748e", "Wordpress Com metallic blue"),
    ("#3d596d", "Wordpress Com slate"),
    ("#2e4453", "Wordpress Com dark grey blue"),
    ("#d54e21", "Wordpress Com rusty orange"),
    ("#f0821e", "Wordpress Com pumpkin orange"),
    ("#4ab866", "Wordpress Com dark mint"),
    ("#f0b849", "Wordpress Com butterscotch"),
    ("#d94f4f", "Wordpress Com pale red"),
    (
        "#622599",
        "World Organisation Of The Scout Movement Wosm purple",
    ),
    (
        "#0054a0",
        "World Organisation Of The Scout Movement Wosm peacock blue",
    ),
    (
        "#aaba0a",
        "World Organisation Of The Scout Movement Wosm snot",
    ),
    (
        "#dd7500",
        "World Organisation Of The Scout Movement Wosm pumpkin",
    ),
    (
        "#e23d28",
        "World Organisation Of The Scout Movement Wosm tomato",
    ),
    (
        "#3d8e33",
        "World Organisation Of The Scout Movement Wosm darkish green",
    ),
    (
        "#3399ff",
        "World Organisation Of The Scout Movement Wosm dodger blue",
    ),
    (
        "#ff3399",
        "World Organisation Of The Scout Movement Wosm barbie pink",
    ),
    (
        "#fcd116",
        "World Organisation Of The Scout Movement Wosm golden yellow",
    ),
    (
        "#999999",
        "World Organisation Of The Scout Movement Wosm grey",
    ),
    ("#0066a1", "Worldline peacock blue"),
    ("#e66760", "Wufoo pastel red"),
    ("#8c88cd", "Wufoo perrywinkle"),
    ("#69c5e4", "Wufoo lightblue"),
    ("#ffdf8b", "Wufoo wheat"),
    ("#61e064", "Wufoo lightish green"),
    ("#2b96f1", "Wunderlist dark sky blue"),
    ("#d7182a", "Wwe cherry"),
    ("#0c2340", "Xavier University navy"),
    ("#9ea2a2", "Xavier University cool grey"),
    ("#0099cc", "Xavier University cerulean"),
    ("#52b043", "Xbox mid green"),
    ("#f59714", "Xda Developers tangerine"),
    ("#06b3e8", "Xero azure"),
    ("#000000", "Xero black"),
    ("#ffffff", "Xero white"),
    ("#7a7e85", "Xero medium grey"),
    ("#6138f5", "Xfinity purpleish blue"),
    ("#1f69ff", "Xfinity clear blue"),
    ("#008558", "Xfinity dark sea green"),
    ("#ffaa00", "Xfinity orange yellow"),
    ("#e64f00", "Xfinity deep orange"),
    ("#e6004d", "Xfinity pink red"),
    ("#026466", "Xing petrol"),
    ("#cfdc00", "Xing dirty yellow"),
    ("#3299cc", "Xy Gaming dark sky blue"),
    ("#333333", "Xy Gaming dark grey"),
    ("#ff4000", "Y Combinator red orange"),
    ("#410093", "Yahoo indigo"),
    ("#ffcc00", "Yandex goldenrod"),
    ("#ffd400", "Yellow Pages sunflower yellow"),
    ("#000000", "Yellow Pages black"),
    ("#af0606", "Yelp darkish red"),
    ("#d8582b", "Yii Framework terra cotta"),
    ("#16a314", "Yii Framework green"),
    ("#3b6fba", "Yii Framework windows blue"),
    ("#9b59b6", "Yo amethyst"),
    ("#e74c3c", "Yo pale red"),
    ("#8e44ad", "Yo purply"),
    ("#2980b9", "Yo bluish"),
    ("#f1c40f", "Yo golden rod"),
    ("#16a085", "Yo blue/green"),
    ("#34495e", "Yo dark grey blue"),
    ("#3498db", "Yo dark sky blue"),
    ("#2ecc71", "Yo algae green"),
    ("#1abc9c", "Yo tealish"),
    ("#ff0000", "Youtube fire engine red"),
    ("#282828", "Youtube dark"),
    ("#e16120", "Yummly brownish orange"),
    ("#3a9691", "Yummly sea"),
    ("#363533", "Yummly dark grey"),
    ("#ff4a00", "Zapier blood orange"),
    ("#fd7622", "Zapier pumpkin orange"),
    ("#ffc43e", "Zapier butterscotch"),
    ("#5f6c72", "Zapier slate grey"),
    ("#499df3", "Zapier dark sky blue"),
    ("#13d0ab", "Zapier aquamarine"),
    ("#00363d", "Zendesk evergreen"),
    ("#f79a3e", "Zendesk faded orange"),
    ("#eb6651", "Zendesk coral"),
    ("#30aabc", "Zendesk tealish"),
    ("#eb4962", "Zendesk watermelon"),
    ("#37b8af", "Zendesk tealish"),
    ("#78a300", "Zendesk ugly green"),
    ("#f0ca28", "Zendesk golden yellow"),
    ("#9dbc7a", "Zerply lichen"),
    ("#1277e1", "Zillow cerulean blue"),
    ("#cb202d", "Zomato cherry"),
    ("#2d2d2d", "Zomato charcoal"),
    ("#f4f4f2", "Zomato very light pink"),
    ("#2d8cff", "Zoom dodger blue"),
    ("#f26d21", "Zoom orange"),
    ("#ff9d3b", "Zopim mango"),
];
