// Canadian Provinces palette: Colors representing each province and territory
// Color palettes inspired by provincial flags, nature, and cultural symbols
use crate::core::color_types::{HexCode, ColorName};

pub const DATA: &[(HexCode, ColorName)] = &[
    // British Columbia - Pacific coastal blues, forest greens, mountain whites
    (HexCode::new("#003F87"), ColorName::new("bc parliament blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("bc mountain snow")),
    (HexCode::new("#FFD700"), ColorName::new("bc golden sun")),
    (HexCode::new("#2E8B57"), ColorName::new("bc coastal forest")),
    (HexCode::new("#4682B4"), ColorName::new("bc pacific ocean")),
    (HexCode::new("#228B22"), ColorName::new("bc evergreen")),
    (HexCode::new("#FF6347"), ColorName::new("bc sunset salmon")),
    (HexCode::new("#87CEEB"), ColorName::new("bc sky blue")),
    (HexCode::new("#8FBC8F"), ColorName::new("bc rainforest")),
    (HexCode::new("#1E90FF"), ColorName::new("bc glacier blue")),

    // Alberta - Prairie golds, oil blacks, mountain blues, cowboy browns
    (HexCode::new("#003C71"), ColorName::new("alberta blue")),
    (HexCode::new("#FFD700"), ColorName::new("alberta wheat gold")),
    (HexCode::new("#8B4513"), ColorName::new("alberta prairie soil")),
    (HexCode::new("#000000"), ColorName::new("alberta oil black")),
    (HexCode::new("#DC143C"), ColorName::new("alberta wild rose")),
    (HexCode::new("#32CD32"), ColorName::new("alberta grassland")),
    (HexCode::new("#A0522D"), ColorName::new("alberta badlands")),
    (HexCode::new("#4169E1"), ColorName::new("alberta sky")),
    (HexCode::new("#CD853F"), ColorName::new("alberta rodeo dust")),
    (HexCode::new("#2F4F4F"), ColorName::new("alberta oil sands")),

    // Saskatchewan - Wheat golds, prairie greens, sky blues
    (HexCode::new("#006A4E"), ColorName::new("saskatchewan green")),
    (HexCode::new("#FFD700"), ColorName::new("saskatchewan wheat")),
    (HexCode::new("#87CEEB"), ColorName::new("saskatchewan sky")),
    (HexCode::new("#FF6347"), ColorName::new("saskatchewan lily")),
    (HexCode::new("#8B4513"), ColorName::new("saskatchewan soil")),
    (HexCode::new("#32CD32"), ColorName::new("saskatchewan canola")),
    (HexCode::new("#DC143C"), ColorName::new("saskatchewan poppy")),
    (HexCode::new("#4682B4"), ColorName::new("saskatchewan lake")),
    (HexCode::new("#DDA0DD"), ColorName::new("saskatchewan prairie rose")),
    (HexCode::new("#228B22"), ColorName::new("saskatchewan boreal")),

    // Manitoba - Prairie colors with lake blues
    (HexCode::new("#DC143C"), ColorName::new("manitoba red")),
    (HexCode::new("#FFD700"), ColorName::new("manitoba buffalo gold")),
    (HexCode::new("#000080"), ColorName::new("manitoba blue")),
    (HexCode::new("#228B22"), ColorName::new("manitoba prairie")),
    (HexCode::new("#4682B4"), ColorName::new("manitoba lake")),
    (HexCode::new("#8B4513"), ColorName::new("manitoba earth")),
    (HexCode::new("#87CEEB"), ColorName::new("manitoba big sky")),
    (HexCode::new("#32CD32"), ColorName::new("manitoba pasture")),
    (HexCode::new("#FF69B4"), ColorName::new("manitoba prairie rose")),
    (HexCode::new("#2F4F4F"), ColorName::new("manitoba granite")),

    // Ontario - Great Lakes blues, forest greens, autumn colors
    (HexCode::new("#DC143C"), ColorName::new("ontario red")),
    (HexCode::new("#FFD700"), ColorName::new("ontario gold")),
    (HexCode::new("#000080"), ColorName::new("ontario blue")),
    (HexCode::new("#228B22"), ColorName::new("ontario forest")),
    (HexCode::new("#4682B4"), ColorName::new("ontario great lakes")),
    (HexCode::new("#FF8C00"), ColorName::new("ontario maple")),
    (HexCode::new("#32CD32"), ColorName::new("ontario trillium")),
    (HexCode::new("#8B4513"), ColorName::new("ontario muskoka")),
    (HexCode::new("#FF6347"), ColorName::new("ontario fall leaves")),
    (HexCode::new("#87CEEB"), ColorName::new("ontario cottage sky")),

    // Quebec - Fleur-de-lis blues and whites, autumn maples
    (HexCode::new("#003F87"), ColorName::new("quebec blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("quebec white")),
    (HexCode::new("#FFD700"), ColorName::new("quebec fleur gold")),
    (HexCode::new("#DC143C"), ColorName::new("quebec red maple")),
    (HexCode::new("#228B22"), ColorName::new("quebec laurentian")),
    (HexCode::new("#4682B4"), ColorName::new("quebec st lawrence")),
    (HexCode::new("#8B4513"), ColorName::new("quebec sugar maple")),
    (HexCode::new("#32CD32"), ColorName::new("quebec spring")),
    (HexCode::new("#FF8C00"), ColorName::new("quebec autumn")),
    (HexCode::new("#87CEEB"), ColorName::new("quebec winter sky")),

    // New Brunswick - Maritime blues, forest greens, fiddlehead greens
    (HexCode::new("#FFD700"), ColorName::new("new brunswick gold")),
    (HexCode::new("#DC143C"), ColorName::new("new brunswick red")),
    (HexCode::new("#000080"), ColorName::new("new brunswick blue")),
    (HexCode::new("#228B22"), ColorName::new("new brunswick forest")),
    (HexCode::new("#4682B4"), ColorName::new("new brunswick bay")),
    (HexCode::new("#32CD32"), ColorName::new("new brunswick fiddlehead")),
    (HexCode::new("#8B4513"), ColorName::new("new brunswick lumber")),
    (HexCode::new("#FF6347"), ColorName::new("new brunswick potato blossom")),
    (HexCode::new("#87CEEB"), ColorName::new("new brunswick fundy sky")),
    (HexCode::new("#2E8B57"), ColorName::new("new brunswick pine")),

    // Nova Scotia - Ocean blues, tartan plaids, highland greens
    (HexCode::new("#003F87"), ColorName::new("nova scotia blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("nova scotia white")),
    (HexCode::new("#DC143C"), ColorName::new("nova scotia red")),
    (HexCode::new("#FFD700"), ColorName::new("nova scotia gold")),
    (HexCode::new("#228B22"), ColorName::new("nova scotia highland")),
    (HexCode::new("#4682B4"), ColorName::new("nova scotia atlantic")),
    (HexCode::new("#8B4513"), ColorName::new("nova scotia tartan")),
    (HexCode::new("#32CD32"), ColorName::new("nova scotia mayflower")),
    (HexCode::new("#FF69B4"), ColorName::new("nova scotia pink")),
    (HexCode::new("#2F4F4F"), ColorName::new("nova scotia slate")),

    // Prince Edward Island - Red soils, potato greens, coastal blues
    (HexCode::new("#DC143C"), ColorName::new("pei red")),
    (HexCode::new("#FFD700"), ColorName::new("pei gold")),
    (HexCode::new("#FFFFFF"), ColorName::new("pei white")),
    (HexCode::new("#228B22"), ColorName::new("pei potato green")),
    (HexCode::new("#4682B4"), ColorName::new("pei coastal blue")),
    (HexCode::new("#8B4513"), ColorName::new("pei red soil")),
    (HexCode::new("#32CD32"), ColorName::new("pei farmland")),
    (HexCode::new("#FF6347"), ColorName::new("pei sandstone")),
    (HexCode::new("#87CEEB"), ColorName::new("pei gentle sea")),
    (HexCode::new("#DDA0DD"), ColorName::new("pei lupine")),

    // Newfoundland and Labrador - Ocean blues, icebergs, wild berries
    (HexCode::new("#003F87"), ColorName::new("newfoundland blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("newfoundland white")),
    (HexCode::new("#DC143C"), ColorName::new("newfoundland red")),
    (HexCode::new("#FFD700"), ColorName::new("newfoundland gold")),
    (HexCode::new("#228B22"), ColorName::new("newfoundland forest")),
    (HexCode::new("#4682B4"), ColorName::new("newfoundland north atlantic")),
    (HexCode::new("#8B4513"), ColorName::new("newfoundland rugged")),
    (HexCode::new("#FF69B4"), ColorName::new("newfoundland fireweed")),
    (HexCode::new("#87CEEB"), ColorName::new("newfoundland iceberg")),
    (HexCode::new("#32CD32"), ColorName::new("newfoundland pitcher plant")),

    // Yukon - Gold rush, aurora colors, wilderness
    (HexCode::new("#FFD700"), ColorName::new("yukon gold")),
    (HexCode::new("#000080"), ColorName::new("yukon midnight")),
    (HexCode::new("#DC143C"), ColorName::new("yukon red")),
    (HexCode::new("#228B22"), ColorName::new("yukon wilderness")),
    (HexCode::new("#4682B4"), ColorName::new("yukon river")),
    (HexCode::new("#00FFFF"), ColorName::new("yukon aurora cyan")),
    (HexCode::new("#FF00FF"), ColorName::new("yukon aurora magenta")),
    (HexCode::new("#32CD32"), ColorName::new("yukon aurora green")),
    (HexCode::new("#8B4513"), ColorName::new("yukon permafrost")),
    (HexCode::new("#87CEEB"), ColorName::new("yukon klondike sky")),

    // Northwest Territories - Arctic blues, aurora borealis, tundra
    (HexCode::new("#003F87"), ColorName::new("nwt blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("nwt arctic white")),
    (HexCode::new("#FFD700"), ColorName::new("nwt gold")),
    (HexCode::new("#DC143C"), ColorName::new("nwt red")),
    (HexCode::new("#228B22"), ColorName::new("nwt tundra")),
    (HexCode::new("#00FFFF"), ColorName::new("nwt ice blue")),
    (HexCode::new("#FF00FF"), ColorName::new("nwt aurora purple")),
    (HexCode::new("#32CD32"), ColorName::new("nwt aurora green")),
    (HexCode::new("#8B4513"), ColorName::new("nwt earth")),
    (HexCode::new("#4682B4"), ColorName::new("nwt great slave lake")),

    // Nunavut - Arctic ice, aurora, inuksuk stone
    (HexCode::new("#003F87"), ColorName::new("nunavut blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("nunavut ice white")),
    (HexCode::new("#FFD700"), ColorName::new("nunavut inuksuk gold")),
    (HexCode::new("#DC143C"), ColorName::new("nunavut red")),
    (HexCode::new("#00FFFF"), ColorName::new("nunavut ice cyan")),
    (HexCode::new("#4682B4"), ColorName::new("nunavut arctic sea")),
    (HexCode::new("#8B4513"), ColorName::new("nunavut stone brown")),
    (HexCode::new("#228B22"), ColorName::new("nunavut tundra moss")),
    (HexCode::new("#FF00FF"), ColorName::new("nunavut aurora pink")),
    (HexCode::new("#32CD32"), ColorName::new("nunavut brief summer")),
];