/// Full CSS Level 4/X11 named color list (140 entries).
/// Each entry is (`#RRGGBB`, "name").
use crate::color_types::{HexCode, ColorName};

/// Hindi/Sanskrit color names with structured types.
/// Each entry is a tuple of (HexCode, ColorName) with sortable components.
pub const COLORS_HINDI: &[(HexCode, ColorName)] = &[
    (HexCode::new("#002FA7"), ColorName::new("Hindi International Klein Blue")),
    (HexCode::new("#FF4F00"), ColorName::new("Hindi International Orange")),
    (HexCode::new("#003366"), ColorName::new("Hindi Midnight Blue")),
    (HexCode::new("#FFE5B4"), ColorName::new("Hindi Peach")),
    (HexCode::new("#FFCC99"), ColorName::new("Hindi Peach Orange")),
    (HexCode::new("#FADFAD"), ColorName::new("Hindi Peach Yellow")),
    (HexCode::new("#87CEEB"), ColorName::new("Hindi Sky Blue")),
    (HexCode::new("#4B0082"), ColorName::new("Hindi Indigo")),
    (HexCode::new("#00416A"), ColorName::new("Hindi Indigo Dye")),
    (HexCode::new("#4682B4"), ColorName::new("Hindi Steel Blue")),
    (HexCode::new("#009000"), ColorName::new("Hindi Islamic Green")),
    (HexCode::new("#08E8DE"), ColorName::new("Hindi Bright Turquoise")),
    (HexCode::new("#66FF00"), ColorName::new("Hindi Bright Green")),
    (HexCode::new("#FF69B4"), ColorName::new("Hindi Warm Pink")),
    (HexCode::new("#FF00CC"), ColorName::new("Hindi Warm Queen Pink")),
    (HexCode::new("#C2B280"), ColorName::new("Hindi Ecru")),
    (HexCode::new("#00FFFF"), ColorName::new("Hindi Aqua")),
    (HexCode::new("#7FFFD4"), ColorName::new("Hindi Aquamarine")),
    (HexCode::new("#F0F8FF"), ColorName::new("Hindi Alice Blue")),
    (HexCode::new("#E32636"), ColorName::new("Hindi Alizarin")),
    (HexCode::new("#465945"), ColorName::new("Hindi Asparagus Gray")),
    (HexCode::new("#0080FF"), ColorName::new("Hindi Azure")),
    (HexCode::new("#F0FFFF"), ColorName::new("Hindi Azure Web")),
    (HexCode::new("#E52B50"), ColorName::new("Hindi Amaranth")),
    (HexCode::new("#7BA05B"), ColorName::new("Hindi Asparagus")),
    (HexCode::new("#008000"), ColorName::new("Hindi Office Green")),
    (HexCode::new("#DA70D6"), ColorName::new("Hindi Orchid")),
    (HexCode::new("#9AB973"), ColorName::new("Hindi Olivine")),
    (HexCode::new("#6D351A"), ColorName::new("Hindi Auburn")),
    (HexCode::new("#FF7518"), ColorName::new("Hindi Pumpkin")),
    (HexCode::new("#008080"), ColorName::new("Hindi Teal")),
    (HexCode::new("#FFBF00"), ColorName::new("Hindi Amber")),
    (HexCode::new("#C41E3A"), ColorName::new("Hindi Cardinal")),
    (HexCode::new("#960018"), ColorName::new("Hindi Carmine")),
    (HexCode::new("#000000"), ColorName::new("Hindi Black")),
    (HexCode::new("#CD7F32"), ColorName::new("Hindi Bronze")),
    (HexCode::new("#DC143C"), ColorName::new("Hindi Crimson")),
    (HexCode::new("#592720"), ColorName::new("Hindi Caput Mortuum")),
    (HexCode::new("#F4C430"), ColorName::new("Hindi Saffron")),
    (HexCode::new("#4CBB17"), ColorName::new("Hindi Kelly Green")),
    (HexCode::new("#996666"), ColorName::new("Hindi Copper Rose")),
    (HexCode::new("#FBEC5D"), ColorName::new("Hindi Corn")),
    (HexCode::new("#6495ED"), ColorName::new("Hindi Cornflower Blue")),
    (HexCode::new("#FFF8E7"), ColorName::new("Hindi Cosmic Latte")),
    (HexCode::new("#0047AB"), ColorName::new("Hindi Cobalt")),
    (HexCode::new("#01FEFE"), ColorName::new("Hindi Cyan")),
    (HexCode::new("#FFFDD0"), ColorName::new("Hindi Cream")),
    (HexCode::new("#BDB76B"), ColorName::new("Hindi Khaki")),
    (HexCode::new("#FBCEB1"), ColorName::new("Hindi Apricot")),
    (HexCode::new("#FFFFF0"), ColorName::new("Hindi Ivory")),
    (HexCode::new("#9955BB"), ColorName::new("Hindi Deep Lilac")),
    (HexCode::new("#986960"), ColorName::new("Hindi Dark Walnut")),
    (HexCode::new("#FFCBA4"), ColorName::new("Hindi Dark Peach")),
    (HexCode::new("#FFA812"), ColorName::new("Hindi Dark Saffron")),
    (HexCode::new("#E75480"), ColorName::new("Hindi Dark Pink")),
    (HexCode::new("#B8860B"), ColorName::new("Hindi Dark Goldenrod")),
    (HexCode::new("#900020"), ColorName::new("Hindi Dark Burgundy")),
    (HexCode::new("#918151"), ColorName::new("Hindi Dark Tan")),
    (HexCode::new("#0000C8"), ColorName::new("Hindi Dark Blue")),
    (HexCode::new("#03C03C"), ColorName::new("Hindi Dark Pastel Green")),
    (HexCode::new("#116062"), ColorName::new("Hindi Dark Turquoise")),
    (HexCode::new("#654321"), ColorName::new("Hindi Dark Brown")),
    (HexCode::new("#CD5B45"), ColorName::new("Hindi Dark Coral")),
    (HexCode::new("#177245"), ColorName::new("Hindi Dark Spring Green")),
    (HexCode::new("#DA3287"), ColorName::new("Hindi Dark Cerise")),
    (HexCode::new("#08457E"), ColorName::new("Hindi Dark Cerulean")),
    (HexCode::new("#2F4F4F"), ColorName::new("Hindi Dark Slate Gray")),
    (HexCode::new("#013220"), ColorName::new("Hindi Dark Green")),
    (HexCode::new("#FFA6C9"), ColorName::new("Hindi Carnation Pink")),
    (HexCode::new("#FF007F"), ColorName::new("Hindi Rose")),
    (HexCode::new("#FEA7CA"), ColorName::new("Hindi Pink")),
    (HexCode::new("#FF9966"), ColorName::new("Hindi Pink Orange")),
    (HexCode::new("#CC7722"), ColorName::new("Hindi Ochre")),
    (HexCode::new("#F5DEB3"), ColorName::new("Hindi Wheat")),
    (HexCode::new("#E49B0F"), ColorName::new("Hindi Gamboge")),
    (HexCode::new("#DAA520"), ColorName::new("Hindi Goldenrod")),
    (HexCode::new("#D0F0C0"), ColorName::new("Hindi Tea Green")),
    (HexCode::new("#7FFF00"), ColorName::new("Hindi Chartreuse")),
    (HexCode::new("#DFFF00"), ColorName::new("Hindi Chartreuse Yellow")),
    (HexCode::new("#01796F"), ColorName::new("Hindi Pine Green")),
    (HexCode::new("#7B3F00"), ColorName::new("Hindi Chocolate")),
    (HexCode::new("#78866B"), ColorName::new("Hindi Camouflage Green")),
    (HexCode::new("#9966CC"), ColorName::new("Hindi Amethyst")),
    (HexCode::new("#EBC2AF"), ColorName::new("Hindi Zinwaldite")),
    (HexCode::new("#808000"), ColorName::new("Hindi Olive")),
    (HexCode::new("#FC0FC0"), ColorName::new("Hindi Shocking Pink")),
    (HexCode::new("#483C32"), ColorName::new("Hindi Taupe")),
    (HexCode::new("#66023C"), ColorName::new("Hindi Tyrian Purple")),
    (HexCode::new("#F88379"), ColorName::new("Hindi Tea Rose")),
    (HexCode::new("#F28500"), ColorName::new("Hindi Tangerine")),
    (HexCode::new("#FFCC00"), ColorName::new("Hindi Tangerine Yellow")),
    (HexCode::new("#D2B48C"), ColorName::new("Hindi Tan")),
    (HexCode::new("#E2725B"), ColorName::new("Hindi Terracotta")),
    (HexCode::new("#CD5700"), ColorName::new("Hindi Tawny")),
    (HexCode::new("#1560BD"), ColorName::new("Hindi Denim")),
    (HexCode::new("#1E90FF"), ColorName::new("Hindi Dodger Blue")),
    (HexCode::new("#0BDA51"), ColorName::new("Hindi Malachite")),
    (HexCode::new("#B87333"), ColorName::new("Hindi Copper")),
    (HexCode::new("#009E60"), ColorName::new("Hindi Shamrock Green")),
    (HexCode::new("#FF55A3"), ColorName::new("Hindi Vivid Pink")),
    (HexCode::new("#D2691E"), ColorName::new("Hindi Cinnamon")),
    (HexCode::new("#ADFF2F"), ColorName::new("Hindi Green Yellow")),
    (HexCode::new("#FFE4E1"), ColorName::new("Hindi Misty Rose")),
    (HexCode::new("#FFA000"), ColorName::new("Hindi Orange")),
    (HexCode::new("#D1E231"), ColorName::new("Hindi Pear")),
    (HexCode::new("#FDE910"), ColorName::new("Hindi Lemon")),
    (HexCode::new("#CCFF00"), ColorName::new("Hindi Lime Yellow")),
    (HexCode::new("#FFFACD"), ColorName::new("Hindi Lemon Chiffon")),
    (HexCode::new("#6B8E23"), ColorName::new("Hindi Drab Olive")),
    (HexCode::new("#8A2BE2"), ColorName::new("Hindi Blue Violet")),
    (HexCode::new("#00DDDD"), ColorName::new("Hindi Blue Green")),
    (HexCode::new("#082567"), ColorName::new("Hindi Sapphire")),
    (HexCode::new("#0000FF"), ColorName::new("Hindi Blue")),
    (HexCode::new("#000080"), ColorName::new("Hindi Navy Blue")),
    (HexCode::new("#FFDEAD"), ColorName::new("Hindi Navajo White")),
    (HexCode::new("#50C878"), ColorName::new("Hindi Emerald")),
    (HexCode::new("#FFEFD5"), ColorName::new("Hindi Papaya Whip")),
    (HexCode::new("#120A8F"), ColorName::new("Hindi Ultramarine")),
    (HexCode::new("#800080"), ColorName::new("Hindi Purple")),
    (HexCode::new("#50404D"), ColorName::new("Hindi Purple Taupe")),
    (HexCode::new("#B0E0E6"), ColorName::new("Hindi Powder Blue")),
    (HexCode::new("#003399"), ColorName::new("Hindi Powder Blue")),
    (HexCode::new("#B5A642"), ColorName::new("Hindi Brass")),
    (HexCode::new("#FFFF00"), ColorName::new("Hindi Yellow")),
    (HexCode::new("#928252"), ColorName::new("Hindi Yellow Brown")),
    (HexCode::new("#C08081"), ColorName::new("Hindi Old Rose")),
    (HexCode::new("#796878"), ColorName::new("Hindi Old Lavender")),
    (HexCode::new("#FDF5E6"), ColorName::new("Hindi Old Lace")),
    (HexCode::new("#CFB53B"), ColorName::new("Hindi Old Green")),
    (HexCode::new("#FFD1DC"), ColorName::new("Hindi Pastel Pink")),
    (HexCode::new("#77DD77"), ColorName::new("Hindi Pastel Green")),
    (HexCode::new("#CC8899"), ColorName::new("Hindi Puce")),
    (HexCode::new("#003153"), ColorName::new("Hindi Prussian Blue")),
    (HexCode::new("#4F7942"), ColorName::new("Hindi Fern Green")),
    (HexCode::new("#32127A"), ColorName::new("Hindi Persian Indigo")),
    (HexCode::new("#F77FBE"), ColorName::new("Hindi Persian Pink")),
    (HexCode::new("#1C39BB"), ColorName::new("Hindi Persian Blue")),
    (HexCode::new("#F880BF"), ColorName::new("Hindi Persian Rose")),
    (HexCode::new("#CC3333"), ColorName::new("Hindi Persian Red")),
    (HexCode::new("#00A693"), ColorName::new("Hindi Persian Green")),
    (HexCode::new("#EE82EE"), ColorName::new("Hindi Violet")),
    (HexCode::new("#801818"), ColorName::new("Hindi Falu Red")),
    (HexCode::new("#DDADAF"), ColorName::new("Hindi Pale Walnut")),
    (HexCode::new("#AF4035"), ColorName::new("Hindi Pale Carmine")),
    (HexCode::new("#ABCDEF"), ColorName::new("Hindi Pale Cornflower Blue")),
    (HexCode::new("#FADADD"), ColorName::new("Hindi Pale Pink")),
    (HexCode::new("#AFEEEE"), ColorName::new("Hindi Pale Blue")),
    (HexCode::new("#987654"), ColorName::new("Hindi Pale Brown")),
    (HexCode::new("#F984E5"), ColorName::new("Hindi Pale Magenta")),
    (HexCode::new("#DB7093"), ColorName::new("Hindi Pale Violet Red")),
    (HexCode::new("#30D5C8"), ColorName::new("Hindi Turquoise")),
    (HexCode::new("#FF77FF"), ColorName::new("Hindi Fuchsia Pink")),
    (HexCode::new("#228B22"), ColorName::new("Hindi Forest Green")),
    (HexCode::new("#FF00FF"), ColorName::new("Hindi Fuchsia")),
    (HexCode::new("#F64A8A"), ColorName::new("Hindi French Rose")),
    (HexCode::new("#EEDC82"), ColorName::new("Hindi Flax")),
    (HexCode::new("#8A3324"), ColorName::new("Hindi Burnt Umber")),
    (HexCode::new("#CC5500"), ColorName::new("Hindi Burnt Orange")),
    (HexCode::new("#E97451"), ColorName::new("Hindi Burnt Sienna")),
    (HexCode::new("#0095B6"), ColorName::new("Hindi Bondi Blue")),
    (HexCode::new("#F0DC82"), ColorName::new("Hindi Buff")),
    (HexCode::new("#3D2B1F"), ColorName::new("Hindi Bistre")),
    (HexCode::new("#F5F5DC"), ColorName::new("Hindi Beige")),
    (HexCode::new("#E0FFFF"), ColorName::new("Hindi Baby Blue")),
    (HexCode::new("#423189"), ColorName::new("Hindi Violet")),
    (HexCode::new("#D8BFD8"), ColorName::new("Hindi Thistle")),
    (HexCode::new("#CD5C5C"), ColorName::new("Hindi Brown")),
    (HexCode::new("#B04136"), ColorName::new("Hindi Medium Carmine")),
    (HexCode::new("#0000CD"), ColorName::new("Hindi Medium Blue")),
    (HexCode::new("#9370DB"), ColorName::new("Hindi Medium Purple")),
    (HexCode::new("#DD00FF"), ColorName::new("Hindi Psychedelic Purple")),
    (HexCode::new("#997A8D"), ColorName::new("Hindi Mountbatten Pink")),
    (HexCode::new("#73C2FB"), ColorName::new("Hindi Maya Blue")),
    (HexCode::new("#98FF98"), ColorName::new("Hindi Mint Green")),
    (HexCode::new("#FF7F50"), ColorName::new("Hindi Coral")),
    (HexCode::new("#FF4040"), ColorName::new("Hindi Coral Red")),
    (HexCode::new("#21421E"), ColorName::new("Hindi Henna")),
    (HexCode::new("#800000"), ColorName::new("Hindi Maroon")),
    (HexCode::new("#E0B0FF"), ColorName::new("Hindi Mauve")),
    (HexCode::new("#915F6D"), ColorName::new("Hindi Mauve Taupe")),
    (HexCode::new("#ADDFAD"), ColorName::new("Hindi Moss Green")),
    (HexCode::new("#C0C0C0"), ColorName::new("Hindi Silver")),
    (HexCode::new("#80461B"), ColorName::new("Hindi Russet")),
    (HexCode::new("#CD00CC"), ColorName::new("Hindi Magenta")),
    (HexCode::new("#D70040"), ColorName::new("Hindi Rich Carmine")),
    (HexCode::new("#CA1F7B"), ColorName::new("Hindi Rich Magenta")),
    (HexCode::new("#734A12"), ColorName::new("Hindi Raw Umber")),
    (HexCode::new("#00CCCC"), ColorName::new("Hindi Robin Egg Blue")),
    (HexCode::new("#905D5D"), ColorName::new("Hindi Rose Taupe")),
    (HexCode::new("#BFFF00"), ColorName::new("Hindi Lime")),
    (HexCode::new("#C8A2C8"), ColorName::new("Hindi Lilac")),
    (HexCode::new("#FF0000"), ColorName::new("Hindi Red")),
    (HexCode::new("#C71585"), ColorName::new("Hindi Red Violet")),
    (HexCode::new("#E0115F"), ColorName::new("Hindi Ruby")),
    (HexCode::new("#FAF0E6"), ColorName::new("Hindi Linen")),
    (HexCode::new("#B57EDC"), ColorName::new("Hindi Lavender")),
    (HexCode::new("#FFF0F5"), ColorName::new("Hindi Lavender Blush")),
    (HexCode::new("#FBAED2"), ColorName::new("Hindi Lavender Pink")),
    (HexCode::new("#967BB6"), ColorName::new("Hindi Lavender Purple")),
    (HexCode::new("#CCCCFF"), ColorName::new("Hindi Lavender Blue")),
    (HexCode::new("#EF83EF"), ColorName::new("Hindi Lavender Magenta")),
    (HexCode::new("#FBA0E3"), ColorName::new("Hindi Lavender Rose")),
    (HexCode::new("#C4C3D0"), ColorName::new("Hindi Lavender Gray")),
    (HexCode::new("#B7410E"), ColorName::new("Hindi Rust")),
    (HexCode::new("#A7FC00"), ColorName::new("Hindi Spring Bud")),
    (HexCode::new("#00FF7F"), ColorName::new("Hindi Spring Green")),
    (HexCode::new("#7DF9FF"), ColorName::new("Hindi Electric Blue")),
    (HexCode::new("#BF00FF"), ColorName::new("Hindi Electric Purple")),
    (HexCode::new("#8B00FF"), ColorName::new("Hindi Electric Violet")),
    (HexCode::new("#00FF00"), ColorName::new("Hindi Electric Green")),
    (HexCode::new("#40826D"), ColorName::new("Hindi Viridian")),
    (HexCode::new("#C9A0DC"), ColorName::new("Hindi Wisteria")),
    (HexCode::new("#FFF5EE"), ColorName::new("Hindi Seashell")),
    (HexCode::new("#4169E1"), ColorName::new("Hindi Royal Blue")),
    (HexCode::new("#6B3FA0"), ColorName::new("Hindi Royal Purple")),
    (HexCode::new("#FFFFFF"), ColorName::new("Hindi White")),
    (HexCode::new("#CDCDFE"), ColorName::new("Hindi Periwinkle")),
    (HexCode::new("#2E8B57"), ColorName::new("Hindi Sea Green")),
    (HexCode::new("#FFDB58"), ColorName::new("Hindi Mustard")),
    (HexCode::new("#808080"), ColorName::new("Hindi Gray")),
    (HexCode::new("#E9967A"), ColorName::new("Hindi Salmon")),
    (HexCode::new("#FF4D00"), ColorName::new("Hindi Vermilion")),
    (HexCode::new("#FF4500"), ColorName::new("Hindi Vermilion Red")),
    (HexCode::new("#E34234"), ColorName::new("Hindi Cinnabar")),
    (HexCode::new("#704214"), ColorName::new("Hindi Sepia")),
    (HexCode::new("#D4AF37"), ColorName::new("Hindi Gold")),
    (HexCode::new("#996515"), ColorName::new("Hindi Golden Brown")),
    (HexCode::new("#FF2400"), ColorName::new("Hindi Scarlet")),
    (HexCode::new("#FFD700"), ColorName::new("Hindi Gold")),
    (HexCode::new("#FFDF00"), ColorName::new("Hindi Golden Yellow")),
    (HexCode::new("#FF6600"), ColorName::new("Hindi Safety Orange")),
    (HexCode::new("#DE3163"), ColorName::new("Hindi Cerise")),
    (HexCode::new("#007BA7"), ColorName::new("Hindi Cerulean")),
    (HexCode::new("#2A52BE"), ColorName::new("Hindi Cerulean Blue")),
    (HexCode::new("#ACE1AF"), ColorName::new("Hindi Celadon")),
    (HexCode::new("#FFBA00"), ColorName::new("Hindi Selective Yellow")),
    (HexCode::new("#92000A"), ColorName::new("Hindi Sangria")),
    (HexCode::new("#F4A460"), ColorName::new("Hindi Sandy Brown")),
    (HexCode::new("#4B5320"), ColorName::new("Hindi Army Green")),
    (HexCode::new("#FF8C69"), ColorName::new("Hindi Salmon")),
    (HexCode::new("#FFD800"), ColorName::new("Hindi School Bus Yellow")),
    (HexCode::new("#708090"), ColorName::new("Hindi Slate Gray")),
    (HexCode::new("#EC5800"), ColorName::new("Hindi Mango")),
    (HexCode::new("#79876C"), ColorName::new("Hindi Green")),
    (HexCode::new("#00A86B"), ColorName::new("Hindi Jade")),
    (HexCode::new("#F0E68C"), ColorName::new("Hindi Light Khaki")),
    (HexCode::new("#990066"), ColorName::new("Hindi Light Purple")),
    (HexCode::new("#ADD8E6"), ColorName::new("Hindi Light Blue")),
    (HexCode::new("#3FFF00"), ColorName::new("Hindi Harlequin")),
    (HexCode::new("#5218FA"), ColorName::new("Hindi Han Purple")),
    (HexCode::new("#DF73FF"), ColorName::new("Hindi Heliotrope")),
    (HexCode::new("#F400A1"), ColorName::new("Hindi Hollywood Cerise")),
];

