/// Full CSS Level 4/X11 named color list (140 entries).
/// Each entry is (`#RRGGBB`, "name").
use crate::color_types::{HexCode, ColorName, Entity, Ordering};
use crate::colors_helper::Origin;

/// Hindi/Sanskrit color names with structured types.
/// Each entry is a tuple of (HexCode, ColorName) with sortable components.
pub const COLORS_HINDI: &[(HexCode, ColorName)] = &[
    (HexCode::new("#002FA7"), ColorName::new_full("HindiInternational Klein Blue", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FF4F00"), ColorName::new_full("HindiInternational Orange", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#003366"), ColorName::new_full("HindiMidnight Blue", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFE5B4"), ColorName::new_full("HindiPeach", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFCC99"), ColorName::new_full("HindiPeach Orange", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FADFAD"), ColorName::new_full("HindiPeach Yellow", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#87CEEB"), ColorName::new_full("HindiSky Blue", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#4B0082"), ColorName::new_full("HindiIndigo", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#00416A"), ColorName::new_full("HindiIndigo Dye", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#4682B4"), ColorName::new_full("HindiSteel Blue", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#009000"), ColorName::new_full("HindiIslamic Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#08E8DE"), ColorName::new_full("HindiBright Turquoise", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#66FF00"), ColorName::new_full("HindiBright Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FF69B4"), ColorName::new_full("HindiWarm Pink", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FF00CC"), ColorName::new_full("HindiWarm Queen Pink", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#C2B280"), ColorName::new_full("HindiEcru", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#00FFFF"), ColorName::new_full("HindiAqua", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#7FFFD4"), ColorName::new_full("HindiAquamarine", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#F0F8FF"), ColorName::new_full("HindiAlice Blue", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#E32636"), ColorName::new_full("HindiAlizarin", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#465945"), ColorName::new_full("HindiAsparagus Gray", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#0080FF"), ColorName::new_full("HindiAzure", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#F0FFFF"), ColorName::new_full("HindiAzure Web", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#E52B50"), ColorName::new_full("HindiAmaranth", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#7BA05B"), ColorName::new_full("HindiAsparagus", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#008000"), ColorName::new_full("HindiOffice Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#DA70D6"), ColorName::new_full("HindiOrchid", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#9AB973"), ColorName::new_full("HindiOlivine", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#6D351A"), ColorName::new_full("HindiAuburn", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FF7518"), ColorName::new_full("HindiPumpkin", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#008080"), ColorName::new_full("HindiTeal", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFBF00"), ColorName::new_full("HindiAmber", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#C41E3A"), ColorName::new_full("HindiCardinal", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#960018"), ColorName::new_full("HindiCarmine", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("HindiBlack", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#CD7F32"), ColorName::new_full("HindiBronze", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#DC143C"), ColorName::new_full("HindiCrimson", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#592720"), ColorName::new_full("HindiCaput Mortuum", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#F4C430"), ColorName::new_full("HindiSaffron", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#4CBB17"), ColorName::new_full("HindiKelly Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#996666"), ColorName::new_full("HindiCopper Rose", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FBEC5D"), ColorName::new_full("HindiCorn", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#6495ED"), ColorName::new_full("HindiCornflower Blue", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFF8E7"), ColorName::new_full("HindiCosmic Latte", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#0047AB"), ColorName::new_full("HindiCobalt", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#01FEFE"), ColorName::new_full("HindiCyan", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFFDD0"), ColorName::new_full("HindiCream", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#BDB76B"), ColorName::new_full("HindiKhaki", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FBCEB1"), ColorName::new_full("HindiApricot", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFFFF0"), ColorName::new_full("HindiIvory", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#9955BB"), ColorName::new_full("HindiDeep Lilac", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#986960"), ColorName::new_full("HindiDark Walnut", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFCBA4"), ColorName::new_full("HindiDark Peach", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFA812"), ColorName::new_full("HindiDark Saffron", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#E75480"), ColorName::new_full("HindiDark Pink", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#B8860B"), ColorName::new_full("HindiDark Goldenrod", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#900020"), ColorName::new_full("HindiDark Burgundy", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#918151"), ColorName::new_full("HindiDark Tan", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#0000C8"), ColorName::new_full("HindiDark Blue", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#03C03C"), ColorName::new_full("HindiDark Pastel Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#116062"), ColorName::new_full("HindiDark Turquoise", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#654321"), ColorName::new_full("HindiDark Brown", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#CD5B45"), ColorName::new_full("HindiDark Coral", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#177245"), ColorName::new_full("HindiDark Spring Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#DA3287"), ColorName::new_full("HindiDark Cerise", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#08457E"), ColorName::new_full("HindiDark Cerulean", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#2F4F4F"), ColorName::new_full("HindiDark Slate Gray", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#013220"), ColorName::new_full("HindiDark Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFA6C9"), ColorName::new_full("HindiCarnation Pink", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FF007F"), ColorName::new_full("HindiRose", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FEA7CA"), ColorName::new_full("HindiPink", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FF9966"), ColorName::new_full("HindiPink Orange", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#CC7722"), ColorName::new_full("HindiOchre", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#F5DEB3"), ColorName::new_full("HindiWheat", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#E49B0F"), ColorName::new_full("HindiGamboge", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#DAA520"), ColorName::new_full("HindiGoldenrod", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#D0F0C0"), ColorName::new_full("HindiTea Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#7FFF00"), ColorName::new_full("HindiChartreuse", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#DFFF00"), ColorName::new_full("HindiChartreuse Yellow", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#01796F"), ColorName::new_full("HindiPine Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#7B3F00"), ColorName::new_full("HindiChocolate", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#78866B"), ColorName::new_full("HindiCamouflage Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#9966CC"), ColorName::new_full("HindiAmethyst", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#EBC2AF"), ColorName::new_full("HindiZinwaldite", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#808000"), ColorName::new_full("HindiOlive", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FC0FC0"), ColorName::new_full("HindiShocking Pink", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#483C32"), ColorName::new_full("HindiTaupe", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#66023C"), ColorName::new_full("HindiTyrian Purple", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#F88379"), ColorName::new_full("HindiTea Rose", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#F28500"), ColorName::new_full("HindiTangerine", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FFCC00"), ColorName::new_full("HindiTangerine Yellow", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#D2B48C"), ColorName::new_full("HindiTan", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#E2725B"), ColorName::new_full("HindiTerracotta", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#CD5700"), ColorName::new_full("HindiTawny", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#1560BD"), ColorName::new_full("HindiDenim", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#1E90FF"), ColorName::new_full("HindiDodger Blue", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#0BDA51"), ColorName::new_full("HindiMalachite", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#B87333"), ColorName::new_full("HindiCopper", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#009E60"), ColorName::new_full("HindiShamrock Green", Entity::Place, Origin::Hindi, Ordering::Name)),
    (HexCode::new("#FF55A3"), ColorName::new_full("Hindi Vivid Pink", Entity::Place, Origin::Hindi, Ordering::Name)),
   /* (HexCode::new("#D2691E"), ColorName::new_full("HindiCinnamon")),
    (HexCode::new("#ADFF2F"), ColorName::new_full("HindiGreen Yellow")),
    (HexCode::new("#FFE4E1"), ColorName::new_full("HindiMisty Rose")),
    (HexCode::new("#FFA000"), ColorName::new_full("HindiOrange")),
    (HexCode::new("#D1E231"), ColorName::new_full("HindiPear")),
    (HexCode::new("#FDE910"), ColorName::new_full("HindiLemon")),
    (HexCode::new("#CCFF00"), ColorName::new_full("HindiLime Yellow")),
    (HexCode::new("#FFFACD"), ColorName::new_full("HindiLemon Chiffon")),
    (HexCode::new("#6B8E23"), ColorName::new_full("HindiDrab Olive")),
    (HexCode::new("#8A2BE2"), ColorName::new_full("HindiBlue Violet")),
    (HexCode::new("#00DDDD"), ColorName::new_full("HindiBlue Green")),
    (HexCode::new("#082567"), ColorName::new_full("HindiSapphire")),
    (HexCode::new("#0000FF"), ColorName::new_full("HindiBlue")),
    (HexCode::new("#000080"), ColorName::new_full("HindiNavy Blue")),
    (HexCode::new("#FFDEAD"), ColorName::new_full("HindiNavajo White")),
    (HexCode::new("#50C878"), ColorName::new_full("HindiEmerald")),
    (HexCode::new("#FFEFD5"), ColorName::new_full("HindiPapaya Whip")),
    (HexCode::new("#120A8F"), ColorName::new_full("HindiUltramarine")),
    (HexCode::new("#800080"), ColorName::new_full("HindiPurple")),
    (HexCode::new("#50404D"), ColorName::new_full("HindiPurple Taupe")),
    (HexCode::new("#B0E0E6"), ColorName::new_full("HindiPowder Blue")),
    (HexCode::new("#003399"), ColorName::new_full("HindiPowder Blue")),
    (HexCode::new("#B5A642"), ColorName::new_full("HindiBrass")),
    (HexCode::new("#FFFF00"), ColorName::new_full("HindiYellow")),
    (HexCode::new("#928252"), ColorName::new_full("HindiYellow Brown")),
    (HexCode::new("#C08081"), ColorName::new_full("HindiOld Rose")),
    (HexCode::new("#796878"), ColorName::new_full("HindiOld Lavender")),
    (HexCode::new("#FDF5E6"), ColorName::new_full("HindiOld Lace")),
    (HexCode::new("#CFB53B"), ColorName::new_full("HindiOld Green")),
    (HexCode::new("#FFD1DC"), ColorName::new_full("HindiPastel Pink")),
    (HexCode::new("#77DD77"), ColorName::new_full("HindiPastel Green")),
    (HexCode::new("#CC8899"), ColorName::new_full("HindiPuce")),
    (HexCode::new("#003153"), ColorName::new_full("HindiPrussian Blue")),
    (HexCode::new("#4F7942"), ColorName::new_full("HindiFern Green")),
    (HexCode::new("#32127A"), ColorName::new_full("HindiPersian Indigo")),
    (HexCode::new("#F77FBE"), ColorName::new_full("HindiPersian Pink")),
    (HexCode::new("#1C39BB"), ColorName::new_full("HindiPersian Blue")),
    (HexCode::new("#F880BF"), ColorName::new_full("HindiPersian Rose")),
    (HexCode::new("#CC3333"), ColorName::new_full("HindiPersian Red")),
    (HexCode::new("#00A693"), ColorName::new_full("HindiPersian Green")),
    (HexCode::new("#EE82EE"), ColorName::new_full("HindiViolet")),
    (HexCode::new("#801818"), ColorName::new_full("HindiFalu Red")),
    (HexCode::new("#DDADAF"), ColorName::new_full("HindiPale Walnut")),
    (HexCode::new("#AF4035"), ColorName::new_full("HindiPale Carmine")),
    (HexCode::new("#ABCDEF"), ColorName::new_full("HindiPale Cornflower Blue")),
    (HexCode::new("#FADADD"), ColorName::new_full("HindiPale Pink")),
    (HexCode::new("#AFEEEE"), ColorName::new_full("HindiPale Blue")),
    (HexCode::new("#987654"), ColorName::new_full("HindiPale Brown")),
    (HexCode::new("#F984E5"), ColorName::new_full("HindiPale Magenta")),
    (HexCode::new("#DB7093"), ColorName::new_full("HindiPale Violet Red")),
    (HexCode::new("#30D5C8"), ColorName::new_full("HindiTurquoise")),
    (HexCode::new("#FF77FF"), ColorName::new_full("HindiFuchsia Pink")),
    (HexCode::new("#228B22"), ColorName::new_full("HindiForest Green")),
    (HexCode::new("#FF00FF"), ColorName::new_full("HindiFuchsia")),
    (HexCode::new("#F64A8A"), ColorName::new_full("HindiFrench Rose")),
    (HexCode::new("#EEDC82"), ColorName::new_full("HindiFlax")),
    (HexCode::new("#8A3324"), ColorName::new_full("HindiBurnt Umber")),
    (HexCode::new("#CC5500"), ColorName::new_full("HindiBurnt Orange")),
    (HexCode::new("#E97451"), ColorName::new_full("HindiBurnt Sienna")),
    (HexCode::new("#0095B6"), ColorName::new_full("HindiBondi Blue")),
    (HexCode::new("#F0DC82"), ColorName::new_full("HindiBuff")),
    (HexCode::new("#3D2B1F"), ColorName::new_full("HindiBistre")),
    (HexCode::new("#F5F5DC"), ColorName::new_full("HindiBeige")),
    (HexCode::new("#E0FFFF"), ColorName::new_full("HindiBaby Blue")),
    (HexCode::new("#423189"), ColorName::new_full("HindiViolet")),
    (HexCode::new("#D8BFD8"), ColorName::new_full("HindiThistle")),
    (HexCode::new("#CD5C5C"), ColorName::new_full("HindiBrown")),
    (HexCode::new("#B04136"), ColorName::new_full("HindiMedium Carmine")),
    (HexCode::new("#0000CD"), ColorName::new_full("HindiMedium Blue")),
    (HexCode::new("#9370DB"), ColorName::new_full("HindiMedium Purple")),
    (HexCode::new("#DD00FF"), ColorName::new_full("HindiPsychedelic Purple")),
    (HexCode::new("#997A8D"), ColorName::new_full("HindiMountbatten Pink")),
    (HexCode::new("#73C2FB"), ColorName::new_full("HindiMaya Blue")),
    (HexCode::new("#98FF98"), ColorName::new_full("HindiMint Green")),
    (HexCode::new("#FF7F50"), ColorName::new_full("HindiCoral")),
    (HexCode::new("#FF4040"), ColorName::new_full("HindiCoral Red")),
    (HexCode::new("#21421E"), ColorName::new_full("HindiHenna")),
    (HexCode::new("#800000"), ColorName::new_full("HindiMaroon")),
    (HexCode::new("#E0B0FF"), ColorName::new_full("HindiMauve")),
    (HexCode::new("#915F6D"), ColorName::new_full("HindiMauve Taupe")),
    (HexCode::new("#ADDFAD"), ColorName::new_full("HindiMoss Green")),
    (HexCode::new("#C0C0C0"), ColorName::new_full("HindiSilver")),
    (HexCode::new("#80461B"), ColorName::new_full("HindiRusset")),
    (HexCode::new("#CD00CC"), ColorName::new_full("HindiMagenta")),
    (HexCode::new("#D70040"), ColorName::new_full("HindiRich Carmine")),
    (HexCode::new("#CA1F7B"), ColorName::new_full("HindiRich Magenta")),
    (HexCode::new("#734A12"), ColorName::new_full("HindiRaw Umber")),
    (HexCode::new("#00CCCC"), ColorName::new_full("HindiRobin Egg Blue")),
    (HexCode::new("#905D5D"), ColorName::new_full("HindiRose Taupe")),
    (HexCode::new("#BFFF00"), ColorName::new_full("HindiLime")),
    (HexCode::new("#C8A2C8"), ColorName::new_full("HindiLilac")),
    (HexCode::new("#FF0000"), ColorName::new_full("HindiRed")),
    (HexCode::new("#C71585"), ColorName::new_full("HindiRed Violet")),
    (HexCode::new("#E0115F"), ColorName::new_full("HindiRuby")),
    (HexCode::new("#FAF0E6"), ColorName::new_full("HindiLinen")),
    (HexCode::new("#B57EDC"), ColorName::new_full("HindiLavender")),
    (HexCode::new("#FFF0F5"), ColorName::new_full("HindiLavender Blush")),
    (HexCode::new("#FBAED2"), ColorName::new_full("HindiLavender Pink")),
    (HexCode::new("#967BB6"), ColorName::new_full("HindiLavender Purple")),
    (HexCode::new("#CCCCFF"), ColorName::new_full("HindiLavender Blue")),
    (HexCode::new("#EF83EF"), ColorName::new_full("HindiLavender Magenta")),
    (HexCode::new("#FBA0E3"), ColorName::new_full("HindiLavender Rose")),
    (HexCode::new("#C4C3D0"), ColorName::new_full("HindiLavender Gray")),
    (HexCode::new("#B7410E"), ColorName::new_full("HindiRust")),
    (HexCode::new("#A7FC00"), ColorName::new_full("HindiSpring Bud")),
    (HexCode::new("#00FF7F"), ColorName::new_full("HindiSpring Green")),
    (HexCode::new("#7DF9FF"), ColorName::new_full("HindiElectric Blue")),
    (HexCode::new("#BF00FF"), ColorName::new_full("HindiElectric Purple")),
    (HexCode::new("#8B00FF"), ColorName::new_full("HindiElectric Violet")),
    (HexCode::new("#00FF00"), ColorName::new_full("HindiElectric Green")),
    (HexCode::new("#40826D"), ColorName::new_full("HindiViridian")),
    (HexCode::new("#C9A0DC"), ColorName::new_full("HindiWisteria")),
    (HexCode::new("#FFF5EE"), ColorName::new_full("HindiSeashell")),
    (HexCode::new("#4169E1"), ColorName::new_full("HindiRoyal Blue")),
    (HexCode::new("#6B3FA0"), ColorName::new_full("HindiRoyal Purple")),
    (HexCode::new("#FFFFFF"), ColorName::new_full("HindiWhite")),
    (HexCode::new("#CDCDFE"), ColorName::new_full("HindiPeriwinkle")),
    (HexCode::new("#2E8B57"), ColorName::new_full("HindiSea Green")),
    (HexCode::new("#FFDB58"), ColorName::new_full("HindiMustard")),
    (HexCode::new("#808080"), ColorName::new_full("HindiGray")),
    (HexCode::new("#E9967A"), ColorName::new_full("HindiSalmon")),
    (HexCode::new("#FF4D00"), ColorName::new_full("HindiVermilion")),
    (HexCode::new("#FF4500"), ColorName::new_full("HindiVermilion Red")),
    (HexCode::new("#E34234"), ColorName::new_full("HindiCinnabar")),
    (HexCode::new("#704214"), ColorName::new_full("HindiSepia")),
    (HexCode::new("#D4AF37"), ColorName::new_full("HindiGold")),
    (HexCode::new("#996515"), ColorName::new_full("HindiGolden Brown")),
    (HexCode::new("#FF2400"), ColorName::new_full("HindiScarlet")),
    (HexCode::new("#FFD700"), ColorName::new_full("HindiGold")),
    (HexCode::new("#FFDF00"), ColorName::new_full("HindiGolden Yellow")),
    (HexCode::new("#FF6600"), ColorName::new_full("HindiSafety Orange")),
    (HexCode::new("#DE3163"), ColorName::new_full("HindiCerise")),
    (HexCode::new("#007BA7"), ColorName::new_full("HindiCerulean")),
    (HexCode::new("#2A52BE"), ColorName::new_full("HindiCerulean Blue")),
    (HexCode::new("#ACE1AF"), ColorName::new_full("HindiCeladon")),
    (HexCode::new("#FFBA00"), ColorName::new_full("HindiSelective Yellow")),
    (HexCode::new("#92000A"), ColorName::new_full("HindiSangria")),
    (HexCode::new("#F4A460"), ColorName::new_full("HindiSandy Brown")),
    (HexCode::new("#4B5320"), ColorName::new_full("HindiArmy Green")),
    (HexCode::new("#FF8C69"), ColorName::new_full("HindiSalmon")),
    (HexCode::new("#FFD800"), ColorName::new_full("HindiSchool Bus Yellow")),
    (HexCode::new("#708090"), ColorName::new_full("HindiSlate Gray")),
    (HexCode::new("#EC5800"), ColorName::new_full("HindiMango")),
    (HexCode::new("#79876C"), ColorName::new_full("HindiGreen")),
    (HexCode::new("#00A86B"), ColorName::new_full("HindiJade")),
    (HexCode::new("#F0E68C"), ColorName::new_full("HindiLight Khaki")),
    (HexCode::new("#990066"), ColorName::new_full("HindiLight Purple")),
    (HexCode::new("#ADD8E6"), ColorName::new_full("HindiLight Blue")),
    (HexCode::new("#3FFF00"), ColorName::new_full("HindiHarlequin")),
    (HexCode::new("#5218FA"), ColorName::new_full("HindiHan Purple")),
    (HexCode::new("#DF73FF"), ColorName::new_full("HindiHeliotrope")),
    (HexCode::new("#F400A1"), ColorName::new_full("HindiHollywood Cerise")),
*/
];

