use crate::color_types::{HexCode, ColorName};

/// Kelvin color temperature palette with structured types.
/// Each entry is a tuple of (HexCode, ColorName) with sortable components.
pub const KELVIN_COLORS: &[(HexCode, ColorName)] = &[
    //const KELVIN_PALETTE: &[(&str, &str)] = &[
    (HexCode::new("#FFFFFF"), ColorName::new("Skylight 20000K Very Pale Blue-White")),
    (HexCode::new("#050573"), ColorName::new("Skylight 19500K Deep Navy Blue")),
    (HexCode::new("#0D0DD2"), ColorName::new("Skylight 18500K Royal Blue")),
    (HexCode::new("#1313FF"), ColorName::new("Skylight 16500K Pure Blue")),
    (HexCode::new("#4242FC"), ColorName::new("Shade 8000K Bright Blue")),
    (HexCode::new("#6B6BFB"), ColorName::new("Shade→Monitor 7500K Cornflower Blue")),
    (HexCode::new("#8989FC"), ColorName::new("Monitors 6500K Lavender Blue")),
    (HexCode::new("#C4C4FD"), ColorName::new("Noon Sun 5600K Pale Periwinkle")),
    (HexCode::new("#FEFDF0"), ColorName::new("Fluorescent 4300K Soft White")),
    (HexCode::new("#FBF695"), ColorName::new("Tungsten Halogen 3200K Light Yellow")),
    (HexCode::new("#F7EE35"), ColorName::new("Halogen Transition 3500K Lemon Yellow")),
    (HexCode::new("#F8E213"), ColorName::new("Incandescent 2800K Golden Yellow")),
    (HexCode::new("#FE5C0D"), ColorName::new("Candle 1800K Orange Red")),
    (HexCode::new("#F8170E"), ColorName::new("Candle→Embers 1500K Bright Red")),
    (HexCode::new("#BA0709"), ColorName::new("Embers 800K Dark Red")),
    (HexCode::new("#600708"), ColorName::new("Deep Embers 700K Blackish Red")),
    // Gradient fill-ins to keep smooth steps
    (HexCode::new("#1212FF"), ColorName::new("Skylight 16473K Bright Blue")),
    (HexCode::new("#2527FF"), ColorName::new("Skylight 16081K Bright Blue")),
    (HexCode::new("#3C3DFE"), ColorName::new("Skylight 15689K Bright Blue")),
    (HexCode::new("#5F5FFA"), ColorName::new("Skylight 14906K Bright Blue")),
    (HexCode::new("#6969FF"), ColorName::new("Skylight 14514K Light Blue")),
    (HexCode::new("#7777FE"), ColorName::new("Skylight 14122K Light Blue")),
    (HexCode::new("#8B8AF9"), ColorName::new("Skylight 13730K Light Blue")),
    (HexCode::new("#9696FB"), ColorName::new("Skylight 13338K Light Blue")),
    (HexCode::new("#A4A3FE"), ColorName::new("Skylight 12946K Pale Blue")),
    (HexCode::new("#ACADFC"), ColorName::new("Skylight 12555K Pale Blue")),
    (HexCode::new("#B7B7FD"), ColorName::new("Skylight 12163K Pale Blue")),
    (HexCode::new("#C1C0FE"), ColorName::new("Skylight 11771K Pale Blue")),
    (HexCode::new("#CFD1FD"), ColorName::new("Skylight 11379K Pale Blue")),
    (HexCode::new("#E2E2FE"), ColorName::new("Skylight 10987K Pale Blue")),
    (HexCode::new("#F1F0FF"), ColorName::new("Skylight 10595K Pale Blue")),
    (HexCode::new("#FCFCFE"), ColorName::new("Daylight 10204K Very Pale Blue")),
    (HexCode::new("#FEFEEF"), ColorName::new("Daylight 9812K Very Pale Yellow")),
    (HexCode::new("#FEFACB"), ColorName::new("Daylight 9420K Pale Yellow")),
    (HexCode::new("#FCF6A0"), ColorName::new("Daylight 9028K Pale Orange")),
    (HexCode::new("#FAF26C"), ColorName::new("Daylight 8636K Light Orange")),
    (HexCode::new("#F9F04D"), ColorName::new("Daylight 8244K Light Yellow")),
    (HexCode::new("#F9D51E"), ColorName::new("Noon Sun 6285K Golden Yellow")),
    (HexCode::new("#FDCB0F"), ColorName::new("Noon Sun 5893K Golden Yellow")),
    (HexCode::new("#FDC608"), ColorName::new("Fluorescent 5502K Warm Yellow")),
    (HexCode::new("#FEB707"), ColorName::new("Fluorescent 5110K Yellow-Orange")),
    (HexCode::new("#FE9C09"), ColorName::new("Fluorescent 4718K Orange")),
    (HexCode::new("#FD801A"), ColorName::new("Halogen 4326K Bright Orange")),
    (HexCode::new("#FD6B01"), ColorName::new("Halogen 3934K Orange-Red")),
    (HexCode::new("#FF4200"), ColorName::new("Halogen 3542K Bright Red-Orange")),
    (HexCode::new("#FF1C02"), ColorName::new("Incandescent 3151K Bright Red")),
    (HexCode::new("#FD0600"), ColorName::new("Incandescent 2759K Bright Red")),
    (HexCode::new("#EA0000"), ColorName::new("Candle 2367K Bright Red")),
    (HexCode::new("#CB0000"), ColorName::new("Candle 1975K Vivid Red")),
    (HexCode::new("#A10200"), ColorName::new("Candle 1583K Red")),
    (HexCode::new("#760001"), ColorName::new("Embers 1191K Deep Red")),
    (HexCode::new("#320100"), ColorName::new("Embers 800K Dark Red")),
];
