pub const COLORS_METALS_FLAME: &[(&str, &str)] = &[
    ("#C0C0C0", "Al Aluminum Silvery-white"),
    ("#1F75FE", "As Arsenic Blue"),
    ("#00FF00", "B Boron Bright green"),
    ("#8DB600", "Ba Barium Light apple green"),
    ("#FFFFFF", "Be Beryllium White"),
    ("#007FFF", "Bi Bismuth Azure blue"),
    ("#FF7F00", "C Carbon Orange"),
    ("#B22222", "Ca Calcium Brick red"),
    ("#B22222", "Cd Cadmium Brick red"),
    ("#FFFF00", "Ce Cerium Yellow"),
    ("#E0E0E0", "Co Cobalt Silvery white"),
    ("#DCDCDC", "Cr Chromium Silvery white"),
    ("#8A2BE2", "Cs Cesium Blue violet"),
    ("#0D98BA", "Cu(I) Copper(I) Blue-green"),
    ("#228B22", "Cu(II) Copper(II) Green → blue-green"),
    ("#AFEEEE", "Ge Germanium Pale blue"),
    ("#FFD700", "Fe(II) Iron(II) Gold"),
    ("#CC5500", "Fe(III) Iron(III) Orange brown"),
    ("#B0E0E6", "H Hydrogen Pale blue"),
    ("#FFFFFF", "Hf Hafnium White"),
    ("#FF0000", "Hg Mercury Red"),
    ("#4B0082", "In Indium Indigo blue"),
    ("#C8A2C8", "K Potassium Lilac"),
    ("#960018", "Li Lithium Carmine red"),
    ("#FFFFFF", "Mg Magnesium Colorless to white"),
    ("#9ACD32", "Mn(II) Manganese(II) Yellowish green"),
    ("#ADFF2F", "Mo Molybdenum Yellowish green"),
    ("#FFFF33", "Na Sodium Bright yellow"),
    ("#32CD32", "Nb Niobium Green or blue"),
    ("#D9D9D9", "Ni Nickel Colorless to silvery white"),
    ("#98FF98", "P Phosphorus Pale blue-green"),
    ("#F0F8FF", "Pb Lead Blue-white"),
    ("#DC143C", "Ra Radium Crimson red"),
    ("#922B3E", "Rb Rubidium Violet red"),
    ("#98FB98", "Sb Antimony Pale green"),
    ("#FFA500", "Sc Scandium Orange"),
    ("#007FFF", "Se Selenium Azure blue"),
    ("#E6F0FA", "Sn Tin Blue-white"),
    ("#DC143C", "Sr Strontium Crimson or scarlet red"),
    ("#0000FF", "Ta Tantalum Blue"),
    ("#98FB98", "Te Tellurium Pale green"),
    ("#C0C0C0", "Ti Titanium Silver-white"),
    ("#00A550", "Tl Thallium True green"),
    ("#9ACD32", "V Vanadium Yellowish green"),
    ("#008000", "W Tungsten Green"),
    ("#B22222", "Y Yttrium Red: carmine, scarlet, or crimson"),
    ("#66CDAA", "Zn Zinc Colorless → blue-green"),
    ("#A52A2A", "Zr Zirconium Dull red"),
];
