use crate::core::color_types::{HexCode, ColorName};

/// Metal flame test colors with structured types.
/// Each entry is a tuple of (HexCode, ColorName) with sortable components.
pub const COLORS_METALS_FLAME: &[(HexCode, ColorName)] = &[
    (HexCode::new("#C0C0C0"), ColorName::new("Al Aluminum Silvery-white")),
    (HexCode::new("#1F75FE"), ColorName::new("As Arsenic Blue")),
    (HexCode::new("#00FF00"), ColorName::new("B Boron Bright green")),
    (HexCode::new("#8DB600"), ColorName::new("Ba Barium Light apple green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Be Beryllium White")),
    (HexCode::new("#007FFF"), ColorName::new("Bi Bismuth Azure blue")),
    (HexCode::new("#FF7F00"), ColorName::new("C Carbon Orange")),
    (HexCode::new("#B22222"), ColorName::new("Ca Calcium Brick red")),
    (HexCode::new("#B22222"), ColorName::new("Cd Cadmium Brick red")),
    (HexCode::new("#FFFF00"), ColorName::new("Ce Cerium Yellow")),
    (HexCode::new("#E0E0E0"), ColorName::new("Co Cobalt Silvery white")),
    (HexCode::new("#DCDCDC"), ColorName::new("Cr Chromium Silvery white")),
    (HexCode::new("#8A2BE2"), ColorName::new("Cs Cesium Blue violet")),
    (HexCode::new("#0D98BA"), ColorName::new("Cu(I) Copper(I) Blue-green")),
    (HexCode::new("#228B22"), ColorName::new("Cu(II) Copper(II) Green → blue-green")),
    (HexCode::new("#AFEEEE"), ColorName::new("Ge Germanium Pale blue")),
    (HexCode::new("#FFD700"), ColorName::new("Fe(II) Iron(II) Gold")),
    (HexCode::new("#CC5500"), ColorName::new("Fe(III) Iron(III) Orange brown")),
    (HexCode::new("#B0E0E6"), ColorName::new("H Hydrogen Pale blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Hf Hafnium White")),
    (HexCode::new("#FF0000"), ColorName::new("Hg Mercury Red")),
    (HexCode::new("#4B0082"), ColorName::new("In Indium Indigo blue")),
    (HexCode::new("#C8A2C8"), ColorName::new("K Potassium Lilac")),
    (HexCode::new("#960018"), ColorName::new("Li Lithium Carmine red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Mg Magnesium Colorless to white")),
    (HexCode::new("#9ACD32"), ColorName::new("Mn(II) Manganese(II) Yellowish green")),
    (HexCode::new("#ADFF2F"), ColorName::new("Mo Molybdenum Yellowish green")),
    (HexCode::new("#FFFF33"), ColorName::new("Na Sodium Bright yellow")),
    (HexCode::new("#32CD32"), ColorName::new("Nb Niobium Green or blue")),
    (HexCode::new("#D9D9D9"), ColorName::new("Ni Nickel Colorless to silvery white")),
    (HexCode::new("#98FF98"), ColorName::new("P Phosphorus Pale blue-green")),
    (HexCode::new("#F0F8FF"), ColorName::new("Pb Lead Blue-white")),
    (HexCode::new("#DC143C"), ColorName::new("Ra Radium Crimson red")),
    (HexCode::new("#922B3E"), ColorName::new("Rb Rubidium Violet red")),
    (HexCode::new("#98FB98"), ColorName::new("Sb Antimony Pale green")),
    (HexCode::new("#FFA500"), ColorName::new("Sc Scandium Orange")),
    (HexCode::new("#007FFF"), ColorName::new("Se Selenium Azure blue")),
    (HexCode::new("#E6F0FA"), ColorName::new("Sn Tin Blue-white")),
    (HexCode::new("#DC143C"), ColorName::new("Sr Strontium Crimson or scarlet red")),
    (HexCode::new("#0000FF"), ColorName::new("Ta Tantalum Blue")),
    (HexCode::new("#98FB98"), ColorName::new("Te Tellurium Pale green")),
    (HexCode::new("#C0C0C0"), ColorName::new("Ti Titanium Silver-white")),
    (HexCode::new("#00A550"), ColorName::new("Tl Thallium True green")),
    (HexCode::new("#9ACD32"), ColorName::new("V Vanadium Yellowish green")),
    (HexCode::new("#008000"), ColorName::new("W Tungsten Green")),
    (HexCode::new("#B22222"), ColorName::new("Y Yttrium Red: carmine, scarlet, or crimson")),
    (HexCode::new("#66CDAA"), ColorName::new("Zn Zinc Colorless → blue-green")),
    (HexCode::new("#A52A2A"), ColorName::new("Zr Zirconium Dull red")),
];
