// src/colors/national.rs
//
// National colors (approximated from official flag specs / Pantone → sRGB).
// Each entry is (HexCode, ColorName) with structured types.
use once_cell::sync::Lazy;
use crate::color_types::{HexCode, ColorName};
use std::collections::BTreeSet;

/// Combined, normalized, de-duplicated, and sorted national colors.
/// Sort key: (case-insensitive name, then hex).
pub static COLORS_NATIONAL: Lazy<Vec<(HexCode, ColorName)>> = Lazy::new(|| {
    // 1) chain base + supplement
    let iter = COLORS_NATIONAL_UNORDERED
        .iter()
        .copied()
        .chain(COLORS_NATIONAL_UNORDERED.iter().copied());

    // 2) normalize (trim whitespace) - extract the strings from HexCode/ColorName
    let mut v: Vec<(HexCode, ColorName)> = iter
        .map(|(hex, name)| {
            let hex_str = hex.as_str().trim();
            let name_str = name.as_str().trim();
            (HexCode::new(hex_str), ColorName::new(name_str))
        })
        .collect();

    // 3) exact de-duplication by (hex, name)
    let mut seen: BTreeSet<(String, String)> = BTreeSet::new();
    v.retain(|(h, n)| seen.insert((h.as_str().to_string(), n.as_str().to_string())));

    // 4) sort by name (case-insensitive), then by hex - use the Ord implementation
    v.sort_by(|a, b| {
        let (ha, na) = a;
        let (hb, nb) = b;
        na.cmp(nb).then_with(|| ha.cmp(hb))
    });

    v
});
pub const COLORS_NATIONAL_UNORDERED: &[(HexCode, ColorName)] = &[
    // United States
    (HexCode::new("#000000"), ColorName::new("Afghanistan Black")),
    (HexCode::new("#D32011"), ColorName::new("Afghanistan Red")),
    (HexCode::new("#007A36"), ColorName::new("Afghanistan Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Afghanistan White")),
    (HexCode::new("#ED1C24"), ColorName::new("Albania Red")),
    (HexCode::new("#006233"), ColorName::new("Algeria Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Algeria White")),
    (HexCode::new("#D21034"), ColorName::new("Algeria Red")),
    (HexCode::new("#74ACDF"), ColorName::new("Argentina Light Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Argentina White")),
    (HexCode::new("#F6B40E"), ColorName::new("Argentina Yellow")),
    (HexCode::new("#00843D"), ColorName::new("Australia Green")),
    (HexCode::new("#FFCD00"), ColorName::new("Australia Gold")),
    (HexCode::new("#ED2939"), ColorName::new("Austria Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Austria White")),
    (HexCode::new("#006A4E"), ColorName::new("Bangladesh Green")),
    (HexCode::new("#F42A41"), ColorName::new("Bangladesh Red")),
    (HexCode::new("#000000"), ColorName::new("Belgium Black")),
    (HexCode::new("#FDDA24"), ColorName::new("Belgium Yellow")),
    (HexCode::new("#EF3340"), ColorName::new("Belgium Red")),
    (HexCode::new("#009B3A"), ColorName::new("Brazil Green")),
    (HexCode::new("#FEDF00"), ColorName::new("Brazil Yellow")),
    (HexCode::new("#002776"), ColorName::new("Brazil Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Bulgaria White")),
    (HexCode::new("#00966E"), ColorName::new("Bulgaria Green")),
    (HexCode::new("#D62612"), ColorName::new("Bulgaria Red")),
    (HexCode::new("#FF0000"), ColorName::new("Canada Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Canada White")),
    (HexCode::new("#D52B1E"), ColorName::new("Chile Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Chile White")),
    (HexCode::new("#0033A0"), ColorName::new("Chile Blue")),
    (HexCode::new("#DE2910"), ColorName::new("China Red")),
    (HexCode::new("#FFDE00"), ColorName::new("China Yellow")),
    (HexCode::new("#FCD116"), ColorName::new("Colombia Yellow")),
    (HexCode::new("#003893"), ColorName::new("Colombia Blue")),
    (HexCode::new("#CE1126"), ColorName::new("Colombia Red")),
    (HexCode::new("#ED1C24"), ColorName::new("Croatia Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Croatia White")),
    (HexCode::new("#171796"), ColorName::new("Croatia Blue")),
    (HexCode::new("#C60C30"), ColorName::new("Denmark Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Denmark White")),
    (HexCode::new("#CE1126"), ColorName::new("Egypt Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Egypt White")),
    (HexCode::new("#000000"), ColorName::new("Egypt Black")),
    (HexCode::new("#C09300"), ColorName::new("Egypt Gold")),
    (HexCode::new("#078930"), ColorName::new("Ethiopia Green")),
    (HexCode::new("#FCDD09"), ColorName::new("Ethiopia Yellow")),
    (HexCode::new("#DA121A"), ColorName::new("Ethiopia Red")),
    (HexCode::new("#003580"), ColorName::new("Finland Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Finland White")),
    (HexCode::new("#002395"), ColorName::new("France Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("France White")),
    (HexCode::new("#ED2939"), ColorName::new("France Red")),
    (HexCode::new("#000000"), ColorName::new("Germany Black")),
    (HexCode::new("#DD0000"), ColorName::new("Germany Red")),
    (HexCode::new("#FFCC00"), ColorName::new("Germany Gold")),
    (HexCode::new("#CE1126"), ColorName::new("Ghana Red")),
    (HexCode::new("#FCD116"), ColorName::new("Ghana Yellow")),
    (HexCode::new("#006B3F"), ColorName::new("Ghana Green")),
    (HexCode::new("#000000"), ColorName::new("Ghana Black")),
    (HexCode::new("#0D5EAF"), ColorName::new("Greece Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Greece White")),
    (HexCode::new("#FF9933"), ColorName::new("India Saffron")),
    (HexCode::new("#FFFFFF"), ColorName::new("India White")),
    (HexCode::new("#138808"), ColorName::new("India Green")),
    (HexCode::new("#000080"), ColorName::new("India Blue")),
    (HexCode::new("#CE1126"), ColorName::new("Indonesia Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Indonesia White")),
    (HexCode::new("#239F40"), ColorName::new("Iran Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Iran White")),
    (HexCode::new("#DA0000"), ColorName::new("Iran Red")),
    (HexCode::new("#169B62"), ColorName::new("Ireland Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Ireland White")),
    (HexCode::new("#FF883E"), ColorName::new("Ireland Orange")),
    (HexCode::new("#0038B8"), ColorName::new("Israel Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Israel White")),
    (HexCode::new("#009246"), ColorName::new("Italy Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Italy White")),
    (HexCode::new("#CE2B37"), ColorName::new("Italy Red")),
    (HexCode::new("#BC002D"), ColorName::new("Japan Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Japan White")),
    (HexCode::new("#000000"), ColorName::new("Kenya Black")),
    (HexCode::new("#BB0000"), ColorName::new("Kenya Red")),
    (HexCode::new("#006600"), ColorName::new("Kenya Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Kenya White")),
    (HexCode::new("#006341"), ColorName::new("Mexico Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Mexico White")),
    (HexCode::new("#CE1126"), ColorName::new("Mexico Red")),
    (HexCode::new("#C1272D"), ColorName::new("Morocco Red")),
    (HexCode::new("#006233"), ColorName::new("Morocco Green")),
    (HexCode::new("#AE1C28"), ColorName::new("Netherlands Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Netherlands White")),
    (HexCode::new("#21468B"), ColorName::new("Netherlands Blue")),
    (HexCode::new("#000000"), ColorName::new("New Zealand Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("New Zealand White")),
    (HexCode::new("#CC0000"), ColorName::new("New Zealand Red")),
    (HexCode::new("#008753"), ColorName::new("Nigeria Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Nigeria White")),
    (HexCode::new("#01411C"), ColorName::new("Pakistan Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Pakistan White")),
    (HexCode::new("#D91023"), ColorName::new("Peru Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Peru White")),
    (HexCode::new("#FFFFFF"), ColorName::new("Poland White")),
    (HexCode::new("#DC143C"), ColorName::new("Poland Red")),
    (HexCode::new("#006600"), ColorName::new("Portugal Green")),
    (HexCode::new("#FF0000"), ColorName::new("Portugal Red")),
    (HexCode::new("#FFFF00"), ColorName::new("Portugal Yellow")),
    (HexCode::new("#FFFFFF"), ColorName::new("Russia White")),
    (HexCode::new("#0039A6"), ColorName::new("Russia Blue")),
    (HexCode::new("#D52B1E"), ColorName::new("Russia Red")),
    (HexCode::new("#006C35"), ColorName::new("Saudi Arabia Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Saudi Arabia White")),
    (HexCode::new("#E03C31"), ColorName::new("South Africa Red")),
    (HexCode::new("#001489"), ColorName::new("South Africa Blue")),
    (HexCode::new("#007749"), ColorName::new("South Africa Green")),
    (HexCode::new("#FFB81C"), ColorName::new("South Africa Yellow")),
    (HexCode::new("#000000"), ColorName::new("South Africa Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("South Africa White")),
    (HexCode::new("#FFFFFF"), ColorName::new("South Korea White")),
    (HexCode::new("#CD2E3A"), ColorName::new("South Korea Red")),
    (HexCode::new("#0047A0"), ColorName::new("South Korea Blue")),
    (HexCode::new("#000000"), ColorName::new("South Korea Black")),
    (HexCode::new("#AA151B"), ColorName::new("Spain Red")),
    (HexCode::new("#F1BF00"), ColorName::new("Spain Yellow")),
    (HexCode::new("#ED1C24"), ColorName::new("Thailand Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Thailand White")),
    (HexCode::new("#241D4F"), ColorName::new("Thailand Blue")),
    (HexCode::new("#E30A17"), ColorName::new("Turkey Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Turkey White")),
    (HexCode::new("#0057B7"), ColorName::new("Ukraine Blue")),
    (HexCode::new("#FFD700"), ColorName::new("Ukraine Yellow")),
    (HexCode::new("#012169"), ColorName::new("United Kingdom Blue")),
    (HexCode::new("#C8102E"), ColorName::new("United Kingdom Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("United Kingdom White")),
    (HexCode::new("#BF0A30"), ColorName::new("United States Red")),
    (HexCode::new("#002868"), ColorName::new("United States Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("United States White")),
    (HexCode::new("#DA251D"), ColorName::new("Vietnam Red")),
    (HexCode::new("#FFFF00"), ColorName::new("Vietnam Yellow")),
    // Append below to COLORS_NATIONAL:

    // --- Europe (Nordics, Baltics, Balkans, etc.)
    (HexCode::new("#005293"), ColorName::new("Sweden Blue")),
    (HexCode::new("#FECB00"), ColorName::new("Sweden Yellow")),
    (HexCode::new("#BA0C2F"), ColorName::new("Norway Red")),
    (HexCode::new("#00205B"), ColorName::new("Norway Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Norway White")),
    (HexCode::new("#003897"), ColorName::new("Iceland Blue")),
    (HexCode::new("#D72828"), ColorName::new("Iceland Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Iceland White")),
    (HexCode::new("#DA291C"), ColorName::new("Switzerland Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Switzerland White")),
    (HexCode::new("#002B7F"), ColorName::new("Romania Blue")),
    (HexCode::new("#FCD116"), ColorName::new("Romania Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Romania Red")),
    (HexCode::new("#9E1B34"), ColorName::new("Latvia Carmine")),
    (HexCode::new("#FFFFFF"), ColorName::new("Latvia White")),
    (HexCode::new("#FDB913"), ColorName::new("Lithuania Yellow")),
    (HexCode::new("#006A44"), ColorName::new("Lithuania Green")),
    (HexCode::new("#C1272D"), ColorName::new("Lithuania Red")),
    (HexCode::new("#0072CE"), ColorName::new("Estonia Blue")),
    (HexCode::new("#000000"), ColorName::new("Estonia Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Estonia White")),
    (HexCode::new("#D90012"), ColorName::new("Armenia Red")),
    (HexCode::new("#0033A0"), ColorName::new("Armenia Blue")),
    (HexCode::new("#F2A800"), ColorName::new("Armenia Apricot")),
    (HexCode::new("#00B5E2"), ColorName::new("Azerbaijan Blue")),
    (HexCode::new("#EF3340"), ColorName::new("Azerbaijan Red")),
    (HexCode::new("#009F4D"), ColorName::new("Azerbaijan Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Azerbaijan White")),
    (HexCode::new("#E62B1E"), ColorName::new("Georgia Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Georgia White")),
    (HexCode::new("#0F47AF"), ColorName::new("Bosnia and Herzegovina Blue")),
    (HexCode::new("#FCDD09"), ColorName::new("Bosnia and Herzegovina Yellow")),
    (HexCode::new("#FFFFFF"), ColorName::new("Bosnia and Herzegovina White")),
    (HexCode::new("#C8102E"), ColorName::new("Montenegro Red")),
    (HexCode::new("#FFCD00"), ColorName::new("Montenegro Gold")),
    (HexCode::new("#FFFFFF"), ColorName::new("Montenegro White")),
    (HexCode::new("#D20000"), ColorName::new("Serbia Red")),
    (HexCode::new("#0C4076"), ColorName::new("Serbia Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Serbia White")),
    (HexCode::new("#C6363C"), ColorName::new("North Macedonia Red")),
    (HexCode::new("#F8E500"), ColorName::new("North Macedonia Yellow")),
    (HexCode::new("#0032A0"), ColorName::new("Slovakia Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Slovakia White")),
    (HexCode::new("#CE1126"), ColorName::new("Slovakia Red")),
    (HexCode::new("#005DA4"), ColorName::new("Slovenia Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Slovenia White")),
    (HexCode::new("#D50000"), ColorName::new("Slovenia Red")),
    (HexCode::new("#11457E"), ColorName::new("Czechia Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Czechia White")),
    (HexCode::new("#D7141A"), ColorName::new("Czechia Red")),
    (HexCode::new("#CC0000"), ColorName::new("Malta Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Malta White")),
    (HexCode::new("#DA291C"), ColorName::new("Monaco Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Monaco White")),
    (HexCode::new("#00A3E0"), ColorName::new("Luxembourg Light Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Luxembourg White")),
    (HexCode::new("#EF3340"), ColorName::new("Luxembourg Red")),
    // --- Middle East & North Africa
    (HexCode::new("#8D1B3D"), ColorName::new("Qatar Maroon")),
    (HexCode::new("#FFFFFF"), ColorName::new("Qatar White")),
    (HexCode::new("#CE1126"), ColorName::new("Bahrain Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Bahrain White")),
    (HexCode::new("#007A3D"), ColorName::new("Jordan Green")),
    (HexCode::new("#000000"), ColorName::new("Jordan Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Jordan White")),
    (HexCode::new("#CE1126"), ColorName::new("Jordan Red")),
    (HexCode::new("#00732F"), ColorName::new("United Arab Emirates Green")),
    (HexCode::new("#000000"), ColorName::new("United Arab Emirates Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("United Arab Emirates White")),
    (HexCode::new("#CE1126"), ColorName::new("United Arab Emirates Red")),
    (HexCode::new("#E70013"), ColorName::new("Tunisia Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Tunisia White")),
    (HexCode::new("#239E46"), ColorName::new("Libya Green")),
    (HexCode::new("#E70013"), ColorName::new("Libya Red")),
    (HexCode::new("#000000"), ColorName::new("Libya Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Libya White")),
    (HexCode::new("#D21034"), ColorName::new("Sudan Red")),
    (HexCode::new("#007229"), ColorName::new("Sudan Green")),
    (HexCode::new("#000000"), ColorName::new("Sudan Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Sudan White")),
    (HexCode::new("#ED1C24"), ColorName::new("Lebanon Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Lebanon White")),
    (HexCode::new("#007A3B"), ColorName::new("Lebanon Green")),
    (HexCode::new("#CE1126"), ColorName::new("Syria Red")),
    (HexCode::new("#000000"), ColorName::new("Syria Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Syria White")),
    (HexCode::new("#007A3B"), ColorName::new("Syria Green")),
    (HexCode::new("#CE1126"), ColorName::new("Iraq Red")),
    (HexCode::new("#000000"), ColorName::new("Iraq Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Iraq White")),
    (HexCode::new("#007A3B"), ColorName::new("Iraq Green")),
    // --- Sub-Saharan Africa
    (HexCode::new("#1EB53A"), ColorName::new("Tanzania Green")),
    (HexCode::new("#FCD116"), ColorName::new("Tanzania Yellow")),
    (HexCode::new("#000000"), ColorName::new("Tanzania Black")),
    (HexCode::new("#00A3DD"), ColorName::new("Tanzania Blue")),
    (HexCode::new("#000000"), ColorName::new("Uganda Black")),
    (HexCode::new("#FCDC04"), ColorName::new("Uganda Yellow")),
    (HexCode::new("#D90000"), ColorName::new("Uganda Red")),
    (HexCode::new("#00A1DE"), ColorName::new("Rwanda Sky Blue")),
    (HexCode::new("#FAD201"), ColorName::new("Rwanda Yellow")),
    (HexCode::new("#20603D"), ColorName::new("Rwanda Green")),
    (HexCode::new("#6DA9D2"), ColorName::new("Botswana Light Blue")),
    (HexCode::new("#000000"), ColorName::new("Botswana Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Botswana White")),
    (HexCode::new("#003580"), ColorName::new("Namibia Blue")),
    (HexCode::new("#D21034"), ColorName::new("Namibia Red")),
    (HexCode::new("#009543"), ColorName::new("Namibia Green")),
    (HexCode::new("#FFCE00"), ColorName::new("Namibia Yellow")),
    (HexCode::new("#FFFFFF"), ColorName::new("Namibia White")),
    (HexCode::new("#00A859"), ColorName::new("Zimbabwe Green")),
    (HexCode::new("#FFD200"), ColorName::new("Zimbabwe Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Zimbabwe Red")),
    (HexCode::new("#000000"), ColorName::new("Zimbabwe Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Zimbabwe White")),
    (HexCode::new("#198A00"), ColorName::new("Zambia Green")),
    (HexCode::new("#FF7F00"), ColorName::new("Zambia Orange")),
    (HexCode::new("#000000"), ColorName::new("Zambia Black")),
    (HexCode::new("#CE1126"), ColorName::new("Zambia Red")),
    // --- Central & South Asia
    (HexCode::new("#00AFCA"), ColorName::new("Kazakhstan Sky Blue")),
    (HexCode::new("#FEC50C"), ColorName::new("Kazakhstan Gold")),
    (HexCode::new("#1EB0E9"), ColorName::new("Uzbekistan Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Uzbekistan White")),
    (HexCode::new("#1E9F45"), ColorName::new("Uzbekistan Green")),
    (HexCode::new("#CE1126"), ColorName::new("Uzbekistan Red")),
    (HexCode::new("#006847"), ColorName::new("Turkmenistan Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Turkmenistan White")),
    (HexCode::new("#CE1126"), ColorName::new("Turkmenistan Red")),
    (HexCode::new("#E8112D"), ColorName::new("Kyrgyzstan Red")),
    (HexCode::new("#FCDD09"), ColorName::new("Kyrgyzstan Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Tajikistan Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Tajikistan White")),
    (HexCode::new("#00843D"), ColorName::new("Tajikistan Green")),
    (HexCode::new("#F8C300"), ColorName::new("Tajikistan Yellow")),
    (HexCode::new("#C4272F"), ColorName::new("Mongolia Red")),
    (HexCode::new("#015197"), ColorName::new("Mongolia Blue")),
    (HexCode::new("#FFD900"), ColorName::new("Mongolia Yellow")),
    // --- South & South-East Asia
    (HexCode::new("#DC143C"), ColorName::new("Nepal Crimson")),
    (HexCode::new("#003893"), ColorName::new("Nepal Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Nepal White")),
    (HexCode::new("#FECB00"), ColorName::new("Myanmar Yellow")),
    (HexCode::new("#34B233"), ColorName::new("Myanmar Green")),
    (HexCode::new("#EA1F26"), ColorName::new("Myanmar Red")),
    (HexCode::new("#CE1126"), ColorName::new("Laos Red")),
    (HexCode::new("#002868"), ColorName::new("Laos Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Laos White")),
    (HexCode::new("#ED1C24"), ColorName::new("Cambodia Red")),
    (HexCode::new("#032EA1"), ColorName::new("Cambodia Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Cambodia White")),
    (HexCode::new("#0038A8"), ColorName::new("Philippines Blue")),
    (HexCode::new("#CE1126"), ColorName::new("Philippines Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Philippines White")),
    (HexCode::new("#FCD116"), ColorName::new("Philippines Yellow")),
    (HexCode::new("#010066"), ColorName::new("Malaysia Blue")),
    (HexCode::new("#CC0000"), ColorName::new("Malaysia Red")),
    (HexCode::new("#FFCC00"), ColorName::new("Malaysia Yellow")),
    (HexCode::new("#FFFFFF"), ColorName::new("Malaysia White")),
    (HexCode::new("#EF3340"), ColorName::new("Singapore Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Singapore White")),
    // --- The Americas (additions)
    (HexCode::new("#D52B1E"), ColorName::new("Bolivia Red")),
    (HexCode::new("#FFCC00"), ColorName::new("Bolivia Yellow")),
    (HexCode::new("#007934"), ColorName::new("Bolivia Green")),
    (HexCode::new("#FFD100"), ColorName::new("Ecuador Yellow")),
    (HexCode::new("#0033A0"), ColorName::new("Ecuador Blue")),
    (HexCode::new("#EF3340"), ColorName::new("Ecuador Red")),
    (HexCode::new("#FFCC00"), ColorName::new("Venezuela Yellow")),
    (HexCode::new("#0033A0"), ColorName::new("Venezuela Blue")),
    (HexCode::new("#EF3340"), ColorName::new("Venezuela Red")),
    (HexCode::new("#56A5D8"), ColorName::new("Uruguay Sky Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Uruguay White")),
    (HexCode::new("#FCD116"), ColorName::new("Uruguay Yellow")),
    (HexCode::new("#EF3340"), ColorName::new("Paraguay Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Paraguay White")),
    (HexCode::new("#0033A0"), ColorName::new("Paraguay Blue")),
    (HexCode::new("#4997D0"), ColorName::new("Guatemala Sky Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Guatemala White")),
    (HexCode::new("#0073CF"), ColorName::new("Honduras Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Honduras White")),
    (HexCode::new("#0047AB"), ColorName::new("El Salvador Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("El Salvador White")),
    (HexCode::new("#0067C6"), ColorName::new("Nicaragua Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Nicaragua White")),
    (HexCode::new("#CE1126"), ColorName::new("Costa Rica Red")),
    (HexCode::new("#002B7F"), ColorName::new("Costa Rica Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Costa Rica White")),
    (HexCode::new("#EF3340"), ColorName::new("Panama Red")),
    (HexCode::new("#005293"), ColorName::new("Panama Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Panama White")),
    (HexCode::new("#002A8F"), ColorName::new("Cuba Blue")),
    (HexCode::new("#CF142B"), ColorName::new("Cuba Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Cuba White")),
    (HexCode::new("#002D62"), ColorName::new("Dominican Republic Blue")),
    (HexCode::new("#CE1126"), ColorName::new("Dominican Republic Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Dominican Republic White")),
    (HexCode::new("#00209F"), ColorName::new("Haiti Blue")),
    (HexCode::new("#D21034"), ColorName::new("Haiti Red")),
    // --- Europe (Additions) ("#FF0000", "Albania Red"), ("#000000", "Albania Black"),
    (HexCode::new("#F31500"), ColorName::new("Andorra Red")),
    (HexCode::new("#0018A8"), ColorName::new("Andorra Blue")),
    (HexCode::new("#FEE700"), ColorName::new("Andorra Yellow")),
    (HexCode::new("#ED2939"), ColorName::new("Bulgaria Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Bulgaria White")),
    (HexCode::new("#00966E"), ColorName::new("Bulgaria Green")),
    (HexCode::new("#DA291C"), ColorName::new("Austria Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Austria White")),
    (HexCode::new("#AE1C28"), ColorName::new("Belgium Red")),
    (HexCode::new("#FAE042"), ColorName::new("Belgium Yellow")),
    (HexCode::new("#000000"), ColorName::new("Belgium Black")),
    (HexCode::new("#C6363C"), ColorName::new("Croatia Red")),
    (HexCode::new("#171796"), ColorName::new("Croatia Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Croatia White")),
    (HexCode::new("#0093DD"), ColorName::new("Croatia Cyan")), // For coat of arms ("#F7D417", "Croatia Gold"),  // For coat of arms
    (HexCode::new("#0033A0"), ColorName::new("Cyprus Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Cyprus White")),
    (HexCode::new("#D57800"), ColorName::new("Cyprus Copper")), // Representative color
    (HexCode::new("#C60B1E"), ColorName::new("Denmark Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Denmark White")),
    (HexCode::new("#4891D9"), ColorName::new("Finland Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Finland White")),
    (HexCode::new("#002395"), ColorName::new("France Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("France White")),
    (HexCode::new("#ED2939"), ColorName::new("France Red")),
    (HexCode::new("#FFCE00"), ColorName::new("Germany Gold")),
    (HexCode::new("#000000"), ColorName::new("Germany Black")),
    (HexCode::new("#DD0000"), ColorName::new("Germany Red")),
    (HexCode::new("#0D5EAF"), ColorName::new("Greece Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Greece White")),
    (HexCode::new("#C8102E"), ColorName::new("Hungary Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Hungary White")),
    (HexCode::new("#00843D"), ColorName::new("Hungary Green")),
    (HexCode::new("#009A49"), ColorName::new("Ireland Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Ireland White")),
    (HexCode::new("#FF7900"), ColorName::new("Ireland Orange")),
    (HexCode::new("#009246"), ColorName::new("Italy Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Italy White")),
    (HexCode::new("#CE2B37"), ColorName::new("Italy Red")),
    (HexCode::new("#9E3039"), ColorName::new("Liechtenstein Red")),
    (HexCode::new("#002B7F"), ColorName::new("Liechtenstein Blue")),
    (HexCode::new("#FFD83C"), ColorName::new("Liechtenstein Gold")),
    (HexCode::new("#C8102E"), ColorName::new("Moldova Red")),
    (HexCode::new("#FFCD00"), ColorName::new("Moldova Yellow")),
    (HexCode::new("#003DA5"), ColorName::new("Moldova Blue")),
    (HexCode::new("#AE1C28"), ColorName::new("Netherlands Red")),
    (HexCode::new("#21468B"), ColorName::new("Netherlands Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Netherlands White")),
    (HexCode::new("#D4213D"), ColorName::new("Poland Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Poland White")),
    (HexCode::new("#006600"), ColorName::new("Portugal Green")),
    (HexCode::new("#FF0000"), ColorName::new("Portugal Red")),
    (HexCode::new("#FFFF00"), ColorName::new("Portugal Yellow")), // For coat of arms ("#002D72", "Portugal Blue"),   // For coat of arms
    (HexCode::new("#CC0000"), ColorName::new("San Marino Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("San Marino White")),
    (HexCode::new("#5CACEE"), ColorName::new("San Marino Azure")), // For coat of arms ("#CFB53B", "San Marino Gold"),  // For coat of arms
    (HexCode::new("#C6363C"), ColorName::new("Spain Red")),
    (HexCode::new("#FFC400"), ColorName::new("Spain Yellow")),
    (HexCode::new("#FFCD00"), ColorName::new("Ukraine Yellow")),
    (HexCode::new("#0057B7"), ColorName::new("Ukraine Blue")),
    (HexCode::new("#E4002B"), ColorName::new("United Kingdom Red")),
    (HexCode::new("#012169"), ColorName::new("United Kingdom Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("United Kingdom White")),
    // --- Middle East & North Africa (Additions) ("#006233", "Algeria Green"), ("#FFFFFF", "Algeria White"), ("#D21034", "Algeria Red"),
    (HexCode::new("#C1272D"), ColorName::new("Egypt Red")),
    (HexCode::new("#000000"), ColorName::new("Egypt Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Egypt White")),
    (HexCode::new("#DA0000"), ColorName::new("Iran Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Iran White")),
    (HexCode::new("#239F40"), ColorName::new("Iran Green")),
    (HexCode::new("#CE1126"), ColorName::new("Kuwait Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Kuwait White")),
    (HexCode::new("#007A3D"), ColorName::new("Kuwait Green")),
    (HexCode::new("#000000"), ColorName::new("Kuwait Black")),
    (HexCode::new("#C2111A"), ColorName::new("Morocco Red")),
    (HexCode::new("#007A3D"), ColorName::new("Oman Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Oman White")),
    (HexCode::new("#D21034"), ColorName::new("Oman Red")),
    (HexCode::new("#00692B"), ColorName::new("Pakistan Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Pakistan White")),
    (HexCode::new("#CE1126"), ColorName::new("Palestine Red")),
    (HexCode::new("#000000"), ColorName::new("Palestine Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Palestine White")),
    (HexCode::new("#007A3D"), ColorName::new("Palestine Green")),
    (HexCode::new("#9D2235"), ColorName::new("Saudi Arabia Red")), // Often used with the Shahada ("#006C35", "Saudi Arabia Green"),
    (HexCode::new("#8B0723"), ColorName::new("Turkey Red")),
    (HexCode::new("#E30A17"), ColorName::new("Turkey Crimson")), // A common variant ("#FFFFFF", "Turkey White"),
    (HexCode::new("#FF0000"), ColorName::new("Yemen Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Yemen White")),
    (HexCode::new("#000000"), ColorName::new("Yemen Black")),
    // --- Sub-Saharan Africa (Additions) ("#009E49", "Benin Green"), ("#FCD116", "Benin Yellow"), ("#E8112D", "Benin Red"),
    (HexCode::new("#FFFFFF"), ColorName::new("Burkina Faso White")),
    (HexCode::new("#009E49"), ColorName::new("Burkina Faso Green")),
    (HexCode::new("#EF2B2D"), ColorName::new("Burkina Faso Red")),
    (HexCode::new("#007A5E"), ColorName::new("Cameroon Green")),
    (HexCode::new("#FCD116"), ColorName::new("Cameroon Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Cameroon Red")),
    (HexCode::new("#3C3B6E"), ColorName::new("Cameroon Star")), // Color of the star
    (HexCode::new("#002B7F"), ColorName::new("DR Congo Blue")),
    (HexCode::new("#FCD116"), ColorName::new("DR Congo Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("DR Congo Red")),
    (HexCode::new("#009E60"), ColorName::new("Ethiopia Green")),
    (HexCode::new("#DA121A"), ColorName::new("Ethiopia Red")),
    (HexCode::new("#FCDD09"), ColorName::new("Ethiopia Yellow")),
    (HexCode::new("#078930"), ColorName::new("Ethiopia Light Green")), // Newer flag addition ("#0F47AF", "Ethiopia Blue"),        // Newer flag addition
    (HexCode::new("#FFCE00"), ColorName::new("Ghana Yellow")),
    (HexCode::new("#006B3F"), ColorName::new("Ghana Green")),
    (HexCode::new("#CE1126"), ColorName::new("Ghana Red")),
    (HexCode::new("#000000"), ColorName::new("Ghana Black")),
    (HexCode::new("#009F4D"), ColorName::new("Guinea Green")),
    (HexCode::new("#FCD116"), ColorName::new("Guinea Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Guinea Red")),
    (HexCode::new("#009E49"), ColorName::new("Kenya Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Kenya White")),
    (HexCode::new("#000000"), ColorName::new("Kenya Black")),
    (HexCode::new("#B00D23"), ColorName::new("Kenya Red")), // Shield color ("#E8B725", "Kenya Gold"), // Shield color
    (HexCode::new("#CE1126"), ColorName::new("Mali Red")),
    (HexCode::new("#FCD116"), ColorName::new("Mali Yellow")),
    (HexCode::new("#14B53A"), ColorName::new("Mali Green")),
    (HexCode::new("#E31B23"), ColorName::new("Mozambique Red")),
    (HexCode::new("#000000"), ColorName::new("Mozambique Black")),
    (HexCode::new("#009E49"), ColorName::new("Mozambique Green")),
    (HexCode::new("#FFFF00"), ColorName::new("Mozambique Yellow")),
    (HexCode::new("#FFFFFF"), ColorName::new("Mozambique White")),
    (HexCode::new("#00A859"), ColorName::new("Nigeria Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Nigeria White")),
    (HexCode::new("#FFB81C"), ColorName::new("South Africa Gold")),
    (HexCode::new("#000000"), ColorName::new("South Africa Black")),
    (HexCode::new("#E03C31"), ColorName::new("South Africa Chili Red")),
    (HexCode::new("#007749"), ColorName::new("South Africa Green")),
    (HexCode::new("#001489"), ColorName::new("South Africa Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("South Africa White")),
    (HexCode::new("#CE1126"), ColorName::new("Senegal Red")),
    (HexCode::new("#FCD116"), ColorName::new("Senegal Yellow")),
    (HexCode::new("#00853F"), ColorName::new("Senegal Green")),
    // --- Central & South Asia (Additions) ("#006A4D", "Bangladesh Green"), ("#F42A41", "Bangladesh Red"),
    (HexCode::new("#FF9933"), ColorName::new("India Saffron")),
    (HexCode::new("#FFFFFF"), ColorName::new("India White")),
    (HexCode::new("#138808"), ColorName::new("India Green")),
    (HexCode::new("#000080"), ColorName::new("India Navy Blue")), // For Ashoka Chakra
    (HexCode::new("#006847"), ColorName::new("Maldives Green")),
    (HexCode::new("#D21034"), ColorName::new("Maldives Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Maldives White")),
    (HexCode::new("#9CA69C"), ColorName::new("Afghanistan Black")), // Representative ("#DE2029", "Afghanistan Red"),   // Representative ("#FFFFFF", "Afghanistan White"), // Representative ("#007A36", "Afghanistan Green"), // Representative ("##000000", "Afghanistan Shahada"), // Note: Flag has changed; these are representative.
    // --- East Asia & Oceania ("#DE2910", "China Red"), ("#FFDE00", "China Yellow"),
    (HexCode::new("#BC002D"), ColorName::new("Japan Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Japan White")),
    (HexCode::new("#C60C30"), ColorName::new("South Korea Red")),
    (HexCode::new("#003478"), ColorName::new("South Korea Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("South Korea White")),
    (HexCode::new("#000000"), ColorName::new("South Korea Black")),
    (HexCode::new("#00247D"), ColorName::new("Australia Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Australia White")),
    (HexCode::new("#E4002B"), ColorName::new("Australia Red")),
    (HexCode::new("#FFCD00"), ColorName::new("Australia Gold")), // Commonwealth Star
    (HexCode::new("#00247D"), ColorName::new("New Zealand Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("New Zealand White")),
    (HexCode::new("#CC0000"), ColorName::new("New Zealand Red")),
    (HexCode::new("#FF0000"), ColorName::new("Fiji Red")),
    (HexCode::new("#00247D"), ColorName::new("Fiji Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Fiji White")),
    (HexCode::new("#012169"), ColorName::new("Papua New Guinea Blue")),
    (HexCode::new("#000000"), ColorName::new("Papua New Guinea Black")),
    (HexCode::new("#C8102E"), ColorName::new("Papua New Guinea Red")),
    (HexCode::new("#FFC72C"), ColorName::new("Papua New Guinea Gold")),
    (HexCode::new("#D21034"), ColorName::new("Samoa Red")),
    (HexCode::new("#00247D"), ColorName::new("Samoa Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Samoa White")),
    (HexCode::new("#C1272D"), ColorName::new("Tonga Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Tonga White")),
    (HexCode::new("#00247D"), ColorName::new("Vanuatu Blue")),
    (HexCode::new("#FFC72C"), ColorName::new("Vanuatu Yellow")),
    (HexCode::new("#BD1019"), ColorName::new("Vanuatu Red")),
    (HexCode::new("#000000"), ColorName::new("Vanuatu Black")),
    (HexCode::new("#009543"), ColorName::new("Vanuatu Green")),
    // --- The Americas (Additions) ("#75AADB", "Argentina Light Blue"), ("#FFFFFF", "Argentina White"), ("#F6B40E", "Argentina Sun Yellow"), // For Sun of May ("#85340A", "Argentina Sun Brown"),  // For Sun of May
    (HexCode::new("#009C3B"), ColorName::new("Brazil Green")),
    (HexCode::new("#FFDF00"), ColorName::new("Brazil Yellow")),
    (HexCode::new("#002776"), ColorName::new("Brazil Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Brazil White")),
    (HexCode::new("#FF0000"), ColorName::new("Chile Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Chile White")),
    (HexCode::new("#0039A6"), ColorName::new("Chile Blue")),
    (HexCode::new("#FFCE00"), ColorName::new("Colombia Yellow")),
    (HexCode::new("#003893"), ColorName::new("Colombia Blue")),
    (HexCode::new("#CE1126"), ColorName::new("Colombia Red")),
    (HexCode::new("#E30A17"), ColorName::new("Canada Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Canada White")),
    (HexCode::new("#002B7F"), ColorName::new("Jamaica Gold")), // Color name is "Gold", but hex is often dark blue for contrast ("#000000", "Jamaica Black"), ("#009B3A", "Jamaica Green"), ("#FED100", "Jamaica Yellow"),
    (HexCode::new("#D52B1E"), ColorName::new("Mexico Red")),
    (HexCode::new("#006847"), ColorName::new("Mexico Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Mexico White")),
    (HexCode::new("#CE1126"), ColorName::new("Mexico Red (Coat)")), // Slightly different red in coat of arms ("#9D5B29", "Mexico Brown"),      // For the eagle in coat of arms
    (HexCode::new("#002A8F"), ColorName::new("Peru Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Peru White")),
    (HexCode::new("#012169"), ColorName::new("Trinidad and Tobago Red")),
    (HexCode::new("#000000"), ColorName::new("Trinidad and Tobago Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Trinidad and Tobago White")),
    // --- Caribbean Additions ("#CE1126", "Barbados Red"), ("#00267F", "Barbados Blue"), ("#FFC726", "Barbados Gold"),
    (HexCode::new("#FFB81C"), ColorName::new("Bahamas Gold")),
    (HexCode::new("#00ABC9"), ColorName::new("Bahamas Aquamarine")),
    (HexCode::new("#000000"), ColorName::new("Bahamas Black")),
    (HexCode::new("#CE1126"), ColorName::new("Grenada Red")),
    (HexCode::new("#007A5E"), ColorName::new("Grenada Green")),
    (HexCode::new("#FCD116"), ColorName::new("Grenada Yellow")),
    (HexCode::new("#C8102E"), ColorName::new("Saint Lucia Cerise")),
    (HexCode::new("#6CC5EB"), ColorName::new("Saint Lucia Azure")),
    (HexCode::new("#FCD680"), ColorName::new("Saint Lucia Gold")),
    (HexCode::new("#000000"), ColorName::new("Saint Lucia Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Saint Lucia White")),
    (HexCode::new("#FCD116"), ColorName::new("Saint Vincent and the Grenadines Yellow")),
    (HexCode::new("#009E60"), ColorName::new("Saint Vincent and the Grenadines Green")),
    (HexCode::new("#0072CE"), ColorName::new("Saint Vincent and the Grenadines Blue")),
    // Add a small supplement for commonly missing countries.
    // (Feel free to extend this list later.)
    // South Asia / Indian Ocean
    (HexCode::new("#FF9933"), ColorName::new("Sri Lanka Saffron")),
    (HexCode::new("#006A4E"), ColorName::new("Sri Lanka Green")),
    (HexCode::new("#003893"), ColorName::new("Sri Lanka Blue")),
    (HexCode::new("#FCD116"), ColorName::new("Sri Lanka Yellow")),
    (HexCode::new("#8D153A"), ColorName::new("Bhutan Maroon")),
    (HexCode::new("#FFCC00"), ColorName::new("Bhutan Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Brunei Red")),
    (HexCode::new("#F7E017"), ColorName::new("Brunei Yellow")),
    (HexCode::new("#000000"), ColorName::new("Brunei Black")),
    (HexCode::new("#FFFFFF"), ColorName::new("Brunei White")),
    (HexCode::new("#0000FF"), ColorName::new("Timor-Leste Blue")), // coat usage; flag: red/yellow/black
    (HexCode::new("#DA291C"), ColorName::new("Timor-Leste Red")),
    (HexCode::new("#000000"), ColorName::new("Timor-Leste Black")),
    (HexCode::new("#F8C300"), ColorName::new("Timor-Leste Yellow")),
    // East Asia
    (HexCode::new("#024FA2"), ColorName::new("North Korea Blue")),
    (HexCode::new("#ED1C27"), ColorName::new("North Korea Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("North Korea White")),
    // Europe
    (HexCode::new("#0057A4"), ColorName::new("Belarus Blue")),
    (HexCode::new("#D22730"), ColorName::new("Belarus Red")),
    (HexCode::new("#009E49"), ColorName::new("Belarus Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Belarus White")),
    // Central / North Africa
    (HexCode::new("#10AF2A"), ColorName::new("Eritrea Green")),
    (HexCode::new("#EF2B2D"), ColorName::new("Eritrea Red")),
    (HexCode::new("#00A3E0"), ColorName::new("Eritrea Blue")),
    (HexCode::new("#FCD116"), ColorName::new("Eritrea Yellow")),
    (HexCode::new("#6AB2E7"), ColorName::new("Somalia Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Somalia White")),
    (HexCode::new("#00A3DD"), ColorName::new("Djibouti Blue")),
    (HexCode::new("#9ECE3F"), ColorName::new("Djibouti Green")),
    (HexCode::new("#EF3340"), ColorName::new("Djibouti Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Djibouti White")),
    (HexCode::new("#00A95C"), ColorName::new("Burundi Green")),
    (HexCode::new("#EF3340"), ColorName::new("Burundi Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Burundi White")),
    (HexCode::new("#00A859"), ColorName::new("Gabon Green")),
    (HexCode::new("#FCD116"), ColorName::new("Gabon Yellow")),
    (HexCode::new("#009E60"), ColorName::new("Gabon Blue")),
    (HexCode::new("#009543"), ColorName::new("Equatorial Guinea Green")),
    (HexCode::new("#0073CF"), ColorName::new("Equatorial Guinea Blue")),
    (HexCode::new("#CE1126"), ColorName::new("Equatorial Guinea Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Equatorial Guinea White")),
    (HexCode::new("#003082"), ColorName::new("Chad Blue")),
    (HexCode::new("#FCD116"), ColorName::new("Chad Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Chad Red")),
    (HexCode::new("#EEC900"), ColorName::new("Niger Orange")),
    (HexCode::new("#FFFFFF"), ColorName::new("Niger White")),
    (HexCode::new("#0DB02B"), ColorName::new("Niger Green")),
    (HexCode::new("#000000"), ColorName::new("Angola Black")),
    (HexCode::new("#CC092F"), ColorName::new("Angola Red")),
    (HexCode::new("#F7D417"), ColorName::new("Angola Yellow")),
    // West Africa
    (HexCode::new("#008751"), ColorName::new("Benin Green")),
    (HexCode::new("#FCD116"), ColorName::new("Benin Yellow")),
    (HexCode::new("#E8112D"), ColorName::new("Benin Red")),
    (HexCode::new("#009E60"), ColorName::new("Côte d'Ivoire Green")),
    (HexCode::new("#FFFFFF"), ColorName::new("Côte d'Ivoire White")),
    (HexCode::new("#FF8200"), ColorName::new("Côte d'Ivoire Orange")),
    (HexCode::new("#CE1126"), ColorName::new("Guinea-Bissau Red")),
    (HexCode::new("#FCD116"), ColorName::new("Guinea-Bissau Yellow")),
    (HexCode::new("#009E49"), ColorName::new("Guinea-Bissau Green")),
    (HexCode::new("#007749"), ColorName::new("Gambia Green")),
    (HexCode::new("#CE1126"), ColorName::new("Gambia Red")),
    (HexCode::new("#0C1C8C"), ColorName::new("Gambia Blue")),
    (HexCode::new("#FCD116"), ColorName::new("Gambia Yellow")),
    (HexCode::new("#009543"), ColorName::new("Cape Verde Green")),
    (HexCode::new("#0033A0"), ColorName::new("Cape Verde Blue")),
    (HexCode::new("#FCD116"), ColorName::new("Cape Verde Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Cape Verde Red")),
    (HexCode::new("#006233"), ColorName::new("Mauritania Green")),
    (HexCode::new("#FFC61E"), ColorName::new("Mauritania Gold")),
    // Central Africa
    (HexCode::new("#003082"), ColorName::new("Central African Republic Blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("Central African Republic White")),
    (HexCode::new("#FCD116"), ColorName::new("Central African Republic Yellow")),
    (HexCode::new("#289728"), ColorName::new("Central African Republic Green")),
    (HexCode::new("#D21034"), ColorName::new("Central African Republic Red")),
    (HexCode::new("#009543"), ColorName::new("Republic of the Congo Green")),
    (HexCode::new("#FCD116"), ColorName::new("Republic of the Congo Yellow")),
    (HexCode::new("#DC241F"), ColorName::new("Republic of the Congo Red")),
    // Caribbean / Americas
    (HexCode::new("#00267F"), ColorName::new("Barbados Blue")),
    (HexCode::new("#FFC726"), ColorName::new("Barbados Gold")),
    (HexCode::new("#CE1126"), ColorName::new("Barbados Red (Emblem)")),
    (HexCode::new("#007749"), ColorName::new("Jamaica Green")),
    (HexCode::new("#000000"), ColorName::new("Jamaica Black")),
    (HexCode::new("#FED100"), ColorName::new("Jamaica Gold")),
    (HexCode::new("#007A5E"), ColorName::new("Belize Green")),
    (HexCode::new("#003F87"), ColorName::new("Belize Blue")),
    (HexCode::new("#CE1126"), ColorName::new("Belize Red")),
    (HexCode::new("#009E49"), ColorName::new("Guyana Green")),
    (HexCode::new("#FCD116"), ColorName::new("Guyana Yellow")),
    (HexCode::new("#CE1126"), ColorName::new("Guyana Red")),
    (HexCode::new("#3A75C4"), ColorName::new("Suriname Blue")), // (flag is green/red/white/yellow; blue used in COA contexts)
    (HexCode::new("#377E3F"), ColorName::new("Suriname Green")),
    (HexCode::new("#B40A2D"), ColorName::new("Suriname Red")),
    (HexCode::new("#FFFFFF"), ColorName::new("Suriname White")),
    (HexCode::new("#ECC81D"), ColorName::new("Suriname Yellow")),
];
