// src/colors/national.rs
//
// National colors (approximated from official flag specs / Pantone → sRGB).
// Each entry is (HexCode, ColorName) with structured types.
use once_cell::sync::Lazy;
use crate::color_types::{HexCode, ColorName, Entity, Ordering};
use crate::colors_helper::Origin;
use std::collections::BTreeSet;

/// Combined, normalized, de-duplicated, and sorted national colors.
/// Sort key: (case-insensitive name, then hex).
pub static COLORS_NATIONAL: Lazy<Vec<(HexCode, ColorName)>> = Lazy::new(|| {
    // 1) chain base + supplement
    let iter = COLORS_NATIONAL_UNORDERED
        .iter()
        .copied()
        .chain(COLORS_NATIONAL_UNORDERED.iter().copied());

    // 2) normalize (trim whitespace) - extract the strings from HexCode/ColorName
    let mut v: Vec<(HexCode, ColorName)> = iter
        .map(|(hex, name)| {
            let hex_str = hex.as_str().trim();
            let name_str = name.as_str().trim();
            (HexCode::new(hex_str), ColorName::new_full(name_str, Entity::Place, Origin::National, Ordering::Name))
        })
        .collect();

    // 3) exact de-duplication by (hex, name)
    let mut seen: BTreeSet<(String, String)> = BTreeSet::new();
    v.retain(|(h, n)| seen.insert((h.as_str().to_string(), n.as_str().to_string())));

    // 4) sort by name (case-insensitive), then by hex - use the Ord implementation
    v.sort_by(|a, b| {
        let (ha, na) = a;
        let (hb, nb) = b;
        na.cmp(nb).then_with(|| ha.cmp(hb))
    });

    v
});
pub const COLORS_NATIONAL_UNORDERED: &[(HexCode, ColorName)] = &[
    // United States
    (HexCode::new("#000000"), ColorName::new_full("Afghanistan Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D32011"), ColorName::new_full("Afghanistan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A36"), ColorName::new_full("Afghanistan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Afghanistan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED1C24"), ColorName::new_full("Albania Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006233"), ColorName::new_full("Algeria Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Algeria White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D21034"), ColorName::new_full("Algeria Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#74ACDF"), ColorName::new_full("Argentina Light Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Argentina White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F6B40E"), ColorName::new_full("Argentina Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00843D"), ColorName::new_full("Australia Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCD00"), ColorName::new_full("Australia Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED2939"), ColorName::new_full("Austria Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Austria White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006A4E"), ColorName::new_full("Bangladesh Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F42A41"), ColorName::new_full("Bangladesh Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Belgium Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FDDA24"), ColorName::new_full("Belgium Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Belgium Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009B3A"), ColorName::new_full("Brazil Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FEDF00"), ColorName::new_full("Brazil Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002776"), ColorName::new_full("Brazil Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Bulgaria White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00966E"), ColorName::new_full("Bulgaria Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D62612"), ColorName::new_full("Bulgaria Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF0000"), ColorName::new_full("Canada Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Canada White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D52B1E"), ColorName::new_full("Chile Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Chile White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0033A0"), ColorName::new_full("Chile Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DE2910"), ColorName::new_full("China Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFDE00"), ColorName::new_full("China Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Colombia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003893"), ColorName::new_full("Colombia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Colombia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED1C24"), ColorName::new_full("Croatia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Croatia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#171796"), ColorName::new_full("Croatia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C60C30"), ColorName::new_full("Denmark Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Denmark White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Egypt Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Egypt White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Egypt Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C09300"), ColorName::new_full("Egypt Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#078930"), ColorName::new_full("Ethiopia Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCDD09"), ColorName::new_full("Ethiopia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DA121A"), ColorName::new_full("Ethiopia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003580"), ColorName::new_full("Finland Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Finland White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002395"), ColorName::new_full("France Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("France White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED2939"), ColorName::new_full("France Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Germany Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DD0000"), ColorName::new_full("Germany Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCC00"), ColorName::new_full("Germany Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Ghana Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Ghana Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006B3F"), ColorName::new_full("Ghana Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Ghana Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0D5EAF"), ColorName::new_full("Greece Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Greece White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF9933"), ColorName::new_full("India Saffron", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("India White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#138808"), ColorName::new_full("India Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000080"), ColorName::new_full("India Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Indonesia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Indonesia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#239F40"), ColorName::new_full("Iran Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Iran White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DA0000"), ColorName::new_full("Iran Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#169B62"), ColorName::new_full("Ireland Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Ireland White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF883E"), ColorName::new_full("Ireland Orange", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0038B8"), ColorName::new_full("Israel Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Israel White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009246"), ColorName::new_full("Italy Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Italy White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE2B37"), ColorName::new_full("Italy Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#BC002D"), ColorName::new_full("Japan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Japan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Kenya Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#BB0000"), ColorName::new_full("Kenya Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006600"), ColorName::new_full("Kenya Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Kenya White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006341"), ColorName::new_full("Mexico Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Mexico White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Mexico Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C1272D"), ColorName::new_full("Morocco Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006233"), ColorName::new_full("Morocco Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#AE1C28"), ColorName::new_full("Netherlands Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Netherlands White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#21468B"), ColorName::new_full("Netherlands Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("New Zealand Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("New Zealand White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CC0000"), ColorName::new_full("New Zealand Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#008753"), ColorName::new_full("Nigeria Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Nigeria White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#01411C"), ColorName::new_full("Pakistan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Pakistan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D91023"), ColorName::new_full("Peru Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Peru White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Poland White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DC143C"), ColorName::new_full("Poland Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006600"), ColorName::new_full("Portugal Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF0000"), ColorName::new_full("Portugal Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFF00"), ColorName::new_full("Portugal Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Russia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0039A6"), ColorName::new_full("Russia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D52B1E"), ColorName::new_full("Russia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006C35"), ColorName::new_full("Saudi Arabia Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Saudi Arabia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E03C31"), ColorName::new_full("South Africa Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#001489"), ColorName::new_full("South Africa Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007749"), ColorName::new_full("South Africa Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFB81C"), ColorName::new_full("South Africa Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("South Africa Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("South Africa White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("South Korea White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CD2E3A"), ColorName::new_full("South Korea Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0047A0"), ColorName::new_full("South Korea Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("South Korea Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#AA151B"), ColorName::new_full("Spain Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F1BF00"), ColorName::new_full("Spain Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED1C24"), ColorName::new_full("Thailand Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Thailand White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#241D4F"), ColorName::new_full("Thailand Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E30A17"), ColorName::new_full("Turkey Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Turkey White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0057B7"), ColorName::new_full("Ukraine Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFD700"), ColorName::new_full("Ukraine Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#012169"), ColorName::new_full("United Kingdom Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C8102E"), ColorName::new_full("United Kingdom Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("United Kingdom White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#BF0A30"), ColorName::new_full("United States Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002868"), ColorName::new_full("United States Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("United States White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DA251D"), ColorName::new_full("Vietnam Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFF00"), ColorName::new_full("Vietnam Yellow", Entity::Place, Origin::National, Ordering::Name)),
    // Append below to COLORS_NATIONAL:

    // --- Europe (Nordics, Baltics, Balkans, etc.)
    (HexCode::new("#005293"), ColorName::new_full("Sweden Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FECB00"), ColorName::new_full("Sweden Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#BA0C2F"), ColorName::new_full("Norway Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00205B"), ColorName::new_full("Norway Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Norway White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003897"), ColorName::new_full("Iceland Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D72828"), ColorName::new_full("Iceland Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Iceland White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DA291C"), ColorName::new_full("Switzerland Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Switzerland White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002B7F"), ColorName::new_full("Romania Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Romania Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Romania Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#9E1B34"), ColorName::new_full("Latvia Carmine", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Latvia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FDB913"), ColorName::new_full("Lithuania Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006A44"), ColorName::new_full("Lithuania Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C1272D"), ColorName::new_full("Lithuania Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0072CE"), ColorName::new_full("Estonia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Estonia Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Estonia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D90012"), ColorName::new_full("Armenia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0033A0"), ColorName::new_full("Armenia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F2A800"), ColorName::new_full("Armenia Apricot", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00B5E2"), ColorName::new_full("Azerbaijan Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Azerbaijan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009F4D"), ColorName::new_full("Azerbaijan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Azerbaijan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E62B1E"), ColorName::new_full("Georgia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Georgia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0F47AF"), ColorName::new_full("Bosnia and Herzegovina Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCDD09"), ColorName::new_full("Bosnia and Herzegovina Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Bosnia and Herzegovina White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C8102E"), ColorName::new_full("Montenegro Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCD00"), ColorName::new_full("Montenegro Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Montenegro White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D20000"), ColorName::new_full("Serbia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0C4076"), ColorName::new_full("Serbia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Serbia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C6363C"), ColorName::new_full("North Macedonia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F8E500"), ColorName::new_full("North Macedonia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0032A0"), ColorName::new_full("Slovakia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Slovakia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Slovakia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#005DA4"), ColorName::new_full("Slovenia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Slovenia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D50000"), ColorName::new_full("Slovenia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#11457E"), ColorName::new_full("Czechia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Czechia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D7141A"), ColorName::new_full("Czechia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CC0000"), ColorName::new_full("Malta Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Malta White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DA291C"), ColorName::new_full("Monaco Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Monaco White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A3E0"), ColorName::new_full("Luxembourg Light Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Luxembourg White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Luxembourg Red", Entity::Place, Origin::National, Ordering::Name)),
    // --- Middle East & North Africa
    (HexCode::new("#8D1B3D"), ColorName::new_full("Qatar Maroon", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Qatar White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Bahrain Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Bahrain White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A3D"), ColorName::new_full("Jordan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Jordan Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Jordan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Jordan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00732F"), ColorName::new_full("United Arab Emirates Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("United Arab Emirates Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("United Arab Emirates White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("United Arab Emirates Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E70013"), ColorName::new_full("Tunisia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Tunisia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#239E46"), ColorName::new_full("Libya Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E70013"), ColorName::new_full("Libya Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Libya Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Libya White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D21034"), ColorName::new_full("Sudan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007229"), ColorName::new_full("Sudan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Sudan Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Sudan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED1C24"), ColorName::new_full("Lebanon Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Lebanon White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A3B"), ColorName::new_full("Lebanon Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Syria Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Syria Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Syria White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A3B"), ColorName::new_full("Syria Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Iraq Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Iraq Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Iraq White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A3B"), ColorName::new_full("Iraq Green", Entity::Place, Origin::National, Ordering::Name)),
    // --- Sub-Saharan Africa
    (HexCode::new("#1EB53A"), ColorName::new_full("Tanzania Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Tanzania Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Tanzania Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A3DD"), ColorName::new_full("Tanzania Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Uganda Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCDC04"), ColorName::new_full("Uganda Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D90000"), ColorName::new_full("Uganda Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A1DE"), ColorName::new_full("Rwanda Sky Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FAD201"), ColorName::new_full("Rwanda Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#20603D"), ColorName::new_full("Rwanda Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#6DA9D2"), ColorName::new_full("Botswana Light Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Botswana Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Botswana White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003580"), ColorName::new_full("Namibia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D21034"), ColorName::new_full("Namibia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009543"), ColorName::new_full("Namibia Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCE00"), ColorName::new_full("Namibia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Namibia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A859"), ColorName::new_full("Zimbabwe Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFD200"), ColorName::new_full("Zimbabwe Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Zimbabwe Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Zimbabwe Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Zimbabwe White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#198A00"), ColorName::new_full("Zambia Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF7F00"), ColorName::new_full("Zambia Orange", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Zambia Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Zambia Red", Entity::Place, Origin::National, Ordering::Name)),
    // --- Central & South Asia
    (HexCode::new("#00AFCA"), ColorName::new_full("Kazakhstan Sky Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FEC50C"), ColorName::new_full("Kazakhstan Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#1EB0E9"), ColorName::new_full("Uzbekistan Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Uzbekistan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#1E9F45"), ColorName::new_full("Uzbekistan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Uzbekistan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006847"), ColorName::new_full("Turkmenistan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Turkmenistan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Turkmenistan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E8112D"), ColorName::new_full("Kyrgyzstan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCDD09"), ColorName::new_full("Kyrgyzstan Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Tajikistan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Tajikistan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00843D"), ColorName::new_full("Tajikistan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F8C300"), ColorName::new_full("Tajikistan Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C4272F"), ColorName::new_full("Mongolia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#015197"), ColorName::new_full("Mongolia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFD900"), ColorName::new_full("Mongolia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    // --- South & South-East Asia
    (HexCode::new("#DC143C"), ColorName::new_full("Nepal Crimson", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003893"), ColorName::new_full("Nepal Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Nepal White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FECB00"), ColorName::new_full("Myanmar Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#34B233"), ColorName::new_full("Myanmar Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EA1F26"), ColorName::new_full("Myanmar Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Laos Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002868"), ColorName::new_full("Laos Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Laos White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED1C24"), ColorName::new_full("Cambodia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#032EA1"), ColorName::new_full("Cambodia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Cambodia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0038A8"), ColorName::new_full("Philippines Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Philippines Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Philippines White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Philippines Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#010066"), ColorName::new_full("Malaysia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CC0000"), ColorName::new_full("Malaysia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCC00"), ColorName::new_full("Malaysia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Malaysia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Singapore Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Singapore White", Entity::Place, Origin::National, Ordering::Name)),
    // --- The Americas (additions)
    (HexCode::new("#D52B1E"), ColorName::new_full("Bolivia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCC00"), ColorName::new_full("Bolivia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007934"), ColorName::new_full("Bolivia Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFD100"), ColorName::new_full("Ecuador Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0033A0"), ColorName::new_full("Ecuador Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Ecuador Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCC00"), ColorName::new_full("Venezuela Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0033A0"), ColorName::new_full("Venezuela Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Venezuela Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#56A5D8"), ColorName::new_full("Uruguay Sky Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Uruguay White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Uruguay Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Paraguay Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Paraguay White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0033A0"), ColorName::new_full("Paraguay Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#4997D0"), ColorName::new_full("Guatemala Sky Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Guatemala White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0073CF"), ColorName::new_full("Honduras Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Honduras White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0047AB"), ColorName::new_full("El Salvador Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("El Salvador White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0067C6"), ColorName::new_full("Nicaragua Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Nicaragua White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Costa Rica Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002B7F"), ColorName::new_full("Costa Rica Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Costa Rica White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Panama Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#005293"), ColorName::new_full("Panama Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Panama White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002A8F"), ColorName::new_full("Cuba Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CF142B"), ColorName::new_full("Cuba Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Cuba White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002D62"), ColorName::new_full("Dominican Republic Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Dominican Republic Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Dominican Republic White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00209F"), ColorName::new_full("Haiti Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D21034"), ColorName::new_full("Haiti Red", Entity::Place, Origin::National, Ordering::Name)),
    // --- Europe (Additions) ("#FF0000", "Albania Red"), ("#000000", "Albania Black"),
    (HexCode::new("#F31500"), ColorName::new_full("Andorra Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0018A8"), ColorName::new_full("Andorra Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FEE700"), ColorName::new_full("Andorra Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED2939"), ColorName::new_full("Bulgaria Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Bulgaria White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00966E"), ColorName::new_full("Bulgaria Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DA291C"), ColorName::new_full("Austria Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Austria White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#AE1C28"), ColorName::new_full("Belgium Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FAE042"), ColorName::new_full("Belgium Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Belgium Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C6363C"), ColorName::new_full("Croatia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#171796"), ColorName::new_full("Croatia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Croatia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0093DD"), ColorName::new_full("Croatia Cyan", Entity::Place, Origin::National, Ordering::Name)), // For coat of arms ("#F7D417", "Croatia Gold"),  // For coat of arms
    (HexCode::new("#0033A0"), ColorName::new_full("Cyprus Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Cyprus White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D57800"), ColorName::new_full("Cyprus Copper", Entity::Place, Origin::National, Ordering::Name)), // Representative color
    (HexCode::new("#C60B1E"), ColorName::new_full("Denmark Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Denmark White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#4891D9"), ColorName::new_full("Finland Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Finland White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002395"), ColorName::new_full("France Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("France White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED2939"), ColorName::new_full("France Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCE00"), ColorName::new_full("Germany Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Germany Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DD0000"), ColorName::new_full("Germany Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0D5EAF"), ColorName::new_full("Greece Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Greece White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C8102E"), ColorName::new_full("Hungary Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Hungary White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00843D"), ColorName::new_full("Hungary Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009A49"), ColorName::new_full("Ireland Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Ireland White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF7900"), ColorName::new_full("Ireland Orange", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009246"), ColorName::new_full("Italy Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Italy White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE2B37"), ColorName::new_full("Italy Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#9E3039"), ColorName::new_full("Liechtenstein Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002B7F"), ColorName::new_full("Liechtenstein Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFD83C"), ColorName::new_full("Liechtenstein Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C8102E"), ColorName::new_full("Moldova Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCD00"), ColorName::new_full("Moldova Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003DA5"), ColorName::new_full("Moldova Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#AE1C28"), ColorName::new_full("Netherlands Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#21468B"), ColorName::new_full("Netherlands Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Netherlands White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D4213D"), ColorName::new_full("Poland Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Poland White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006600"), ColorName::new_full("Portugal Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF0000"), ColorName::new_full("Portugal Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFF00"), ColorName::new_full("Portugal Yellow", Entity::Place, Origin::National, Ordering::Name)), // For coat of arms ("#002D72", "Portugal Blue"),   // For coat of arms
    (HexCode::new("#CC0000"), ColorName::new_full("San Marino Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("San Marino White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#5CACEE"), ColorName::new_full("San Marino Azure", Entity::Place, Origin::National, Ordering::Name)), // For coat of arms ("#CFB53B", "San Marino Gold"),  // For coat of arms
    (HexCode::new("#C6363C"), ColorName::new_full("Spain Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFC400"), ColorName::new_full("Spain Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCD00"), ColorName::new_full("Ukraine Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0057B7"), ColorName::new_full("Ukraine Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E4002B"), ColorName::new_full("United Kingdom Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#012169"), ColorName::new_full("United Kingdom Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("United Kingdom White", Entity::Place, Origin::National, Ordering::Name)),
    // --- Middle East & North Africa (Additions) ("#006233", "Algeria Green"), ("#FFFFFF", "Algeria White"), ("#D21034", "Algeria Red"),
    (HexCode::new("#C1272D"), ColorName::new_full("Egypt Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Egypt Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Egypt White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DA0000"), ColorName::new_full("Iran Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Iran White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#239F40"), ColorName::new_full("Iran Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Kuwait Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Kuwait White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A3D"), ColorName::new_full("Kuwait Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Kuwait Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C2111A"), ColorName::new_full("Morocco Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A3D"), ColorName::new_full("Oman Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Oman White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D21034"), ColorName::new_full("Oman Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00692B"), ColorName::new_full("Pakistan Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Pakistan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Palestine Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Palestine Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Palestine White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A3D"), ColorName::new_full("Palestine Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#9D2235"), ColorName::new_full("Saudi Arabia Red", Entity::Place, Origin::National, Ordering::Name)), // Often used with the Shahada ("#006C35", "Saudi Arabia Green"),
    (HexCode::new("#8B0723"), ColorName::new_full("Turkey Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E30A17"), ColorName::new_full("Turkey Crimson", Entity::Place, Origin::National, Ordering::Name)), // A common variant ("#FFFFFF", "Turkey White"),
    (HexCode::new("#FF0000"), ColorName::new_full("Yemen Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Yemen White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Yemen Black", Entity::Place, Origin::National, Ordering::Name)),
    // --- Sub-Saharan Africa (Additions) ("#009E49", "Benin Green"), ("#FCD116", "Benin Yellow"), ("#E8112D", "Benin Red"),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Burkina Faso White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E49"), ColorName::new_full("Burkina Faso Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF2B2D"), ColorName::new_full("Burkina Faso Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A5E"), ColorName::new_full("Cameroon Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Cameroon Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Cameroon Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#3C3B6E"), ColorName::new_full("Cameroon Star", Entity::Place, Origin::National, Ordering::Name)), // Color of the star
    (HexCode::new("#002B7F"), ColorName::new_full("DR Congo Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("DR Congo Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("DR Congo Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E60"), ColorName::new_full("Ethiopia Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DA121A"), ColorName::new_full("Ethiopia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCDD09"), ColorName::new_full("Ethiopia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#078930"), ColorName::new_full("Ethiopia Light Green", Entity::Place, Origin::National, Ordering::Name)), // Newer flag addition ("#0F47AF", "Ethiopia Blue"),        // Newer flag addition
    (HexCode::new("#FFCE00"), ColorName::new_full("Ghana Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006B3F"), ColorName::new_full("Ghana Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Ghana Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Ghana Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009F4D"), ColorName::new_full("Guinea Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Guinea Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Guinea Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E49"), ColorName::new_full("Kenya Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Kenya White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Kenya Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#B00D23"), ColorName::new_full("Kenya Red", Entity::Place, Origin::National, Ordering::Name)), // Shield color ("#E8B725", "Kenya Gold"), // Shield color
    (HexCode::new("#CE1126"), ColorName::new_full("Mali Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Mali Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#14B53A"), ColorName::new_full("Mali Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E31B23"), ColorName::new_full("Mozambique Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Mozambique Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E49"), ColorName::new_full("Mozambique Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFF00"), ColorName::new_full("Mozambique Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Mozambique White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A859"), ColorName::new_full("Nigeria Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Nigeria White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFB81C"), ColorName::new_full("South Africa Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("South Africa Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E03C31"), ColorName::new_full("South Africa Chili Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007749"), ColorName::new_full("South Africa Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#001489"), ColorName::new_full("South Africa Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("South Africa White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Senegal Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Senegal Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00853F"), ColorName::new_full("Senegal Green", Entity::Place, Origin::National, Ordering::Name)),
    // --- Central & South Asia (Additions) ("#006A4D", "Bangladesh Green"), ("#F42A41", "Bangladesh Red"),
    (HexCode::new("#FF9933"), ColorName::new_full("India Saffron", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("India White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#138808"), ColorName::new_full("India Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000080"), ColorName::new_full("India Navy Blue", Entity::Place, Origin::National, Ordering::Name)), // For Ashoka Chakra
    (HexCode::new("#006847"), ColorName::new_full("Maldives Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D21034"), ColorName::new_full("Maldives Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Maldives White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#9CA69C"), ColorName::new_full("Afghanistan Black", Entity::Place, Origin::National, Ordering::Name)), // Representative ("#DE2029", "Afghanistan Red"),   // Representative ("#FFFFFF", "Afghanistan White"), // Representative ("#007A36", "Afghanistan Green"), // Representative ("##000000", "Afghanistan Shahada"), // Note: Flag has changed; these are representative.
    // --- East Asia & Oceania ("#DE2910", "China Red"), ("#FFDE00", "China Yellow"),
    (HexCode::new("#BC002D"), ColorName::new_full("Japan Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Japan White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C60C30"), ColorName::new_full("South Korea Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003478"), ColorName::new_full("South Korea Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("South Korea White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("South Korea Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00247D"), ColorName::new_full("Australia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Australia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E4002B"), ColorName::new_full("Australia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCD00"), ColorName::new_full("Australia Gold", Entity::Place, Origin::National, Ordering::Name)), // Commonwealth Star
    (HexCode::new("#00247D"), ColorName::new_full("New Zealand Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("New Zealand White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CC0000"), ColorName::new_full("New Zealand Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF0000"), ColorName::new_full("Fiji Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00247D"), ColorName::new_full("Fiji Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Fiji White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#012169"), ColorName::new_full("Papua New Guinea Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Papua New Guinea Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C8102E"), ColorName::new_full("Papua New Guinea Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFC72C"), ColorName::new_full("Papua New Guinea Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D21034"), ColorName::new_full("Samoa Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00247D"), ColorName::new_full("Samoa Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Samoa White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C1272D"), ColorName::new_full("Tonga Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Tonga White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00247D"), ColorName::new_full("Vanuatu Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFC72C"), ColorName::new_full("Vanuatu Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#BD1019"), ColorName::new_full("Vanuatu Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Vanuatu Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009543"), ColorName::new_full("Vanuatu Green", Entity::Place, Origin::National, Ordering::Name)),
    // --- The Americas (Additions) ("#75AADB", "Argentina Light Blue"), ("#FFFFFF", "Argentina White"), ("#F6B40E", "Argentina Sun Yellow"), // For Sun of May ("#85340A", "Argentina Sun Brown"),  // For Sun of May
    (HexCode::new("#009C3B"), ColorName::new_full("Brazil Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFDF00"), ColorName::new_full("Brazil Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002776"), ColorName::new_full("Brazil Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Brazil White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF0000"), ColorName::new_full("Chile Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Chile White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0039A6"), ColorName::new_full("Chile Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCE00"), ColorName::new_full("Colombia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003893"), ColorName::new_full("Colombia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Colombia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E30A17"), ColorName::new_full("Canada Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Canada White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#002B7F"), ColorName::new_full("Jamaica Gold", Entity::Place, Origin::National, Ordering::Name)), // Color name is "Gold", but hex is often dark blue for contrast ("#000000", "Jamaica Black"), ("#009B3A", "Jamaica Green"), ("#FED100", "Jamaica Yellow"),
    (HexCode::new("#D52B1E"), ColorName::new_full("Mexico Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006847"), ColorName::new_full("Mexico Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Mexico White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Mexico Red (Coat)", Entity::Place, Origin::National, Ordering::Name)), // Slightly different red in coat of arms ("#9D5B29", "Mexico Brown"),      // For the eagle in coat of arms
    (HexCode::new("#002A8F"), ColorName::new_full("Peru Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Peru White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#012169"), ColorName::new_full("Trinidad and Tobago Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Trinidad and Tobago Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Trinidad and Tobago White", Entity::Place, Origin::National, Ordering::Name)),
    // --- Caribbean Additions ("#CE1126", "Barbados Red"), ("#00267F", "Barbados Blue"), ("#FFC726", "Barbados Gold"),
    (HexCode::new("#FFB81C"), ColorName::new_full("Bahamas Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00ABC9"), ColorName::new_full("Bahamas Aquamarine", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Bahamas Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Grenada Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A5E"), ColorName::new_full("Grenada Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Grenada Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#C8102E"), ColorName::new_full("Saint Lucia Cerise", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#6CC5EB"), ColorName::new_full("Saint Lucia Azure", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD680"), ColorName::new_full("Saint Lucia Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Saint Lucia Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Saint Lucia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Saint Vincent and the Grenadines Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E60"), ColorName::new_full("Saint Vincent and the Grenadines Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0072CE"), ColorName::new_full("Saint Vincent and the Grenadines Blue", Entity::Place, Origin::National, Ordering::Name)),
    // Add a small supplement for commonly missing countries.
    // (Feel free to extend this list later.)
    // South Asia / Indian Ocean
    (HexCode::new("#FF9933"), ColorName::new_full("Sri Lanka Saffron", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006A4E"), ColorName::new_full("Sri Lanka Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003893"), ColorName::new_full("Sri Lanka Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Sri Lanka Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#8D153A"), ColorName::new_full("Bhutan Maroon", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFCC00"), ColorName::new_full("Bhutan Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Brunei Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F7E017"), ColorName::new_full("Brunei Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Brunei Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Brunei White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0000FF"), ColorName::new_full("Timor-Leste Blue", Entity::Place, Origin::National, Ordering::Name)), // coat usage; flag: red/yellow/black
    (HexCode::new("#DA291C"), ColorName::new_full("Timor-Leste Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Timor-Leste Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F8C300"), ColorName::new_full("Timor-Leste Yellow", Entity::Place, Origin::National, Ordering::Name)),
    // East Asia
    (HexCode::new("#024FA2"), ColorName::new_full("North Korea Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ED1C27"), ColorName::new_full("North Korea Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("North Korea White", Entity::Place, Origin::National, Ordering::Name)),
    // Europe
    (HexCode::new("#0057A4"), ColorName::new_full("Belarus Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D22730"), ColorName::new_full("Belarus Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E49"), ColorName::new_full("Belarus Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Belarus White", Entity::Place, Origin::National, Ordering::Name)),
    // Central / North Africa
    (HexCode::new("#10AF2A"), ColorName::new_full("Eritrea Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF2B2D"), ColorName::new_full("Eritrea Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A3E0"), ColorName::new_full("Eritrea Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Eritrea Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#6AB2E7"), ColorName::new_full("Somalia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Somalia White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A3DD"), ColorName::new_full("Djibouti Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#9ECE3F"), ColorName::new_full("Djibouti Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Djibouti Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Djibouti White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A95C"), ColorName::new_full("Burundi Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EF3340"), ColorName::new_full("Burundi Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Burundi White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#00A859"), ColorName::new_full("Gabon Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Gabon Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E60"), ColorName::new_full("Gabon Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009543"), ColorName::new_full("Equatorial Guinea Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0073CF"), ColorName::new_full("Equatorial Guinea Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Equatorial Guinea Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Equatorial Guinea White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003082"), ColorName::new_full("Chad Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Chad Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Chad Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#EEC900"), ColorName::new_full("Niger Orange", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Niger White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0DB02B"), ColorName::new_full("Niger Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Angola Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CC092F"), ColorName::new_full("Angola Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#F7D417"), ColorName::new_full("Angola Yellow", Entity::Place, Origin::National, Ordering::Name)),
    // West Africa
    (HexCode::new("#008751"), ColorName::new_full("Benin Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Benin Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#E8112D"), ColorName::new_full("Benin Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E60"), ColorName::new_full("Côte d'Ivoire Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Côte d'Ivoire White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FF8200"), ColorName::new_full("Côte d'Ivoire Orange", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Guinea-Bissau Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Guinea-Bissau Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E49"), ColorName::new_full("Guinea-Bissau Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007749"), ColorName::new_full("Gambia Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Gambia Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0C1C8C"), ColorName::new_full("Gambia Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Gambia Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009543"), ColorName::new_full("Cape Verde Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#0033A0"), ColorName::new_full("Cape Verde Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Cape Verde Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Cape Verde Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#006233"), ColorName::new_full("Mauritania Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFC61E"), ColorName::new_full("Mauritania Gold", Entity::Place, Origin::National, Ordering::Name)),
    // Central Africa
    (HexCode::new("#003082"), ColorName::new_full("Central African Republic Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Central African Republic White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Central African Republic Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#289728"), ColorName::new_full("Central African Republic Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#D21034"), ColorName::new_full("Central African Republic Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009543"), ColorName::new_full("Republic of the Congo Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Republic of the Congo Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#DC241F"), ColorName::new_full("Republic of the Congo Red", Entity::Place, Origin::National, Ordering::Name)),
    // Caribbean / Americas
    (HexCode::new("#00267F"), ColorName::new_full("Barbados Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFC726"), ColorName::new_full("Barbados Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Barbados Red (Emblem)", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007749"), ColorName::new_full("Jamaica Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#000000"), ColorName::new_full("Jamaica Black", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FED100"), ColorName::new_full("Jamaica Gold", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#007A5E"), ColorName::new_full("Belize Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#003F87"), ColorName::new_full("Belize Blue", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Belize Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#009E49"), ColorName::new_full("Guyana Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FCD116"), ColorName::new_full("Guyana Yellow", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#CE1126"), ColorName::new_full("Guyana Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#3A75C4"), ColorName::new_full("Suriname Blue", Entity::Place, Origin::National, Ordering::Name)), // (flag is green/red/white/yellow; blue used in COA contexts)
    (HexCode::new("#377E3F"), ColorName::new_full("Suriname Green", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#B40A2D"), ColorName::new_full("Suriname Red", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#FFFFFF"), ColorName::new_full("Suriname White", Entity::Place, Origin::National, Ordering::Name)),
    (HexCode::new("#ECC81D"), ColorName::new_full("Suriname Yellow", Entity::Place, Origin::National, Ordering::Name)),
];
