// src/colors/national.rs
//
// National colors (approximated from official flag specs / Pantone → sRGB).
// Each entry is ("#HEX", "Country Color Name")
use once_cell::sync::Lazy;
use std::collections::BTreeSet;

/// Combined, normalized, de-duplicated, and sorted national colors.
/// Sort key: (case-insensitive name, then hex).
pub static COLORS_NATIONAL: Lazy<Vec<(&'static str, &'static str)>> = Lazy::new(|| {
    // 1) chain base + supplement
    let iter = COLORS_NATIONAL_UNORDERED
        .iter()
        .copied()
        .chain(COLORS_NATIONAL_UNORDERED.iter().copied());

    // 2) normalize (trim whitespace)
    let mut v: Vec<(&'static str, &'static str)> =
        iter.map(|(hex, name)| (hex.trim(), name.trim())).collect();

    // 3) exact de-duplication by (hex, name)
    let mut seen: BTreeSet<(String, String)> = BTreeSet::new();
    v.retain(|(h, n)| seen.insert((h.to_string(), n.to_string())));

    // 4) sort by name (case-insensitive), then by hex
    v.sort_by(|a, b| {
        let (ha, na) = a;
        let (hb, nb) = b;
        match na.to_ascii_lowercase().cmp(&nb.to_ascii_lowercase()) {
            std::cmp::Ordering::Equal => ha.cmp(hb),
            ord => ord,
        }
    });

    v
});
pub const COLORS_NATIONAL_UNORDERED: &[(&str, &str)] = &[
    // United States
    ("#000000", "Afghanistan Black"),
    ("#D32011", "Afghanistan Red"),
    ("#007A36", "Afghanistan Green"),
    ("#FFFFFF", "Afghanistan White"),
    ("#ED1C24", "Albania Red"),
    ("#006233", "Algeria Green"),
    ("#FFFFFF", "Algeria White"),
    ("#D21034", "Algeria Red"),
    ("#74ACDF", "Argentina Light Blue"),
    ("#FFFFFF", "Argentina White"),
    ("#F6B40E", "Argentina Yellow"),
    ("#00843D", "Australia Green"),
    ("#FFCD00", "Australia Gold"),
    ("#ED2939", "Austria Red"),
    ("#FFFFFF", "Austria White"),
    ("#006A4E", "Bangladesh Green"),
    ("#F42A41", "Bangladesh Red"),
    ("#000000", "Belgium Black"),
    ("#FDDA24", "Belgium Yellow"),
    ("#EF3340", "Belgium Red"),
    ("#009B3A", "Brazil Green"),
    ("#FEDF00", "Brazil Yellow"),
    ("#002776", "Brazil Blue"),
    ("#FFFFFF", "Bulgaria White"),
    ("#00966E", "Bulgaria Green"),
    ("#D62612", "Bulgaria Red"),
    ("#FF0000", "Canada Red"),
    ("#FFFFFF", "Canada White"),
    ("#D52B1E", "Chile Red"),
    ("#FFFFFF", "Chile White"),
    ("#0033A0", "Chile Blue"),
    ("#DE2910", "China Red"),
    ("#FFDE00", "China Yellow"),
    ("#FCD116", "Colombia Yellow"),
    ("#003893", "Colombia Blue"),
    ("#CE1126", "Colombia Red"),
    ("#ED1C24", "Croatia Red"),
    ("#FFFFFF", "Croatia White"),
    ("#171796", "Croatia Blue"),
    ("#C60C30", "Denmark Red"),
    ("#FFFFFF", "Denmark White"),
    ("#CE1126", "Egypt Red"),
    ("#FFFFFF", "Egypt White"),
    ("#000000", "Egypt Black"),
    ("#C09300", "Egypt Gold"),
    ("#078930", "Ethiopia Green"),
    ("#FCDD09", "Ethiopia Yellow"),
    ("#DA121A", "Ethiopia Red"),
    ("#003580", "Finland Blue"),
    ("#FFFFFF", "Finland White"),
    ("#002395", "France Blue"),
    ("#FFFFFF", "France White"),
    ("#ED2939", "France Red"),
    ("#000000", "Germany Black"),
    ("#DD0000", "Germany Red"),
    ("#FFCC00", "Germany Gold"),
    ("#CE1126", "Ghana Red"),
    ("#FCD116", "Ghana Yellow"),
    ("#006B3F", "Ghana Green"),
    ("#000000", "Ghana Black"),
    ("#0D5EAF", "Greece Blue"),
    ("#FFFFFF", "Greece White"),
    ("#FF9933", "India Saffron"),
    ("#FFFFFF", "India White"),
    ("#138808", "India Green"),
    ("#000080", "India Blue"),
    ("#CE1126", "Indonesia Red"),
    ("#FFFFFF", "Indonesia White"),
    ("#239F40", "Iran Green"),
    ("#FFFFFF", "Iran White"),
    ("#DA0000", "Iran Red"),
    ("#169B62", "Ireland Green"),
    ("#FFFFFF", "Ireland White"),
    ("#FF883E", "Ireland Orange"),
    ("#0038B8", "Israel Blue"),
    ("#FFFFFF", "Israel White"),
    ("#009246", "Italy Green"),
    ("#FFFFFF", "Italy White"),
    ("#CE2B37", "Italy Red"),
    ("#BC002D", "Japan Red"),
    ("#FFFFFF", "Japan White"),
    ("#000000", "Kenya Black"),
    ("#BB0000", "Kenya Red"),
    ("#006600", "Kenya Green"),
    ("#FFFFFF", "Kenya White"),
    ("#006341", "Mexico Green"),
    ("#FFFFFF", "Mexico White"),
    ("#CE1126", "Mexico Red"),
    ("#C1272D", "Morocco Red"),
    ("#006233", "Morocco Green"),
    ("#AE1C28", "Netherlands Red"),
    ("#FFFFFF", "Netherlands White"),
    ("#21468B", "Netherlands Blue"),
    ("#000000", "New Zealand Black"),
    ("#FFFFFF", "New Zealand White"),
    ("#CC0000", "New Zealand Red"),
    ("#008753", "Nigeria Green"),
    ("#FFFFFF", "Nigeria White"),
    ("#01411C", "Pakistan Green"),
    ("#FFFFFF", "Pakistan White"),
    ("#D91023", "Peru Red"),
    ("#FFFFFF", "Peru White"),
    ("#FFFFFF", "Poland White"),
    ("#DC143C", "Poland Red"),
    ("#006600", "Portugal Green"),
    ("#FF0000", "Portugal Red"),
    ("#FFFF00", "Portugal Yellow"),
    ("#FFFFFF", "Russia White"),
    ("#0039A6", "Russia Blue"),
    ("#D52B1E", "Russia Red"),
    ("#006C35", "Saudi Arabia Green"),
    ("#FFFFFF", "Saudi Arabia White"),
    ("#E03C31", "South Africa Red"),
    ("#001489", "South Africa Blue"),
    ("#007749", "South Africa Green"),
    ("#FFB81C", "South Africa Yellow"),
    ("#000000", "South Africa Black"),
    ("#FFFFFF", "South Africa White"),
    ("#FFFFFF", "South Korea White"),
    ("#CD2E3A", "South Korea Red"),
    ("#0047A0", "South Korea Blue"),
    ("#000000", "South Korea Black"),
    ("#AA151B", "Spain Red"),
    ("#F1BF00", "Spain Yellow"),
    ("#ED1C24", "Thailand Red"),
    ("#FFFFFF", "Thailand White"),
    ("#241D4F", "Thailand Blue"),
    ("#E30A17", "Turkey Red"),
    ("#FFFFFF", "Turkey White"),
    ("#0057B7", "Ukraine Blue"),
    ("#FFD700", "Ukraine Yellow"),
    ("#012169", "United Kingdom Blue"),
    ("#C8102E", "United Kingdom Red"),
    ("#FFFFFF", "United Kingdom White"),
    ("#BF0A30", "United States Red"),
    ("#002868", "United States Blue"),
    ("#FFFFFF", "United States White"),
    ("#DA251D", "Vietnam Red"),
    ("#FFFF00", "Vietnam Yellow"),
    // Append below to COLORS_NATIONAL:

    // --- Europe (Nordics, Baltics, Balkans, etc.)
    ("#005293", "Sweden Blue"),
    ("#FECB00", "Sweden Yellow"),
    ("#BA0C2F", "Norway Red"),
    ("#00205B", "Norway Blue"),
    ("#FFFFFF", "Norway White"),
    ("#003897", "Iceland Blue"),
    ("#D72828", "Iceland Red"),
    ("#FFFFFF", "Iceland White"),
    ("#DA291C", "Switzerland Red"),
    ("#FFFFFF", "Switzerland White"),
    ("#002B7F", "Romania Blue"),
    ("#FCD116", "Romania Yellow"),
    ("#CE1126", "Romania Red"),
    ("#9E1B34", "Latvia Carmine"),
    ("#FFFFFF", "Latvia White"),
    ("#FDB913", "Lithuania Yellow"),
    ("#006A44", "Lithuania Green"),
    ("#C1272D", "Lithuania Red"),
    ("#0072CE", "Estonia Blue"),
    ("#000000", "Estonia Black"),
    ("#FFFFFF", "Estonia White"),
    ("#D90012", "Armenia Red"),
    ("#0033A0", "Armenia Blue"),
    ("#F2A800", "Armenia Apricot"),
    ("#00B5E2", "Azerbaijan Blue"),
    ("#EF3340", "Azerbaijan Red"),
    ("#009F4D", "Azerbaijan Green"),
    ("#FFFFFF", "Azerbaijan White"),
    ("#E62B1E", "Georgia Red"),
    ("#FFFFFF", "Georgia White"),
    ("#0F47AF", "Bosnia and Herzegovina Blue"),
    ("#FCDD09", "Bosnia and Herzegovina Yellow"),
    ("#FFFFFF", "Bosnia and Herzegovina White"),
    ("#C8102E", "Montenegro Red"),
    ("#FFCD00", "Montenegro Gold"),
    ("#FFFFFF", "Montenegro White"),
    ("#D20000", "Serbia Red"),
    ("#0C4076", "Serbia Blue"),
    ("#FFFFFF", "Serbia White"),
    ("#C6363C", "North Macedonia Red"),
    ("#F8E500", "North Macedonia Yellow"),
    ("#0032A0", "Slovakia Blue"),
    ("#FFFFFF", "Slovakia White"),
    ("#CE1126", "Slovakia Red"),
    ("#005DA4", "Slovenia Blue"),
    ("#FFFFFF", "Slovenia White"),
    ("#D50000", "Slovenia Red"),
    ("#11457E", "Czechia Blue"),
    ("#FFFFFF", "Czechia White"),
    ("#D7141A", "Czechia Red"),
    ("#CC0000", "Malta Red"),
    ("#FFFFFF", "Malta White"),
    ("#DA291C", "Monaco Red"),
    ("#FFFFFF", "Monaco White"),
    ("#00A3E0", "Luxembourg Light Blue"),
    ("#FFFFFF", "Luxembourg White"),
    ("#EF3340", "Luxembourg Red"),
    // --- Middle East & North Africa
    ("#8D1B3D", "Qatar Maroon"),
    ("#FFFFFF", "Qatar White"),
    ("#CE1126", "Bahrain Red"),
    ("#FFFFFF", "Bahrain White"),
    ("#007A3D", "Jordan Green"),
    ("#000000", "Jordan Black"),
    ("#FFFFFF", "Jordan White"),
    ("#CE1126", "Jordan Red"),
    ("#00732F", "United Arab Emirates Green"),
    ("#000000", "United Arab Emirates Black"),
    ("#FFFFFF", "United Arab Emirates White"),
    ("#CE1126", "United Arab Emirates Red"),
    ("#E70013", "Tunisia Red"),
    ("#FFFFFF", "Tunisia White"),
    ("#239E46", "Libya Green"),
    ("#E70013", "Libya Red"),
    ("#000000", "Libya Black"),
    ("#FFFFFF", "Libya White"),
    ("#D21034", "Sudan Red"),
    ("#007229", "Sudan Green"),
    ("#000000", "Sudan Black"),
    ("#FFFFFF", "Sudan White"),
    ("#ED1C24", "Lebanon Red"),
    ("#FFFFFF", "Lebanon White"),
    ("#007A3B", "Lebanon Green"),
    ("#CE1126", "Syria Red"),
    ("#000000", "Syria Black"),
    ("#FFFFFF", "Syria White"),
    ("#007A3B", "Syria Green"),
    ("#CE1126", "Iraq Red"),
    ("#000000", "Iraq Black"),
    ("#FFFFFF", "Iraq White"),
    ("#007A3B", "Iraq Green"),
    // --- Sub-Saharan Africa
    ("#1EB53A", "Tanzania Green"),
    ("#FCD116", "Tanzania Yellow"),
    ("#000000", "Tanzania Black"),
    ("#00A3DD", "Tanzania Blue"),
    ("#000000", "Uganda Black"),
    ("#FCDC04", "Uganda Yellow"),
    ("#D90000", "Uganda Red"),
    ("#00A1DE", "Rwanda Sky Blue"),
    ("#FAD201", "Rwanda Yellow"),
    ("#20603D", "Rwanda Green"),
    ("#6DA9D2", "Botswana Light Blue"),
    ("#000000", "Botswana Black"),
    ("#FFFFFF", "Botswana White"),
    ("#003580", "Namibia Blue"),
    ("#D21034", "Namibia Red"),
    ("#009543", "Namibia Green"),
    ("#FFCE00", "Namibia Yellow"),
    ("#FFFFFF", "Namibia White"),
    ("#00A859", "Zimbabwe Green"),
    ("#FFD200", "Zimbabwe Yellow"),
    ("#CE1126", "Zimbabwe Red"),
    ("#000000", "Zimbabwe Black"),
    ("#FFFFFF", "Zimbabwe White"),
    ("#198A00", "Zambia Green"),
    ("#FF7F00", "Zambia Orange"),
    ("#000000", "Zambia Black"),
    ("#CE1126", "Zambia Red"),
    // --- Central & South Asia
    ("#00AFCA", "Kazakhstan Sky Blue"),
    ("#FEC50C", "Kazakhstan Gold"),
    ("#1EB0E9", "Uzbekistan Blue"),
    ("#FFFFFF", "Uzbekistan White"),
    ("#1E9F45", "Uzbekistan Green"),
    ("#CE1126", "Uzbekistan Red"),
    ("#006847", "Turkmenistan Green"),
    ("#FFFFFF", "Turkmenistan White"),
    ("#CE1126", "Turkmenistan Red"),
    ("#E8112D", "Kyrgyzstan Red"),
    ("#FCDD09", "Kyrgyzstan Yellow"),
    ("#CE1126", "Tajikistan Red"),
    ("#FFFFFF", "Tajikistan White"),
    ("#00843D", "Tajikistan Green"),
    ("#F8C300", "Tajikistan Yellow"),
    ("#C4272F", "Mongolia Red"),
    ("#015197", "Mongolia Blue"),
    ("#FFD900", "Mongolia Yellow"),
    // --- South & South-East Asia
    ("#DC143C", "Nepal Crimson"),
    ("#003893", "Nepal Blue"),
    ("#FFFFFF", "Nepal White"),
    ("#FECB00", "Myanmar Yellow"),
    ("#34B233", "Myanmar Green"),
    ("#EA1F26", "Myanmar Red"),
    ("#CE1126", "Laos Red"),
    ("#002868", "Laos Blue"),
    ("#FFFFFF", "Laos White"),
    ("#ED1C24", "Cambodia Red"),
    ("#032EA1", "Cambodia Blue"),
    ("#FFFFFF", "Cambodia White"),
    ("#0038A8", "Philippines Blue"),
    ("#CE1126", "Philippines Red"),
    ("#FFFFFF", "Philippines White"),
    ("#FCD116", "Philippines Yellow"),
    ("#010066", "Malaysia Blue"),
    ("#CC0000", "Malaysia Red"),
    ("#FFCC00", "Malaysia Yellow"),
    ("#FFFFFF", "Malaysia White"),
    ("#EF3340", "Singapore Red"),
    ("#FFFFFF", "Singapore White"),
    // --- The Americas (additions)
    ("#D52B1E", "Bolivia Red"),
    ("#FFCC00", "Bolivia Yellow"),
    ("#007934", "Bolivia Green"),
    ("#FFD100", "Ecuador Yellow"),
    ("#0033A0", "Ecuador Blue"),
    ("#EF3340", "Ecuador Red"),
    ("#FFCC00", "Venezuela Yellow"),
    ("#0033A0", "Venezuela Blue"),
    ("#EF3340", "Venezuela Red"),
    ("#56A5D8", "Uruguay Sky Blue"),
    ("#FFFFFF", "Uruguay White"),
    ("#FCD116", "Uruguay Yellow"),
    ("#EF3340", "Paraguay Red"),
    ("#FFFFFF", "Paraguay White"),
    ("#0033A0", "Paraguay Blue"),
    ("#4997D0", "Guatemala Sky Blue"),
    ("#FFFFFF", "Guatemala White"),
    ("#0073CF", "Honduras Blue"),
    ("#FFFFFF", "Honduras White"),
    ("#0047AB", "El Salvador Blue"),
    ("#FFFFFF", "El Salvador White"),
    ("#0067C6", "Nicaragua Blue"),
    ("#FFFFFF", "Nicaragua White"),
    ("#CE1126", "Costa Rica Red"),
    ("#002B7F", "Costa Rica Blue"),
    ("#FFFFFF", "Costa Rica White"),
    ("#EF3340", "Panama Red"),
    ("#005293", "Panama Blue"),
    ("#FFFFFF", "Panama White"),
    ("#002A8F", "Cuba Blue"),
    ("#CF142B", "Cuba Red"),
    ("#FFFFFF", "Cuba White"),
    ("#002D62", "Dominican Republic Blue"),
    ("#CE1126", "Dominican Republic Red"),
    ("#FFFFFF", "Dominican Republic White"),
    ("#00209F", "Haiti Blue"),
    ("#D21034", "Haiti Red"),
    // --- Europe (Additions) ("#FF0000", "Albania Red"), ("#000000", "Albania Black"),
    ("#F31500", "Andorra Red"),
    ("#0018A8", "Andorra Blue"),
    ("#FEE700", "Andorra Yellow"),
    ("#ED2939", "Bulgaria Red"),
    ("#FFFFFF", "Bulgaria White"),
    ("#00966E", "Bulgaria Green"),
    ("#DA291C", "Austria Red"),
    ("#FFFFFF", "Austria White"),
    ("#AE1C28", "Belgium Red"),
    ("#FAE042", "Belgium Yellow"),
    ("#000000", "Belgium Black"),
    ("#C6363C", "Croatia Red"),
    ("#171796", "Croatia Blue"),
    ("#FFFFFF", "Croatia White"),
    ("#0093DD", "Croatia Cyan"), // For coat of arms ("#F7D417", "Croatia Gold"),  // For coat of arms
    ("#0033A0", "Cyprus Blue"),
    ("#FFFFFF", "Cyprus White"),
    ("#D57800", "Cyprus Copper"), // Representative color
    ("#C60B1E", "Denmark Red"),
    ("#FFFFFF", "Denmark White"),
    ("#4891D9", "Finland Blue"),
    ("#FFFFFF", "Finland White"),
    ("#002395", "France Blue"),
    ("#FFFFFF", "France White"),
    ("#ED2939", "France Red"),
    ("#FFCE00", "Germany Gold"),
    ("#000000", "Germany Black"),
    ("#DD0000", "Germany Red"),
    ("#0D5EAF", "Greece Blue"),
    ("#FFFFFF", "Greece White"),
    ("#C8102E", "Hungary Red"),
    ("#FFFFFF", "Hungary White"),
    ("#00843D", "Hungary Green"),
    ("#009A49", "Ireland Green"),
    ("#FFFFFF", "Ireland White"),
    ("#FF7900", "Ireland Orange"),
    ("#009246", "Italy Green"),
    ("#FFFFFF", "Italy White"),
    ("#CE2B37", "Italy Red"),
    ("#9E3039", "Liechtenstein Red"),
    ("#002B7F", "Liechtenstein Blue"),
    ("#FFD83C", "Liechtenstein Gold"),
    ("#C8102E", "Moldova Red"),
    ("#FFCD00", "Moldova Yellow"),
    ("#003DA5", "Moldova Blue"),
    ("#AE1C28", "Netherlands Red"),
    ("#21468B", "Netherlands Blue"),
    ("#FFFFFF", "Netherlands White"),
    ("#D4213D", "Poland Red"),
    ("#FFFFFF", "Poland White"),
    ("#006600", "Portugal Green"),
    ("#FF0000", "Portugal Red"),
    ("#FFFF00", "Portugal Yellow"), // For coat of arms ("#002D72", "Portugal Blue"),   // For coat of arms
    ("#CC0000", "San Marino Red"),
    ("#FFFFFF", "San Marino White"),
    ("#5CACEE", "San Marino Azure"), // For coat of arms ("#CFB53B", "San Marino Gold"),  // For coat of arms
    ("#C6363C", "Spain Red"),
    ("#FFC400", "Spain Yellow"),
    ("#FFCD00", "Ukraine Yellow"),
    ("#0057B7", "Ukraine Blue"),
    ("#E4002B", "United Kingdom Red"),
    ("#012169", "United Kingdom Blue"),
    ("#FFFFFF", "United Kingdom White"),
    // --- Middle East & North Africa (Additions) ("#006233", "Algeria Green"), ("#FFFFFF", "Algeria White"), ("#D21034", "Algeria Red"),
    ("#C1272D", "Egypt Red"),
    ("#000000", "Egypt Black"),
    ("#FFFFFF", "Egypt White"),
    ("#DA0000", "Iran Red"),
    ("#FFFFFF", "Iran White"),
    ("#239F40", "Iran Green"),
    ("#CE1126", "Kuwait Red"),
    ("#FFFFFF", "Kuwait White"),
    ("#007A3D", "Kuwait Green"),
    ("#000000", "Kuwait Black"),
    ("#C2111A", "Morocco Red"),
    ("#007A3D", "Oman Green"),
    ("#FFFFFF", "Oman White"),
    ("#D21034", "Oman Red"),
    ("#00692B", "Pakistan Green"),
    ("#FFFFFF", "Pakistan White"),
    ("#CE1126", "Palestine Red"),
    ("#000000", "Palestine Black"),
    ("#FFFFFF", "Palestine White"),
    ("#007A3D", "Palestine Green"),
    ("#9D2235", "Saudi Arabia Red"), // Often used with the Shahada ("#006C35", "Saudi Arabia Green"),
    ("#8B0723", "Turkey Red"),
    ("#E30A17", "Turkey Crimson"), // A common variant ("#FFFFFF", "Turkey White"),
    ("#FF0000", "Yemen Red"),
    ("#FFFFFF", "Yemen White"),
    ("#000000", "Yemen Black"),
    // --- Sub-Saharan Africa (Additions) ("#009E49", "Benin Green"), ("#FCD116", "Benin Yellow"), ("#E8112D", "Benin Red"),
    ("#FFFFFF", "Burkina Faso White"),
    ("#009E49", "Burkina Faso Green"),
    ("#EF2B2D", "Burkina Faso Red"),
    ("#007A5E", "Cameroon Green"),
    ("#FCD116", "Cameroon Yellow"),
    ("#CE1126", "Cameroon Red"),
    ("#3C3B6E", "Cameroon Star"), // Color of the star
    ("#002B7F", "DR Congo Blue"),
    ("#FCD116", "DR Congo Yellow"),
    ("#CE1126", "DR Congo Red"),
    ("#009E60", "Ethiopia Green"),
    ("#DA121A", "Ethiopia Red"),
    ("#FCDD09", "Ethiopia Yellow"),
    ("#078930", "Ethiopia Light Green"), // Newer flag addition ("#0F47AF", "Ethiopia Blue"),        // Newer flag addition
    ("#FFCE00", "Ghana Yellow"),
    ("#006B3F", "Ghana Green"),
    ("#CE1126", "Ghana Red"),
    ("#000000", "Ghana Black"),
    ("#009F4D", "Guinea Green"),
    ("#FCD116", "Guinea Yellow"),
    ("#CE1126", "Guinea Red"),
    ("#009E49", "Kenya Green"),
    ("#FFFFFF", "Kenya White"),
    ("#000000", "Kenya Black"),
    ("#B00D23", "Kenya Red"), // Shield color ("#E8B725", "Kenya Gold"), // Shield color
    ("#CE1126", "Mali Red"),
    ("#FCD116", "Mali Yellow"),
    ("#14B53A", "Mali Green"),
    ("#E31B23", "Mozambique Red"),
    ("#000000", "Mozambique Black"),
    ("#009E49", "Mozambique Green"),
    ("#FFFF00", "Mozambique Yellow"),
    ("#FFFFFF", "Mozambique White"),
    ("#00A859", "Nigeria Green"),
    ("#FFFFFF", "Nigeria White"),
    ("#FFB81C", "South Africa Gold"),
    ("#000000", "South Africa Black"),
    ("#E03C31", "South Africa Chili Red"),
    ("#007749", "South Africa Green"),
    ("#001489", "South Africa Blue"),
    ("#FFFFFF", "South Africa White"),
    ("#CE1126", "Senegal Red"),
    ("#FCD116", "Senegal Yellow"),
    ("#00853F", "Senegal Green"),
    // --- Central & South Asia (Additions) ("#006A4D", "Bangladesh Green"), ("#F42A41", "Bangladesh Red"),
    ("#FF9933", "India Saffron"),
    ("#FFFFFF", "India White"),
    ("#138808", "India Green"),
    ("#000080", "India Navy Blue"), // For Ashoka Chakra
    ("#006847", "Maldives Green"),
    ("#D21034", "Maldives Red"),
    ("#FFFFFF", "Maldives White"),
    ("#9CA69C", "Afghanistan Black"), // Representative ("#DE2029", "Afghanistan Red"),   // Representative ("#FFFFFF", "Afghanistan White"), // Representative ("#007A36", "Afghanistan Green"), // Representative ("##000000", "Afghanistan Shahada"), // Note: Flag has changed; these are representative.
    // --- East Asia & Oceania ("#DE2910", "China Red"), ("#FFDE00", "China Yellow"),
    ("#BC002D", "Japan Red"),
    ("#FFFFFF", "Japan White"),
    ("#C60C30", "South Korea Red"),
    ("#003478", "South Korea Blue"),
    ("#FFFFFF", "South Korea White"),
    ("#000000", "South Korea Black"),
    ("#00247D", "Australia Blue"),
    ("#FFFFFF", "Australia White"),
    ("#E4002B", "Australia Red"),
    ("#FFCD00", "Australia Gold"), // Commonwealth Star
    ("#00247D", "New Zealand Blue"),
    ("#FFFFFF", "New Zealand White"),
    ("#CC0000", "New Zealand Red"),
    ("#FF0000", "Fiji Red"),
    ("#00247D", "Fiji Blue"),
    ("#FFFFFF", "Fiji White"),
    ("#012169", "Papua New Guinea Blue"),
    ("#000000", "Papua New Guinea Black"),
    ("#C8102E", "Papua New Guinea Red"),
    ("#FFC72C", "Papua New Guinea Gold"),
    ("#D21034", "Samoa Red"),
    ("#00247D", "Samoa Blue"),
    ("#FFFFFF", "Samoa White"),
    ("#C1272D", "Tonga Red"),
    ("#FFFFFF", "Tonga White"),
    ("#00247D", "Vanuatu Blue"),
    ("#FFC72C", "Vanuatu Yellow"),
    ("#BD1019", "Vanuatu Red"),
    ("#000000", "Vanuatu Black"),
    ("#009543", "Vanuatu Green"),
    // --- The Americas (Additions) ("#75AADB", "Argentina Light Blue"), ("#FFFFFF", "Argentina White"), ("#F6B40E", "Argentina Sun Yellow"), // For Sun of May ("#85340A", "Argentina Sun Brown"),  // For Sun of May
    ("#009C3B", "Brazil Green"),
    ("#FFDF00", "Brazil Yellow"),
    ("#002776", "Brazil Blue"),
    ("#FFFFFF", "Brazil White"),
    ("#FF0000", "Chile Red"),
    ("#FFFFFF", "Chile White"),
    ("#0039A6", "Chile Blue"),
    ("#FFCE00", "Colombia Yellow"),
    ("#003893", "Colombia Blue"),
    ("#CE1126", "Colombia Red"),
    ("#E30A17", "Canada Red"),
    ("#FFFFFF", "Canada White"),
    ("#002B7F", "Jamaica Gold"), // Color name is "Gold", but hex is often dark blue for contrast ("#000000", "Jamaica Black"), ("#009B3A", "Jamaica Green"), ("#FED100", "Jamaica Yellow"),
    ("#D52B1E", "Mexico Red"),
    ("#006847", "Mexico Green"),
    ("#FFFFFF", "Mexico White"),
    ("#CE1126", "Mexico Red (Coat)"), // Slightly different red in coat of arms ("#9D5B29", "Mexico Brown"),      // For the eagle in coat of arms
    ("#002A8F", "Peru Red"),
    ("#FFFFFF", "Peru White"),
    ("#012169", "Trinidad and Tobago Red"),
    ("#000000", "Trinidad and Tobago Black"),
    ("#FFFFFF", "Trinidad and Tobago White"),
    // --- Caribbean Additions ("#CE1126", "Barbados Red"), ("#00267F", "Barbados Blue"), ("#FFC726", "Barbados Gold"),
    ("#FFB81C", "Bahamas Gold"),
    ("#00ABC9", "Bahamas Aquamarine"),
    ("#000000", "Bahamas Black"),
    ("#CE1126", "Grenada Red"),
    ("#007A5E", "Grenada Green"),
    ("#FCD116", "Grenada Yellow"),
    ("#C8102E", "Saint Lucia Cerise"),
    ("#6CC5EB", "Saint Lucia Azure"),
    ("#FCD680", "Saint Lucia Gold"),
    ("#000000", "Saint Lucia Black"),
    ("#FFFFFF", "Saint Lucia White"),
    ("#FCD116", "Saint Vincent and the Grenadines Yellow"),
    ("#009E60", "Saint Vincent and the Grenadines Green"),
    ("#0072CE", "Saint Vincent and the Grenadines Blue"),
    // Add a small supplement for commonly missing countries.
    // (Feel free to extend this list later.)
    // South Asia / Indian Ocean
    ("#FF9933", "Sri Lanka Saffron"),
    ("#006A4E", "Sri Lanka Green"),
    ("#003893", "Sri Lanka Blue"),
    ("#FCD116", "Sri Lanka Yellow"),
    ("#8D153A", "Bhutan Maroon"),
    ("#FFCC00", "Bhutan Yellow"),
    ("#CE1126", "Brunei Red"),
    ("#F7E017", "Brunei Yellow"),
    ("#000000", "Brunei Black"),
    ("#FFFFFF", "Brunei White"),
    ("#0000FF", "Timor-Leste Blue"), // coat usage; flag: red/yellow/black
    ("#DA291C", "Timor-Leste Red"),
    ("#000000", "Timor-Leste Black"),
    ("#F8C300", "Timor-Leste Yellow"),
    // East Asia
    ("#024FA2", "North Korea Blue"),
    ("#ED1C27", "North Korea Red"),
    ("#FFFFFF", "North Korea White"),
    // Europe
    ("#0057A4", "Belarus Blue"),
    ("#D22730", "Belarus Red"),
    ("#009E49", "Belarus Green"),
    ("#FFFFFF", "Belarus White"),
    // Central / North Africa
    ("#10AF2A", "Eritrea Green"),
    ("#EF2B2D", "Eritrea Red"),
    ("#00A3E0", "Eritrea Blue"),
    ("#FCD116", "Eritrea Yellow"),
    ("#6AB2E7", "Somalia Blue"),
    ("#FFFFFF", "Somalia White"),
    ("#00A3DD", "Djibouti Blue"),
    ("#9ECE3F", "Djibouti Green"),
    ("#EF3340", "Djibouti Red"),
    ("#FFFFFF", "Djibouti White"),
    ("#00A95C", "Burundi Green"),
    ("#EF3340", "Burundi Red"),
    ("#FFFFFF", "Burundi White"),
    ("#00A859", "Gabon Green"),
    ("#FCD116", "Gabon Yellow"),
    ("#009E60", "Gabon Blue"),
    ("#009543", "Equatorial Guinea Green"),
    ("#0073CF", "Equatorial Guinea Blue"),
    ("#CE1126", "Equatorial Guinea Red"),
    ("#FFFFFF", "Equatorial Guinea White"),
    ("#003082", "Chad Blue"),
    ("#FCD116", "Chad Yellow"),
    ("#CE1126", "Chad Red"),
    ("#EEC900", "Niger Orange"),
    ("#FFFFFF", "Niger White"),
    ("#0DB02B", "Niger Green"),
    ("#000000", "Angola Black"),
    ("#CC092F", "Angola Red"),
    ("#F7D417", "Angola Yellow"),
    // West Africa
    ("#008751", "Benin Green"),
    ("#FCD116", "Benin Yellow"),
    ("#E8112D", "Benin Red"),
    ("#009E60", "Côte d'Ivoire Green"),
    ("#FFFFFF", "Côte d'Ivoire White"),
    ("#FF8200", "Côte d'Ivoire Orange"),
    ("#CE1126", "Guinea-Bissau Red"),
    ("#FCD116", "Guinea-Bissau Yellow"),
    ("#009E49", "Guinea-Bissau Green"),
    ("#007749", "Gambia Green"),
    ("#CE1126", "Gambia Red"),
    ("#0C1C8C", "Gambia Blue"),
    ("#FCD116", "Gambia Yellow"),
    ("#009543", "Cape Verde Green"),
    ("#0033A0", "Cape Verde Blue"),
    ("#FCD116", "Cape Verde Yellow"),
    ("#CE1126", "Cape Verde Red"),
    ("#006233", "Mauritania Green"),
    ("#FFC61E", "Mauritania Gold"),
    // Central Africa
    ("#003082", "Central African Republic Blue"),
    ("#FFFFFF", "Central African Republic White"),
    ("#FCD116", "Central African Republic Yellow"),
    ("#289728", "Central African Republic Green"),
    ("#D21034", "Central African Republic Red"),
    ("#009543", "Republic of the Congo Green"),
    ("#FCD116", "Republic of the Congo Yellow"),
    ("#DC241F", "Republic of the Congo Red"),
    // Caribbean / Americas
    ("#00267F", "Barbados Blue"),
    ("#FFC726", "Barbados Gold"),
    ("#CE1126", "Barbados Red (Emblem)"),
    ("#007749", "Jamaica Green"),
    ("#000000", "Jamaica Black"),
    ("#FED100", "Jamaica Gold"),
    ("#007A5E", "Belize Green"),
    ("#003F87", "Belize Blue"),
    ("#CE1126", "Belize Red"),
    ("#009E49", "Guyana Green"),
    ("#FCD116", "Guyana Yellow"),
    ("#CE1126", "Guyana Red"),
    ("#3A75C4", "Suriname Blue"), // (flag is green/red/white/yellow; blue used in COA contexts)
    ("#377E3F", "Suriname Green"),
    ("#B40A2D", "Suriname Red"),
    ("#FFFFFF", "Suriname White"),
    ("#ECC81D", "Suriname Yellow"),
];
