use crate::color_types::{HexCode, ColorName};

/// XKCD color survey results with structured types.
/// Each entry is a tuple of (HexCode, ColorName) with sortable components.
pub const COLORS_XKCD: &[(HexCode, ColorName)] = &[
    (HexCode::new("#7E1E9C"), ColorName::new("purple")),
    (HexCode::new("#15B01A"), ColorName::new("green")),
    (HexCode::new("#0343DF"), ColorName::new("blue")),
    (HexCode::new("#FF81C0"), ColorName::new("pink")),
    (HexCode::new("#653700"), ColorName::new("brown")),
    (HexCode::new("#E50000"), ColorName::new("red")),
    (HexCode::new("#95D0FC"), ColorName::new("light blue")),
    (HexCode::new("#029386"), ColorName::new("teal")),
    (HexCode::new("#F97306"), ColorName::new("orange")),
    (HexCode::new("#96F97B"), ColorName::new("light green")),
    (HexCode::new("#C20078"), ColorName::new("magenta")),
    (HexCode::new("#FFFF14"), ColorName::new("yellow")),
    (HexCode::new("#75BBFD"), ColorName::new("sky blue")),
    (HexCode::new("#929591"), ColorName::new("grey")),
    (HexCode::new("#89FE05"), ColorName::new("lime green")),
    (HexCode::new("#BF77F6"), ColorName::new("light purple")),
    (HexCode::new("#9A0EEA"), ColorName::new("violet")),
    (HexCode::new("#033500"), ColorName::new("dark green")),
    (HexCode::new("#06C2AC"), ColorName::new("turquoise")),
    (HexCode::new("#C79FEF"), ColorName::new("lavender")),
    (HexCode::new("#00035B"), ColorName::new("dark blue")),
    (HexCode::new("#D1B26F"), ColorName::new("tan")),
    (HexCode::new("#00FFFF"), ColorName::new("cyan")),
    (HexCode::new("#13EAC9"), ColorName::new("aqua")),
    (HexCode::new("#06470C"), ColorName::new("forest green")),
    (HexCode::new("#AE7181"), ColorName::new("mauve")),
    (HexCode::new("#35063E"), ColorName::new("dark purple")),
    (HexCode::new("#01FF07"), ColorName::new("bright green")),
    (HexCode::new("#650021"), ColorName::new("maroon")),
    (HexCode::new("#6E750E"), ColorName::new("olive")),
    (HexCode::new("#FF796C"), ColorName::new("salmon")),
    (HexCode::new("#E6DAA6"), ColorName::new("beige")),
    (HexCode::new("#0504AA"), ColorName::new("royal blue")),
    (HexCode::new("#001146"), ColorName::new("navy blue")),
    (HexCode::new("#CEA2FD"), ColorName::new("lilac")),
    (HexCode::new("#000000"), ColorName::new("black")),
    (HexCode::new("#FF028D"), ColorName::new("hot pink")),
    (HexCode::new("#AD8150"), ColorName::new("light brown")),
    (HexCode::new("#C7FDB5"), ColorName::new("pale green")),
    (HexCode::new("#FFB07C"), ColorName::new("peach")),
    (HexCode::new("#677A04"), ColorName::new("olive green")),
    (HexCode::new("#CB416B"), ColorName::new("dark pink")),
    (HexCode::new("#8E82FE"), ColorName::new("periwinkle")),
    (HexCode::new("#53FCA1"), ColorName::new("sea green")),
    (HexCode::new("#AAFF32"), ColorName::new("lime")),
    (HexCode::new("#380282"), ColorName::new("indigo")),
    (HexCode::new("#CEB301"), ColorName::new("mustard")),
    (HexCode::new("#FFD1DF"), ColorName::new("light pink")),
    (HexCode::new("#CF6275"), ColorName::new("rose")),
    (HexCode::new("#0165FC"), ColorName::new("bright blue")),
    (HexCode::new("#0CFF0C"), ColorName::new("neon green")),
    (HexCode::new("#C04E01"), ColorName::new("burnt orange")),
    (HexCode::new("#04D8B2"), ColorName::new("aquamarine")),
    (HexCode::new("#01153E"), ColorName::new("navy")),
    (HexCode::new("#3F9B0B"), ColorName::new("grass green")),
    (HexCode::new("#D0FEFE"), ColorName::new("pale blue")),
    (HexCode::new("#840000"), ColorName::new("dark red")),
    (HexCode::new("#BE03FD"), ColorName::new("bright purple")),
    (HexCode::new("#C0FB2D"), ColorName::new("yellow green")),
    (HexCode::new("#A2CFFE"), ColorName::new("baby blue")),
    (HexCode::new("#DBB40C"), ColorName::new("gold")),
    (HexCode::new("#8FFF9F"), ColorName::new("mint green")),
    (HexCode::new("#580F41"), ColorName::new("plum")),
    (HexCode::new("#4B006E"), ColorName::new("royal purple")),
    (HexCode::new("#8F1402"), ColorName::new("brick red")),
    (HexCode::new("#014D4E"), ColorName::new("dark teal")),
    (HexCode::new("#610023"), ColorName::new("burgundy")),
    (HexCode::new("#AAA662"), ColorName::new("khaki")),
    (HexCode::new("#137E6D"), ColorName::new("blue green")),
    (HexCode::new("#7AF9AB"), ColorName::new("seafoam green")),
    (HexCode::new("#02AB2E"), ColorName::new("kelly green")),
    (HexCode::new("#9AAE07"), ColorName::new("puke green")),
    (HexCode::new("#8EAB12"), ColorName::new("pea green")),
    (HexCode::new("#B9A281"), ColorName::new("taupe")),
    (HexCode::new("#341C02"), ColorName::new("dark brown")),
    (HexCode::new("#36013F"), ColorName::new("deep purple")),
    (HexCode::new("#C1F80A"), ColorName::new("chartreuse")),
    (HexCode::new("#FE01B1"), ColorName::new("bright pink")),
    (HexCode::new("#FDAA48"), ColorName::new("light orange")),
    (HexCode::new("#9FFEB0"), ColorName::new("mint")),
    (HexCode::new("#B0FF9D"), ColorName::new("pastel green")),
    (HexCode::new("#E2CA76"), ColorName::new("sand")),
    (HexCode::new("#C65102"), ColorName::new("dark orange")),
    (HexCode::new("#A9F971"), ColorName::new("spring green")),
    (HexCode::new("#A57E52"), ColorName::new("puce")),
    (HexCode::new("#80F9AD"), ColorName::new("seafoam")),
    (HexCode::new("#6B8BA4"), ColorName::new("grey blue")),
    (HexCode::new("#4B5D16"), ColorName::new("army green")),
    (HexCode::new("#363737"), ColorName::new("dark grey")),
    (HexCode::new("#D5B60A"), ColorName::new("dark yellow")),
    (HexCode::new("#FAC205"), ColorName::new("goldenrod")),
    (HexCode::new("#516572"), ColorName::new("slate")),
    (HexCode::new("#90E4C1"), ColorName::new("light teal")),
    (HexCode::new("#A83C09"), ColorName::new("rust")),
    (HexCode::new("#040273"), ColorName::new("deep blue")),
    (HexCode::new("#FFCFDC"), ColorName::new("pale pink")),
    (HexCode::new("#0485D1"), ColorName::new("cerulean")),
    (HexCode::new("#FF474C"), ColorName::new("light red")),
    (HexCode::new("#D2BD0A"), ColorName::new("mustard yellow")),
    (HexCode::new("#BF9005"), ColorName::new("ochre")),
    (HexCode::new("#FFFF84"), ColorName::new("pale yellow")),
    (HexCode::new("#8C000F"), ColorName::new("crimson")),
    (HexCode::new("#ED0DD9"), ColorName::new("fuchsia")),
    (HexCode::new("#0B4008"), ColorName::new("hunter green")),
    (HexCode::new("#607C8E"), ColorName::new("blue grey")),
    (HexCode::new("#5B7C99"), ColorName::new("slate blue")),
    (HexCode::new("#B790D4"), ColorName::new("pale purple")),
    (HexCode::new("#047495"), ColorName::new("sea blue")),
    (HexCode::new("#D648D7"), ColorName::new("pinkish purple")),
    (HexCode::new("#A5A502"), ColorName::new("puke")),
    (HexCode::new("#D8DCD6"), ColorName::new("light grey")),
    (HexCode::new("#5CA904"), ColorName::new("leaf green")),
    (HexCode::new("#FFFE7A"), ColorName::new("light yellow")),
    (HexCode::new("#380835"), ColorName::new("eggplant")),
    (HexCode::new("#5A7D9A"), ColorName::new("steel blue")),
    (HexCode::new("#658B38"), ColorName::new("moss green")),
    (HexCode::new("#98EFF9"), ColorName::new("robin's egg blue")),
    (HexCode::new("#FFFFFF"), ColorName::new("white")),
    (HexCode::new("#789B73"), ColorName::new("grey green")),
    (HexCode::new("#87AE73"), ColorName::new("sage")),
    (HexCode::new("#A03623"), ColorName::new("brick")),
    (HexCode::new("#B04E0F"), ColorName::new("burnt sienna")),
    (HexCode::new("#7F2B0A"), ColorName::new("reddish brown")),
    (HexCode::new("#FFFFC2"), ColorName::new("cream")),
    (HexCode::new("#FC5A50"), ColorName::new("coral")),
    (HexCode::new("#03719C"), ColorName::new("ocean blue")),
    (HexCode::new("#40A368"), ColorName::new("greenish")),
    (HexCode::new("#960056"), ColorName::new("dark magenta")),
    (HexCode::new("#FD3C06"), ColorName::new("red orange")),
    (HexCode::new("#703BE7"), ColorName::new("bluish purple")),
    (HexCode::new("#020035"), ColorName::new("midnight blue")),
    (HexCode::new("#D6B4FC"), ColorName::new("light violet")),
    (HexCode::new("#C0737A"), ColorName::new("dusty rose")),
    (HexCode::new("#2C6FBB"), ColorName::new("medium blue")),
    (HexCode::new("#CDFD02"), ColorName::new("greenish yellow")),
    (HexCode::new("#B0DD16"), ColorName::new("yellowish green")),
    (HexCode::new("#601EF9"), ColorName::new("purplish blue")),
    (HexCode::new("#5E819D"), ColorName::new("greyish blue")),
    (HexCode::new("#6C3461"), ColorName::new("grape")),
    (HexCode::new("#ACBF69"), ColorName::new("light olive")),
    (HexCode::new("#5170D7"), ColorName::new("cornflower blue")),
    (HexCode::new("#F10C45"), ColorName::new("pinkish red")),
    (HexCode::new("#FF000D"), ColorName::new("bright red")),
    (HexCode::new("#069AF3"), ColorName::new("azure")),
    (HexCode::new("#5729CE"), ColorName::new("blue purple")),
    (HexCode::new("#045C5A"), ColorName::new("dark turquoise")),
    (HexCode::new("#0652FF"), ColorName::new("electric blue")),
    (HexCode::new("#FFFFE4"), ColorName::new("off white")),
    (HexCode::new("#B1D1FC"), ColorName::new("powder blue")),
    (HexCode::new("#80013F"), ColorName::new("wine")),
    (HexCode::new("#74A662"), ColorName::new("dull green")),
    (HexCode::new("#76CD26"), ColorName::new("apple green")),
    (HexCode::new("#7EF4CC"), ColorName::new("light turquoise")),
    (HexCode::new("#BC13FE"), ColorName::new("neon purple")),
    (HexCode::new("#1E488F"), ColorName::new("cobalt")),
    (HexCode::new("#D46A7E"), ColorName::new("pinkish")),
    (HexCode::new("#6F7632"), ColorName::new("olive drab")),
    (HexCode::new("#0A888A"), ColorName::new("dark cyan")),
    (HexCode::new("#632DE9"), ColorName::new("purple blue")),
    (HexCode::new("#34013F"), ColorName::new("dark violet")),
    (HexCode::new("#856798"), ColorName::new("dark lavender")),
    (HexCode::new("#154406"), ColorName::new("forrest green")),
    (HexCode::new("#A2A415"), ColorName::new("vomit")),
    (HexCode::new("#FFA756"), ColorName::new("pale orange")),
    (HexCode::new("#0B8B87"), ColorName::new("greenish blue")),
    (HexCode::new("#AF884A"), ColorName::new("dark tan")),
    (HexCode::new("#06B48B"), ColorName::new("green blue")),
    (HexCode::new("#10A674"), ColorName::new("bluish green")),
    (HexCode::new("#A2BFFE"), ColorName::new("pastel blue")),
    (HexCode::new("#769958"), ColorName::new("moss")),
    (HexCode::new("#5CAC2D"), ColorName::new("grass")),
    (HexCode::new("#CB0162"), ColorName::new("deep pink")),
    (HexCode::new("#980002"), ColorName::new("blood red")),
    (HexCode::new("#88B378"), ColorName::new("sage green")),
    (HexCode::new("#02D8E9"), ColorName::new("aqua blue")),
    (HexCode::new("#CA6641"), ColorName::new("terracotta")),
    (HexCode::new("#CAA0FF"), ColorName::new("pastel purple")),
    (HexCode::new("#A9561E"), ColorName::new("sienna")),
    (HexCode::new("#373E02"), ColorName::new("dark olive")),
    (HexCode::new("#C9FF27"), ColorName::new("green yellow")),
    (HexCode::new("#BE0119"), ColorName::new("scarlet")),
    (HexCode::new("#82A67D"), ColorName::new("greyish green")),
    (HexCode::new("#3D1C02"), ColorName::new("chocolate")),
    (HexCode::new("#5D06E9"), ColorName::new("blue violet")),
    (HexCode::new("#6A79F7"), ColorName::new("cornflower")),
    (HexCode::new("#FFB7CE"), ColorName::new("baby pink")),
    (HexCode::new("#343837"), ColorName::new("charcoal")),
    (HexCode::new("#0A481E"), ColorName::new("pine green")),
    (HexCode::new("#E17701"), ColorName::new("pumpkin")),
    (HexCode::new("#696112"), ColorName::new("greenish brown")),
    (HexCode::new("#8B2E16"), ColorName::new("red brown")),
    (HexCode::new("#6A6E09"), ColorName::new("brownish green")),
    (HexCode::new("#FF9408"), ColorName::new("tangerine")),
    (HexCode::new("#FE7B7C"), ColorName::new("salmon pink")),
    (HexCode::new("#12E193"), ColorName::new("aqua green")),
    (HexCode::new("#B00149"), ColorName::new("raspberry")),
    (HexCode::new("#887191"), ColorName::new("greyish purple")),
    (HexCode::new("#F7879A"), ColorName::new("rose pink")),
    (HexCode::new("#FE019A"), ColorName::new("neon pink")),
    (HexCode::new("#030AA7"), ColorName::new("cobalt blue")),
    (HexCode::new("#BE6400"), ColorName::new("orange brown")),
    (HexCode::new("#9A0200"), ColorName::new("deep red")),
    (HexCode::new("#FD411E"), ColorName::new("orange red")),
    (HexCode::new("#CDC50A"), ColorName::new("dirty yellow")),
    (HexCode::new("#C875C4"), ColorName::new("orchid")),
    (HexCode::new("#FE2C54"), ColorName::new("reddish pink")),
    (HexCode::new("#910951"), ColorName::new("reddish purple")),
    (HexCode::new("#FCB001"), ColorName::new("yellow orange")),
    (HexCode::new("#ACFFFC"), ColorName::new("light cyan")),
    (HexCode::new("#82CAFC"), ColorName::new("sky")),
    (HexCode::new("#FA5FF7"), ColorName::new("light magenta")),
    (HexCode::new("#D9544D"), ColorName::new("pale red")),
    (HexCode::new("#01A049"), ColorName::new("emerald")),
    (HexCode::new("#AC9362"), ColorName::new("dark beige")),
    (HexCode::new("#7A9703"), ColorName::new("ugly green")),
    (HexCode::new("#1FA774"), ColorName::new("jade")),
    (HexCode::new("#96AE8D"), ColorName::new("greenish grey")),
    (HexCode::new("#C85A53"), ColorName::new("dark salmon")),
    (HexCode::new("#CE5DAE"), ColorName::new("purplish pink")),
    (HexCode::new("#05696B"), ColorName::new("dark aqua")),
    (HexCode::new("#CB7723"), ColorName::new("brownish orange")),
    (HexCode::new("#A4BE5C"), ColorName::new("light olive green")),
    (HexCode::new("#8CFFDB"), ColorName::new("light aqua")),
    (HexCode::new("#B66A50"), ColorName::new("clay")),
    (HexCode::new("#39AD48"), ColorName::new("medium green")),
    (HexCode::new("#A0450E"), ColorName::new("burnt umber")),
    (HexCode::new("#49759C"), ColorName::new("dull blue")),
    (HexCode::new("#B1916E"), ColorName::new("pale brown")),
    (HexCode::new("#028F1E"), ColorName::new("emerald green")),
    (HexCode::new("#9C6D57"), ColorName::new("brownish")),
    (HexCode::new("#735C12"), ColorName::new("mud")),
    (HexCode::new("#B5485D"), ColorName::new("dark rose")),
    (HexCode::new("#9E3623"), ColorName::new("brownish red")),
    (HexCode::new("#DB4BDA"), ColorName::new("pink purple")),
    (HexCode::new("#C94CBE"), ColorName::new("pinky purple")),
    (HexCode::new("#526525"), ColorName::new("camo green")),
    (HexCode::new("#7BB274"), ColorName::new("faded green")),
    (HexCode::new("#D58A94"), ColorName::new("dusty pink")),
    (HexCode::new("#E03FD8"), ColorName::new("purple pink")),
    (HexCode::new("#89A203"), ColorName::new("vomit green")),
    (HexCode::new("#02590F"), ColorName::new("deep green")),
    (HexCode::new("#F8481C"), ColorName::new("reddish orange")),
    (HexCode::new("#4A0100"), ColorName::new("mahogany")),
    (HexCode::new("#3D0734"), ColorName::new("aubergine")),
    (HexCode::new("#D5869D"), ColorName::new("dull pink")),
    (HexCode::new("#05472A"), ColorName::new("evergreen")),
    (HexCode::new("#448EE4"), ColorName::new("dark sky blue")),
    (HexCode::new("#D1FFBD"), ColorName::new("very light green")),
    (HexCode::new("#FFBACD"), ColorName::new("pastel pink")),
    (HexCode::new("#826D8C"), ColorName::new("grey purple")),
    (HexCode::new("#D5FFFF"), ColorName::new("very light blue")),
    (HexCode::new("#874C62"), ColorName::new("dark mauve")),
    (HexCode::new("#4E7496"), ColorName::new("cadet blue")),
    (HexCode::new("#D7FFFE"), ColorName::new("ice blue")),
    (HexCode::new("#FBEEAC"), ColorName::new("light tan")),
    (HexCode::new("#667E2C"), ColorName::new("dirty green")),
    (HexCode::new("#04D9FF"), ColorName::new("neon blue")),
    (HexCode::new("#7B0323"), ColorName::new("wine red")),
    (HexCode::new("#411900"), ColorName::new("chocolate brown")),
    (HexCode::new("#84597E"), ColorName::new("dull purple")),
    (HexCode::new("#B79400"), ColorName::new("yellow brown")),
    (HexCode::new("#3B638C"), ColorName::new("denim")),
    (HexCode::new("#FFFFD4"), ColorName::new("eggshell")),
    (HexCode::new("#048243"), ColorName::new("jungle green")),
    (HexCode::new("#DE7E5D"), ColorName::new("dark peach")),
    (HexCode::new("#7F5E00"), ColorName::new("poop")),
    (HexCode::new("#B26400"), ColorName::new("umber")),
    (HexCode::new("#DFC5FE"), ColorName::new("light lavender")),
    (HexCode::new("#FFFD01"), ColorName::new("bright yellow")),
    (HexCode::new("#FEC615"), ColorName::new("golden yellow")),
    (HexCode::new("#5A86AD"), ColorName::new("dusty blue")),
    (HexCode::new("#21FC0D"), ColorName::new("electric green")),
    (HexCode::new("#75FD63"), ColorName::new("lighter green")),
    (HexCode::new("#59656D"), ColorName::new("slate grey")),
    (HexCode::new("#25A36F"), ColorName::new("teal green")),
    (HexCode::new("#01386A"), ColorName::new("marine blue")),
    (HexCode::new("#90B134"), ColorName::new("avocado")),
    (HexCode::new("#C9643B"), ColorName::new("terra cotta")),
    (HexCode::new("#825F87"), ColorName::new("dusty purple")),
    (HexCode::new("#A24857"), ColorName::new("light maroon")),
    (HexCode::new("#C44240"), ColorName::new("reddish")),
    (HexCode::new("#9C6DA5"), ColorName::new("dark lilac")),
    (HexCode::new("#665FD1"), ColorName::new("dark periwinkle")),
    (HexCode::new("#748B97"), ColorName::new("bluish grey")),
    (HexCode::new("#C2BE0E"), ColorName::new("puke yellow")),
    (HexCode::new("#94568C"), ColorName::new("purplish")),
    (HexCode::new("#2000B1"), ColorName::new("ultramarine")),
    (HexCode::new("#A00498"), ColorName::new("barney purple")),
    (HexCode::new("#0B5509"), ColorName::new("forest")),
    (HexCode::new("#929901"), ColorName::new("pea soup")),
    (HexCode::new("#C9B003"), ColorName::new("brownish yellow")),
    (HexCode::new("#01F9C6"), ColorName::new("bright teal")),
    (HexCode::new("#017A79"), ColorName::new("bluegreen")),
    (HexCode::new("#544E03"), ColorName::new("green brown")),
    (HexCode::new("#5539CC"), ColorName::new("blurple")),
    (HexCode::new("#C6FCFF"), ColorName::new("light sky blue")),
    (HexCode::new("#8F99FB"), ColorName::new("periwinkle blue")),
    (HexCode::new("#CEAEFA"), ColorName::new("pale violet")),
    (HexCode::new("#087804"), ColorName::new("darker green")),
    (HexCode::new("#010FCC"), ColorName::new("true blue")),
    (HexCode::new("#77926F"), ColorName::new("green grey")),
    (HexCode::new("#7F7053"), ColorName::new("grey brown")),
    (HexCode::new("#3C4D03"), ColorName::new("dark olive green")),
    (HexCode::new("#FFB16D"), ColorName::new("apricot")),
    (HexCode::new("#916E99"), ColorName::new("faded purple")),
    (HexCode::new("#011288"), ColorName::new("darker blue")),
    (HexCode::new("#DE0C62"), ColorName::new("cerise")),
    (HexCode::new("#728639"), ColorName::new("khaki green")),
    (HexCode::new("#9F2305"), ColorName::new("burnt red")),
    (HexCode::new("#4F9153"), ColorName::new("light forest green")),
    (HexCode::new("#510AC9"), ColorName::new("violet blue")),
    (HexCode::new("#EECFFE"), ColorName::new("pale lavender")),
    (HexCode::new("#8FFE09"), ColorName::new("acid green")),
    (HexCode::new("#866F85"), ColorName::new("purple grey")),
    (HexCode::new("#FDFF52"), ColorName::new("lemon")),
    (HexCode::new("#FF5B00"), ColorName::new("bright orange")),
    (HexCode::new("#6FC276"), ColorName::new("soft green")),
    (HexCode::new("#F29E8E"), ColorName::new("blush")),
    (HexCode::new("#9B7A01"), ColorName::new("yellowish brown")),
    (HexCode::new("#08FF08"), ColorName::new("fluorescent green")),
    (HexCode::new("#AA23FF"), ColorName::new("electric purple")),
    (HexCode::new("#738595"), ColorName::new("steel")),
    (HexCode::new("#D8863B"), ColorName::new("dull orange")),
    (HexCode::new("#657432"), ColorName::new("muddy green")),
    (HexCode::new("#FCC006"), ColorName::new("marigold")),
    (HexCode::new("#017B92"), ColorName::new("ocean")),
    (HexCode::new("#C292A1"), ColorName::new("light mauve")),
    (HexCode::new("#7B002C"), ColorName::new("bordeaux")),
    (HexCode::new("#7EFBB3"), ColorName::new("light blue green")),
    (HexCode::new("#FAEE66"), ColorName::new("yellowish")),
    (HexCode::new("#9DC100"), ColorName::new("snot green")),
    (HexCode::new("#B9FF66"), ColorName::new("light lime green")),
    (HexCode::new("#749551"), ColorName::new("drab green")),
    (HexCode::new("#658CBB"), ColorName::new("faded blue")),
    (HexCode::new("#002D04"), ColorName::new("dark forest green")),
    (HexCode::new("#CB00F5"), ColorName::new("hot purple")),
    (HexCode::new("#3C0008"), ColorName::new("dark maroon")),
    (HexCode::new("#706C11"), ColorName::new("brown green")),
    (HexCode::new("#748500"), ColorName::new("swamp green")),
    (HexCode::new("#6D5ACF"), ColorName::new("light indigo")),
    (HexCode::new("#5F34E7"), ColorName::new("purpley blue")),
    (HexCode::new("#3D7AFD"), ColorName::new("lightish blue")),
    (HexCode::new("#01889F"), ColorName::new("teal blue")),
    (HexCode::new("#3B5B92"), ColorName::new("denim blue")),
    (HexCode::new("#7EBD01"), ColorName::new("dark lime green")),
    (HexCode::new("#EEDC5B"), ColorName::new("dull yellow")),
    (HexCode::new("#C0FA8B"), ColorName::new("pistachio")),
    (HexCode::new("#FDFF38"), ColorName::new("lemon yellow")),
    (HexCode::new("#9E0168"), ColorName::new("red violet")),
    (HexCode::new("#CC7A8B"), ColorName::new("dusky pink")),
    (HexCode::new("#8A6E45"), ColorName::new("dirt")),
    (HexCode::new("#062E03"), ColorName::new("very dark green")),
    (HexCode::new("#9E43A2"), ColorName::new("medium purple")),
    (HexCode::new("#7F5F00"), ColorName::new("shit")),
    (HexCode::new("#A88905"), ColorName::new("dark mustard")),
    (HexCode::new("#94A617"), ColorName::new("pea soup green")),
    (HexCode::new("#FE83CC"), ColorName::new("bubblegum pink")),
    (HexCode::new("#FE46A5"), ColorName::new("barbie pink")),
    (HexCode::new("#667C3E"), ColorName::new("military green")),
    (HexCode::new("#82CBB2"), ColorName::new("pale teal")),
    (HexCode::new("#A87900"), ColorName::new("bronze")),
    (HexCode::new("#FC2647"), ColorName::new("pinky red")),
    (HexCode::new("#BB3F3F"), ColorName::new("dull red")),
    (HexCode::new("#014182"), ColorName::new("darkish blue")),
    (HexCode::new("#2976BB"), ColorName::new("bluish")),
    (HexCode::new("#B59410"), ColorName::new("dark gold")),
    (HexCode::new("#BFF128"), ColorName::new("yellowy green")),
    (HexCode::new("#2B5D34"), ColorName::new("pine")),
    (HexCode::new("#005249"), ColorName::new("dark blue green")),
    (HexCode::new("#CA7B80"), ColorName::new("dirty pink")),
    (HexCode::new("#658D6D"), ColorName::new("slate green")),
    (HexCode::new("#004577"), ColorName::new("prussian blue")),
    (HexCode::new("#AD0AFD"), ColorName::new("bright violet")),
    (HexCode::new("#A55AF4"), ColorName::new("lighter purple")),
    (HexCode::new("#6F828A"), ColorName::new("steel grey")),
    (HexCode::new("#A13905"), ColorName::new("russet")),
    (HexCode::new("#F4320C"), ColorName::new("vermillion")),
    (HexCode::new("#7A6A4F"), ColorName::new("greyish brown")),
    (HexCode::new("#820747"), ColorName::new("red purple")),
    (HexCode::new("#FA2A55"), ColorName::new("red pink")),
    (HexCode::new("#0FFEF9"), ColorName::new("bright turquoise")),
    (HexCode::new("#B27A01"), ColorName::new("golden brown")),
    (HexCode::new("#056EEE"), ColorName::new("cerulean blue")),
    (HexCode::new("#6488EA"), ColorName::new("soft blue")),
    (HexCode::new("#8CFD7E"), ColorName::new("easter green")),
    (HexCode::new("#FEB308"), ColorName::new("amber")),
    (HexCode::new("#276AB3"), ColorName::new("mid blue")),
    (HexCode::new("#7B5804"), ColorName::new("shit brown")),
    (HexCode::new("#9BE5AA"), ColorName::new("hospital green")),
    (HexCode::new("#6140EF"), ColorName::new("purpleish blue")),
    (HexCode::new("#661AEE"), ColorName::new("purply blue")),
    (HexCode::new("#C5C9C7"), ColorName::new("silver")),
    (HexCode::new("#94B21C"), ColorName::new("sickly green")),
    (HexCode::new("#FF7855"), ColorName::new("melon")),
    (HexCode::new("#BA6873"), ColorName::new("dusky rose")),
    (HexCode::new("#B96902"), ColorName::new("brown orange")),
    (HexCode::new("#287C37"), ColorName::new("darkish green")),
    (HexCode::new("#9E003A"), ColorName::new("cranberry")),
    (HexCode::new("#98568D"), ColorName::new("purpleish")),
    (HexCode::new("#FEFFCA"), ColorName::new("ecru")),
    (HexCode::new("#5F1B6B"), ColorName::new("darker purple")),
    (HexCode::new("#9D7651"), ColorName::new("mocha")),
    (HexCode::new("#FF08E8"), ColorName::new("bright magenta")),
    (HexCode::new("#A6814C"), ColorName::new("coffee")),
    (HexCode::new("#985E2B"), ColorName::new("sepia")),
    (HexCode::new("#D3494E"), ColorName::new("faded red")),
    (HexCode::new("#FFFE40"), ColorName::new("canary yellow")),
    (HexCode::new("#6241C7"), ColorName::new("bluey purple")),
    (HexCode::new("#FFFE71"), ColorName::new("pastel yellow")),
    (HexCode::new("#A5FBD5"), ColorName::new("pale turquoise")),
    (HexCode::new("#C88D94"), ColorName::new("greyish pink")),
    (HexCode::new("#042E60"), ColorName::new("marine")),
    (HexCode::new("#7A687F"), ColorName::new("purplish grey")),
    (HexCode::new("#C69F59"), ColorName::new("camel")),
    (HexCode::new("#86775F"), ColorName::new("brownish grey")),
    (HexCode::new("#D5AB09"), ColorName::new("burnt yellow")),
    (HexCode::new("#F7022A"), ColorName::new("cherry red")),
    (HexCode::new("#B16002"), ColorName::new("orangey brown")),
    (HexCode::new("#FDB0C0"), ColorName::new("soft pink")),
    (HexCode::new("#11875D"), ColorName::new("dark sea green")),
    (HexCode::new("#2EE8BB"), ColorName::new("aqua marine")),
    (HexCode::new("#8AF1FE"), ColorName::new("robin egg blue")),
    (HexCode::new("#98F6B0"), ColorName::new("light sea green")),
    (HexCode::new("#60460F"), ColorName::new("mud brown")),
    (HexCode::new("#C9AE74"), ColorName::new("sandstone")),
    (HexCode::new("#05480D"), ColorName::new("british racing green")),
    (HexCode::new("#DE9DAC"), ColorName::new("faded pink")),
    (HexCode::new("#F4D054"), ColorName::new("maize")),
    (HexCode::new("#C69C04"), ColorName::new("ocre")),
    (HexCode::new("#FFAD01"), ColorName::new("orange yellow")),
    (HexCode::new("#9B8F55"), ColorName::new("dark khaki")),
    (HexCode::new("#AEFD6C"), ColorName::new("light lime")),
    (HexCode::new("#26F7FD"), ColorName::new("bright light blue")),
    (HexCode::new("#2BAF6A"), ColorName::new("jade green")),
    (HexCode::new("#AC1DB8"), ColorName::new("barney")),
    (HexCode::new("#BD6C48"), ColorName::new("adobe")),
    (HexCode::new("#0BF77D"), ColorName::new("minty green")),
    (HexCode::new("#2E5A88"), ColorName::new("light navy blue")),
    (HexCode::new("#76A973"), ColorName::new("dusty green")),
    (HexCode::new("#000133"), ColorName::new("very dark blue")),
    (HexCode::new("#3D9973"), ColorName::new("ocean green")),
    (HexCode::new("#A8B504"), ColorName::new("mustard green")),
    (HexCode::new("#7A5901"), ColorName::new("poop brown")),
    (HexCode::new("#645403"), ColorName::new("olive brown")),
    (HexCode::new("#F5054F"), ColorName::new("pink red")),
    (HexCode::new("#155084"), ColorName::new("light navy")),
    (HexCode::new("#F6CEFC"), ColorName::new("very light purple")),
    (HexCode::new("#FFFFCB"), ColorName::new("ivory")),
    (HexCode::new("#C760FF"), ColorName::new("bright lavender")),
    (HexCode::new("#0BF9EA"), ColorName::new("bright aqua")),
    (HexCode::new("#6DEDFD"), ColorName::new("robin's egg")),
    (HexCode::new("#5FA052"), ColorName::new("muted green")),
    (HexCode::new("#7F5112"), ColorName::new("medium brown")),
    (HexCode::new("#B66325"), ColorName::new("copper")),
    (HexCode::new("#84B701"), ColorName::new("dark lime")),
    (HexCode::new("#FB2943"), ColorName::new("strawberry")),
    (HexCode::new("#836539"), ColorName::new("dirt brown")),
    (HexCode::new("#C1FD95"), ColorName::new("celery")),
    (HexCode::new("#02CCFE"), ColorName::new("bright sky blue")),
    (HexCode::new("#885F01"), ColorName::new("poo brown")),
    (HexCode::new("#B17261"), ColorName::new("pinkish brown")),
    (HexCode::new("#BEFDB7"), ColorName::new("celadon")),
    (HexCode::new("#65FE08"), ColorName::new("bright lime green")),
    (HexCode::new("#9A3001"), ColorName::new("auburn")),
    (HexCode::new("#FE02A2"), ColorName::new("shocking pink")),
    (HexCode::new("#920A4E"), ColorName::new("mulberry")),
    (HexCode::new("#8AB8FE"), ColorName::new("carolina blue")),
    (HexCode::new("#61E160"), ColorName::new("lightish green")),
    (HexCode::new("#EDC8FF"), ColorName::new("light lilac")),
    (HexCode::new("#B9CC81"), ColorName::new("pale olive")),
    (HexCode::new("#FB7D07"), ColorName::new("pumpkin orange")),
    (HexCode::new("#CB9D06"), ColorName::new("yellow ochre")),
    (HexCode::new("#FE0002"), ColorName::new("fire engine red")),
    (HexCode::new("#0D75F8"), ColorName::new("deep sky blue")),
    (HexCode::new("#FD4659"), ColorName::new("watermelon")),
    (HexCode::new("#044A05"), ColorName::new("bottle green")),
    (HexCode::new("#2A0134"), ColorName::new("very dark purple")),
    (HexCode::new("#FBDD7E"), ColorName::new("wheat")),
    (HexCode::new("#6C7A0E"), ColorName::new("murky green")),
    (HexCode::new("#76424E"), ColorName::new("brownish purple")),
    (HexCode::new("#5CB200"), ColorName::new("kermit green")),
    (HexCode::new("#0804F9"), ColorName::new("primary blue")),
    (HexCode::new("#FA4224"), ColorName::new("orangey red")),
    (HexCode::new("#E4CBFF"), ColorName::new("pale lilac")),
    (HexCode::new("#AA2704"), ColorName::new("rust red")),
    (HexCode::new("#C87606"), ColorName::new("dirty orange")),
    (HexCode::new("#C8ACA9"), ColorName::new("pinkish grey")),
    (HexCode::new("#9D5783"), ColorName::new("light plum")),
    (HexCode::new("#42B395"), ColorName::new("greeny blue")),
    (HexCode::new("#000435"), ColorName::new("dark navy")),
    (HexCode::new("#EF1DE7"), ColorName::new("pink/purple")),
    (HexCode::new("#019529"), ColorName::new("irish green")),
    (HexCode::new("#937C00"), ColorName::new("baby poop")),
    (HexCode::new("#99CC04"), ColorName::new("slime green")),
    (HexCode::new("#B0054B"), ColorName::new("purplish red")),
    (HexCode::new("#AB1239"), ColorName::new("rouge")),
    (HexCode::new("#FFC5CB"), ColorName::new("light rose")),
    (HexCode::new("#828344"), ColorName::new("drab")),
    (HexCode::new("#00022E"), ColorName::new("dark navy blue")),
    (HexCode::new("#CCFD7F"), ColorName::new("light yellow green")),
    (HexCode::new("#C071FE"), ColorName::new("easter purple")),
    (HexCode::new("#ACBB0D"), ColorName::new("snot")),
    (HexCode::new("#FEA993"), ColorName::new("light salmon")),
    (HexCode::new("#C83CB9"), ColorName::new("purpley pink")),
    (HexCode::new("#8F7303"), ColorName::new("poo")),
    (HexCode::new("#990F4B"), ColorName::new("berry")),
    (HexCode::new("#7D7F7C"), ColorName::new("medium grey")),
    (HexCode::new("#922B05"), ColorName::new("brown red")),
    (HexCode::new("#770001"), ColorName::new("blood")),
    (HexCode::new("#A66FB5"), ColorName::new("soft purple")),
    (HexCode::new("#C3909B"), ColorName::new("grey pink")),
    (HexCode::new("#2BB179"), ColorName::new("bluey green")),
    (HexCode::new("#03012D"), ColorName::new("midnight")),
    (HexCode::new("#1F0954"), ColorName::new("dark indigo")),
    (HexCode::new("#978A84"), ColorName::new("warm grey")),
    (HexCode::new("#C4A661"), ColorName::new("sandy brown")),
    (HexCode::new("#CF0234"), ColorName::new("cherry")),
    (HexCode::new("#5A06EF"), ColorName::new("blue/purple")),
    (HexCode::new("#536267"), ColorName::new("gunmetal")),
    (HexCode::new("#490648"), ColorName::new("deep violet")),
    (HexCode::new("#2A7E19"), ColorName::new("tree green")),
    (HexCode::new("#B25F03"), ColorName::new("orangish brown")),
    (HexCode::new("#02C14D"), ColorName::new("shamrock green")),
    (HexCode::new("#F43605"), ColorName::new("orangish red")),
    (HexCode::new("#C6F808"), ColorName::new("greeny yellow")),
    (HexCode::new("#D0C101"), ColorName::new("ugly yellow")),
    (HexCode::new("#436BAD"), ColorName::new("french blue")),
    (HexCode::new("#895B7B"), ColorName::new("dusky purple")),
    (HexCode::new("#FFFD74"), ColorName::new("butter yellow")),
    (HexCode::new("#FFFEB6"), ColorName::new("light beige")),
    (HexCode::new("#F5BF03"), ColorName::new("golden")),
    (HexCode::new("#475F94"), ColorName::new("dusky blue")),
    (HexCode::new("#7BC8F6"), ColorName::new("lightblue")),
    (HexCode::new("#F075E6"), ColorName::new("purply pink")),
    (HexCode::new("#6BA353"), ColorName::new("off green")),
    (HexCode::new("#BF9B0C"), ColorName::new("ocher")),
    (HexCode::new("#7F4E1E"), ColorName::new("milk chocolate")),
    (HexCode::new("#FFD8B1"), ColorName::new("light peach")),
    (HexCode::new("#A0025C"), ColorName::new("deep magenta")),
    (HexCode::new("#AF6F09"), ColorName::new("caramel")),
    (HexCode::new("#32BF84"), ColorName::new("greenish teal")),
    (HexCode::new("#BEFD73"), ColorName::new("pale lime")),
    (HexCode::new("#990147"), ColorName::new("purple red")),
    (HexCode::new("#464196"), ColorName::new("blueberry")),
    (HexCode::new("#77AB56"), ColorName::new("asparagus")),
    (HexCode::new("#FDFDFE"), ColorName::new("pale grey")),
    (HexCode::new("#9DBCD4"), ColorName::new("light grey blue")),
    (HexCode::new("#B1FF65"), ColorName::new("pale lime green")),
    (HexCode::new("#419C03"), ColorName::new("grassy green")),
    (HexCode::new("#638B27"), ColorName::new("mossy green")),
    (HexCode::new("#A2653E"), ColorName::new("earth")),
    (HexCode::new("#DC4D01"), ColorName::new("deep orange")),
    (HexCode::new("#B8FFEB"), ColorName::new("pale aqua")),
    (HexCode::new("#BE013C"), ColorName::new("rose red")),
    (HexCode::new("#ADA587"), ColorName::new("stone")),
    (HexCode::new("#CD5909"), ColorName::new("rusty orange")),
    (HexCode::new("#A4BF20"), ColorName::new("pea")),
    (HexCode::new("#9DB92C"), ColorName::new("sick green")),
    (HexCode::new("#C4387F"), ColorName::new("darker pink")),
    (HexCode::new("#742802"), ColorName::new("chestnut")),
    (HexCode::new("#0F9B8E"), ColorName::new("blue/green")),
    (HexCode::new("#9B5FC0"), ColorName::new("amethyst")),
    (HexCode::new("#20C073"), ColorName::new("dark mint green")),
    (HexCode::new("#FDC1C5"), ColorName::new("pale rose")),
    (HexCode::new("#3B719F"), ColorName::new("muted blue")),
    (HexCode::new("#CFAF7B"), ColorName::new("fawn")),
    (HexCode::new("#FEF69E"), ColorName::new("buff")),
    (HexCode::new("#04F489"), ColorName::new("turquoise green")),
    (HexCode::new("#886806"), ColorName::new("muddy brown")),
    (HexCode::new("#3C9992"), ColorName::new("sea")),
    (HexCode::new("#EF4026"), ColorName::new("tomato")),
    (HexCode::new("#FF7FA7"), ColorName::new("carnation pink")),
    (HexCode::new("#FFFF7E"), ColorName::new("banana")),
    (HexCode::new("#CFFF04"), ColorName::new("neon yellow")),
    (HexCode::new("#A8A495"), ColorName::new("greyish")),
    (HexCode::new("#50A747"), ColorName::new("mid green")),
    (HexCode::new("#805B87"), ColorName::new("muted purple")),
    (HexCode::new("#FF0490"), ColorName::new("electric pink")),
    (HexCode::new("#F1DA7A"), ColorName::new("sandy")),
    (HexCode::new("#CD7584"), ColorName::new("ugly pink")),
    (HexCode::new("#06B1C4"), ColorName::new("turquoise blue")),
    (HexCode::new("#A8415B"), ColorName::new("light burgundy")),
    (HexCode::new("#BCCB7A"), ColorName::new("greenish tan")),
    (HexCode::new("#48C072"), ColorName::new("dark mint")),
    (HexCode::new("#B36FF6"), ColorName::new("light urple")),
    (HexCode::new("#280137"), ColorName::new("midnight purple")),
    (HexCode::new("#FF724C"), ColorName::new("pinkish orange")),
    (HexCode::new("#CBF85F"), ColorName::new("pear")),
    (HexCode::new("#3F012C"), ColorName::new("dark plum")),
    (HexCode::new("#24BCA8"), ColorName::new("tealish")),
    (HexCode::new("#8F8CE7"), ColorName::new("perrywinkle")),
    (HexCode::new("#FFAB0F"), ColorName::new("yellowish orange")),
    (HexCode::new("#FF964F"), ColorName::new("pastel orange")),
    (HexCode::new("#6258C4"), ColorName::new("iris")),
    (HexCode::new("#1805DB"), ColorName::new("ultramarine blue")),
    (HexCode::new("#35530A"), ColorName::new("navy green")),
    (HexCode::new("#18D17B"), ColorName::new("seaweed")),
    (HexCode::new("#9CEF43"), ColorName::new("kiwi")),
    (HexCode::new("#0AFF02"), ColorName::new("fluro green")),
    (HexCode::new("#2DFE54"), ColorName::new("bright light green")),
    (HexCode::new("#2FEF10"), ColorName::new("vivid green")),
    (HexCode::new("#58BC08"), ColorName::new("frog green")),
    (HexCode::new("#876E4B"), ColorName::new("dull brown")),
    (HexCode::new("#4E5481"), ColorName::new("dusk")),
    (HexCode::new("#AC7E04"), ColorName::new("mustard brown")),
    (HexCode::new("#51B73B"), ColorName::new("leafy green")),
    (HexCode::new("#4984B8"), ColorName::new("cool blue")),
    (HexCode::new("#070D0D"), ColorName::new("almost black")),
    (HexCode::new("#C8FD3D"), ColorName::new("yellow/green")),
    (HexCode::new("#D94FF5"), ColorName::new("heliotrope")),
    (HexCode::new("#5EDC1F"), ColorName::new("green apple")),
    (HexCode::new("#8F9805"), ColorName::new("baby poop green")),
    (HexCode::new("#6ECB3C"), ColorName::new("apple")),
    (HexCode::new("#DF4EC8"), ColorName::new("purpleish pink")),
    (HexCode::new("#040348"), ColorName::new("night blue")),
    (HexCode::new("#730039"), ColorName::new("merlot")),
    (HexCode::new("#76FF7B"), ColorName::new("lightgreen")),
    (HexCode::new("#EC2D01"), ColorName::new("tomato red")),
    (HexCode::new("#AEFF6E"), ColorName::new("key lime")),
    (HexCode::new("#B7FFFA"), ColorName::new("pale cyan")),
    (HexCode::new("#C7C10C"), ColorName::new("vomit yellow")),
    (HexCode::new("#6B4247"), ColorName::new("purplish brown")),
    (HexCode::new("#FF6CB5"), ColorName::new("bubblegum")),
    (HexCode::new("#01B44C"), ColorName::new("shamrock")),
    (HexCode::new("#FFA62B"), ColorName::new("mango")),
    (HexCode::new("#D0FE1D"), ColorName::new("lime yellow")),
    (HexCode::new("#25FF29"), ColorName::new("hot green")),
    (HexCode::new("#5D1451"), ColorName::new("grape purple")),
    (HexCode::new("#F0944D"), ColorName::new("faded orange")),
    (HexCode::new("#87A922"), ColorName::new("avocado green")),
    (HexCode::new("#016795"), ColorName::new("peacock blue")),
    (HexCode::new("#3AE57F"), ColorName::new("weird green")),
    (HexCode::new("#C95EFB"), ColorName::new("bright lilac")),
    (HexCode::new("#548D44"), ColorName::new("fern green")),
    (HexCode::new("#3F829D"), ColorName::new("dirty blue")),
    (HexCode::new("#C45508"), ColorName::new("rust orange")),
    (HexCode::new("#A484AC"), ColorName::new("heather")),
    (HexCode::new("#00555A"), ColorName::new("deep teal")),
    (HexCode::new("#1FB57A"), ColorName::new("dark seafoam")),
    (HexCode::new("#AB9004"), ColorName::new("baby poo")),
    (HexCode::new("#BBF90F"), ColorName::new("yellowgreen")),
    (HexCode::new("#BCECAC"), ColorName::new("light sage")),
    (HexCode::new("#7BFDC7"), ColorName::new("light aquamarine")),
    (HexCode::new("#1EF876"), ColorName::new("spearmint")),
    (HexCode::new("#87FD05"), ColorName::new("bright lime")),
    (HexCode::new("#0ADD08"), ColorName::new("vibrant green")),
    (HexCode::new("#CFFDBC"), ColorName::new("very pale green")),
    (HexCode::new("#FEFF7F"), ColorName::new("faded yellow")),
    (HexCode::new("#B5C306"), ColorName::new("bile")),
    (HexCode::new("#1E9167"), ColorName::new("viridian")),
    (HexCode::new("#FFF4F2"), ColorName::new("very light pink")),
    (HexCode::new("#947706"), ColorName::new("puke brown")),
    (HexCode::new("#F36196"), ColorName::new("medium pink")),
    (HexCode::new("#A442A0"), ColorName::new("ugly purple")),
    (HexCode::new("#FFFD37"), ColorName::new("sunshine yellow")),
    (HexCode::new("#35AD6B"), ColorName::new("seaweed green")),
    (HexCode::new("#C1C6FC"), ColorName::new("light periwinkle")),
    (HexCode::new("#ADF802"), ColorName::new("lemon green")),
    (HexCode::new("#696006"), ColorName::new("greeny brown")),
    (HexCode::new("#29465B"), ColorName::new("dark grey blue")),
    (HexCode::new("#9CBB04"), ColorName::new("bright olive")),
    (HexCode::new("#75B84F"), ColorName::new("turtle green")),
    (HexCode::new("#BDF6FE"), ColorName::new("pale sky blue")),
    (HexCode::new("#F7D560"), ColorName::new("light mustard")),
    (HexCode::new("#9F8303"), ColorName::new("diarrhea")),
    (HexCode::new("#017371"), ColorName::new("dark aquamarine")),
    (HexCode::new("#C27E79"), ColorName::new("brownish pink")),
    (HexCode::new("#889717"), ColorName::new("baby shit green")),
    (HexCode::new("#8756E4"), ColorName::new("purpley")),
    (HexCode::new("#77A1B5"), ColorName::new("greyblue")),
    (HexCode::new("#F504C9"), ColorName::new("hot magenta")),
    (HexCode::new("#758DA3"), ColorName::new("blue/grey")),
    (HexCode::new("#FFF9D0"), ColorName::new("pale")),
    (HexCode::new("#33B864"), ColorName::new("cool green")),
    (HexCode::new("#FDEE73"), ColorName::new("sandy yellow")),
    (HexCode::new("#C4FFF7"), ColorName::new("eggshell blue")),
    (HexCode::new("#94AC02"), ColorName::new("barf green")),
    (HexCode::new("#8CFF9E"), ColorName::new("baby green")),
    (HexCode::new("#AD03DE"), ColorName::new("vibrant purple")),
    (HexCode::new("#8D8468"), ColorName::new("brown grey")),
    (HexCode::new("#0E87CC"), ColorName::new("water blue")),
    (HexCode::new("#C0022F"), ColorName::new("lipstick red")),
    (HexCode::new("#FAFE4B"), ColorName::new("banana yellow")),
    (HexCode::new("#A87DC2"), ColorName::new("wisteria")),
    (HexCode::new("#673A3F"), ColorName::new("purple brown")),
    (HexCode::new("#B29705"), ColorName::new("brown yellow")),
    (HexCode::new("#D725DE"), ColorName::new("purple/pink")),
    (HexCode::new("#BFFE28"), ColorName::new("lemon lime")),
    (HexCode::new("#647D8E"), ColorName::new("grey/blue")),
    (HexCode::new("#B9484E"), ColorName::new("dusty red")),
    (HexCode::new("#C74767"), ColorName::new("deep rose")),
    (HexCode::new("#3EAF76"), ColorName::new("dark seafoam green")),
    (HexCode::new("#BFAC05"), ColorName::new("muddy yellow")),
    (HexCode::new("#FD798F"), ColorName::new("carnation")),
    (HexCode::new("#AE8B0C"), ColorName::new("yellowy brown")),
    (HexCode::new("#A50055"), ColorName::new("violet red")),
    (HexCode::new("#0A437A"), ColorName::new("twilight blue")),
    (HexCode::new("#0203E2"), ColorName::new("pure blue")),
    (HexCode::new("#FE2F4A"), ColorName::new("lightish red")),
    (HexCode::new("#C14A09"), ColorName::new("brick orange")),
    (HexCode::new("#750851"), ColorName::new("velvet")),
    (HexCode::new("#FFC512"), ColorName::new("sunflower")),
    (HexCode::new("#A6FBB2"), ColorName::new("light mint green")),
    (HexCode::new("#9AF764"), ColorName::new("light grass green")),
    (HexCode::new("#8B88F8"), ColorName::new("lavender blue")),
    (HexCode::new("#AF2F0D"), ColorName::new("rusty red")),
    (HexCode::new("#A552E6"), ColorName::new("lightish purple")),
    (HexCode::new("#4B0101"), ColorName::new("dried blood")),
    (HexCode::new("#B7C9E2"), ColorName::new("light blue grey")),
    (HexCode::new("#71AA34"), ColorName::new("leaf")),
    (HexCode::new("#FC824A"), ColorName::new("orangish")),
    (HexCode::new("#B1D27B"), ColorName::new("pale olive green")),
    (HexCode::new("#F1F33F"), ColorName::new("off yellow")),
    (HexCode::new("#F0833A"), ColorName::new("dusty orange")),
    (HexCode::new("#FFFF81"), ColorName::new("butter")),
    (HexCode::new("#0C1793"), ColorName::new("royal")),
    (HexCode::new("#005F6A"), ColorName::new("petrol")),
    (HexCode::new("#2AFEB7"), ColorName::new("greenish cyan")),
    (HexCode::new("#C3FBF4"), ColorName::new("duck egg blue")),
    (HexCode::new("#FF69AF"), ColorName::new("bubble gum pink")),
    (HexCode::new("#85A3B2"), ColorName::new("bluegrey")),
    (HexCode::new("#964E02"), ColorName::new("warm brown")),
    (HexCode::new("#4E518B"), ColorName::new("twilight")),
    (HexCode::new("#FEB209"), ColorName::new("saffron")),
    (HexCode::new("#5D21D0"), ColorName::new("purple/blue")),
    (HexCode::new("#A88F59"), ColorName::new("dark sand")),
    (HexCode::new("#0339F8"), ColorName::new("vibrant blue")),
    (HexCode::new("#BEAE8A"), ColorName::new("putty")),
    (HexCode::new("#4DA409"), ColorName::new("lawn green")),
    (HexCode::new("#4B6113"), ColorName::new("camouflage green")),
    (HexCode::new("#FE828C"), ColorName::new("blush pink")),
    (HexCode::new("#6E1005"), ColorName::new("reddy brown")),
    (HexCode::new("#A90308"), ColorName::new("darkish red")),
    (HexCode::new("#21C36F"), ColorName::new("algae green")),
    (HexCode::new("#CF524E"), ColorName::new("dark coral")),
    (HexCode::new("#41FDFE"), ColorName::new("bright cyan")),
    (HexCode::new("#DDD618"), ColorName::new("piss yellow")),
    (HexCode::new("#DB5856"), ColorName::new("pastel red")),
    (HexCode::new("#00FBB0"), ColorName::new("greenish turquoise")),
    (HexCode::new("#1B2431"), ColorName::new("dark")),
    (HexCode::new("#CA0147"), ColorName::new("ruby")),
    (HexCode::new("#6F7C00"), ColorName::new("poop green")),
    (HexCode::new("#FE420F"), ColorName::new("orangered")),
    (HexCode::new("#FEDF08"), ColorName::new("dandelion")),
    (HexCode::new("#680018"), ColorName::new("claret")),
    (HexCode::new("#FED0FC"), ColorName::new("pale mauve")),
    (HexCode::new("#D5174E"), ColorName::new("lipstick")),
    (HexCode::new("#FE86A4"), ColorName::new("rosa")),
    (HexCode::new("#030764"), ColorName::new("darkblue")),
    (HexCode::new("#AB7E4C"), ColorName::new("tan brown")),
    (HexCode::new("#758000"), ColorName::new("shit green")),
    (HexCode::new("#8C0034"), ColorName::new("red wine")),
    (HexCode::new("#FC86AA"), ColorName::new("pinky")),
    (HexCode::new("#606602"), ColorName::new("mud green")),
    (HexCode::new("#63F7B4"), ColorName::new("light greenish blue")),
    (HexCode::new("#5F9E8F"), ColorName::new("dull teal")),
    (HexCode::new("#8D5EB7"), ColorName::new("deep lavender")),
    (HexCode::new("#152EFF"), ColorName::new("vivid blue")),
    (HexCode::new("#A75E09"), ColorName::new("raw umber")),
    (HexCode::new("#B6FFBB"), ColorName::new("light mint")),
    (HexCode::new("#CAFFFB"), ColorName::new("light light blue")),
    (HexCode::new("#1BFC06"), ColorName::new("highlighter green")),
    (HexCode::new("#7EA07A"), ColorName::new("greeny grey")),
    (HexCode::new("#89A0B0"), ColorName::new("bluey grey")),
    (HexCode::new("#54AC68"), ColorName::new("algae")),
    (HexCode::new("#5C8B15"), ColorName::new("sap green")),
    (HexCode::new("#FFB19A"), ColorName::new("pale salmon")),
    (HexCode::new("#4F738E"), ColorName::new("metallic blue")),
    (HexCode::new("#D6FFFA"), ColorName::new("ice")),
    (HexCode::new("#A0BF16"), ColorName::new("gross green")),
    (HexCode::new("#3E82FC"), ColorName::new("dodger blue")),
    (HexCode::new("#FB5581"), ColorName::new("warm pink")),
    (HexCode::new("#56FCA2"), ColorName::new("light green blue")),
    (HexCode::new("#699D4C"), ColorName::new("flat green")),
    (HexCode::new("#1F3B4D"), ColorName::new("dark blue grey")),
    (HexCode::new("#B2713D"), ColorName::new("clay brown")),
    (HexCode::new("#FCE166"), ColorName::new("sand yellow")),
    (HexCode::new("#FD5956"), ColorName::new("grapefruit")),
    (HexCode::new("#FE4B03"), ColorName::new("blood orange")),
    (HexCode::new("#D6FFFE"), ColorName::new("very pale blue")),
    (HexCode::new("#C77986"), ColorName::new("old pink")),
    (HexCode::new("#FF073A"), ColorName::new("neon red")),
    (HexCode::new("#F9BC08"), ColorName::new("golden rod")),
    (HexCode::new("#4E0550"), ColorName::new("plum purple")),
    (HexCode::new("#FFE5AD"), ColorName::new("pale peach")),
    (HexCode::new("#16D43F"), ColorName::new("green again")),
    (HexCode::new("#728F02"), ColorName::new("dark yellow green")),
    (HexCode::new("#9D0216"), ColorName::new("carmine")),
    (HexCode::new("#015482"), ColorName::new("deep sea blue")),
    (HexCode::new("#D90166"), ColorName::new("dark hot pink")),
    (HexCode::new("#4B57DB"), ColorName::new("warm blue")),
    (HexCode::new("#E6F2A2"), ColorName::new("light khaki")),
    (HexCode::new("#8FAE22"), ColorName::new("icky green")),
    (HexCode::new("#23C48B"), ColorName::new("greenblue")),
    (HexCode::new("#734A65"), ColorName::new("dirty purple")),
    (HexCode::new("#021BF9"), ColorName::new("rich blue")),
    (HexCode::new("#BA9E88"), ColorName::new("mushroom")),
    (HexCode::new("#3C73A8"), ColorName::new("flat blue")),
    (HexCode::new("#214761"), ColorName::new("dark slate blue")),
    (HexCode::new("#598556"), ColorName::new("dark sage")),
    (HexCode::new("#FF6163"), ColorName::new("coral pink")),
    (HexCode::new("#089404"), ColorName::new("true green")),
    (HexCode::new("#751973"), ColorName::new("darkish purple")),
    (HexCode::new("#7F684E"), ColorName::new("dark taupe")),
    (HexCode::new("#95A3A6"), ColorName::new("cool grey")),
    (HexCode::new("#FDFF63"), ColorName::new("canary")),
    (HexCode::new("#96B403"), ColorName::new("booger green")),
    (HexCode::new("#D1768F"), ColorName::new("muted pink")),
    (HexCode::new("#8E7618"), ColorName::new("hazel")),
    (HexCode::new("#02066F"), ColorName::new("dark royal blue")),
    (HexCode::new("#9900FA"), ColorName::new("vivid purple")),
    (HexCode::new("#014600"), ColorName::new("racing green")),
    (HexCode::new("#AC7434"), ColorName::new("leather")),
    (HexCode::new("#01C08D"), ColorName::new("green/blue")),
    (HexCode::new("#FFDA03"), ColorName::new("sunflower yellow")),
    (HexCode::new("#720058"), ColorName::new("rich purple")),
    (HexCode::new("#D767AD"), ColorName::new("pale magenta")),
    (HexCode::new("#C2FF89"), ColorName::new("light yellowish green")),
    (HexCode::new("#3A18B1"), ColorName::new("indigo blue")),
    (HexCode::new("#9D0759"), ColorName::new("dark fuchsia")),
    (HexCode::new("#FFE36E"), ColorName::new("yellow tan")),
    (HexCode::new("#20F986"), ColorName::new("wintergreen")),
    (HexCode::new("#FB5FFC"), ColorName::new("violet pink")),
    (HexCode::new("#13BBAF"), ColorName::new("topaz")),
    (HexCode::new("#78D1B6"), ColorName::new("seafoam blue")),
    (HexCode::new("#FDDC5C"), ColorName::new("light gold")),
    (HexCode::new("#86A17D"), ColorName::new("grey/green")),
    (HexCode::new("#90FDA9"), ColorName::new("foam green")),
    (HexCode::new("#FFFFB6"), ColorName::new("creme")),
    (HexCode::new("#247AFD"), ColorName::new("clear blue")),
    (HexCode::new("#31668A"), ColorName::new("ugly blue")),
    (HexCode::new("#CB6843"), ColorName::new("terracota")),
    (HexCode::new("#1D0200"), ColorName::new("very dark brown")),
    (HexCode::new("#FCF679"), ColorName::new("straw")),
    (HexCode::new("#FEFCAF"), ColorName::new("parchment")),
    (HexCode::new("#FDB915"), ColorName::new("orangey yellow")),
    (HexCode::new("#719F91"), ColorName::new("greyish teal")),
    (HexCode::new("#2138AB"), ColorName::new("sapphire")),
    (HexCode::new("#107AB0"), ColorName::new("nice blue")),
    (HexCode::new("#CA6B02"), ColorName::new("browny orange")),
    (HexCode::new("#BCF5A6"), ColorName::new("washed out green")),
    (HexCode::new("#7BF2DA"), ColorName::new("tiffany blue")),
    (HexCode::new("#A0FEBF"), ColorName::new("light seafoam")),
    (HexCode::new("#4EFD54"), ColorName::new("light neon green")),
    (HexCode::new("#53FE5C"), ColorName::new("light bright green")),
    (HexCode::new("#76FDA8"), ColorName::new("light bluish green")),
    (HexCode::new("#F6688E"), ColorName::new("rosy pink")),
    (HexCode::new("#FF9A8A"), ColorName::new("peachy pink")),
    (HexCode::new("#B1FC99"), ColorName::new("pale light green")),
    (HexCode::new("#C87F89"), ColorName::new("old rose")),
    (HexCode::new("#63A950"), ColorName::new("fern")),
    (HexCode::new("#26538D"), ColorName::new("dusk blue")),
    (HexCode::new("#7F8F4E"), ColorName::new("camo")),
    (HexCode::new("#B75203"), ColorName::new("burnt siena")),
    (HexCode::new("#0CDC73"), ColorName::new("tealish green")),
    (HexCode::new("#698339"), ColorName::new("swamp")),
    (HexCode::new("#CBA560"), ColorName::new("sand brown")),
    (HexCode::new("#8B3103"), ColorName::new("rust brown")),
    (HexCode::new("#FD8D49"), ColorName::new("orangeish")),
    (HexCode::new("#3A2EFE"), ColorName::new("light royal blue")),
    (HexCode::new("#875F42"), ColorName::new("cocoa")),
    (HexCode::new("#CA9BF7"), ColorName::new("baby purple")),
    (HexCode::new("#9A6200"), ColorName::new("raw sienna")),
    (HexCode::new("#2CFA1F"), ColorName::new("radioactive green")),
    (HexCode::new("#C4FE82"), ColorName::new("light pea green")),
    (HexCode::new("#AC4F06"), ColorName::new("cinnamon")),
    (HexCode::new("#F2AB15"), ColorName::new("squash")),
    (HexCode::new("#3C4142"), ColorName::new("charcoal grey")),
    (HexCode::new("#9DFF00"), ColorName::new("bright yellow green")),
    (HexCode::new("#B6C406"), ColorName::new("baby puke green")),
    (HexCode::new("#40FD14"), ColorName::new("poison green")),
    (HexCode::new("#EFC0FE"), ColorName::new("light lavendar")),
    (HexCode::new("#850E04"), ColorName::new("indian red")),
    (HexCode::new("#FFF39A"), ColorName::new("dark cream")),
    (HexCode::new("#C7AC7D"), ColorName::new("toupe")),
    (HexCode::new("#FDB147"), ColorName::new("butterscotch")),
    (HexCode::new("#6832E3"), ColorName::new("burple")),
    (HexCode::new("#A9BE70"), ColorName::new("tan green")),
    (HexCode::new("#FFDF22"), ColorName::new("sun yellow")),
    (HexCode::new("#FDDE6C"), ColorName::new("pale gold")),
    (HexCode::new("#C8FFB0"), ColorName::new("light light green")),
    (HexCode::new("#8FB67B"), ColorName::new("lichen")),
    (HexCode::new("#B5CE08"), ColorName::new("green/yellow")),
    (HexCode::new("#054907"), ColorName::new("darkgreen")),
    (HexCode::new("#1D5DEC"), ColorName::new("azul")),
    (HexCode::new("#FFF917"), ColorName::new("sunny yellow")),
    (HexCode::new("#D0E429"), ColorName::new("sickly yellow")),
    (HexCode::new("#009337"), ColorName::new("kelley green")),
    (HexCode::new("#7E4071"), ColorName::new("bruise")),
    (HexCode::new("#6F6C0A"), ColorName::new("browny green")),
    (HexCode::new("#6B7C85"), ColorName::new("battleship grey")),
    (HexCode::new("#5684AE"), ColorName::new("off blue")),
    (HexCode::new("#FFFA86"), ColorName::new("manilla")),
    (HexCode::new("#C9D179"), ColorName::new("greenish beige")),
    (HexCode::new("#410200"), ColorName::new("deep brown")),
    (HexCode::new("#DA467D"), ColorName::new("darkish pink")),
    (HexCode::new("#FFFD78"), ColorName::new("custard")),
    (HexCode::new("#7D7103"), ColorName::new("ugly brown")),
    (HexCode::new("#507B9C"), ColorName::new("stormy blue")),
    (HexCode::new("#C48EFD"), ColorName::new("liliac")),
    (HexCode::new("#AD900D"), ColorName::new("baby shit brown")),
    (HexCode::new("#997570"), ColorName::new("reddish grey")),
    (HexCode::new("#FFB2D0"), ColorName::new("powder pink")),
    (HexCode::new("#430541"), ColorName::new("eggplant purple")),
    (HexCode::new("#FFFCC4"), ColorName::new("egg shell")),
    (HexCode::new("#D3B683"), ColorName::new("very light brown")),
    (HexCode::new("#BDF8A3"), ColorName::new("tea green")),
    (HexCode::new("#FF6F52"), ColorName::new("orange pink")),
    (HexCode::new("#B7E1A1"), ColorName::new("light grey green")),
    (HexCode::new("#8EE53F"), ColorName::new("kiwi green")),
    (HexCode::new("#63B365"), ColorName::new("boring green")),
    (HexCode::new("#B2FBA5"), ColorName::new("light pastel green")),
    (HexCode::new("#FF63E9"), ColorName::new("candy pink")),
    (HexCode::new("#983FB2"), ColorName::new("purply")),
    (HexCode::new("#947E94"), ColorName::new("purpley grey")),
    (HexCode::new("#AC86A8"), ColorName::new("dusty lavender")),
    (HexCode::new("#CCAD60"), ColorName::new("desert")),
    (HexCode::new("#966EBD"), ColorName::new("deep lilac")),
    (HexCode::new("#E78EA5"), ColorName::new("pig pink")),
    (HexCode::new("#C2B709"), ColorName::new("olive yellow")),
    (HexCode::new("#A7FFB5"), ColorName::new("light seafoam green")),
    (HexCode::new("#A6C875"), ColorName::new("light moss green")),
    (HexCode::new("#DD85D7"), ColorName::new("lavender pink")),
    (HexCode::new("#08787F"), ColorName::new("deep aqua")),
    (HexCode::new("#AFA88B"), ColorName::new("bland")),
    (HexCode::new("#FF0789"), ColorName::new("strong pink")),
    (HexCode::new("#0CB577"), ColorName::new("green teal")),
    (HexCode::new("#017374"), ColorName::new("deep turquoise")),
    (HexCode::new("#1F6357"), ColorName::new("dark green blue")),
    (HexCode::new("#05FFA6"), ColorName::new("bright sea green")),
    (HexCode::new("#9BB53C"), ColorName::new("booger")),
    (HexCode::new("#533CC6"), ColorName::new("blue with a hint of purple")),
    (HexCode::new("#2242C7"), ColorName::new("blue blue")),
    (HexCode::new("#3778BF"), ColorName::new("windows blue")),
    (HexCode::new("#61DE2A"), ColorName::new("toxic green")),
    (HexCode::new("#0C06F7"), ColorName::new("strong blue")),
    (HexCode::new("#0A5F38"), ColorName::new("spruce")),
    (HexCode::new("#D99B82"), ColorName::new("pinkish tan")),
    (HexCode::new("#EFB435"), ColorName::new("macaroni and cheese")),
    (HexCode::new("#5E9B8A"), ColorName::new("grey teal")),
    (HexCode::new("#4C9085"), ColorName::new("dusty teal")),
    (HexCode::new("#388004"), ColorName::new("dark grass green")),
    (HexCode::new("#A5A391"), ColorName::new("cement")),
    (HexCode::new("#FCFC81"), ColorName::new("yellowish tan")),
    (HexCode::new("#952E8F"), ColorName::new("warm purple")),
    (HexCode::new("#65AB7C"), ColorName::new("tea")),
    (HexCode::new("#D4FFFF"), ColorName::new("really light blue")),
    (HexCode::new("#70B23F"), ColorName::new("nasty green")),
    (HexCode::new("#894585"), ColorName::new("light eggplant")),
    (HexCode::new("#69D84F"), ColorName::new("fresh green")),
    (HexCode::new("#A8FF04"), ColorName::new("electric lime")),
    (HexCode::new("#B2996E"), ColorName::new("dust")),
    (HexCode::new("#56AE57"), ColorName::new("dark pastel green")),
    (HexCode::new("#ACC2D9"), ColorName::new("cloudy blue")),
];
